### ISSUE TITLE
Update CONTRIBUTING.md with internal examples

### ISSUE THREAD

**Issue by HudsonHumphries** [open-telemetry/opentelemetry-cpp#101]
In [PR 97](https://github.com/open-telemetry/opentelemetry-cpp/pull/97) I added a Useful Resources section in [CONTRIBUTING.md](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/CONTRIBUTING.md) that generally point outwards to other Open Telemetry projects and their examples. This Issue will serve as a reminder to update these resources as examples and exporters are added to the C++ repository.

**Comment by lalitb** [comment]
Closing this. as the examples and exporters have their own README.md in corresponding folders.
