### ISSUE TITLE
Compilation of dependent target fails with G++ targeting C++ standard

### ISSUE THREAD

**Issue by manushawijekoon** [open-telemetry/opentelemetry-cpp#1010]
I am using latest release tag.
I get following compiler error when trying to include headers:

```
include/opentelemetry/sdk/metrics/sync_instruments.h:192:25: error: expected unqualified-id before ‘)’ token
    BoundUpDownCounter<T>() = default;
```
   
Apparently according to C++ 20 standard, above syntax is illegal.

We are using multiple features of C++ 20 so reverting to 17 would not work.

Any suggestions?

**Comment by manushawijekoon** [comment]
Here it is:
https://timsong-cpp.github.io/cppwp/n4861/diff.cpp17.class#2

Can certainly raise a PR for this.

**Comment by lalitb** [comment]
#1029 fixes it.
