### ISSUE TITLE
Cannot construct exporter::etw::PropertyValue from a long-typed value on a platform with 32-bit longs

### ISSUE THREAD

**Issue by MKadaner** [open-telemetry/opentelemetry-cpp#1013]
On architectures where type `long` is 32-bit, e.g., MSVC on Windows, the following constructor is ill-formed (ambiguous):

```
exporter::etw::PropertyValue(42L);
```

Here is the reduced example: https://godbolt.org/z/z8aYcrcc6. Please refer to MSVC v19.27 variant.

The ambiguity is because the underlying `PropertyVariant` does not have the `long` option. Without it, conversions from `long` to either `int32_t` or `int64_t` are equally good.

The fix should be as simple as adding `long` and `unsigned long` options to [PropertyVariant](https://github.com/open-telemetry/opentelemetry-cpp/blob/5aa73655b5bb1af0be22463255b62e6d2f7dd10f/exporters/etw/include/opentelemetry/exporters/etw/etw_properties.h#L29) type. (I am not sure if [PropertyType](https://github.com/open-telemetry/opentelemetry-cpp/blob/5aa73655b5bb1af0be22463255b62e6d2f7dd10f/exporters/etw/include/opentelemetry/exporters/etw/etw_properties.h#L49) enumeration needs to be adjusted as well.)

**Comment by lalitb** [comment]
Thanks for reporting the issue with an example. While this is a valid issue, this would be slightly complicated to support than it appears. The changes are required in [opentelemetry::attributes::AttributeValue](https://github.com/open-telemetry/opentelemetry-cpp/blob/74d4be44f9b12e86e9355f60f35e0d11f1a0ffc5/api/include/opentelemetry/common/attribute_value.h#L37) , along with the [exporter::etw::PropertyVariant](https://github.com/open-telemetry/opentelemetry-cpp/blob/5aa73655b5bb1af0be22463255b62e6d2f7dd10f/exporters/etw/include/opentelemetry/exporters/etw/etw_properties.h#L29). And `long`, or `unsigned long` are not the supported types as per the specs ( https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md#attributes ), also not supported by [ProtoBuff](https://developers.google.com/protocol-buffers/docs/proto?csw=1#scalar).

More importantly, adding a new alternate type for variant would break the ABI compatibility between API and SDK. Will raise this issue during next week's community meeting.

I know this may be not so clean solution, but explicit typecast to uint32/int32 or using the disambiguation tag `std/nostd::in_place_type` can be a short-term solution.

**Comment by MKadaner** [comment]
> Cast `long` to `int` type with fixed length might be required as the data is sending out of the process, because the length of `long` does depend on the platform.

That's a good point. The user of the API should not depend on integral types with implementation-defined width. With this in mind, it would be nice to disallow use of `long` (or `int`) with this API no matter compiler, architecture, language flavor, etc.

What happened to me was that in our codebase we had `long` event members in a couple of places, and everything "just worked" even though the final data width was implementation-defined and could be not what was intended. When I tried to upgrade compiler to a newer version, all of a sudden, the long-existing "working" code broke. And this was a good outcome. It could be worse if the compiler silently accepted the old code but interpreted it different way.

**Comment by ThomsonTan** [comment]
Close it as the build error is expected and catches unexpected cast. Please feel free to reactive this if it is still an issue.
