### ISSUE TITLE
Running make failed on AIX 7.2 with error: SpinLockMutex::try_lock() operation is not supported by the target hardware

### ISSUE THREAD

**Issue by apm-opentt** [open-telemetry/opentelemetry-cpp#1039]
**Describe your environment** 
Platform: AIX 7.2
Architecture: ppc64
Compiler: xlclang++ --version IBM XL C/C++ for AIX, V16.1.0  (5725-C72, 5765-J12) Version: 16.01.0000.0009

**Steps to reproduce**
$ mkdir source && cd source
$ git clone --recursive https://github.com/open-telemetry/opentelemetry-cpp
$ cd opentelemetry-cpp
$ mkdir build && cd build
$ cmake .. -DCMAKE_C_COMPILER=xlclang -DCMAKE_CXX_COMPILER=xlclang++ -DBUILD_TESTING=OFF
$ cmake --build . --target all

**What is the expected behavior?**
Expecting the compilation to be successful.

**What is the actual behavior?**
<pre>
bash-5.1# cmake --build . --target all
[  2%] Linking CXX static library libopentelemetry_common
Target "sdk/src/common/CMakeFiles/opentelemetry_common.dir/build" is up to date.
[ 10%] Built target opentelemetry_common
[ 13%] Linking CXX static library libopentelemetry_resources
Target "sdk/src/resource/CMakeFiles/opentelemetry_resources.dir/build" is up to date.
[ 18%] Built target opentelemetry_resources
[ 21%] Linking CXX static library libopentelemetry_trace
Target "sdk/src/trace/CMakeFiles/opentelemetry_trace.dir/build" is up to date.
[ 43%] Built target opentelemetry_trace
[ 45%] Linking CXX static library libopentelemetry_version
Target "sdk/src/version/CMakeFiles/opentelemetry_version.dir/build" is up to date.
[ 48%] Built target opentelemetry_version
[ 51%] Linking CXX static library libopentelemetry_exporter_ostream_span
Target "exporters/ostream/CMakeFiles/opentelemetry_exporter_ostream_span.dir/build" is up to date.
[ 54%] Built target opentelemetry_exporter_ostream_span
Target "examples/plugin/load/CMakeFiles/load_plugin_example.dir/build" is up to date.
[ 59%] Built target load_plugin_example
[ 62%] Linking CXX shared library libexample_plugin
Target "examples/plugin/plugin/CMakeFiles/example_plugin.dir/build" is up to date.
[ 67%] Built target example_plugin
[ 70%] Building CXX object examples/simple/CMakeFiles/foo_library.dir/foo_library/foo_library.cc.o
    1500-055: (S) ERROR in opentelemetry::v1::common::SpinLockMutex::try_lock(): The ATM_RMW      operation is not supported by the target hardware.
make: 1254-004 The error code from the last command is 1.

Stop.
make: 1254-004 The error code from the last command is 2.

Stop.
make: 1254-004 The error code from the last command is 2.

Stop.
</pre>

**Additional context**
There is an existing discussion about spin lock crash #791 that could be related to this.

**Comment by lalitb** [comment]
`flag_.exchange` here is the atomic read-modify-write (ATM_RMW) operation which should ideally be supported across intel/arm/PowerPC hardware. This could also be the issue with the C++11 support in the IBM XL C/C++ compiler.
@apm-opentt - unless you would like to debug it further, and contribute the fix, I don't think much can be done with this issue.

**Comment by apm-opentt** [comment]
Thank you @lalitb @ThomsonTan for your help.  We have been talking to AIX Compiler team about this issue.  It turns out that a compiler flag needs to be set for our power8 environment.  Adding this `cmake` option resolved the compilation error `add_compile_options(-qarch=pwr8)`
