### ISSUE TITLE
Building OTLP exporter from the release tarball fails for opentelemetry-proto dependency 

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1051]
**Describe your environment** 
ubuntu 20.04

**Steps to reproduce**
Download the release tarball, and try building OTLP exporter with cmake option WITH_OTLP=ON
The problem is that the release tarball contains the `third_party/opentelemetry-proto` directory but it is empty as it is a git submodule and the CI/build is not including this as part of the tarball).

**What is the expected behavior?**
Build to be successful.

**What is the actual behavior?**
Build fails

**Additional context**
Few ways I can think to fix it:

1 Let cmake download the opentelemetry-proto dependency at build time using (say) `FetchContent` if the `third_party/opentelemetry-proto` directory is empty. `FetchContent` is introduced in cmake 3.14, so we may have to upgrade the cmake version for this.
2. Pre-compile proto source(cpp) and headers (hpp) using protocol buffer compiler and check-in them in the repo ( similar to how opentelemetry-python does it - https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-proto ). We can also have a script to generate these files, to be used every time the version needs to be bumped.

**Comment by lalitb** [comment]
@esigo  - fyi, have assigned it to you as discussed in today's meeting.

**Comment by esigo** [comment]
@lalitb seems I can't assign it to myself. I will see if I can come up with a solution that doesn't require cmake version change.

**Comment by esigo** [comment]
I will use `ExternalProject_Add` as it is available in cmake 3.1.

**Comment by esigo** [comment]
There is a similar issue with `nlohmann_json`. I try to fix both.
