### ISSUE TITLE
Different-named tracers got the same tracer_id if they have overlapped spans in a single thread.

### ISSUE THREAD

**Issue by RandyLee16** [open-telemetry/opentelemetry-cpp#1054]
Different-named tracers got the same tracer_id if they have overlapped spans in a single thread.
Is it inline with expectations of design for Opentelemetry tracer/span concepts ？ 
I'm trying to track different input data progress in a sdk with different tracers using Opentelemtry.  But these different tracers merged by getting the same trace_id when they have time overlaps.  I cannot distinguish one input process flow from another。
Not sure if it is a bug  or my misunderstanding of the relationship between tracer and span in Opentelemetry。

**Describe your environment** 
My system is Ubuntu 16.04 LTS. And the compiler is gcc  4.9.4。

**Steps to reproduce**

My case is based on example/simple.  I update get_tracer() and main() in this simple sample:

```
nostd::shared_ptr<trace::Tracer> get_tracer(std::string tracer_name="")
{
	  auto provider = trace::Provider::GetTracerProvider();
	  return provider->GetTracer(tracer_name.c_str(), OPENTELEMETRY_SDK_VERSION);
}

int main()
{
	initTracer();

	auto span_a1  = get_tracer("A")->StartSpan("A_1");
	auto scope_a1 = get_tracer("A")->WithActiveSpan(span_a1);
	usleep(100);

	auto span_b1  = get_tracer("B")->StartSpan("B_1");
	auto scope_b1 = get_tracer("B")->WithActiveSpan(span_b1);

	{
		auto span_a2  = get_tracer("A")->StartSpan("A_2");
		auto scope_a2 = get_tracer("A")->WithActiveSpan(span_a2);
		usleep(100);
		span_a2->End();
	}

	span_a1->End();

	{
		auto span_b2  = get_tracer("B")->StartSpan("B_2");
		auto scope_b2 = get_tracer("B")->WithActiveSpan(span_b2);
		usleep(100);
		span_b2->End();
	}

	span_b1->End();
}
```

**What is the expected behavior?**
I expected that different tracer maintains its own spans independently, even in a single thread。Different tracers have different trace_ids.  And all spans under one tracer share the same trace_id with the root span of the tracer.
In this case, span A_1 and A_2 share one trace_id, and span B_1 and B_2 share another trace_id.

**What is the actual behavior?**
In my run,  span B_1 created by tracer B does not get its own unique trace_id， but the same trace_id with tracer A instead like below.   

```
{
  name          : A_2
  trace_id      : 44a3a91b385b506a98fa3b09890e09f0
  span_id       : 1132bd5c93274896
  tracestate    :
  parent_span_id: 30d4a3a4d571cec9
  start         : 1636106799378347479
  duration      : 143093
  description   :
  span kind     : Internal
  status        : Unset
  attributes    :
  events        :
  links         :
  resources     :
	service.name: unknown_service
	telemetry.sdk.version: 1.0.0-rc4
	telemetry.sdk.name: opentelemetry
	telemetry.sdk.language: cpp
  instr-lib     : A-1.0.0-rc4
}
{
  name          : A_1
  trace_id      : 44a3a91b385b506a98fa3b09890e09f0
  span_id       : 1b00491109e8bf80
  tracestate    :
  parent_span_id: 0000000000000000
  start         : 1636106799378178877
  duration      : 381938
  description   :
  span kind     : Internal
  status        : Unset
  attributes    :
  events        :
  links         :
  resources     :
	service.name: unknown_service
	telemetry.sdk.version: 1.0.0-rc4
	telemetry.sdk.name: opentelemetry
	telemetry.sdk.language: cpp
  instr-lib     : A-1.0.0-rc4
}
{
  name          : B_2
  trace_id      : 44a3a91b385b506a98fa3b09890e09f0
  span_id       : 048b09b70b279899
  tracestate    :
  parent_span_id: 30d4a3a4d571cec9
  start         : 1636106799378645579
  duration      : 154145
  description   :
  span kind     : Internal
  status        : Unset
  attributes    :
  events        :
  links         :
  resources     :
	service.name: unknown_service
	telemetry.sdk.version: 1.0.0-rc4
	telemetry.sdk.name: opentelemetry
	telemetry.sdk.language: cpp
  instr-lib     : B-1.0.0-rc4
}
{
  name          : B_1
  trace_id      : 44a3a91b385b506a98fa3b09890e09f0
  span_id       : 30d4a3a4d571cec9
  tracestate    :
  parent_span_id: 1b00491109e8bf80
  start         : 1636106799378343757
  duration      : 496717
  description   :
  span kind     : Internal
  status        : Unset
  attributes    :
  events        :
  links         :
  resources     :
	service.name: unknown_service
	telemetry.sdk.version: 1.0.0-rc4
	telemetry.sdk.name: opentelemetry
	telemetry.sdk.language: cpp
  instr-lib     : B-1.0.0-rc4
}

```
**Additional context**

**Comment by lalitb** [comment]
> Different tracers have different trace_ids. And all spans under one tracer share the same trace_id with the root span of the tracer.

I don't think the expectation is correct and is specified anywhere in the Specs. Once the given span is made active, the nested child span ( irrespective of the tracer it belongs to ) gets the span_id and trace_id from the currently active span. So in the quoted example, `span_b1` gets the parent_id and trace_id from `span_a1` even though they are created from different Tracers.

The correct way of implementing this would be using explicit context management as below:

```cpp
       auto span_a1  = get_tracer("A")->StartSpan("A_1");
       trace_api::StartSpanOptions options_a1;
       options_a1.parent   = span_a1.GetContext();
       usleep(100);
       auto span_b1  = get_tracer("B")->StartSpan("B_1");
       trace_api::StartSpanOptions options_b1;
	{
		auto span_a2  = get_tracer("A")->StartSpan("A_2", options_a1);
		usleep(100);
		span_a2->End();
	}
	span_a1->End();
	{
		auto span_b2  = get_tracer("B")->StartSpan("B_2", options_b1);
		usleep(100);
		span_b2->End();
	}
	span_b1->End();
```

To validate it further I just tested the behavior in Python , and the behavior is similar: 

```python
tracer1 = trace.get_tracer("tracer1")
tracer2 = trace.get_tracer("tracer2")

with tracer1.start_as_current_span("A_1"):
    with tracer2.start_as_current_span("B_1"):
       with tracer1.start_as_current_span("A_2"):
            with tracer2.start_as_current_span("B_2"):
                   print("Hello world from OpenTelemetry Python!")
```

Output:


<details>

```
Hello world from OpenTelemetry Python!
{
    "name": "B_2",
    "context": {
        "trace_id": "0x656e6ff67111353570baa2c54936a690",
        "span_id": "0x20cba4d63099f364",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x11c9d7b2b93de8e8",
    "start_time": "2021-11-05T17:29:29.380790Z",
    "end_time": "2021-11-05T17:29:29.380839Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "1.6.2",
        "service.name": "unknown_service"
    }
}
{
    "name": "A_2",
    "context": {
        "trace_id": "0x656e6ff67111353570baa2c54936a690",
        "span_id": "0x11c9d7b2b93de8e8",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x6b15715a850c38f0",
    "start_time": "2021-11-05T17:29:29.380757Z",
    "end_time": "2021-11-05T17:29:29.380853Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "1.6.2",
        "service.name": "unknown_service"
    }
}
{
    "name": "B_1",
    "context": {
        "trace_id": "0x656e6ff67111353570baa2c54936a690",
        "span_id": "0x6b15715a850c38f0",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xed7cd180ff688e98",
    "start_time": "2021-11-05T17:29:29.380724Z",
    "end_time": "2021-11-05T17:29:29.380860Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "1.6.2",
        "service.name": "unknown_service"
    }
}
{
    "name": "A_1",
    "context": {
        "trace_id": "0x656e6ff67111353570baa2c54936a690",
        "span_id": "0xed7cd180ff688e98",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2021-11-05T17:29:29.380677Z",
    "end_time": "2021-11-05T17:29:29.380867Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "1.6.2",
        "service.name": "unknown_service"
    }
}

```
</details>

**Comment by RandyLee16** [comment]
`We can't have multiple active spans at given time in same thread,`
Yes, that's the point.  Even we have multiple tracers at the given time in a single thread, we can only have one active span.  That depends on the way how traceId and spanId is generated in current opentelemetry code， right？
Here my problems comes:

1.why we cannot have an independent active span for each tracer in a single thread? or what's the advantage for that we have only one shared active span at the given time for a single thread？

2. Recently，I am enabling a sdk which can process requests in pipeline to track different request processing flow .  I tried to tracking different request processing flow with different tracers using opentelemetry. But these request processing flow sometimes get time overlaps in the same thread. Do you have any idea if I want to distinguish different request processing flow when using opentelemetry tracer?

**Comment by lalitb** [comment]
> Do you have any suggestions if I want to distinguish different request processing flow from each other when using opentelemetry tracer?

Ideally, the span should be made active only if we want to propagate its context (i.e parent_id and trace_id) to the child span. The span can record and eventually export all telemetry data (attributes, events, status) even if it's not made explicitly active. That means, we can make span "A_1" active just before creating span "A_2", and span "B_1" active just before creating span "B_2". And there is no need to make span "A_2" and span "B_2" active as they don't have any child spans. I have modified your code to reflect that (below), let me know if this solves the purpose.

```cpp
int main()
{
 	initTracer();

	auto span_a1  = get_tracer("A")->StartSpan("A_1");
        span_a1->AddEvent("Span a1 started");
	usleep(100);

	auto span_b1  = get_tracer("B")->StartSpan("B_1");
        span_b1->AddEvent("Span b1 started");

	{
                auto scope_a1 = get_tracer("A")->WithActiveSpan(span_a1);
		auto span_a2  = get_tracer("A")->StartSpan("A_2");
                span_a2->AddEvent("Span a2 is child of span a1");
		usleep(100);
		span_a2->End();
	}

	span_a1->End();

	{
               auto scope_b1 = get_tracer("B")->WithActiveSpan(span_b1);
	       auto span_b2  = get_tracer("B")->StartSpan("B_2");
               span_b2->AddEvent("Span b2 is child of span b1");
	       usleep(100);
	       span_b2->End();
	}

	span_b1->End();
}
```

You can also achieve the same behavior using the explicit context management example posted in my earlier comment.

**Comment by RandyLee16** [comment]
Thanks, latitb.  These two methods works for my example.
I'm considering if we have better pratise.  When the application scenario becomes complicated，extra work these methods bring grows up,  making it not that friendly to use.

**Comment by lalitb** [comment]
> I'm considering if we have better pratise. 

Thanks for the feedback @RandyLee16 . The current implementation for the active spans is driven by the Context API in the specs ( https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#context-interaction ). There can be only one span active in context at a given time. If you see any improvement required here, I would suggest you raise an issue in the Specs repo for further discussion.

**Comment by lalitb** [comment]
@RandyLee16  - closing this, please raise/reopen if you still find any issue.
