### ISSUE TITLE
Implement Cloud Trace exporter

### ISSUE THREAD

**Issue by IlyaKobelevskiy** [open-telemetry/opentelemetry-cpp#106]
Refer to https://github.com/open-telemetry/opentelemetry-python/tree/master/ext/opentelemetry-exporter-cloud-trace

**Comment by anshulkumar19** [comment]
@reyang @lalitb I would like to work on this, can you assign it to me.

**Comment by lalitb** [comment]
Sure @anshulkumar19. Assigned to you. Thanks for the initiative on this. Just for your information, this needs to be contributed in https://github.com/open-telemetry/opentelemetry-cpp-contrib repo, and not this repo.

**Comment by anshulkumar19** [comment]
@lalitb Google repository (https://github.com/GoogleCloudPlatform/opentelemetry-operations-cpp) implementing gcp exporter. It would be duplication, any opinion?

**Comment by reyang** [comment]
> @lalitb Google repository (https://github.com/GoogleCloudPlatform/opentelemetry-operations-cpp) implementing gcp exporter. It would be duplication, any opinion?

Looks like the GCP exporter is not run by the OpenTelemetry community. Please reach out to @aabmass and @jsuereth and see what's their guidance.

Closing this issue now.

**Comment by aabmass** [comment]
> @lalitb Google repository (https://github.com/GoogleCloudPlatform/opentelemetry-operations-cpp) implementing gcp exporter. It would be duplication, any opinion?

Yup, https://github.com/GoogleCloudPlatform/opentelemetry-operations-cpp is the correct place
