### ISSUE TITLE
The document say gcc 4.8 is supported but failed to run with gcc 4.9.2

### ISSUE THREAD

**Issue by hcoona** [open-telemetry/opentelemetry-cpp#1066]
It's easy to understand so didn't follow the template.

GCC didn't support `std::regex` at least in v4.9.2, see https://gcc.gnu.org/onlinedocs/gcc-4.9.2/libstdc++/manual/manual/status.html 7.11.2.

**Comment by hcoona** [comment]
I found the option `HAVE_WORKING_REGEX`. It detects against gcc 4.8, so not working on gcc 4.9.2. I think it better to detect against libstdc++ instead of the compiler version.

**Comment by lalitb** [comment]
>  I think it better to detect against libstdc++ instead of the compiler version.

Yes, there are better ways to detect regex support than to check the compiler version.

**Comment by hcoona** [comment]
`_GLIBCXX_RELEASE` could do that but only provided after GCC v7.1. (https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_macros.html)

`__GLIBCXX__` is the release date. However, some minor updates could be later than next major release. For example:

* GCC 4.9.4: 2016-08-03
* GCC 7.1.0: 2016-04-27

Google cpplint mark that only versions <= 4.9 have such problem. (https://github.com/google/styleguide/pull/432)

The GCC document shows that until GCC 11.2.0 `std::regex_match` is not supported, which is absolutely wrong. (https://gcc.gnu.org/onlinedocs/gcc-11.2.0/libstdc++/manual/manual/status.html)

**Comment by hcoona** [comment]
I'll just exclude gcc 4.9.x just like 4.8.x
