### ISSUE TITLE
Question: how to make a slow log by span chain?

### ISSUE THREAD

**Issue by hcoona** [open-telemetry/opentelemetry-cpp#1070]
Assume there is a chain of micro-services. The user request flows as following:

```
User Request  -> A -> B -> C
                           |
User Response <- A <- B <- C
```

We want to find why some request slower than expect. We know the accumulated time in service A. If the accumulated time is longer than a threshold (for example 3s), we would like to print the tracing spans to help figure out which span/event cause the slow.

Is it any possible with help of opentelemetry-cpp API & SDK? We didn't want to adopt Zipkin or any other external services because of the costs. As shown above, we already got all necessary information just when replying user response in service A.

The basic idea is to pass recorded spans across services by RPC to collect a full span tracing chain. Finally print the chain just before return the response. I looked a few into `OStreamSpanExporter` & `InMemorySpanExporter`, but neither of them satisfy the scenario. `OStreamSpanExporter` would print all spans periodically. `InMemorySpanExporter` is just a joke. I must move it into `SpanProcessor`, thus there is no way to access the exporter later to extract the recorded data. I need a further help on how to make the idea possible.

> I understand the desgin of `SpanExporter` now. It would not be a dangling pointer because the `TracerProvider` is global persisted.

**Comment by hcoona** [comment]
I found some details about the above idea. Still want to know if there is a better way.

For passing the spans across micro-services, I need to customize a propagator to extract/restore the local span tree into/from response message.

For collecting span tree, I need to customize an exporter like `InMemorySpanExporter`. The exporter needs to maintain a forest for span trees lookup & extraction. Before returning the response message, I must ensure the root span is end-up because the processor would send the recordable to exporter during the end step. Then lookup & extract the span tree from exporter according to root span context.

**Comment by lalitb** [comment]
Your idea is correct. Span data needs to be propagated across services using one of the supported propagators. As you rightly mentioned, both `Console` and `Memory` exporters have basic functionality, not meant for the production environment. You may have to tweak either of them to meet the requirement, or else look for other available exporters for opentelemetry-collector from here ( https://opentelemetry.io/registry/?language=collector&component=exporter).

**Comment by lalitb** [comment]
Closing as the query is answered
