### ISSUE TITLE
Need fine-grained HAVE_CPP_STDLIB

### ISSUE THREAD

**Issue by hcoona** [open-telemetry/opentelemetry-cpp#1071]
**Is your feature request related to a problem?**

The `std::shared_ptr` & `std::unique_ptr` are well-supported by wide-spread compilers in c++11, while `std::string_view` & `std::variant` are unavailable until c++17. We currently use a coarse-grained switch `HAVE_CPP_STDLIB` to control all these things. As a result, we cannot enable any of them.

Using our private implemented `nonstd::shared_ptr` would lead to interoperability issue with `std::shared_ptr`, which is quite annoying.

**Describe the solution you'd like**

I'd like to split `HAVE_CPP_STDLIB` into more fine-grained switches:

* OPENTELEMETRY_HAVE_CXX11
  * OPENTELEMETRY_HAVE_STD_SHARED_PTR
  * OPENTELEMETRY_HAVE_STD_UNIQUE_PTR
* OPENTELEMETRY_HAVE_CXX17
  * OPENTELEMETRY_HAVE_STD_STRING_VIEW
  * OPENTELEMETRY_HAVE_STD_VARIANT
* OPENTELEMETRY_HAVE_CXX20
  * OPENTELEMETRY_HAVE_STD_SPAN

**Describe alternatives you've considered**

Didn't find a better approach.

**Comment by hcoona** [comment]
I think the switches could be smarter to automatically detect the value from built-in macros & pragmas.

* 0: Automatically
* 1: Force STD
* 2: Force Non-STD
* 3: Force Abseil-cpp
* 4: Force GSL

**Comment by lalitb** [comment]
> I personally would prefer STD->Abseil/GSL->Non-STD.

It's encouraged to use non-std libraries whenever possible to maintain ABI compatibility ( https://github.com/open-telemetry/opentelemetry-cpp/blob/main/docs/abi-policy.md#application-binary-interface-abi-policy ).

**Comment by lalitb** [comment]
> We currently use a coarse-grained switch HAVE_CPP_STDLIB to control all these things. As a result, we cannot enable any of them.

Do we have a use case why do we want to enable the STL components individually?

**Comment by hcoona** [comment]
1. I have to do tedious converting between `std::string_view` and `nonstd::string_view`. (actually `absl::string_view` in my case, because we are using c++14)
2. `nonstd::shared_ptr` and `nonstd::unique_ptr` breaks the strict aliasing assumption, which prevent enable strict aliasing optimization in our code.

**Comment by hcoona** [comment]
It's good to maintain ABI compatibility. If we provide such switches, we could still make the default setting ABI compatible.

**Comment by ThomsonTan** [comment]
For the suggested flag like `OPENTELEMETRY_HAVE_STD_SHARED_PTR`, could they be detected by CMake automatically so no need to expose these flags to developers?

**Comment by owent** [comment]
> For the suggested flag like `OPENTELEMETRY_HAVE_STD_SHARED_PTR`, could they be detected by CMake automatically so no need to expose these flags to developers?

```cmake
check_cxx_source_compiles(
  "
#include <iostream>
#include <string_view>
int main() {
constexpr std::string_view unicode[] {\"▀▄─\", \"▄▀─\", \"▀─▄\", \"▄─▀\"};

for (int y{}, p{}; y != 6; ++y, p = ((p + 1) % 4)) {
  for (int x{}; x != 16; ++x)
    std::cout << unicode[p];
  std::cout << std::endl;
}
return 0;
}"
  LIBATFRAME_UTILS_TEST_STL_STRING_VIEW)
```

We use these cmake script to test `std::string_view` in our project, maybe we can also use it to test `std::string_view`, `std::variant` or `std::span` ?
BTW: I think all the environment thaa supported by opentelemetry-cpp has `std::shared_ptr` and `std::unique_ptr` , but not all the environments have `std::make_span`. Is it necessary to test `std::shared_ptr` or `std::unique_ptr` ?

**Comment by marcalff** [comment]
Trying to use opentelemetry-cpp on several platforms, which have varying degrees of STL support, I am facing the same issues.

Currently:

- `HAVE_CPP_STDLIB` is coarse grained, making it impossible to use some C++11/14/17 features without a full C++20 STL.
- `HAVE_CPP_STDLIB` pollutes the application namespace, a `OPENTELEMETRY` prefix is needed.

Proposal for a fix:

In CMake, change the option to:

- WITH_STL=OFF (unchanged)
- WITH_STL=CXX11 (new)
- WITH_STL=CXX14 (new)
- WITH_STL=CXX17 (new)
- WITH_STL=CXX20 (new)
- WITH_STL=ON (unchanged, means WITH_STL=CXX20 as currently)

Use pre processor symbols like:

- OPENTELEMETRY_HAVE_CXX11
- OPENTELEMETRY_HAVE_CXX14
- OPENTELEMETRY_HAVE_CXX17
- OPENTELEMETRY_HAVE_CXX20

When a feature is not available in the STL library, for example when building WITH_STL=CXX17, alternate implementations needed to satisfy nostd can be chosen depending on WITH_GSL, as currently for nostd::span.
