### ISSUE TITLE
Mark tags to bazel targets

### ISSUE THREAD

**Issue by hcoona** [open-telemetry/opentelemetry-cpp#1072]
**Is your feature request related to a problem?**

The project could build with GCC4.8 + CMake but failed to build with GCC4.8+Bazel. I cannot understand it although I know the higher version of GRPC could not compile with GCC4.8.

I think most of the core components rely on nothing than some extremely basic libraries such as abseil, gsl, gtest & google benchmark. We at least should support bazel build for these targets.

**Describe the solution you'd like**

I'd like to mark the bazel targets with tags, so we can easily to exclude some components. For example, excluding OTLP would significantly simplify dependencies.

** Example **

```python
cc_test(
    name = "otlp_recordable_test",
    srcs = ["test/otlp_recordable_test.cc"],
    deps = [
        ":otlp_recordable",
        "@com_google_googletest//:gtest_main",
    ],
    tags = ["otlp"],
)
```

```bash
bazel build //... --build_tag_filters=-otlp
```

**Comment by lalitb** [comment]
Thanks for bringing this up. 

Bazel build for GCC4.8 was disabled [in this PR](https://github.com/open-telemetry/opentelemetry-cpp/pull/953) once grpc and bazel version was upgraded. As you rightly mentioned higher version of gRPC doesn't compile with gcc4.8.

For CMake, we use the latest gRPC version for > gcc5.1 and older compatible gRPC version for gcc4.8  as done [in this PR](https://github.com/open-telemetry/opentelemetry-cpp/pull/927)

Though I am not a bazel expert ( and we are missing expertise for that in the forum ), your approach for being able to choose/exclude the bazel target based on the platform looks a good approach.
