### ISSUE TITLE
Bazel built cURL could rely on zlib because gRPC already included zlib

### ISSUE THREAD

**Issue by hcoona** [open-telemetry/opentelemetry-cpp#1073]
See https://github.com/grpc/grpc/blob/7a40f50cb32ad7aadcce15ab57abcadaff1042aa/bazel/grpc_deps.bzl#L83

**Comment by lalitb** [comment]
@hcoona - Can you please elaborate the ask here. Thanks.

**Comment by lalitb** [comment]
Closing for incomplete information. Please feel free to open it with more information.
