### ISSUE TITLE
Add a Changelog or Release Schedule

### ISSUE THREAD

**Issue by ankit-bhargava** [open-telemetry/opentelemetry-cpp#108]
**Is your feature request related to a problem?**

Currently, there is no changelog for the C++ client.  New contributors therefore have to pore over the codebase to determine which project features have been implemented.  When looking for ways to contribute, they are forced to scroll through the issues list without any context as to which ones are priorities for the community.  

**Describe the solution you'd like**

Adding a [changelog](https://keepachangelog.com/en/1.0.0/) similar to the ones present in the [Java](https://github.com/open-telemetry/opentelemetry-java/blob/master/CHANGELOG.md) and [Python](https://github.com/open-telemetry/opentelemetry-python#release-schedule) clients (under the "Release Schedule" sections) gives new contributors a sense of how mature the project is and which features are currently under development.  They also see which issues are slated for development either in the present of the near future and can focus their efforts there.

**Describe alternatives you've considered**

Tagging issues with priority or building out a feature completeness matrix will mitigate the current issues but still fail to outline the project's overarching trajectory which is important for contributors as they can gauge where and when their expertise will be most impactful.

**Comment by HudsonHumphries** [comment]
Recommendation for Change-Log, [NextRelease](https://github.com/marketplace/nextrelease-io) - a GitHub Marketplace App.

NextRelease is a free tool, that sets up Change-Log and Release notes for a project. For setup, follow this [link](https://github.com/marketplace/nextrelease-io) and add it to the repository. Then setup the labels that match with the type of release you want with them.

NextRelease works right out of the box and requires minimal setup to get a Change-Log setup. This tool will allow the C++ repository to have a good change-log with minimal effort required. This tool also does not require contributors to change their workflow. It works directly from labels, making the workflow simple. It is also an automatic tool that will update when new PRs are merged into the repo, keeping the maintenance low. 

A downside for this service is that the functionality is simple, so there is not a lot of customization when it comes to releases. There are only 3 types of releases and each require a specific label.

@alolita

**Comment by lalitb** [comment]
#392 fixes it.
