### ISSUE TITLE
Logger: Support for Instrumentation library.

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1087]
1. Updating loggerProvider::GetLogger()  in API and SDK for optional schema_url parameter.
2. Add Instrumentation Library support as for trace implementation:
https://github.com/open-telemetry/opentelemetry-cpp/blob/089b04d77fc9f2e0e4e4d87b1fff5b10a79ab3e1/sdk/src/trace/tracer_provider.cc#L39
3. Propagate instrumentation library to the exporter through recordable interface ( adding Recordable::SetInstrumentationLibrary() ) method.

**Comment by esigo** [comment]
1 shouldn't be `loggerProvider::GetLogger()`?

**Comment by lalitb** [comment]
yes thanks. fixed now.

**Comment by esigo** [comment]
could you please assign it to me? thanks
