### ISSUE TITLE
Add Doxygen for C++ OpenTelemetry API/SDK documentation

### ISSUE THREAD

**Issue by Brandon-Kimberly** [open-telemetry/opentelemetry-cpp#109]
**Is your feature request related to a problem?**
Yes. Currently the C++ repository contains little internal documentation due to ongoing development. This can make it difficult for prospective contributors to get started with the project.

**Describe the solution you'd like**
The incorporation of, and requirement to use, Doxygen will help contributors constructively create documentation as features are built out. This makes it easier to build complete and comprehensive documentation.

**Describe alternatives you've considered**
I explored two other alternatives to using Doxygen:

1. Using a different documentation generator. Other docs generators exist for C++ but none have quite the popularity or accessibility of Doxygen. Doxygen is open-source, works on all major OS platforms, is compatible with a variety of languages, and is the de facto standard for C++ documentation generation. Contributors will likely be more comfortable and more experienced with using Doxygen compared to another documentation generators.
2. Not using a documentation generator. This approach is sub-optimal because it requires contributors to retroactively create documentation for built functionality. This documentation may never be created and is therefore not helpful to newcomers. Additionally, Doxygen can help to produce comprehensive, low-level documentation on class structure and class functions. This type of documentation is time-consuming and tedious to manually create.

**Additional context**
Other OpenTelemetry repositories have included docs generator tools into their code ([such as Java with Javadoc](https://github.com/open-telemetry/opentelemetry-java)).

**Comment by lalitb** [comment]
closing as this is fixed majorly by #562, will add a separate ticket to add SDK documentation.
