### ISSUE TITLE
Metrics SDK: Add Metrics exemplar

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1093]
Specs: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exemplar

- A metrics **exemplar** is a trace that is representative of the metrics being collected. The spec requires that exemplars be implemented in a way such that they may be disabled and that if disabled they should have no performance impact (collection should be disabled, not just export). When enabled, the exemplars will come from the currently active context.
_Properties_: Value, Time, Attributes, Trace ID, Span ID

- **ExemplarFilter** determines if a measurement should be sampled
_Properties_ - value of measurement, attributes of measurement, context of measurement, timestamp

- **ExemplarReservoir** provides a method to offer measurements to the reservoir and to collect accumulated exemplars

**Comment by lalitb** [comment]
The record API / SDK needs to be modified too to pass span context, which would be required to get trace id and span id.

```cpp
template <class T>
class UpDownCounter : public SynchronousInstrument
{
  virtual void Add(T value, opentelemetry::context::Context context) noexcept = 0;
  virtual void Add(T value, const common::KeyValueIterable &attributes, opentelemetry::context::Context context) noexcept = 0;
}
```

**Comment by esigo** [comment]
> The record API / SDK needs to be modified too to pass span context, which would be required to get trace id and span id.
> 
> ```c++
> template <class T>
> class UpDownCounter : public SynchronousInstrument
> {
>   virtual void Add(T value, opentelemetry::context::Context context) noexcept = 0;
>   virtual void Add(T value, const common::KeyValueIterable &attributes, opentelemetry::context::Context context) noexcept = 0;
> }
> ```

@lalitb Shoudn't the `context` be `opentelemetry::trace::SpanContext`?
