### ISSUE TITLE
Jaeger exporter: attributes of unsupported types are silently forgotten

### ISSUE THREAD

**Issue by PetrSilar** [open-telemetry/opentelemetry-cpp#1104]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.

Actually, it does not matter, it's a consistent bug.

- Windows 10, MSVC 2022, c++17
- Ubuntu 21.10, gcc 11.2, c++17
- CMake 3.21.3
- opentelemetry-cpp 1.1.0
- thrift 0.15.0

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

Add attribute of `int32_t type to a span. e.g.:

- in examples/common/foo_library/foo_library.cc change function f1() as follows:
```
void f1()
{
  auto span = get_tracer()->StartSpan("f1");
  auto scoped_span = trace::Scope(span);
  int32_t myValue = 42;
  span->AddAttribute("some.attribute", myValue);
}
```
- have some jaeger agent running and listening on localhost:6831
- have jaeger collector and query working
- run examples/jaeger

**What is the expected behavior?**
What did you expect to see?

- Jaeger UI shows `some.attribute` with value 42 among other span's attributes.

**What is the actual behavior?**
What did you see instead?

- There is no such attribute in Jaeger UI
- No warning during compilation
- No assert nor log nor anything during runtime

**Additional context**

- in exporters/jaeger/src/recordable.cc
  - in function `JaegerRecordable::PopulateAttribute()` only some types of attributes are stored as tags.
  - unsupported types are just: `// TODO: extend other AttributeType to the types supported by Jaeger.`

There should be some assert at least.
Please consider support at least all non-vector types. This actually means static_cast of few integer types of different size and with/without the sign.
Vector-type attributes may be stored as a list of normal attributes with index suffix in name, i.e. `my.vector.0`, `my.vector.1`, etc. Just a thought.

**Comment by esigo** [comment]
@PetrSilar Thanks for bringing this up. I will raise a PR to add support for the other types.

**Comment by esigo** [comment]
@lalitb could you please assign this issue to me?
thanks
