### ISSUE TITLE
Add labels to issues

### ISSUE THREAD

**Issue by HudsonHumphries** [open-telemetry/opentelemetry-cpp#111]
**Is your feature request related to a problem?**
Yes. Currently there are very few labels on the issues open in this repository. This makes it very hard to navigate the issues, especially for a newcomer to the project. 

**Describe the solution you'd like**
For the current issues the Maintainers would need to go through the open issues and label them. For future issues,
whenever an issue is opened, descriptive labels should be added to them. 

**Describe alternatives you've considered**
A great way to assist the Maintainers in adding labels is have contributors add their own labels when creating an issue. This would make the work of adding labels extremely easy for the Maintainers. When creating an issue there could be a reminder to add labels to it.

**Additional context**
Many other Open Telemetry projects have many labels on there issues, here are a few:
[JavaScript](https://github.com/open-telemetry/opentelemetry-js/issues?page=3&q=is%3Aissue+is%3Aopen)
[.NET](https://github.com/open-telemetry/opentelemetry-dotnet/issues)
[Collector](https://github.com/open-telemetry/opentelemetry-collector)

**Comment by lalitb** [comment]
This is being done now.
