### ISSUE TITLE
Make a Quick-Start Guide

### ISSUE THREAD

**Issue by ankit-bhargava** [open-telemetry/opentelemetry-cpp#112]
**Is your feature request related to a problem?**

New contributors currently have little guidance on what the library is or how to use it.  As of now, the only way to learn about basic instrumentation and collection is to either carefully examine the code or work over the single tracer example.  This, however, covers a very narrow set of features.  Users must reference other language documentation for a comprehensive overview of OpenTelemetry features with example usage.

**Describe the solution you'd like**

The [Java](https://github.com/open-telemetry/opentelemetry-java/blob/master/QUICKSTART.md) quick-start is a model example which marries explanations of fundamental OpenTelemetry concepts with short, digestible code blocks.  After reading over this, users have enough information to get immediate results from the OpenTelemetry library.  The quick-start also teaches users what their options are and builds a solid enough foundation for them to look over more technical documentation on their own.

**Describe alternatives you've considered**

Without a quick-start, users can look over documentation and examples independently.  It takes longer to obtain useful results from the library and its much harder to reconcile the specification requirements with their concrete applications.  Users also do not have a single location to refer back to when integrating the library into their workflows which can be frustrating and time consuming.

**Comment by lalitb** [comment]
Closing as we do have the getting started doc now https://opentelemetry-cpp.readthedocs.io/en/latest/GettingStarted.html for API instrumentation. Will add a separate ticket for SDK documentation,
