### ISSUE TITLE
Exporters build error

### ISSUE THREAD

**Issue by Grace-1024** [open-telemetry/opentelemetry-cpp#1122]
when I buid my project by bazel, I get an error like this:

```
ERROR: 
/root/.cache/bazel/_bazel_root/11e5ed4eaaab71c19c0ccc3ce7d4bed3/external/io_opentelemetry_cpp/exporters/otlp/BUILD:43:11: 
no such target '@com_github_opentelemetry_proto//:trace_service_grpc_cc': target 'trace_service_grpc_cc' not declared in package '' (did you mean 'trace_service_proto_cc'?) defined by 
/root/.cache/bazel/_bazel_root/11e5ed4eaaab71c19c0ccc3ce7d4bed3/external/com_github_opentelemetry_proto/BUILD.bazel and referenced by '@io_opentelemetry_cpp//exporters/otlp:otlp_grpc_exporter'
```

It seems like the dependence of exporters is missing?

**Comment by lalitb** [comment]
Have you followed steps mentioned [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md#incorporating-into-an-existing-bazel-project) to incorporate otel-cpp in existing bazel project. If yes, please share the WORKSPACE file used?

**Comment by esigo** [comment]
@Grace-1024 would it be possible to try changing the order of the loads?

**Comment by Grace-1024** [comment]
> 

Yes, I change the order of the loads and then it works well, thanks for your help, I'll close this issue.
