### ISSUE TITLE
Add external documentation for API/SDK functionality

### ISSUE THREAD

**Issue by Brandon-Kimberly** [open-telemetry/opentelemetry-cpp#113]
**Is your feature request related to a problem?**
Yes. Currently there is minimal documentation about the built functionality in the C++ API/SDK. This can make it difficult for users and contributors alike to get started with the library.

**Describe the solution you'd like**
I would like some external documentation similar to Python’s [readthedocs](https://opentelemetry-python.readthedocs.io/en/stable/index.html) (https://opentelemetry-python.readthedocs.io/en/stable/index.html) pages. This feature is easily expandable and will allow for more documentation to be created as more functionality is built out.

**Describe alternatives you've considered**
1. Simply using the [OpenTelemetry specification docs](https://github.com/open-telemetry/opentelemetry-specification) (https://github.com/open-telemetry/opentelemetry-specification). I believe this approach is sub-optimal for two reasons. First, not all functionality listed in the specification has been built in the C++ repository. This approach can make it difficult for contributors and users to gauge which features are built and which are not. Second, the languages OpenTelemetry supports are very different and each have their own idiomatic approaches to implementing the spec. The specification documents does not elaborate on the C++ specific implementation details. This can cause confusion for contributors and users.

2. Docs generation tools such as [Doxygen](https://www.doxygen.nl/index.html) (https://www.doxygen.nl/index.html). However, these tools provide very low-level documentation not suitable for many users. These docs can also be difficult to navigate. Because of this, they should be used to bolster existing documentation, not stand on their own.

**Additional context**
I believe examples are the best place to start adding documentation. This helps users understand what the library has to offer and how they can use the library in their own programs. Additionally, it gives contributors an idea of how the components interact and the purpose of each component. This combined with Doxygen would create quite comprehensive documentation.

**Comment by eyjohn** [comment]
@lalitb is this perhaps a candidate for cleanup given that we now have:
https://opentelemetry-cpp.readthedocs.io/en/latest/

**Comment by lalitb** [comment]
Yes right. I did few cleanups yesterday, seems this got missed out. We don't have sdk documentation ( as sdk is still evolving) but will create a ticket specific to that.
