### ISSUE TITLE
Could internal log level be set by runtime?

### ISSUE THREAD

**Issue by owent** [open-telemetry/opentelemetry-cpp#1138]
**Is your feature request related to a problem?**

We usually need debug log when testing and integrating opentelemetry-cpp, and just need error log after that.But now the internal log  level can only be set when compiling, which is usual WARNING.

**Describe the solution you'd like**

Maybe add `GlobalLogHandler::SetLogLevel(...)` or add `log_level` to `GlobalLogHandler::SetLogHandler(...)` ?

**Comment by lalitb** [comment]
The original intention of the internal logger was to configure the custom error handler as specified in specs ( https://github.com/open-telemetry/opentelemetry-specification/blob/v1.6.x/specification/error-handling.md#configuring-error-handlers ) and not to use it for debugging/testing. So, the levels were kept compile-only, to ensure we have header-only logging.
Said that I don't see any issue extending it further to have the levels configurable at runtime if it helps to debug. Would just be cautious not to make it as another full-fledged logger implementation ( along with otel logger API ).

**Comment by ThomsonTan** [comment]
If the SDK allows user to register customized error handlers, then they can do any whatever filtering there like the dynamic log level, is this correct?

**Comment by lalitb** [comment]
> If the SDK allows user to register customized error handlers, then they can do any whatever filtering there like the dynamic log level, is this correct?

Yes, but the custom handler will only receive the logs at the level configured during compile time.

**Comment by owent** [comment]
> The original intention of the internal logger was to configure the custom error handler as specified in specs ( https://github.com/open-telemetry/opentelemetry-specification/blob/v1.6.x/specification/error-handling.md#configuring-error-handlers ) and not to use it for debugging/testing. So, the levels were kept compile-only, to ensure we have header-only logging. Said that I don't see any issue extending it further to have the levels configurable at runtime if it helps to debug. Would just be cautious not to make it as another full-fledged logger implementation ( along with OTel logger API ).

The java example in https://github.com/open-telemetry/opentelemetry-specification/blob/v1.6.x/specification/error-handling.md#configuring-error-handlers seems to use a global variable `io.opentelemetry.level` to control the log level. Could we use the same way or use another static variable to set log level here?(Just like the global log handle)

**Comment by lalitb** [comment]
>  Could we use the same way or use another static variable to set log level here(Just like the global log handle)? I think we can still keep header-only logging by this way.

Yes, that would be good. Thanks.
