### ISSUE TITLE
Add unit-test for Zipkin exporter

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1143]
As of now, Zipkin exporter only has unit tests for recordable. Need to add tests for the exporter interface. It can use the test http-server provided as part of this repo, and also used for otlp-http exporter tests ( https://github.com/open-telemetry/opentelemetry-cpp/blob/main/exporters/otlp/test/otlp_http_exporter_test.cc )

**Comment by esigo** [comment]
@lalitb could you please assign this to me? thanks
