### ISSUE TITLE
benchmark tests as part of the CI

### ISSUE THREAD

**Issue by esigo** [open-telemetry/opentelemetry-cpp#1170]
**Is your feature request related to a problem?**
It is hard to overstate the importance of benchmarking and monitoring the benchmarks over time. This becomes even more important to us as it is expected/desired that telemetry operations should have minimal adverse impact on performance. In order to quantify and measure how well we're doing there, benchmark tests have to be added as part of the CI.

**Describe the solution you'd like**

This can be done using [continuous-benchmark](https://github.com/marketplace/actions/continuous-benchmark) where benchmark results can be stored on every merge to the main branch. To avoid noising the main branch, [gh-pages](https://stackoverflow.com/questions/4750520/git-branch-gh-pages) branch can be used to push the benchmark results. This has already been used in [python SIG](https://open-telemetry.github.io/opentelemetry-python/benchmarks/index.html).

Tasks which require privilege:
- Activating githbub-pages
- Creating gh-pages branch

**Describe alternatives you've considered**
Which alternative solutions or features have you considered?

**Additional context**
Add any other context about the feature request here.

**Comment by esigo** [comment]
This can be assigned to me.

**Comment by esigo** [comment]
The graphs for the benchmark tests we already have in the repo can be found [here](https://esigo.github.io/opentelemetry-cpp/benchmarks/index.html)

**Comment by lalitb** [comment]
Please see if this is what is required:

![gh-pages](https://user-images.githubusercontent.com/1196320/149207632-fd2d7ebd-e7c8-4b41-b9a1-3e1aee40b910.JPG)

**Comment by esigo** [comment]
Thanks @lalitb, yes it is.
