### ISSUE TITLE
cmake integration not working

### ISSUE THREAD

**Issue by VivekSubr** [open-telemetry/opentelemetry-cpp#1179]
**Describe your environment** 
Environment - Windows subsystem for linux, ubuntu.
Build System - integrating into a cmake project
version - main

**Steps to reproduce**
git clone repo, build using cmake.
cmake build will generate cmake export file opentelemetry-cpp-config.cmake
Integrate into your own cmake project using steps given in: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md
cmake build

**What is the expected behavior?**
Build should go through

**What is the actual behavior?**
Build fails with error,
 File or directory
  /home/vivek/Client-Server/module/opentelemetry-cpp/include referenced by
  variable OPENTELEMETRY_CPP_INCLUDE_DIRS does not exist !

And indeep, there is no such dir, these are the include dirs in the project - 
vivek@LAPTOP-7E1991MU:~/Client-Server/module/opentelemetry-cpp$ find . -name "include"
./ext/include
./sdk/include
./exporters/jaeger/include
./exporters/memory/include
./exporters/etw/include
./exporters/zipkin/include
./exporters/elasticsearch/include
./exporters/otlp/include
./exporters/ostream/include
./exporters/prometheus/include
./api/include

Looking into the cmake file,
set_and_check(OPENTELEMETRY_CPP_INCLUDE_DIRS "${PACKAGE_PREFIX_DIR}/include")
set_and_check(OPENTELEMETRY_CPP_LIBRARY_DIRS "${PACKAGE_PREFIX_DIR}/lib")

It seems to be wrongly setting the include? Or is there some step being missed here?

**Comment by lalitb** [comment]
Please ensure opentelemetry-cpp was installed properly. There should be ${PACKAGE_PREFIX_DIR}/include directory created during installation.

**Comment by VivekSubr** [comment]
Sorry, I missed the 'cmake install', got confused since it said it was optional. It's working fine.
