### ISSUE TITLE
Errors about devinit.exe missing on build window using VS 2022

### ISSUE THREAD

**Issue by jspaith** [open-telemetry/opentelemetry-cpp#1192]
Not urgent.  Full disclosure I have a weird setup - I quickly gave up on making gtest building and disabled via CMake.  *I'm otherwise unblocked running `example_simple.exe` so I'm happy.*

But I do want to record as part of "Where there's smoke there maybe fire."

I have a VS2022 based build window, though as I said gtest not configured.  When I do a "cmake .." I get errors about `devinit.exe` not being present coming out in middle of log.  This seems to be by design though, as a quick look in my VS2022 folders show there's no such exe.  VS2019 though there is the EXE.

As an additional data point, I have previously setup vcpkg and have environment variables pointing to that dir.  So by time I'm running this repo, a lot of initial setup is done.  My vcpkg is on latest master branch as of entering this bug.  I also tried `vcpkg install gtest` directly, but as it seems sensitive to versions from my reading of some of your other docs.  And I don't care about making gtest work as I said I just disabled via CMake.

I'm not sure if gtest would've been successfully created for me without this error, though.  So if there's a path to getting gtest auto-built by fixing this then that would suggest it's a touch higher prio.

Relevant lines of my cmake run below, though I've copied entire log into attachment.
[cmake-error-log.txt](https://github.com/open-telemetry/opentelemetry-cpp/files/7989298/cmake-error-log.txt)

```
Installing build tools and dependencies...
Running without Administrative privilege...
Building with vs2019 Enterprise...
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.8
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[ERROR:devinit.bat] File not found : "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\devinit\devinit.exe"
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
[ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
[ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
```

**Comment by ThomsonTan** [comment]
@jspaith our setup script is still launching vs2019 even vs2022 is available. I have PR attached to address this issue. Please let us know if it fixes the issue.
