### ISSUE TITLE
Errors in SDK documentation

### ISSUE THREAD

**Issue by sirzooro** [open-telemetry/opentelemetry-cpp#1199]
I was trying to write some code to initialize tracer using code from https://opentelemetry-cpp.readthedocs.io/en/latest/sdk/GettingStarted.html as an example. During this I found few errors in code snippets there:

- `resource_attributes` initializer uses colons instead of commas to separate key and value;
- samplers (e.g. `always_on_sampler`) have to be allocated dynamically and stored in `std::unique_ptr<>`;
- `tracer_provider` has to be allocated dynamically and stored in `nostd::shared_ptr<>`.

**Comment by esigo** [comment]
@sirzooro thanks for bringing this to our attention. I will raise a PR to fix it, if you have not planned to raise one already.

**Comment by sirzooro** [comment]
No, I did not create any.
