### ISSUE TITLE
Invalid parent ID (all zeros)

### ISSUE THREAD

**Issue by swgoldwood** [open-telemetry/opentelemetry-cpp#1223]
Hey, could anyone point me to real world repo using opentelemetry-cpp? I'd like to study code already successfully using it.

I'm struggling to produce usable traces into Jaeger. Each time i create a span and scope, it produces a new trace in Jaeger, so I'm unable to get anything useful other than for a single function runtime. It seems like the way I am using it doesn't handle parents correctly.

The way I'm using it is as follows:

- there is tracer object created for each user request. This is stored in TLS.
- i start a span/scope that lives for the duration of the request
- i create new span and scope using this tracer, for each function I want to measure
- each span/scope produces just a single trace in Jaeger - pretty useless

I must be doing something wrong!

Thanks!

**Comment by lalitb** [comment]
Example code for parent-child span creation with Jaeger is [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/jaeger/main.cc). But looks like you are doing steps correctly. Which OS/compiler you are testing with. There are issues with Ubuntu 18.04.5 LTS/ gcc 7.5.0 where TLS is not handled correctly due to a bug in the compiler. More details along with a workaround #1014

**Comment by swgoldwood** [comment]
> Example code for parent-child span creation with Jaeger is [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/jaeger/main.cc). But looks like you are doing steps correctly. Which OS/compiler you are testing with. There are issues with Ubuntu 18.04.5 LTS/ gcc 7.5.0 where TLS is not handled correctly due to a bug in the compiler. More details along with a workaround #1014

Thanks. This seems to be the same issue I am having.

I'm using Release built static libs. GCC 6.3 on RHEL6.10. I'll try out the workaround and get back. Thanks a lot for quick reply

**Comment by swgoldwood** [comment]
Nope my issue is something else. Very strange. I'm going to look into it more.

**Comment by swgoldwood** [comment]
Any ideas what I could do to debug this? My issue is very similar to the issue you linked. Parent id is zero'd out just like that issue.

What line of code populates the parent_id? Debugging the Stack i can see objects getting added appropriately. This seems correct.

Thanks a lot! This library will be awesome when it works!

**Comment by lalitb** [comment]
Parent-id gets populated [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/cf7f9e28ab6610e81a9fc2799b31bbcbef7cf613/sdk/src/trace/tracer.cc#L40).

Meanwhile, if you are able to build [sample example](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/simple/main.cc), and share the console output after running, it would give some idea.

**Comment by swgoldwood** [comment]
I finally got this working. I pulled out the StartSpan function in tracer.cc into the header file, and it worked. So I'm just going to use my local revision for time being!

**Comment by swgoldwood** [comment]
In case anyone sees this. The fix was likely not my changes in tracer.cc. it was the same issue as here: https://github.com/open-telemetry/opentelemetry-cpp/issues/1014

**Comment by lalitb** [comment]
> In case anyone sees this. The fix was likely not my changes in tracer.cc. it was the same issue as here: https://github.com/open-telemetry/opentelemetry-cpp/issues/1014

Thanks for confirming.
