### ISSUE TITLE
Remove gmock/gtest depepdency from ext::http::client::nosend

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1226]
As discussed [here](https://github.com/open-telemetry/opentelemetry-cpp/pull/1185#discussion_r808715341), it would be good to remove gmock/gtest dependency from [ext::http::client::nosend](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/ext/src/http/client/nosend/CMakeLists.txt). 

One option could be - We do plan to modify [EventHandler::OnEvent](https://github.com/open-telemetry/opentelemetry-cpp/blob/ef3a623a3bedd3fded167bade625d7fa392d2b88/ext/include/opentelemetry/ext/http/client/http_client.h#L203) to return the client implementation data at various phases of http(s) request handling if we can use that to return the Request object and validate for tests.

**Comment by owent** [comment]
Also, nosend shoube be installed when using cmake.
