### ISSUE TITLE
GPL License for dependencies

### ISSUE THREAD

**Issue by sirzooro** [open-telemetry/opentelemetry-cpp#1230]
I have checked license details for dependencies listed on https://github.com/open-telemetry/opentelemetry-cpp/blob/main/docs/dependencies.md and to my surprise I found that some of them uses GNU GPL License. This means that anyone who would use this library in his proprietary closed-source app would have to release its source code.

After closer look I realized that information on that page are not fully correct. GNU Standard C++ library is licensed on GNU GPL with special exception for compiled code, so OTLP libs compiled with `WITH_STL` cmake option would be fine for proprietary apps: https://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.license.what

I am worried about `nostd::span`, which you copied from libstdc++. Linked page also mentions GNU GPL, but in [source code](https://github.com/open-telemetry/opentelemetry-cpp/blob/v1.0.0-rc1/api/include/opentelemetry/nostd/span.h) you have Apache 2.0. That page also mentions possible fallback to `gsl::span`, but as a fallback when `WITH_STL` is used and compiler with C++ below C++20 is used.

Please clarify these licensing issues. For now it seems that the safest way for proprietary apps is to compile OTLP libs with `WITH_STL` enabled and GSL libs in order to avoid possible problems with `nostd::span`.

**Comment by lalitb** [comment]
Thanks for raising this issue. It is important for licensing information to be correct.

> After closer look I realized that information on that page are not fully correct. GNU Standard C++ library is licensed on GNU GPL with special exception for compiled code

Can you suggest the wordings here to clarify - We can explicitly mention GPL v3 for nostd::span if that helps?

> I am worried about nostd::span, which you copied from libstdc++. Linked page also mentions GNU GPL, but in [source code](https://github.com/open-telemetry/opentelemetry-cpp/blob/v1.0.0-rc1/api/include/opentelemetry/nostd/span.h) you have Apache 2.0.

Correct. The nostd::span header got included by mistake in the automated script used to add Apache 2.0 license, and need to be fixed.

> That page also mentions possible fallback to gsl::span, but as a fallback when WITH_STL is used and compiler with C++ below C++20 is used.

This has been fixed in #1167. The gsl::span would be used only if the WITH_GSL build option is provided. The dependency document needs an update.

**Comment by sirzooro** [comment]
> Thanks for raising this issue. It is important for licensing information to be correct.
> 
> > After closer look I realized that information on that page are not fully correct. GNU Standard C++ library is licensed on GNU GPL with special exception for compiled code
> 
> Can you suggest the wordings here to clarify - We can explicitly mention GPL v3 for nostd::span if that helps?

My intention here was to point that things in `std` namespace used by `#include`-ing appropriate headers from standard C++ library are on GNU GPL with special exception. This applies to 1st bullet in API&SDK section.

`nostd::span` code is copied with some changes (like namespace name change), so this is different thing and I am not sure about exact license details for it, as IANAL.

**Comment by sirzooro** [comment]
I wonder if you could replace code of `nostd::span` with copy of `gsl::span`, which uses MIT License. My main concern here is that this may break ABI compatibility, so it may not be so easy to perform.

**Comment by lalitb** [comment]
IANAL too, does anyone see an issue with adding  GPLv3 license along with the Section 7 exception in the [nostd::span](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/nostd/span.h) file header keeping the OpenTelemetry copyright intact? Same for [std::variant](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/std/variant.h)

**Comment by lalitb** [comment]
> I wonder if you could replace code of nostd::span with copy of gsl::span

As you rightly mentioned it won't be a good idea to do it now with the stable release of traces, as this may break ABI compatibility.
