### ISSUE TITLE
building OTel SDK in centos7

### ISSUE THREAD

**Issue by sandakith** [open-telemetry/opentelemetry-cpp#1231]
Wanted to know if anyone have experience with try to build sdk with centos7 based libs. 
With dependencies already installed (benchmark and googletest). This is where I have reached with sdk build 

```
Scanning dependencies of target opentelemetry_version
[ 26%] Building CXX object sdk/src/version/CMakeFiles/opentelemetry_version.dir/version.cc.o
[ 28%] Linking CXX static library libopentelemetry_version.a
[ 28%] Built target opentelemetry_version
Scanning dependencies of target attributemap_hash_benchmark
[ 30%] Building CXX object sdk/test/common/CMakeFiles/attributemap_hash_benchmark.dir/attributemap_hash_benchmark.cc.o
[ 30%] Linking CXX executable attributemap_hash_benchmark
/lib/../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[2]: *** [sdk/test/common/attributemap_hash_benchmark] Error 1
make[1]: *** [sdk/test/common/CMakeFiles/attributemap_hash_benchmark.dir/all] Error 2
make: *** [all] Error 2
```

It seems like it tried to build tests after building SDK libs, Any suggestions about how to avoid it or would skipping building tests is a option ?

**Comment by lalitb** [comment]
Which opentelemetry-cpp release you are using? Also if you can share the build steps.

**Comment by lalitb** [comment]
To skip building tests through cmake, you can use `-DBUILD_TESTING=OFF`.

**Comment by sandakith** [comment]
Thanks for the reply, I am following https://github.com/open-telemetry/opentelemetry-cpp/blob/main/docs/dependencies.md and https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md and plan to use sdk with zipkin exporter.

**Comment by sandakith** [comment]
And I am in the current head not in a specific release of the code : 
```
commit c10bc36e7d7776ac74d45b5b2ca02eaf0df028b4
Author: Lalit Kumar Bhasin <lalit_fin@yahoo.com>
Date:   Thu Feb 24 00:12:23 2022 -0800
```

**Comment by lalitb** [comment]
ok, I can't see this error on my ubuntu 20.04, with benchmark v1.5.3 (same version as used in the build pipeline).

**Comment by sandakith** [comment]
Thanks @lalitb for info. This builds with out tests [-DBUILD_TESTING=OFF].  I assumed there is an issue with attributemap_hash_benchmark linking with centos7 libs (it could be underlying platform issue),  believe this can be easily reproduced with a base centos7 docker image. I can provide more details if needed but I am trying to build zipkin exporter and would be able to provide information on that  bit later.

**Comment by esigo** [comment]
Hi @sandakith, we have a new [Dockerfile](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/docker/Dockerfile.centos) added recently with Centos base. It has `Jaeger`, `Zipkin`, and `otlp` exporters.

**Comment by lalitb** [comment]
@sandakith  - As the docker image for centos7 is successfully building otel-cpp, please check the commit version you are using.
Unless you have further updates, would like to close this issue, or else move this to the Discussion forum.

**Comment by lalitb** [comment]
Closing as stale. Please reopen if there are more details.
