### ISSUE TITLE
Failure to build open-telemetry with missing variable GMOCK_LIB

### ISSUE THREAD

**Issue by vaastav** [open-telemetry/opentelemetry-cpp#1237]
Hi, I am unable to build the library with the following error when I execute the cmake command.

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GMOCK_LIB
    linked by target "http_client_nosend" in directory /home/vaastav/Projects/opentelemetry-cpp/ext/src/http/client/nosend

```

Could someone tell me what is missing or why this is failing?

**Comment by lalitb** [comment]
Duplicate to #1226. 
Meanwhile please use opentelemetry-cpp [v1.2.0](https://github.com/open-telemetry/opentelemetry-cpp/releases/tag/v1.2.0).

**Comment by esigo** [comment]
Hi @vaastav, thanks for reaching out to us. Would it be possible to share the options you have used?
`http_nosend` is used for unit tests only and currently depends on `GMock`.
This can be turned off by `-DBUILD_TESTING=OFF`.

**Comment by vaastav** [comment]
Hi @esigo, I followed the instructions here: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md

I was able to circumnavigaet the error by using the v1.2.0
