### ISSUE TITLE
build process failed: cmake --build . --target all

### ISSUE THREAD

**Issue by Xianyong** [open-telemetry/opentelemetry-cpp#1262]
/home/lz/code/opentelemetry-cpp-1.2.0/exporters/jaeger/test/jaeger_exporter_test.cc:75:89: note:   candidate expects 0 arguments, 1 provided
   auto exporter           = GetExporter(std::unique_ptr<ThriftSender>{mock_thrift_sender});
                                                                                         ^
In file included from /usr/include/gtest/gtest.h:1874:0,
                 from /home/lz/code/opentelemetry-cpp-1.2.0/exporters/jaeger/test/jaeger_exporter_test.cc:16:
/home/lz/code/opentelemetry-cpp-1.2.0/exporters/jaeger/test/jaeger_exporter_test.cc:109:3: error: template argument 1 is invalid
   EXPECT_EQ(parent_ctx.trace_id(), child_ctx.trace_id());
   ^
/home/lz/code/opentelemetry-cpp-1.2.0/exporters/jaeger/test/jaeger_exporter_test.cc:110:3: error: template argument 1 is invalid
   EXPECT_EQ(parent_ctx.trace_state(), child_ctx.trace_state());
   ^
In file included from /usr/include/gmock/gmock-generated-function-mockers.h:43:0,
                 from /usr/include/gmock/gmock.h:61,
                 from /home/lz/code/opentelemetry-cpp-1.2.0/exporters/jaeger/test/jaeger_exporter_test.cc:17:
/home/lz/code/opentelemetry-cpp-1.2.0/exporters/jaeger/test/jaeger_exporter_test.cc: In member function ‘virtual void opentelemetry::v1::exporter::jaeger::JaegerExporterTestPeer_ShutdownTest_Test::TestBody()’:
/home/lz/code/opentelemetry-cpp-1.2.0/exporters/jaeger/test/jaeger_exporter_test.cc:127:3: error: ‘class opentelemetry::v1::exporter::jaeger::MockThriftSender’ has no member named ‘gmock_Append’; did you mean ‘Append’?
   EXPECT_CALL(*mock_thrift_sender, Append(_)).Times(Exactly(1)).WillOnce(Return(1));
   ^
/home/lz/code/opentelemetry-cpp-1.2.0/exporters/jaeger/test/jaeger_exporter_test.cc: In member function ‘virtual void opentelemetry::v1::exporter::jaeger::JaegerExporterTestPeer_ExportTest_Test::TestBody()’:
/home/lz/code/opentelemetry-cpp-1.2.0/exporters/jaeger/test/jaeger_exporter_test.cc:151:3: error: ‘class opentelemetry::v1::exporter::jaeger::MockThriftSender’ has no member named ‘gmock_Append’; did you mean ‘Append’?
   EXPECT_CALL(*mock_thrift_sender, Append(_)).Times(Exactly(1)).WillOnce(Return(1));
   ^
/home/lz/code/opentelemetry-cpp-1.2.0/exporters/jaeger/test/jaeger_exporter_test.cc:157:3: error: ‘class opentelemetry::v1::exporter::jaeger::MockThriftSender’ has no member named ‘gmock_Append’; did you mean ‘Append’?
   EXPECT_CALL(*mock_thrift_sender, Append(_)).Times(Exactly(1)).WillOnce(Return(0));
   ^

**Comment by esigo** [comment]
Hi @Xianyong  thanks for reaching out to us.
Could you please tell us about your environment?
you can turn off the test build by using the `-DBUILD_TESTING=OFF` option. Otherwise you need gtest and gmock installed.

**Comment by Xianyong** [comment]
Once grpc was installed, both options of -DWITH_ZIPKIN=ON and - DWITH_OTLP=ON were fine to compile this project, while the option -DWITH_JAEGER=ON always stopped by errors:

------------
/home/lz/code/opentelemetry-cpp-1.2.0-jaeger/opentelemetry-cpp-1.2.0/exporters/jaeger/test/jaeger_recordable_test.cc:215:66: error: no matching function for call to ‘opentelemetry::v1::nostd::span<const long int>::span(<brace-enclosed initializer list>)’
   rec.SetAttribute("key4", nostd::span<const int64_t>{{-640, 640}});

/home/lz/code/opentelemetry-cpp-1.2.0-jaeger/opentelemetry-cpp-1.2.0/exporters/jaeger/test/jaeger_recordable_test.cc:216:66: error: no matching function for call to ‘opentelemetry::v1::nostd::span<const unsigned int>::span(<brace-enclosed initializer list>)’
   rec.SetAttribute("key5", nostd::span<const uint32_t>{{320, 322}});


/home/lz/code/opentelemetry-cpp-1.2.0-jaeger/opentelemetry-cpp-1.2.0/exporters/jaeger/test/jaeger_recordable_test.cc:218:92: error: no matching function for call to ‘opentelemetry::v1::nostd::span<const opentelemetry::v1::nostd::string_view>::span(<brace-enclosed initializer list>)’
   rec.SetAttribute("key7", nostd::span<const nostd::string_view>{{"string_v1", "string_v2"}});
                                                                                            ^
In file included from /home/lz/code/opentelemetry-cpp-1.2.0-jaeger/opentelemetry-cpp-1.2.0/api/include/opentelemetry/common/attribute_value.h:8:0,
                 from /home/lz/code/opentelemetry-cpp-1.2.0-jaeger/opentelemetry-cpp-1.2.0/sdk/include/opentelemetry/sdk/trace/recordable.h:6,
                 from /home/lz/code/opentelemetry-cpp-1.2.0-jaeger/opentelemetry-cpp-1.2.0/exporters/jaeger/include/opentelemetry/exporters/jaeger/recordable.h:7,

**Comment by esigo** [comment]
I can't reproduce this on ubuntu. It would be great if you could provide reproduction steps. Also let us know if you have gtest, and gmock installed (you don't need them if you use the `-DBUILD_TESTING=OFF` option).
Meanwhile you can try one of our Dockerfiles ([ubuntu](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/docker/ubuntuLatest/Dockerfile) or [centos](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/docker/Dockerfile.centos)) for building.

**Comment by lalitb** [comment]
@Xianyong  - Can you provide the repro steps, version of gtest/gmock used. As this is working fine in CI, and not reproducible locally.
