### ISSUE TITLE
Get an error while build with bazel, looks like related to curl depenence?

### ISSUE THREAD

**Issue by Grace-1024** [open-telemetry/opentelemetry-cpp#1280]
**Describe your environment** 
gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)

**What is the expected behavior?**
What did you expect to see?

**What is the actual behavior?**
```
Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/curl/lib/sendf.c:30:
/usr/include/linux/tcp.h:135:2: error: unknown type name 'u32'
  u32 real_ip;
  ^~~
/usr/include/linux/tcp.h:136:2: error: unknown type name 'u16'
  u16 real_port;
  ^~~
```

**Comment by esigo** [comment]
Hi @Grace-1024, thanks for reaching out to us.
Would it be possible to share your build command?

**Comment by Grace-1024** [comment]
bazel build --verbose_failures --sandbox_debug ...

I fix this problem by edit this line https://github.com/open-telemetry/opentelemetry-cpp/blob/main/bazel/curl.bzl#L200 to "//conditions:default": BASE_CURL_COPTS".

**Comment by lalitb** [comment]
> /usr/include/linux/tcp.h:135:2: error: unknown type name 'u32'

Not sure, but something seems to be messed up with the linux kernel headers in this system. Can you check which rpm package is bringing this file:

```
$ rpm -qf /usr/include/linux/tcp.h
..
```

And kernel version installed:
```
$ uname -a
..
$  cat /proc/version
```

**Comment by Grace-1024** [comment]
> 

The linux kernel I'm using is provided by our company, maybe you can't find it on the internet.

```
[root@]# rpm -qf /usr/include/linux/tcp.h
kernel-tlinux4-headers-5.4.32-1.0001.tl3.x86_64
[root@]#  cat /proc/version
Linux version 3.10.107-1-tlinux2_kvm_guest-0049 (root@TENCENT64.site) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Tue Jul 30 23:46:29 CST 2019
```
The 'tlinux' means Tencent Linux.

**Comment by lalitb** [comment]
Thanks for clarifying. This looks to be an issue in the kernel header, not related to opentelemetry-cpp. `u32` type is not visible after the inclusion of `tcp.h` header. You may want to follow up with the maintainers of this kernel?

**Comment by owent** [comment]
Some old versions of CentOS has this problem,please just run `yum update kernel-headers` or these scripts below to solve this problem.

```bash
sed -i 's;\bu32\b;__u32;g' /usr/include/linux/tcp.h || true
sed -i 's;\bu16\b;__u16;g' /usr/include/linux/tcp.h || true
```

**Comment by lalitb** [comment]
Even though closed by the bot for being stale, the actual problem is with the kernel headers, and needs to be fixed as mentioned above.
