### ISSUE TITLE
Windows Ninja build fails with 'C:\Program' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by juandemanjon** [open-telemetry/opentelemetry-cpp#1292]
In a Windows environment where Ninja binary is a path with spaces the build fails and the error messages is:
```'C:\Program' is not recognized as an internal or external command```

The fix is pretty straight forward, just wrapping the %NINJA% call with quotes, which I am going to send a PR

**Steps to reproduce**
To reproduce it, ninja has to be in a path with spaces. In my environment I have:
```
where ninja
C:\ProgramData\chocolatey\bin\ninja.exe
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe
```

**Comment by ThomsonTan** [comment]
@juandemanjon in your environment, I assume the ninja path issue will not happen because the first one should be used which doesn't include space in the full path, is this correct?

**Comment by juandemanjon** [comment]
@ThomsonTan Actually happens because the script iterates over the _where_ results and the last one is actually the one applied
