### ISSUE TITLE
bazel link `//exporters/jaeger:opentelemetry_exporter_jaeger_trace` failed on: "no such package '@thrift//'"

### ISSUE THREAD

**Issue by flier** [open-telemetry/opentelemetry-cpp#1296]
> **Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.

os: macosx
cc: Apple clang version 13.0.0 (clang-1300.0.29.30)
opentelemetry-cpp: 1.2.0
bazel: 4.2.0 and 5.0.0-homebrew

> **Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

Link a example with bazel

WORKSPACE
```bazel

load("@io_opentelemetry_cpp//bazel:repository.bzl", "opentelemetry_cpp_deps")

opentelemetry_cpp_deps()

# Load gRPC dependencies after load.
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

# Load extra gRPC dependencies due to https://github.com/grpc/grpc/issues/20511
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies()

```

BUILD
```bazel
cc_library(
    // ...
    deps = [
        "@io_opentelemetry_cpp//exporters/jaeger:opentelemetry_exporter_jaeger_trace",
    ],
)
```

> **What is the expected behavior?**
What did you expect to see?

The program can be linked and run normally

> **What is the actual behavior?**
What did you see instead?

ERROR: /private/var/tmp/_bazel_flier/8ec89e316ad357c53101d794ecea3bc6/external/io_opentelemetry_cpp/exporters/jaeger/BUILD:5:6: no such package '@thrift//': The repository '@thrift' could not be resolved: Repository '@thrift' is not defined and referenced by '@io_opentelemetry_cpp//exporters/jaeger:thrift'

>**Additional context**

**Comment by esigo** [comment]
Hi @flier, thanks for reaching out to us. Unfortunately at the moment we don't support bazel for Jaeger exporter on Mac, because of dependencies discussed in #1134.
