### ISSUE TITLE
Could we use add `ENABLE_METRICS_LEGACY` instead of using `ENABLE_METRICS_PREVIEW` to decide whether to use legacy metrics SDK and exporter?

### ISSUE THREAD

**Issue by owent** [open-telemetry/opentelemetry-cpp#1310]
**Is your feature request related to a problem?**

Could we use add `ENABLE_METRICS_LEGACY` instead of using `ENABLE_METRICS_PREVIEW` to decide whether to use legacy metrics SDK and exporter?

The legacy metrics depends RTTI, by use a new option, we can enable new metrics without RTTI.

**Describe the solution you'd like**

Add `ENABLE_METRICS_LEGACY` and replace all checking in `_metrics`.

**Additional context**

If this is acceptable, it can be assigned to me.

**Comment by lalitb** [comment]
The plan is to do a cleanup of legacy metric implementation once we are ready with new metrics which is planned for the next couple of months. These macros would be removed as part of the cleanup. While ENABLE_METRICS_LEGACY is better naming than ENABLE_METRICS_PREVIEW, I feel it won't make sense to change them now as we are anyway going to remove them in the coming days :)

**Comment by owent** [comment]
OK
