### ISSUE TITLE
We should move all public definitions in `CMakeLists.txt` to `target_compile_definitions(opentelemetry_api INTERFACE ...)`

### ISSUE THREAD

**Issue by owent** [open-telemetry/opentelemetry-cpp#1311]
**Describe your environment**

System: Windows
Build System: cmake

**Steps to reproduce**

`cmake <...> -DWITH_ETW=ON`

**What is the expected behavior?**

Now, some definitions are added by `add_definitions(...)` in `CMakeLists.txt` and so that these definitions are private. But we should keep the same behaviour between compiling opentelemetry-cpp and using it by users. We can add these public definitions by `target_compile_definitions(opentelemetry_api INTERFACE ...)` and then these definitions will be auto passed to all cmake targets depend `opentelemetry_api`.

**What is the actual behavior?**

Some definitions are missing and library get a different behavior.

**Additional context**

Should we add prefix to `NO_GETENV` and `NOMINMAX` in case of them will conflict with other libraries?

It this's acceptable, it can be assigned to me please.

**Comment by owent** [comment]
Can I add `OPENTELEMETRY_` prefix for `NO_GETENV` and `NOMINMAX` ?

**Comment by lalitb** [comment]
> Can I add OPENTELEMETRY_ prefix for NO_GETENV and NOMINMAX ?

Just curious, why specifically for these two macro definitions, as we have lots of other definitions like HAVE_MSGPACK, HAVE_GSL.

**Comment by owent** [comment]
OK, I will just move the definitions into `opentelemetry_api` and dn not rename them.
