### ISSUE TITLE
"HAVE_ABSEIL" is not defined even with option "-DWITH_ABSEIL=ON"

### ISSUE THREAD

**Issue by yzhuang93** [open-telemetry/opentelemetry-cpp#1319]
**Describe your environment** 
Build environment: CENTOS7
CXX: clang-6.0.1/bin/cxx
CMake version: 3.6.3

Hi! I am trying to link my project with opentelemetry, the version I used for opentelemetry Is the latest 1.2.0 and since my own project is already linked to some util libraries which use local abseil library. I used the "-DWITH_ABSEIL=ON" to do the compilation with opentelemetry and then linked my project with it. But still got the variant.h conflict issues.

**Steps to reproduce**
Build the opentelemetry with CMake:
```
cmake $srcdir \
     -DCMAKE_INSTALL_PREFIX=$srcdir/install \
     -DCMAKE_CXX_COMPILER=$(which g++) \
     -DCMAKE_PREFIX_PATH=$install \
     -DCMAKE_INSTALL_LIBDIR=lib \
     -DBUILD_SHARED_LIBS=ON \
     -DBUILD_TESTING=OFF \
     -DWITH_EXAMPLES=OFF \
     -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
     -DWITH_JAEGER=ON \
     -DWITH_ABSEIL=ON \
     -DCMAKE_SKIP_RPATH=1
```
Link opentelemetry in another project which uses local abseil lib
```
find_package(opentelemetry-cpp REQUIRED)
target_include_directories(insights_server_lib PRIVATE ${OPENTELEMETRY_CPP_INCLUDE_DIRS})
target_link_libraries(insights_server_lib PRIVATE ${OPENTELEMETRY_CPP_LIBRARIES})
```
Include any of the opentelemetry headers:
```
#include "opentelemetry/trace/provider.h"
```
Then build with cmake.

**What is the expected behavior?**
Successful compilation.

**What is the actual behavior?**
```
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/trace/provider.h:10:
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/trace/noop.h:10:
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/context/runtime_context.h:6:
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/context/context.h:7:
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/context/context_value.h:8:
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/baggage/baggage.h:8:
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/common/kv_properties.h:6:
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/common/key_value_iterable_view.h:10:
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/common/key_value_iterable.h:6:
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/common/attribute_value.h:10:
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/nostd/variant.h:52:
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/nostd/./internal/absl/types/variant.h:46:
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/nostd/./internal/absl/types/../utility/utility.h:50:
In file included from ../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/nostd/./internal/absl/types/../utility/../base/internal/invoke.h:42:
../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/nostd/./internal/absl/types/../utility/../base/internal/../../meta/type_traits.h:657:11: error: reference to 'enable_if_t' is ambiguous
    absl::enable_if_t<std::is_convertible<
    ~~~~~~^
../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/absl/meta/type_traits.h:608:1: note: candidate found by name lookup is 'absl::lts_2020_02_25::enable_if_t'
using enable_if_t = typename std::enable_if<B, T>::type;
^
../../../../../../../toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/include/opentelemetry/nostd/./internal/absl/types/../utility/../base/internal/../../meta/type_traits.h:608:1: note: candidate found by name lookup is 'absl::otel_v1::enable_if_t'
using enable_if_t = typename std::enable_if<B, T>::type;
```
In the `variant.h`, looks like the `HAVE_ABSEIL` is not defined. If I manually add
```
#ifndef HAVE_ABSEIL
#define HAVE_ABSEIL
#endif

#include "opentelemetry/trace/provider.h"
```
before the header include, then the build could pass.

**Additional context**
Could you please let me know if something I am missing to use the local abseil?

**Comment by owent** [comment]
It seems your target (`insights_server_lib`) find a different `opentelemetry-cpp` from your own building.
I see you set `-DCMAKE_INSTALL_PREFIX=$srcdir/install` which should install `opentelemetry-cpp`  into `<Some prefix>/install` , but what your project find is `<...>/toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64`, and it's not the location you install.
Did you `cmake --build . --target install` and add `$srcdir/install` to your find path of `insights_server_lib`?

**Comment by yzhuang93** [comment]
Actually my target `insights_server_lib ` is using exactly the one I built from the opentelemetry v1.2.0 and I only have one opentelemetry build in local, it shows a different path because I copied all the dependency libs to a central directory. So I think this might not relate.

**Comment by owent** [comment]
Could you provide the `set_target_properties(opentelemetry-cpp::api ...)` block in your `toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/lib64/cmake/opentelemetry-cpp/opentelemetry-cpp-target.cmake` or `toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/lib/cmake/opentelemetry-cpp/opentelemetry-cpp-target.cmake` ?

E.g., here is my custom prebuilt cmake installation:

```cmake
set_target_properties(opentelemetry-cpp::api PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAVE_ABSEIL;HAVE_CPP_STDLIB;ENABLE_METRICS_PREVIEW;ENABLE_LOGS_PREVIEW"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "absl::bad_variant_access;absl::any;absl::base;absl::bits;absl::city"
)
```

You can find `HAVE_ABSEIL` in `INTERFACE_COMPILE_DEFINITIONS` and `"absl::bad_variant_access;absl::any;absl::base;absl::bits;absl::city"` in `INTERFACE_LINK_LIBRARIES`, which means add `HAVE_ABSEIL` to all targets depend `opentelemetry-cpp::api` (which is included in `${OPENTELEMETRY_CPP_LIBRARIES}`) and link `absl::bad_variant_access;absl::any;absl::base;absl::bits;absl::city` to these targets.

> BTW: `target_include_directories(insights_server_lib PRIVATE ${OPENTELEMETRY_CPP_INCLUDE_DIRS})` is duplicate and and be removed.

**Comment by yzhuang93** [comment]
Yeah I checked this before and I have the same `set_target_properties` in my `toolchain-builds/82ee087e0bd6693a6f75c04db3ed205df8d84310.x86_64/lib/cmake/opentelemetry-cpp/opentelemetry-cpp-target.cmake`
```
set_target_properties(opentelemetry-cpp::api PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAVE_ABSEIL"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "absl::bad_variant_access;absl::any;absl::base;absl::bits;absl::city"
)
```
So i felt weird to have this issue, it could be something wrong on my end, maybe I will debug a little bit more.
But with the:
```
find_package(opentelemetry-cpp REQUIRED)
target_link_libraries(insights_server_lib INTERFACE ${OPENTELEMETRY_CPP_LIBRARIES})
```
It should be good enough to link all required libs and set all definitions right?

**Comment by owent** [comment]
Yes, `target_link_libraries(insights_server_lib PRIVATE ${OPENTELEMETRY_CPP_LIBRARIES})` should be enough to set all definitions, add all include directories and link all libraries in the right order.
If your `insights_server_lib` is a library, it may be better to use `target_link_libraries(insights_server_lib PUBLIC ${OPENTELEMETRY_CPP_LIBRARIES})`, with `PRIVATE` links in cmake, the dependencies will not be passed to the target depend `insights_server_lib` automatically. It he error message in not shown when compiling `insights_server_lib` but some executables or libraries which will link `insights_server_lib`, that may be the problem.

**Comment by lalitb** [comment]
@yzhuang93 Did you have any further findings. This looks to be something wrong with the setup/env.

**Comment by yzhuang93** [comment]
I am still investigating my setup, we can close this one, in case I have some new things to raise I will reopen. Thanks for the help!
