### ISSUE TITLE
Crash when using `http_client_curl` of `v1.3.0`

### ISSUE THREAD

**Issue by owent** [open-telemetry/opentelemetry-cpp#1335]
**Describe your environment**

OS: Linux
Version: v1.3.0
Build System: cmake

**Steps to reproduce**

Use both `opentelemetry::api` and `opentelemetry::http_client_curl` at the same time.

**What is the actual behavior?**

![Screenshot_16503460452050](https://user-images.githubusercontent.com/1209475/163936953-5d49c4bd-f486-4791-9688-9dc44f519c23.png)

**Additional context**

When building `opentelemetry_ext`, we should link `opentelemetry_ext` with `opentelemetry_api` to import all definitions of  `opentelemetry_api`.Without it the `opentelemetry_ext` will be built without `std::string_view` , `abseil-cpp` and etc. But when we use both `opentelemetry_ext` and other components together, it will use `std::string_view` , `abseil-cpp` and etc when compiler support them.

**Comment by ThomsonTan** [comment]
Wondering whether it is possible to add a test to catch this kind of issue?

**Comment by owent** [comment]
I'm not sure why unit test didn't find this problem.
The test `ext.http.curl.curl_http_test` only links `opentelemetry_http_client_curl` and `opentelemetry_http_client_curl` only links `opentelemetry_ext`. I also checked the flags to compiling `opentelemetry_http_client_curl` and didn't find `HAVE_CPP_STDLIB` or `HAVE_ABSEIL`. This problem should already be tested but it didn't crash on CI.
Maybe it's related to my compiler and STD library.(clang 14.0.1 with `-stdlib=libc++`)
