### ISSUE TITLE
Could we export `opentelemetry_otlp_recordable` headers?

### ISSUE THREAD

**Issue by owent** [open-telemetry/opentelemetry-cpp#1343]
**Is your feature request related to a problem?**

I want to implement a special OTLP exporter to extend the standard OTLP exporters,but I need to control the recordable objects of OTLP exporters. But I found I cann't reuse recordables with cmake because the installation exclude the headers of OTLP recordables.

```cmake
install(
  DIRECTORY include/opentelemetry/exporters/otlp
  DESTINATION include/opentelemetry/exporters
  FILES_MATCHING
  PATTERN "*.h"
  PATTERN "otlp_recordable.h" EXCLUDE)
```

I just wonder why we exclude  `otlp_recordable.h` here, and can we also install it?

**Describe the solution you'd like**

Remove `PATTERN "otlp_recordable.h" EXCLUDE` above.

**Comment by ThomsonTan** [comment]
the header file was excluded in below PR, probably we should discuss to get it back for installation. @esigo 

https://github.com/open-telemetry/opentelemetry-cpp/pull/923

**Comment by lalitb** [comment]
Yes I think this is valid use-case, we can bring this header file as part of installation. I can fix this next week, unless someone wants to raise a PR to fix this earlier?
