### ISSUE TITLE
[docs] GettingStarted.rst incorrect for Jaeger HTTP exporter

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#1347]
In the documentation, in:
  `opentelemetry-cpp/docs/public/sdk/GettingStarted.rst`
the section about exporters states:

```
// Jaeger HTTP exporter
opentelemetry::exporter::jaeger::JaegerExporterOptions opts;
opts.transport_format  = opentelemetry::exporter::jaeger::TransportFormat::kThriftHttp;
opts.endpoint = "localhost";
opts.server_port =  6831;
opts.headers = {{}}; // optional headers
auto jaeger_udp_exporter =
    std::unique_ptr<sdktrace::SpanExporter>(new opentelemetry::exporter::jaeger::JaegerExporter(opts));
```

Bug:

The exporter variable, `jaeger_udp_exporter`, is confusing ... probably meant to be `jeager_http_exporter` instead.

Possibly a bug:

The port number, `6831`, is the same as for the Jaeger UDP exporter above, and look suspicious (copy and paste).
I could not get the example to work on 6831, but unsure if this is due to my install or to the port number.

Should the port be `14268` instead ?
This needs confirmation, I do not know this area well enough for a definitive answer.

Related:
https://www.jaegertracing.io/docs/1.32/deployment/

**Comment by esigo** [comment]
Hi @marcalff, thanks for reaching out to us. Regarding the port you may use the port you have configured your backend. `14268` should be the default port for http yes.
I'd suggest starting with our [example](https://github.com/open-telemetry/opentelemetry-cpp/tree/main/examples/jaeger), to be sure your code is working.
