### ISSUE TITLE
The location of Doxygen configuration file

### ISSUE THREAD

**Issue by CunjunWang** [open-telemetry/opentelemetry-cpp#135]
Try to solve issue #109 

**Is your feature request related to a problem?**
Yes. Currently the C++ repository contains little internal documentation, and we are trying to integrate Doxygen into the repository so that we can easily generate and publish technical documentation.

**Describe the solution you'd like**
In the repository there is already a folder called docs, however it looks like a collection of documents about project introduction, project setup, and policies, not for technical documentation. I prefer to create a new folder called doxygen to generate the configuration file and technical documentation.

**Describe alternatives you've considered**
Put doxygen file in the docs folder as well, so that all kinds of document are in the same directory.

**Additional context**
In [Prometheus C++ client](https://github.com/jupp0r/prometheus-cpp) repository, it puts the doxygen configuration file in a doc folder.

**Comment by reyang** [comment]
Same as Prometheus C++ client, the official doxygen project is using `doc` as the folder name, I suggest we follow it by default.
I'm open to move existing the docs if there is a better place/folder.

**Comment by lalitb** [comment]
closing as #562  add api documentation. Will add the separate ticket for sdk documentation.
