### ISSUE TITLE
Empty headers injected by HTTP and Baggage propagator

### ISSUE THREAD

**Issue by yzsolt** [open-telemetry/opentelemetry-cpp#1366]
If the HTTP propagator is used on an invalid context or the baggage propagator is used on an empty baggage, the resulting header map will contain empty values. I don't know if this is intended or not, but I think it'd be more user friendly if empty values wouldn't be injected, so the user wouldn't have to remove or check them manually before using them as HTTP request headers.

**Comment by lalitb** [comment]
A quick look into the HTTP propagator code, I don't think empty header files are injected if the context is not valid as we return early in that case:

https://github.com/open-telemetry/opentelemetry-cpp/blob/c8bd431be27c71145098a1888dc115ab34997523/api/include/opentelemetry/trace/propagation/http_trace_context.h#L40-L43

Though this may be true for the Baggage propagator and need to be fixed if so.

**Comment by lalitb** [comment]
@yzsolt  #1367 should fix the issue with baggage propagator. Can you check HTTP propagator once again, as our [tests ](https://github.com/open-telemetry/opentelemetry-cpp/blob/13ac5c30b6f8ae996d05f3c4084c58f952734ac6/api/test/trace/propagation/http_text_format_test.cc#L80)does validate that HTTP headers are not populated in case the context is invalid.

**Comment by yzsolt** [comment]
@lalitb Sorry for necro-bumping this issue, but I've finally had time to check it once again, and the Tracestate header still can be empty. I've also found the root cause: while there is a test case for this, it's checking the extracted `carrier` variable instead of the injected `carrier2`. So Tracestate header injection still needs an `if` and the tests should be fixed too. I'd suggest using more meaningful names for the extracted/injected carriers in all propagation tests to avoid an issue like this in the future.
