### ISSUE TITLE
Question on Use of Virtual Functions

### ISSUE THREAD

**Issue by Brandon-Kimberly** [open-telemetry/opentelemetry-cpp#137]
When writing our design for the metrics API and SDK, our team working on this implementation (@Brandon-Kimberly , @ankit-bhargava , and @HudsonHumphries ) were confused about when to make a function virtual and when to make it purely virtual. To me, it makes sense to make the function purely virtual if it is crucial to the purpose of the class that it is in but I am very interested to hear others’ thoughts.

What was decided for the tracing portion of the library?

cc @reyang  @alolita

**Comment by reyang** [comment]
I think this is not specific to OpenTelemetry, more like a C++ question.
Pure virtual function makes the class an abstract one - which means it cannot be instantiated. Examples are when you define an API, and you want to force folks to implement.
In many of our OpenTelemetry APIs, we make it work by default rather than forcing the SDK to provide implementation, in this way we use virtual function but not pure virtual one. OpenTelemetry API package strictly speaking is not the _traditional API_ that we refer to, it is actually API + default implementation.

**Comment by Brandon-Kimberly** [comment]
> I think this is not specific to OpenTelemetry, more like a C++ question.
> Pure virtual function makes the class an abstract one - which means it cannot be instantiated. Examples are when you define an API, and you want to force folks to implement.
> In many of our OpenTelemetry APIs, we make it work by default rather than forcing the SDK to provide implementation, in this way we use virtual function but not pure virtual one. OpenTelemetry API package strictly speaking is not the _traditional API_ that we refer to, it is actually API + default implementation.

Ah, that clears things up a lot for me. So we should refrain from using purely virtual functions (for the most part) and instead just use virtual functions that provide a default implementation because this is more convenient for the user? I just want to make sure I understand this right. Thank you for the response!

**Comment by pyohannes** [comment]
> I think this is not specific to OpenTelemetry, more like a C++ question.

I agree.

> What was decided for the tracing portion of the library?

1. There are pure virtual functions in the [API interface definitions](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/api/include/opentelemetry/trace/tracer.h#L31).
2. The API provides `Noop` classes with a [no-op implementation](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/api/include/opentelemetry/trace/noop.h#L62) for those pure virtual functions. Those `Noop` objects are used when no SDK is initialized.
3. The SDK provides [actual useful implementations](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/src/trace/tracer.cc#L22) for abstract API classes.

I will close this for now, as it is not really an OpenTelemetry C++ issue. Feel free to reach out on Gitter with any further questions!
