### ISSUE TITLE
[Metrics] Prometheus exporter reports instrumentation library name instead of instrument name

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#1370]
Greetings,

I am attempting to export to Prometheus from an application based on the Prometheus example.
WITH_METRICS_PREVIEW is undefined.

Running the example binary appears to work, and reports a metric named `prometheus_metric_example`, type counter,
for an instrument named `prometheus_metric_example_counter` in the C++ code.

Running my application,
No matter how instruments or views are named, the data exported to Prometheus always reports the same metric name,
which is the name given as instrumentation library when calling GetMeter().

Should the prometheus export code use `metric_data.instrument_descriptor.name_` instead of `instrumentation_info.instrumentation_library_->GetName()` ?

Also, there is no HELP exported to Prometheus.

The following change helps to go further ...

Regards.

```
diff --git a/exporters/prometheus/src/exporter_utils.cc b/exporters/prometheus/src/exporter_utils.cc
index 39131e2..0b7a26f 100644
--- a/exporters/prometheus/src/exporter_utils.cc
+++ b/exporters/prometheus/src/exporter_utils.cc
@@ -82,11 +82,17 @@ void PrometheusExporterUtils::SetMetricFamilyByAggregator(
 {
   for (const auto &instrumentation_info : data.instrumentation_info_metric_data_)
   {
+#ifdef NEVER
     auto origin_name    = instrumentation_info.instrumentation_library_->GetName();
     auto sanitized      = SanitizeNames(origin_name);
     metric_family->name = sanitized;
+#endif
     for (const auto &metric_data : instrumentation_info.metric_data_)
     {
+      auto origin_name    = metric_data.instrument_descriptor.name_;
+      auto sanitized      = SanitizeNames(origin_name);
+      metric_family->name = sanitized;
+      metric_family->help = metric_data.instrument_descriptor.description_;
       auto time = metric_data.start_ts.time_since_epoch();
       for (const auto &point_data_attr : metric_data.point_data_attr_)
       {
```

**Comment by bsarden** [comment]
+1: I just hit this same issue actually when trying to spin-up the prometheus example. I see the counter / histogram values being read out by the corresponding `counter_example` and `histogram_example` functions and am expecting a `prometheus_metric_example_counter` and `prometheus_metric_example_histogram` to exist, but instead I just have a `prometheus_metric_example` of TYPE `counter` and the only thing I can query is this:

<img width="1496" alt="Screen Shot 2022-05-04 at 1 37 09 PM" src="https://user-images.githubusercontent.com/7913815/166803131-0d038821-8a8f-46f6-8b83-973708b316f3.png">

I'm assuming this is related because it does also seem like a metric aliasing issue, but maybe I'm down the wrong path.

**Comment by esigo** [comment]
Hi @marcalff and @bsarden, thanks for reaching out to us and also thanks for testing. 
In addition to @marcalff's suggestion, we need to have a fix in [meter.cc](https://github.com/open-telemetry/opentelemetry-cpp/blob/59a48c1c99bbc8822d66eaf9edbe3f384092b125/sdk/src/metrics/meter.cc#L192) as well. I will raise a PR after running some tests.

**Comment by lalitb** [comment]
> In addition to @marcalff's suggestion, we need to have a fix in [meter.cc](https://github.com/open-telemetry/opentelemetry-cpp/blob/59a48c1c99bbc8822d66eaf9edbe3f384092b125/sdk/src/metrics/meter.cc#L192) as well. I will raise a PR after running some tests.

Just curious, what fix is required here. Based on the metrics [specs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#view), the metrics stream should use the `name` and `description` from the View if configured.

**Comment by marcalff** [comment]
The spec says:

> The name of the View (optional). If not provided, the Instrument name MUST be used by default. This will be used as the name of the metrics stream.

and likewise for the description.

If I understand correctly, @esigo meant something like this:

```
diff --git a/sdk/src/metrics/meter.cc b/sdk/src/metrics/meter.cc
index c0b0ce7..af8390b 100644
--- a/sdk/src/metrics/meter.cc
+++ b/sdk/src/metrics/meter.cc
@@ -190,7 +190,13 @@ std::unique_ptr<WritableMetricStorage> Meter::RegisterMetricStorage(
       [this, &instrument_descriptor, &storages](const View &view) {
         auto view_instr_desc         = instrument_descriptor;
         view_instr_desc.name_        = view.GetName();
+        if (view_instr_desc.name_.size() == 0) {
+          view_instr_desc.name_ = instrument_descriptor.name_;
+        }
         view_instr_desc.description_ = view.GetDescription();
+        if (view_instr_desc.description_.size() == 0) {
+          view_instr_desc.description_ = instrument_descriptor.description_;
+        }
         auto storage                 = std::shared_ptr<SyncMetricStorage>(new SyncMetricStorage(
             view_instr_desc, view.GetAggregationType(), &view.GetAttributesProcessor(),
             NoExemplarReservoir::GetNoExemplarReservoir()));

```

Without it, views with an empty name end up exposing metrics with empty names to Prometheus, which fails to scrap.

**Comment by lalitb** [comment]
> Without it, views with an empty name end up exposing metrics with empty names to Prometheus, which fails to scrap.

Good point. Thanks for clarifying.
