### ISSUE TITLE
Metrics Label Storage Convention

### ISSUE THREAD

**Issue by ankit-bhargava** [open-telemetry/opentelemetry-cpp#139]
**Is your feature request related to a problem?**

Currently, different languages use varying data structures to store Metric labels.  Java, for example, uses a string while python uses a dictionary (roughly equivalent to the unordered map in C++).  These decisions were made based on the strengths of each language and the performance/availability of data structures in that particular language.  

**Describe the solution you'd like**

It would be helpful to developers working on metrics and exporters if the community weighed the different approaches then issued explicit guidance on this topic as it would prevent the use of clashing data types when integrating parts of the library.  

**Describe alternatives you've considered**

By using a string to hold labels, we can improve the user experience in some ways since those adding metrics to their code will not have to create a cumbersome map (or other key value data structure) each time they want to add labels to their metrics.  Additionally, this improves readability of code as it is easier to see the labels in a string rather than a map, especially in C++.  Finally, the performance of strings is likely superior as they are a lightweight type which can be compared relatively easily.  Checking the contents of a map for equality is more difficult.  

A map is beneficial because it doesn’t enforce an ordering on the labels.  For example, the label sets “A:1, B:1” and “B:1, A:1” are equal in terms of content and a map would reflect that while a string would treat these as unique sets.  Depending on preference, this could be seen as an advantage or disadvantage.  Also, it may be easier to modify label sets using a map as users can add and remove certain attributes as they wish without complicated string parsing.

**Comment by pyohannes** [comment]
I think a `KeyValueIterable` representation would be safer. This would eliminate several dangers:

* Introducing bugs while implementing the parser.
* A requirement to support a value to be a homogenous list (like `a=[1,2,3]`). I'm not sure about labels, but that's a requirement for span attribute values.
* Avoiding ambiguity. How would you compare the label sets `a=10`, `a=10.0` and `a=1e1`? Or `a=1,b=2` and `b=2,a=1`?

> By using a string to hold labels, we can improve the user experience in some ways since those adding metrics to their code will not have to create a cumbersome map (or other key value data structure) each time they want to add labels to their metrics.

I personally think that
```c++
instrument.Add(3, {{"http.status", 404}, {"url", "/index.html?a=b,c=d"}, {"duration", 3.14159}});
```
is easier to read than:
```c++
instrument.Add(3, "http.status=404,url=/index.html?a\=b\,c\=d,duration=3.14159");
```

> Finally, the performance of strings is likely superior as they are a lightweight type which can be compared relatively easily. Checking the contents of a map for equality is more difficult.

We might handle label sets as strings internally, but I think we shouldn't expose this in the API.
