### ISSUE TITLE
Is it possible to add attributes to "instrumentation scope"?

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-cpp#1403]
[This OTEP](https://github.com/open-telemetry/oteps/pull/201) proposed to add attributes to instrumentation scope.

This issue is a question for the maintainers of this repo: are we able to do this in a non-breaking manner and without significant performance impact?

**Comment by lalitb** [comment]
This is not an API breaking change. So instrumentation libraries can still build with the new otel-cpp API without any code changes.
But there would be ABI incompatibility across different versions. So the instrumentation library build with newer version of otel-cpp won't be ABI compatible with application build using older version of otel-cpp.
