### ISSUE TITLE
[Metrics SDK] Add InMemory metric exporter

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1405]
As required by the specs - https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/in-memory.md

This would also be great tool for testing.

**Comment by marcalff** [comment]
Also, please consider the visitor idea, detailed in:

open-telemetry/opentelemetry-cpp#1698
