### ISSUE TITLE
SDK Version is an empty string

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#1418]
Greetings,

`opentelemetry::sdk::version::FULL_VERSION` is not populated, it is an empty string.

File `sdk/src/version/version.cc` is intended to be post processed by commit hooks (`buildscripts/pre-commit`),
but these don't seem to be used, and beside, attributes like `BUILD_DATE` should probably be populated during the build, not at commit time.

Instead of checking in file version.cc in git,
a possible solution is to check in file version.cc.in,
and have file version.cc generated by CMake during the build.

Not familiar with Bazel, I assume files can be generated there as well.

Regards.

**Comment by lalitb** [comment]
> We are supposed to run the buildscripts/pre-commit before releasing, but we didn't do this so far

I think we should run this script manually for now before releasing. The plan was to automate the release process and execute this script through github action (#593 - Have reopened this issue now).

**Comment by lalitb** [comment]
We can close this PR once new release populates the SDK version. And track the release automation through #593. Assigning to @ThomsonTan to close this once the next release is published.

**Comment by ThomsonTan** [comment]
This was fixed in https://github.com/open-telemetry/opentelemetry-cpp/pull/1458.
