### ISSUE TITLE
Remove LogName argument as deprecated from Logger API

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1421]
To be added

**Comment by owent** [comment]
Are we going to remove `LogName` in next release?

**Comment by lalitb** [comment]
Not necessarily the next release, but we need to do it eventually based on bandwidth. This issue is to track the cleanup.

**Comment by ThomsonTan** [comment]
@owent as removing logger name is a breaking change for logging, I suggest we don't ship it in the same release of the release candidate of OpenTelemetry metrics. So we either make the change in the release this month (the current plan is releasing metrics candidate in July), or make the change after the metrics release candidate. @owent, any recommendation on this?

**Comment by owent** [comment]
> @owent as removing logger name is a breaking change for logging, I suggest we don't ship it in the same release of the release candidate of OpenTelemetry metrics. So we either make the change in the release this month (the current plan is releasing metrics candidate in July), or make the change after the metrics release candidate. @owent, any recommendation on this?

I vote for make the change after the metrics release candidate.

**Comment by owent** [comment]
This issue is solved by #1884
