### ISSUE TITLE
Reconcile BAZEL and CMAKE dependency on nlohmann-json

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#1438]
Greetings,

In file `bazel/repository.bzl`

The `BAZEL` build uses `nlohmann-json` version 3.6.1

```
    # JSON library
    maybe(
        http_archive,
        name = "github_nlohmann_json",
        build_file = "@io_opentelemetry_cpp//bazel:nlohmann_json.BUILD",
        sha256 = "69cc88207ce91347ea530b227ff0776db82dcb8de6704e1a3d74f4841bc651cf",
        urls = [
            "https://github.com/nlohmann/json/releases/download/v3.6.1/include.zip",
        ],
    )
```

In file `third_party_release`

The `CMAKE` build uses `nlohmann-json` version 3.9.1

```
nlohmann-json=v3.9.1
```

At the very least, both builds should use the same version, so an upgrade to 3.9.1 in basel is needed.

Alternately, consider upgrading both to nlohmann-json 3.10.5 (Release date: 2022-01-03)

To avoid future discrepancies, please consider adding maintainer comments in each place,
pointing to the other build scripts.

Regards.

**Comment by owent** [comment]
Agree.
