### ISSUE TITLE
[Trace] Missing async HTTP client context propagation example

### ISSUE THREAD

**Issue by keminming** [open-telemetry/opentelemetry-cpp#1463]
The http client example shows only synchronous mode:
https://github.com/open-telemetry/opentelemetry-cpp/blob/96534a7c2370099ada8bd9dcdc7236c76adf47d9/examples/http/client.cc#L42

However, majority of the time, the http client will be worked in an asynchronous mode, similar to the code below:
http_client->Get(url, carrier.headers_,[](http_client::Result result){
  if (result)
  {
    // set span attributes
    auto status_code = result.GetResponse().GetStatusCode();
...
});

Need an example to show how the trace APIs work with callbacks and how the context gets propagated.

**Comment by lalitb** [comment]
The example code is just to demonstrate the context propagation, not how to use an internal[ http_client](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/ext/include/opentelemetry/ext/http/client/http_client.h) library in sync and async mode.  The internal http_client library won't be used for external applications, so the actual sync/async code would depend on the HTTP library used by the application.

Also, if you are looking for the async example for the internal http_client library, refer to the code sample [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/ef16d0048a0ccd6d664b86da1c95294633965bad/ext/include/opentelemetry/ext/http/client/http_client.h#L27).

**Comment by lalitb** [comment]
closing as reasoned above.
