### ISSUE TITLE
[Trace API] TextMapPropagator requires to use RuntimeContext

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#1467]
In our application, we are keeping track of `Span` manually, and on purpose do not use:
- `Scope`
- `RuntimeContext`

The motivation for this is due to:
- performance overhead concerns, reading and writing to `RuntimeContext` and thread local storage all the time,
- architectural concerns, because the application uses a thread pool, which `RuntimeContext` is not aware of.

I am aware we could implement a `RuntimeContextStorage` that is aware of the thread pool, but this is a no go.

Now, at some point the code needs to use propagation.

With this sample code:

```
class MyTextMapCarrier : public opentelemetry::context::propagation::TextMapCarrier {...}
class MyTextMapPropagator : public opentelemetry::context::propagation::TextMapPropagator {...}

MyTextMapCarrier carrier(...);
MyTextMapPropagator propagator(...);
const opentelemetry::trace::SpanContext & span_context = span->GetContext();
propagator.Inject(client_carrier, span_context);

```
the build fails with an (arcane) message when instantiating `context::Context::DataList` with a `SpanContext`.

```
In file included from /usr/local/include/opentelemetry/context/propagation/text_map_propagator.h:7,
                 from /home/malff/...redacted...cc:20:
/usr/local/include/opentelemetry/context/context.h: In instantiation of ‘opentelemetry::v1::context::Context::DataList::DataList(const T&) [with T = opentelemetry::v1::trace::SpanContext]’:
/usr/local/include/opentelemetry/context/context.h:29:41:   required from ‘opentelemetry::v1::context::Context::Context(const T&) [with T = opentelemetry::v1::trace::SpanContext]’
/home/malff/...redacted....cc:299:53:   required from here
/usr/local/include/opentelemetry/context/context.h:110:7: error: ‘begin’ was not declared in this scope; did you mean ‘std::begin’?
  110 |       for (auto &iter : keys_and_vals)
      |       ^~~
      |       std::begin
In file included from /usr/include/c++/10/string:54,
                 from /usr/include/c++/10/bits/locale_classes.h:40,
                 from /usr/include/c++/10/bits/ios_base.h:41,
                 from /usr/include/c++/10/streambuf:41,
                 from /usr/include/c++/10/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/10/iterator:66,
                 from /home/malff/...redacted....cc:7:
/usr/include/c++/10/bits/range_access.h:108:37: note: ‘std::begin’ declared here
  108 |   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&);
      |                                     ^~~~~
```
What the error message actually means, and how it is related to `propagator.Inject(client_carrier, span_context)` is still a mystery (to me), but this is beside the point.

The issue is that `TextMapPropagator::Inject()` only accepts a `const context::Context &context` parameter, and not a `SpanContext`.

Given that the only way to get a `context::Context` object is to call `RuntimeContext::GetCurrent()`, class `TextMapPropagator` can only be used if the application uses `RuntimeContext` all the time (which does not work in our case).

The application code could also maintain its own `context::Context` object, independently of `RuntimeContext`, but it sounds very inefficient to insert a `SpanContext` in a container (a linked list here), then retrieve it by name, when the `SpanContext` object is available on hand already.

Incidently, the first thing `HttpTraceContext::Inject()` does is:

    SpanContext span_context = trace::GetSpan(context)->GetContext();

before calling `InjectImpl()` with the `SpanContext`, but unfortunately `InjectImpl()` is private and can not be used.

Would it be possible to expose a `TextMapPropagator::Inject()` method that accepts a `SpanContext` directly as input,
so that:
- the entire code path is more efficient
- the `TextMapPropagator` can be used **_without_** a `RuntimeContext`.

Thanks,
-- Marc

**Comment by lalitb** [comment]
Thanks for well written issue, with all the required details. 

In current state, the only better option is to maintain own `context::Context` object and use that to pass `SpanContext` to Propagator.

```
context::Context current_ctx;
current_ctx.SetValue(kSpanKey, span);
prop->Inject(carrier, current_ctx);
```

The `context::propagation::TextMapPropagator` class ideally shouldn't have dependency on any of the Signals (trace, logs, metrics), and it is supposed to use the Context object to inject/extract the data.

Also, just to add there could be scope of improvement in current Context implementation using linked list (it was done by few Interns).

We can discuss this further in community meeting for options/suggestions.

**Comment by marcalff** [comment]
Thanks for the details.

I ended up using

```
      opentelemetry::context::Context wrapped_span_context;
      SetSpan(wrapped_span_context, span);

      propagator.Inject(carrier, wrapped_span_context);
```
which should be equivalent.

In my understanding, the whole concept of propagation is dedicated to the trace signal already.
Only traces needs to pass context to link a parent span to a child span when crossing service boundaries.

For metrics and logs, where would a `TextMapCarrier` + `TextMapPropagator` be needed, and what for ?

**Comment by lalitb** [comment]
> In my understanding, the whole concept of propagation is dedicated to the trace signal already.

Propagation is dedicated to trace and baggage, and baggage stores annotations data for logs, traces and metrics.

**Comment by marcalff** [comment]
(Discussed in community call)

With the following code (now tested)

```
opentelemetry::context::Context empty;
auto wrapped_span_context = SetSpan(empty, span);

propagator.Inject(carrier, wrapped_span_context);
```

propagation can be used without RuntimeContext,
so the issue originally reported is addressed.

Context could be more efficient to store and retrieve a span, but this is another topic.

Closing this issue then.
