### ISSUE TITLE
Add Codecov Badge to README.md

### ISSUE THREAD

**Issue by huyan0** [open-telemetry/opentelemetry-cpp#147]
**Is your feature request related to a problem?**
OpenTelemetry’s Python, JavaScript, Collector, Operator, Go, Java and PHP repository all have a Codecov badge which provide a quick link to details about code coverage. The C++ SDK repository does not have a Codecov badge yet.

**Describe the solution you'd like**
As a developer contributing to the C++ SDK, I’d like to add a Codecov badge. In general, badges help in increasing the readability of the README.md file because they provide key metrics about the health of the repositories.
For the Codecov badge, developers can learn about the effectiveness of the tests and the overall quality of the project by quickly scanning the attached badge.

**Describe alternatives you've considered**
Codecov badge can be acquired from codecov.io and added easily to README.md. We should also consider adding other badges for build status, license, and versions.

**Comment by pyohannes** [comment]
This is covered by #149.
