### ISSUE TITLE
The default value of FD_SETSIZE is too small for real scenario

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-cpp#1476]
**Describe your environment**
Windows 11 10.0.22000.739

**Steps to reproduce**
Run curl_http_test.exe

**What is the expected behavior?**
The test should pass

**What is the actual behavior?**
The test failed

**Additional context**
The test is failed on that the allocated socket handle value is larger than `FD_SETSIZE` which is 64. The value seems too small for real scenario.

**Comment by owent** [comment]
#1413 is already merged, maybe this issue can also be closed?

**Comment by ThomsonTan** [comment]
Resolved by #1413.
