### ISSUE TITLE
[Metrics] Otlp metric gRPC exporter has a wrong name.

### ISSUE THREAD

**Issue by owent** [open-telemetry/opentelemetry-cpp#1484]
Should `OtlpGrpcMetrics*` be  `OtlpGrpcMetric*` ? I found the name with (s) are used for legacy `_metrics` implements in other exporters, but `OtlpGrpcMetricsExporter` is implement of new metric SDK?
@lalitb

**Comment by lalitb** [comment]
@owent  - Correct, It should be `OtlpGrpcMetricExporter` for new implementation.  Would be consistent with `OStreamMetricExporter` and `InMemoryMetricExporter` (from #1481).  Please feel free to assign it to me. Thanks :)

**Comment by owent** [comment]
And bazel script is missing for `OtlpGrpcMetricExporter` now.

**Comment by lalitb** [comment]
> And bazel script is missing for OtlpGrpcMetricExporter now.

Will fix this one #1481 and #1487 are merged to avoid any further merge conflicts :)
