### ISSUE TITLE
Badges and Licensing on the Repo Readme

### ISSUE THREAD

**Issue by danielbang907** [open-telemetry/opentelemetry-cpp#149]
**Is your feature request related to a problem?**
In an effort to have the OpenTelemetry C++ SDK be as up-to-date and consistent with the other more established SDKs, (Python, Java) there should be some sort of status tracking on the main Readme.md file, so that any observer of the repo will be able to quickly and efficiently know of the progress, reliability, and licensing of the codebase.

**Describe the solution you'd like**
We could simply make use of the open source repo-badges (https://github.com/dwyl/repo-badges), version badges (https://github.com/badges/shields) and license badges (https://gist.github.com/lukas-h/2a5d00690736b4c3a7ba) and add them to the current readme, so that the documentation would look similar to its sister repositories: (screenshot of the Python Readme badges for reference)

![Screen Shot 2020-07-01 at 12 21 59 PM](https://user-images.githubusercontent.com/43049538/86274501-652b1700-bb97-11ea-852c-fe3685a149d4.png)

**Comment by huyan0** [comment]
Hi! I’m interested in working on this issue. Can you please assign to me and my mentor @alolita.

**Comment by pyohannes** [comment]
Assigned.

**Comment by pyohannes** [comment]
Thanks for fixing this @huyan!
