### ISSUE TITLE
[CI] Add ci jobs without `ENABLE_METRICS_PREVIEW` (bazel) and `WITH_METRICS_PREVIEW` (cmake)

### ISSUE THREAD

**Issue by owent** [open-telemetry/opentelemetry-cpp#1494]
**Is your feature request related to a problem?**

I notice the new metrics implement is enabled only when building without `ENABLE_METRICS_PREVIEW` (bazel) and `WITH_METRICS_PREVIEW` (cmake). But it's not checked in most CI jobs. I think we should add some steps or jobs to build without them.

**Comment by lalitb** [comment]
This was discussed in today's community meeting - Should we instead remove validating CI builds for old metrics implementation? This would simplify the CI, and also gives a message that the old implementation is going to be cleaned up in the coming days.

**Comment by owent** [comment]
Could we keep few CI jobs for the old metrics, just like `LogName` in log APIs? There are some projects use the old implements and it will take some time to migrate to the new one.
I think keep one job using bazel with new compiler and one jobs using cmake with gcc 4.8 would be enough.

**Comment by esigo** [comment]
`gcc 4.8` is already [broken](https://github.com/open-telemetry/opentelemetry-cpp/runs/7793318222?check_suite_focus=true) for the deprecated metrics. I removed it from #1531.
