### ISSUE TITLE
Add a badge for CI status

### ISSUE THREAD

**Issue by EdZou** [open-telemetry/opentelemetry-cpp#150]
Description:

*Is your feature request related to a problem?*
Most of the existing open-telemetry repositories (java/javascript/python/collector/go/ruby/rust) display a badge for CI status. It would be very useful to have a CI badge for the CPP repo too.

*Describe the solution you'd like.*
As a developer contributing to open-telemetry, I recommend to add a CI status badge on the README.md of C++ repo. Because CI can increases the speed of development while ensuring the quality of the code that teams deploy. 
And by adding a badge to README.md,  a developer will be able to know CI status easily by access CI badge.

*Describe alternatives you've considered.*
As seen in the Rust repo, we may provide a CI status badge which links to “Actions” page instead of linking to CircleCI website as well.

**Comment by pyohannes** [comment]
This is covered by #149.
