### ISSUE TITLE
url parser will incorrect parsing url like "http://aaa.com/eee@bbb/x/y"

### ISSUE THREAD

**Issue by wangzhen2271** [open-telemetry/opentelemetry-cpp#1509]
I report trace to url "http://tracing-analysis-dc-hz.aliyuncs.com/adapt_fdufe5deml@455595430f299c1_fdffe5degl@134f7ad2ffe83/api/otlp/traces".  It always failed,  I trace the code and found the urlparser take a mistake,  the parse result is:  host -- 455595430f299c1_fdffe5degl@134f7ad2ffe83 while it should be -- tracing-analysis-dc-hz.aliyuncs.com. 

I think the "**@**" should be considered just when it in the first segment,  so this should be fixed.

I want to submit a pull request to fix it.

![image](https://user-images.githubusercontent.com/24283291/180213131-a0e8f2c9-cb42-443c-baa8-50a07c03da4f.png)

**Comment by esigo** [comment]
already fixed in #1511.
