### ISSUE TITLE
Enhance tracing in otel-demo for v1 release

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-cpp#1521]
Tracing instrumentation needs to be enhanced in the community demo in preparation for the v1 release. 

Referencing issue:
https://github.com/open-telemetry/opentelemetry-demo/issues/52

**Comment by lalitb** [comment]
Closing it here, let's track it using parent issue - https://github.com/open-telemetry/opentelemetry-demo/issues/52
