### ISSUE TITLE
Produce libraries with consistent name in both bazel and Cmake build

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-cpp#1522]
File as follow up for below comment. Currently bzcel and CMake build produce different set of library names.

[#1420](https://github.com/open-telemetry/opentelemetry-cpp/pull/1420/#discussion_r887445259)

**Comment by lalitb** [comment]
Is it different from #1428? If yes, can we add more information to this issue? Thanks :)

**Comment by ThomsonTan** [comment]
@lalitb it should be covered by #1428 as well.
