### ISSUE TITLE
Build gRPC using CMake

### ISSUE THREAD

**Issue by nadiaciobanu** [open-telemetry/opentelemetry-cpp#154]
**Context**
The OTLP exporter uses gRPC to communicate with the OpenTelemetry Collector. Currently we are building gRPC with Bazel, but not with CMake.

**Problem**
The OTLP exporter tests run on Windows using [CMake](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/.github/workflows/ci.yml#L162) only.

**Solution**
Build gRPC using CMake (see [gRPC documentation](https://github.com/grpc/grpc/blob/master/src/cpp/README.md#cmake)). Add OTLP exporter tests to `exporters/otlp/CMakeLists.txt`.

**Comment by ahaeber** [comment]
I've recently worked with adding gRPC to an internal project with CMake so I'm trying to contribute a fix for this issue in #369 

I couldn't quite figure out which gRPC version is used with Bazel, so it currently is set to v1.32.0. Let me know if something else should be used.

**Comment by ThomsonTan** [comment]
@lalitb should this be as building OTLP+gRPC with CMake is supported?
