### ISSUE TITLE
Nothing calls ObservableRegistry::Observe()

### ISSUE THREAD

**Issue by ahadnagy** [open-telemetry/opentelemetry-cpp#1550]
I've been trying to use async instruments, but got slightly confused about the API and the status of the implementation.

The problem I ran into is that the callbacks are not getting evaluated and no data is exported. I see that the API has recently changed in https://github.com/open-telemetry/opentelemetry-cpp/pull/1388 that introduced `ObservableRegistry`. It seems like the `ObservableRegistry::Observe()` method would be the one evaluating all the registered callbacks, but it doesn't get called anywhere. According to the corresponding issue (https://github.com/open-telemetry/opentelemetry-cpp/issues/1338), all the callbacks should be evaluated before/during `collect()`.

Am I missing something here? I don't see any open issues or PRs for async instruments. If this is a bug, I'd glad to help out with a PR after some explanation about where and how this should happen.

Thanks a lot in advance!

**Comment by lalitb** [comment]
Yes, thanks for raising the issue. I am aware of the issue and was planning for fix. But it you already in process of debugging, please feel free to raise a PR. We need this before going for RC which is tentative planned for 15th Aug - https://github.com/open-telemetry/opentelemetry-cpp/milestone/13

**Comment by ahadnagy** [comment]
What would be your preferred way of implementing this provided that `AsyncMetricStorage` doesn't know about `ObservableRegistry` and `ObservableInstruments` in general?
Giving `AsyncMetricStorage` a shrared_ptr to any of these doesn't seem very idiomatic.

**Comment by lalitb** [comment]
@ahadnagy - This is broken after #1495. For now, I have assigned it to myself, as I am responsible for breaking it :) I don't have the correct approach for now, let me go through the code once. Let me know if that is fine.
