### ISSUE TITLE
Otel Metrics: Asynch Instruments are not displaying values

### ISSUE THREAD

**Issue by tauseef-ah** [open-telemetry/opentelemetry-cpp#1556]
**Describe your environment**
Opentelemetry main branch

**Steps to reproduce**
Build and run sample test "./metrics_ostream_example observable_counter"

**What is the expected behavior?**
What did you expect to see?
The aynch metrics(like observable counter, observable gauge) need to be displayed along with the attributes

**What is the actual behavior?**
What did you see instead?
The Asynch Metrics(like observable counter, observable gauge) are not being displayed, and only the version info is being printed
{
  name          : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Thu Aug 11 10:07:56 2022
  end time      : Thu Aug 11 10:07:57 2022
  name          : ostream_metric_example
  description   : description
  unit          :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.5.0
}

**Additional context**

**Comment by lalitb** [comment]
Duplicate to #1550

**Comment by lalitb** [comment]
#1554 fixes it. Please reopen if there are still any issues.
