### ISSUE TITLE
Received Undefined symbol on loading shared library libopentelemetry_exporter_otlp_grpc_metrics.so

### ISSUE THREAD

**Issue by DebajitDas** [open-telemetry/opentelemetry-cpp#1557]
**Describe your environment**
Built OpenTelemetry version 1.5.0 on centos7, using the command "cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON -DWITH_OTLP=ON" and cmake --build . --target all.
It builts successfully and generates libopentelemetry_exporter_otlp_grpc_metrics.so.
Using this library with Apache server in "otel-webserver-repo" repo gives error while loading the library.

Cannot load /opt/opentelemetry-webserver-sdk/sdk_lib/lib/libopentelemetry_exporter_otlp_grpc_metrics.so into server: /opt/opentelemetry-webserver-sdk/sdk_lib/lib/libopentelemetry_exporter_otlp_grpc_metrics.so: undefined symbol: _ZN13opentelemetry2v18exporter4otlp22OtlpGrpcMetricExporter10ForceFlushENSt6chrono8durationIlSt5ratioILl1ELl1000000EEEE

Also below shows the symbol as undefined
nm libopentelemetry_exporter_otlp_grpc_metrics.so | grep -i ForceFlush            
                 U _ZN13opentelemetry2v18exporter4otlp22OtlpGrpcMetricExporter10ForceFlushENSt6chrono8durationIlSt5ratioILl1ELl1000000EEEE

Need guidance if I am missing anything?

**Comment by lalitb** [comment]
#1539 fixes it. Please try with latest commit. New metrics implementation is flaky in v1.5.0, and you can disable it by enabling old metrics with `-DENABLE_METRICS_PREVIEW=ON`.
