### ISSUE TITLE
[DOCS] API Documentation for Metrics SDK and API

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1575]
The otel-cpp documentation is maintained at https://opentelemetry-cpp.readthedocs.io/en/latest/.

As of now. it only contains API documentation for Traces, along with Baggage, Resources, and InstrumentationLibrary.
Need to add API documentation for Metrics.

**Comment by marcalff** [comment]
Keeping this issue open, as a proxy, so it gets tracked in cpp milestones.

Doc to be delivered in opentelemetry.io,
see https://github.com/open-telemetry/opentelemetry-cpp/issues/1589
