### ISSUE TITLE
Data structure usage for intermediate storage in Prometheus Exporter

### ISSUE THREAD

**Issue by erichsueh3** [open-telemetry/opentelemetry-cpp#158]
**Is your feature request related to a problem?**
In a proposed Prometheus Exporter in C++, intermediate storage between exporting data and collecting data must be implemented due to its nature as a pull based exporter. However, it is unclear whether or not containers from STL such as vectors can be used or not, though usage of STL seems not to be limited when building an exporter.

**Describe the solution you'd like**
If STL is available, a vector would be used as the container for intermediate storage in the Prometheus Exporter. Vectors have the added benefit of being contiguous in memory, allowing for deep copies to be made easily using a function like memcpy(). This is important for concurrency, which needs to be guaranteed when collecting data. 

**Describe alternatives you've considered**
Alternatively, if STL is not available, then we could manage an array internally as our intermediate storage container. This would be more prone to various errors, but if implemented correctly, should function the same as a vector.

**Additional context**
In order to fit in the Metrics API data pipeline, we decided to add an intermediate storage in our Prometheus Exporter design. The controller calls the export() function and sends out the data. It is natural for push based exporters, because then the data can be pushed directly to the target system in the export() function. For Prometheus, it's different because Prometheus uses a pull based exporter. We need to wait for a pull request from the Prometheus server before serving the data, but we don't know when the request will come, so we need some place to store and hold the data.

**Comment by reyang** [comment]
STL can be used in the exporter.
