### ISSUE TITLE
set(WITH_ABSEIL OFF) still requires Abseil

### ISSUE THREAD

**Issue by paro-** [open-telemetry/opentelemetry-cpp#1580]
Hi,

As my project already includes abseil, but another version from opentelementry-cpp's, I get a compilation error: 
`opentelemetry-cpp/api/include/opentelemetry/nostd/./internal/absl/types/../types/internal/variant.h:512:38: error: reference to 'make_index_sequence' is ambiguous`

So I wanted to build opentelemetry without Abseil (as suggested in the [doc](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/docs/dependencies.md)), but using `set(WITH_ABSEIL OFF)`, and even `set(WITH_STL ON)`, still outputs the same abseil-related error.

It there an issue in the doc, or another way to achieve this?

Thanks, good day,
Paul

**Comment by owent** [comment]
When using `set(WITH_ABSEIL OFF)` , otel will use a internal subset of abseil, which has the same namespace with the full version of abseil-cpp.
If your project already has abseil, the better way is just add the installation PATH of abseil in your project to cmake find PATH.So that opentelemetry-cpp can also find and use it.
Maybe by adding it to [CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html) or setting `absl_ROOT` . You can find more detail at https://cmake.org/cmake/help/latest/command/find_package.html#command:find_package .

**Comment by lalitb** [comment]
@paro-  Do you still have any further questions, or can be close this?

**Comment by paro-** [comment]
Hi,
Thank you for the answer.
So it's not clear if otel can use an external abseil (apparently it might work with CMAKE_PREFIX_PATH).
My issue is that in my main CMakeLists I would need to write:
 `add_subdirectory(abseil)`
 `add_subdirectory(otel)`
in which case abseil detects that it is [not in installation mode](https://github.com/abseil/abseil-cpp/blob/master/CMakeLists.txt#L182) and will not install its abseilTargets files, so otel won't understand that abseil will be compiled (it requires to be fully installed beforehand.
Any suggestion on how to deal with that, otherwise we can't use otel with an external abseil in our project it seems.

Kind regards,
Paul

**Comment by owent** [comment]
I'm not sure , but maybe you can use these codes if you import abseil by source

```cmake
add_subdirectory(abseil)
include_directories(<abseil source repo>)
set(WITH_ABSEIL ON)
add_subdirectory(otel)
```

**Comment by ThomsonTan** [comment]
@paro- I saw you posted a similar question to https://github.com/abseil/abseil-cpp/issues/1260#issuecomment-1237411526, it could work for opentelemetry-cpp in the same way (disable `find_package(absl)` in opentelemetry-cpp by `set(absl_FOUND TRUE)`.

**Comment by owent** [comment]
@paro-  Just wondering if you are able to resolve the issue?

**Comment by lalitb** [comment]
Closing this, please reopen if you still see the issue/questions.
