### ISSUE TITLE
Can not build: undefined reference to `absl::lts_20220623::variant_internal

### ISSUE THREAD

**Issue by sddwt** [open-telemetry/opentelemetry-cpp#1587]
Hi, I can build with you provided cmake files, but when I trid to use `g++ -o test test.cc  -lopentelemetry_trace -lopentelemetry_exporter_otlp_grpc -lopentelemetry_resources -lopentelemetry_common` I got such error:
```
[root@OS otlp]# g++ -o test test.cc  -lopentelemetry_trace -lopentelemetry_exporter_otlp_grpc -lopentelemetry_resources -lopentelemetry_common
/usr/bin/ld: /usr/local/lib64/libopentelemetry_trace.a(tracer.cc.o): in function `opentelemetry::v1::nostd::shared_ptr<opentelemetry::v1::trace::Span>& absl::lts_20220623::variant_internal::TypedThrowBadVariantAccess<opentelemetry::v1::nostd::shared_ptr<opentelemetry::v1::trace::Span>&>()':
tracer.cc:(.text._ZN4absl12lts_2022062316variant_internal26TypedThrowBadVariantAccessIRN13opentelemetry2v15nostd10shared_ptrINS4_5trace4SpanEEEEET_v[_ZN4absl12lts_2022062316variant_internal26TypedThrowBadVariantAccessIRN13opentelemetry2v15nostd10shared_ptrINS4_5trace4SpanEEEEET_v]+0x5): undefined reference to `absl::lts_20220623::variant_internal::ThrowBadVariantAccess()'
/usr/bin/ld: /usr/local/lib64/libopentelemetry_trace.a(tracer.cc.o): in function `opentelemetry::v1::trace::SpanContext const& absl::lts_20220623::variant_internal::TypedThrowBadVariantAccess<opentelemetry::v1::trace::SpanContext const&>()':
tracer.cc:(.text._ZN4absl12lts_2022062316variant_internal26TypedThrowBadVariantAccessIRKN13opentelemetry2v15trace11SpanContextEEET_v[_ZN4absl12lts_2022062316variant_internal26TypedThrowBadVariantAccessIRKN13opentelemetry2v15trace11SpanContextEEET_v]+0x5): undefined reference to `absl::lts_20220623::variant_internal::ThrowBadVariantAccess()'
/usr/bin/ld: /usr/local/lib64/libopentelemetry_trace.a(tracer.cc.o): in function `opentelemetry::v1::context::Context const& absl::lts_20220623::variant_internal::TypedThrowBadVariantAccess<opentelemetry::v1::context::Context const&>()':
tracer.cc:(.text._ZN4absl12lts_2022062316variant_internal26TypedThrowBadVariantAccessIRKN13opentelemetry2v17context7ContextEEET_v[_ZN4absl12lts_2022062316variant_internal26TypedThrowBadVariantAccessIRKN13opentelemetry2v17context7ContextEEET_v]+0x5): undefined reference to `absl::lts_20220623::variant_internal::ThrowBadVariantAccess()'
/usr/bin/ld: /usr/local/lib64/libopentelemetry_exporter_otlp_g
```

The output seems to tell me that `absl::lts_20220623::variant_internal` is not exists in file `libopentelemetry_trace.a`,
but I have already installed `abseil` by build their project, how can I use g++ to provide abseil lib?

Thanks for your time!

**Comment by lalitb** [comment]
Can you share the build steps used by you to build opentelemetry-cpp?

If you want to use the externally installed abseil library, you can do this by using `WITH_ABSEIL` cmake option during opentelemetry-cpp build.

**Comment by sddwt** [comment]
> Can you share the build steps used by you to build opentelemetry-cpp?
> 
> If you want to use the externally installed abseil library, you can do this by using `WITH_ABSEIL` cmake option during opentelemetry-cpp build.

Thanks for your reply.
Here is my step to build opentelemetry-cpp:

```
 cd opentelemetry-cpp
 mkdir build && cd build
 cmake -DWITH_OTLP=ON -DWITH_ABSEIL=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DWITH_OTLP_GRPC=ON ..
 cmake --build . --target all
 ctest
 cmake --install . --prefix /root/
```

My environment is:
```
centos stream9
libprotoc 3.21.5 (dnf install)
cmake 3.20.2
```

The example can be built and works as expected, but when I tried to write a single cpp file and use the lib built previously, the error occurred.

I wander if I need to specific the path of absl when I use command like `g++ -o test test.cc -lopentelemetry_trace -lopentelemetry_exporter_otlp_grpc -lopentelemetry_resources -lopentelemetry_common` ? How can I specific the path of absl lib in this command?

Thanks.

**Comment by lalitb** [comment]
@sddwt  Just wondering if you are able to resolve the issue, or have any further questions?

**Comment by lalitb** [comment]
Closing as the solution is suggested above. Feel free to open a discussion thread if there are some more doubts.
