### ISSUE TITLE
More Issues on Intermediate Storage of Prometheus Exporter Design

### ISSUE THREAD

**Issue by CunjunWang** [open-telemetry/opentelemetry-cpp#159]
**Is your feature request related to a problem?**
Yes. In order to guarantee the current Prometheus Exporter design works, we need to figure out the following problems about the intermediate storage:

* What if the storage is full when `export()` function is called? Is the new batch of data discarded or will some data in the storage be replaced? What is the replacement strategy?
* What is the default collection capacity? How to determine it? Are there alternatives you are suggesting? 
* Is capacity (size of the storage) configurable (such as an environment parameter) ?
* What should be the replacement strategy when the storage is full? LRU? LFU? FIFO?
* For the fake dump, where should we dump the data? Shall we discard the data directly?

**Describe the solution you'd like**
We don’t have solution for these problems yet, but we prefer the following mechanism:

* If the free space is not enough for adding the coming batch of data, we are going to discard the coming data. We think the older metrics data are more important.
* We think it’s better to make the storage size configurable, but we have no idea about the default size.
* In this solution, we are not going to replace any data in the storage, so we don’t consider which replacement strategy to use.

**Describe alternatives you've considered**
There are two alternatives:

1. Still use memory bound, and replace old data if the storage is full when new data comes.
    1. The default storage capacity is still a pending problem. 
    2. If we are going to replace data, we will also replace from tail of the storage. They are newer metrics data and we think newer data are less important then older data.
2. Use a time boundary instead. 
    1. We were suggested to use a time boundary initially, which means that we set a timeout, and use a timer to keep track of the time elapsed after last pull. After the pre-defined time threshold, do a fake pull to flush data. When the user pull data successfully, set the timer to zero can keep track of the time again. We don’t think this solution is better than a memory boundary for the following problems:
        1. Where would the fake flush dumps data to? Does the fake flush discard this data?
        2. From the Prometheus side, is it possible that metrics data would be found missing (due to the fake flush)?
        3. What are the standards to choose a reasonable timeout?
        4. We still need to use some data structure to hold the data, so the size of the collection is still limited. What if the collection is full before a fake flush?
3. We are leaning towards using a memory boundary (limiting the storage size).

**Additional context**
The same context with issue #158

**Comment by reyang** [comment]
> * What if the storage is full when `export()` function is called? Is the new batch of data discarded or will some data in the storage be replaced? What is the replacement strategy?

I think we will just drop the new data. This is what most of the tracer exporters would do.

> * What is the default collection capacity? How to determine it? Are there alternatives you are suggesting?

That's a good question, I think this is something the specification should give guidance. For traces, this is [configurable](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#batching-processor) and you can also find the recommended default values.

> * Is capacity (size of the storage) configurable (such as an environment parameter) ?

Same answer as above.

> * What should be the replacement strategy when the storage is full? LRU? LFU? FIFO?

Looks like the same as question 1? I think we should drop new data when storage is full. It will be great if we can have a flag to drop oldest data, but I don't think it is required.

> * For the fake dump, where should we dump the data? Shall we discard the data directly?

Sorry the question wasn't clear to me. I think at minimum we should have a console exporter, which is useful for debugging / simple testing. In memory exporter can be helpful as well since I imagine unit test could leverage it.

**Comment by CunjunWang** [comment]
Thanks for such a quick and clear response, Reiley! Sorry for confusing you in the last question, but since we are going to implement the memory boundary, we can just ignore that.
