### ISSUE TITLE
Compile errors appear when i import api/opentelemetry/logs/logger.h

### ISSUE THREAD

**Issue by NJU-Eden** [open-telemetry/opentelemetry-cpp#1590]
I import opentelemetry-cpp with tag 1.5.0 in my project by bazel. My  environment is centos7 with gcc 8.4.0.

if i include  api/opentelemetry/logs/logger.h file and donot do anything else, the error appears

bazel-out/k8-fastbuild/bin/external/io_opentelemetry_cpp/api/_virtual_includes/api/opentelemetry/logs/logger.h:167:57: error: macro "Log" requires 4 arguments, but only 2 given
   void Log(Severity severity, nostd::string_view message) noexcept
                                                         ^
bazel-out/k8-fastbuild/bin/external/io_opentelemetry_cpp/api/_virtual_includes/api/opentelemetry/logs/logger.h:185:50: error: macro "Log" requires 4 arguments, but only 2 given
   void Log(Severity severity, const T &attributes) noexcept
                                                  ^
bazel-out/k8-fastbuild/bin/external/io_opentelemetry_cpp/api/_virtual_includes/api/opentelemetry/logs/logger.h:235:73: error: macro "Log" requires 4 arguments, but only 2 given
   void Log(Severity severity, const common::KeyValueIterable &attributes) noexcept
                                                                         ^
bazel-out/k8-fastbuild/bin/external/io_opentelemetry_cpp/api/_virtual_includes/api/opentelemetry/logs/logger.h: In member function 'void opentelemetry::v1::logs::Logger::Trace(const T&)':
bazel-out/k8-fastbuild/bin/external/io_opentelemetry_cpp/api/_virtual_includes/api/opentelemetry/logs/logger.h:281:11: error: 'class opentelemetry::v1::logs::Logger' has no member named 'Log'; did you mean 'OI_Log'?
     this->Log(Severity::kTrace, attributes);
           ^~~
           OI_Log

**Comment by marcalff** [comment]
Please check the project code, and any file included before `api/opentelemetry/logs/logger.h`, for a Log macro.

If such macro is present, it will confuse the compiler when reading the `logger.h` header file, causing the errors seen.

**Comment by owent** [comment]
You may try to wrapper pragma push_macro/pop_macro when including logs headers if your project has define `Log` as a macro. e.g.

```cpp
#pragma push_macro("Log")
#ifdef Log
#undef Log
#endif

#include < api/opentelemetry/logs/logger.h>

#pragma pop_macro("Log")
```

**Comment by lalitb** [comment]
Not directly related to this issue, but with the recent changes in the Logs API (https://github.com/open-telemetry/opentelemetry-specification/pull/2676), and potentially in Logs SDK ( https://github.com/open-telemetry/opentelemetry-specification/pull/2768), we may want to change the method name to Logger::Emit() for both Logs and Events.

Closing this issue, as this seems to be macro with same name.

**Comment by ThomsonTan** [comment]
As the names like `Log` or `Emit` is very common to be defined as macro in app code, perhaps we (in logger.h) could checked whether it is pre-defined and prompt the user with more helpful message?

**Comment by lalitb** [comment]
Non capitalized macros are always evil and should be avoided for errors like above. I don't think we should handle these kinds of checks in opentelemetry.
