### ISSUE TITLE
[Metrics SDK] Change the default buckets for Explicit Bucket Histogram

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1629]
Change the default buckets as per specs changes - https://github.com/open-telemetry/opentelemetry-specification/pull/2770 from
0, 5, 10, 25, 50, 75, 100, 250, 500, 1000 to 0, 5, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000

**Comment by esigo** [comment]
closed by #1626
