### ISSUE TITLE
[Metrics SDK] Switch to explicit 64 bit integers

### ISSUE THREAD

**Issue by sam-leitch-oxb** [open-telemetry/opentelemetry-cpp#1639]
All "Long" instruments in the API accept `long` as an input value. `long` does not have a well defined bit depth and can represent either 64 bit or 32 bit integers depending on the compiler implementation (and configuration).

"Long" instruments should be changed to accept `int64_t` integer values, which are unambiguously 64 bit depth as requested by the API specification: https://opentelemetry.io/docs/reference/specification/common/#attribute

**Comment by sam-leitch-oxb** [comment]
You're right. My mistake. I can't find anything that explicitly requires specific value types.

My goal was only to prevent unintended integer overflow on 32 bit compilers, since counters that pass the 32bit boundary are not-uncommon (eg. timestamps, memory usage, network bytes read/written)

**Comment by lalitb** [comment]
> My goal was only to prevent unintended integer overflow on 32 bit compilers, since counters that pass the 32bit boundary are not-uncommon (eg. timestamps, memory usage, network bytes read/written)
