### ISSUE TITLE
[CI] Add a -Wall -Werror build

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#1648]
Add a build in CI to detect compilation warnings, and fail the build on warnings.

To test with a recent version of GCC and/or CLANG.

The build in general should be clean.

In particular, user visible headers (like the API) should be warning free,
to allow the user code to build warning free.

Adding a CI build to enforce this will help to maintain clean code.

**Comment by lalitb** [comment]
related issue for gcc, clang and msvc #249

**Comment by marcalff** [comment]
> Please build using both gcc and clang if possible. Both compilers have different diagnostics, so some issues are detected by one of them only.

Yes, planning both.
