### ISSUE TITLE
TraceZ page in opentelemetry-cpp

### ISSUE THREAD

**Issue by liadavid** [open-telemetry/opentelemetry-cpp#166]
### **Is your feature request related to a problem?**
ZPages are web-pages that display general and debugging information on processes. Tracez provides details about the trace spans in the process. Currently there are few WIP projects to add zPages to OpenTelemetry, following the [zPages spec/general direction](https://github.com/open-telemetry/oteps/blob/master/text/0110-z-pages.md).
We would like to add a Tracez zPage to the OpenTelemetry-CPP package.

### **Describe the solution you'd like**

**The tracez page should include:**
- Aggregated statistics about all current Spans.  
- Span samples that provide additional attributes and are chosen based on errors/latency. 

**Scope and requirements:**
- Render a Tracez page in-proc.
- Integrate with the current C++ SDK (Specifically through TracerProvider). 
- Code is added under 'ext/'.

**High level design**
TraceZ architecture is divided into the following components: 
- **TraceZSpanProcessor** [design](https://docs.google.com/document/d/1kO4iZARYyr-EGBlY2VNM3ELU3iw6ZrC58Omup_YT-fU/edit?usp=sharing) - is responsible for extracting the spans from the process and propagate them to TracezDataAggregator. Implements SpanProcessor [interface](https://github.com/open-telemetry/opentelemetry-cpp/blob/9e2418b41d9de9ed4ead7128458860db23d69616/sdk/include/opentelemetry/sdk/trace/processor.h).
- **TracezDataAggregator** [design](https://docs.google.com/document/d/1ziKFgvhXFfRXZjOlAHQRR-TzcNcTXzg1p2I9oPCEIoU/edit?usp=sharing) - this component performs the needed aggregations on the data propagated by the TraceZSpanProcessor. Possible aggregations are: distribution of latencies for each span, number of spans with errors vs. total count of spans (per unit of time). The aggregator will also be responsible for storing additional attributes for a few Span samples.
- **Data rendering logic** [design(draft)](https://docs.google.com/document/d/1U1V8QZ5LtGl4Mich-aJ6KZGLHrMIE8pWyspmzvnIefI/edit?usp=sharing) - provides the statistics and aggregations to the developer.

### **Describe alternatives you've considered**
- Integrate TraceZ directly with API layer instead of SDK.
- Out of proc data rendering logic. 

Both alternatives are good extensions for the MVP defined above. 
Another possible extension is to add a Tracez Sampler component that will enable the developer to determine the sampling ratio of traces shown/aggregated in TraceZ. 

### **Additional context**
[README](https://github.com/open-telemetry/opentelemetry-cpp/tree/master/ext/src/zpages)

### Open Questions
- SpanProcessor [interface](https://github.com/open-telemetry/opentelemetry-cpp/blob/9e2418b41d9de9ed4ead7128458860db23d69616/sdk/include/opentelemetry/sdk/trace/processor.h) accepts Recordable. Following the interface, should TraceZSpanProcessor accept Recordable as well? If yes, can we add getter functions to the [Recordable interface](https://github.com/open-telemetry/opentelemetry-cpp/blob/9b624b9bbba6761a891b20bc305a9c92d995812d/sdk/include/opentelemetry/sdk/trace/recordable.h)?

**Comment by pyohannes** [comment]
> SpanProcessor interface accepts Recordable. Following the interface, should TraceZSpanProcessor accept Recordable as well? If yes, can we add getter functions to the Recordable interface?

No, we don't want to add getters to the `Recordable` interface and force every vendor to implement it. You can either:
* Use the existing `SpanData`. It derives from `Recordable` and has getters. You can then cast from `Recordable` to `SpanData` in the processor.
* Implement your own class deriving from `Recordable` and implementing getters. You can then cast from `Recordable` to your derived class in the processor.

**Comment by liadavid** [comment]
> > SpanProcessor interface accepts Recordable. Following the interface, should TraceZSpanProcessor accept Recordable as well? If yes, can we add getter functions to the Recordable interface?
> 
> No, we don't want to add getters to the `Recordable` interface and force every vendor to implement it. You can either:
> 
> * Use the existing `SpanData`. It derives from `Recordable` and has getters. You can then cast from `Recordable` to `SpanData` in the processor.
> * Implement your own class deriving from `Recordable` and implementing getters. You can then cast from `Recordable` to your derived class in the processor.

**Comment by liadavid** [comment]
> > SpanProcessor interface accepts Recordable. Following the interface, should TraceZSpanProcessor accept Recordable as well? If yes, can we add getter functions to the Recordable interface?
> 
> No, we don't want to add getters to the `Recordable` interface and force every vendor to implement it. You can either:
> 
> * Use the existing `SpanData`. It derives from `Recordable` and has getters. You can then cast from `Recordable` to `SpanData` in the processor.
> * Implement your own class deriving from `Recordable` and implementing getters. You can then cast from `Recordable` to your derived class in the processor.

Thanks Johannes for the explanation regarding Recordable.

**Comment by marcalff** [comment]
Closing, as zpages is removed, see #2292
