### ISSUE TITLE
[Metrics SDK] -  Supporting changing Aggregation type using Views

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1664]
As of now, implementation supports default aggregation for each instrument as defined here - https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#default-aggregation

As per the specs, it should be possible to customize the aggregation through views - https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#view :

``
Customize the aggregation - if the default aggregation associated with the Instrument does not meet the needs of the user. For example, an HTTP client library might expose HTTP client request duration as [Histogram](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#histogram) by default, but the application developer might only want the total count of outgoing requests.
``

This support needs to be added to the implementation.

**Comment by mprzybylski** [comment]
Hi,

My work is currently impacted by this issue, and I think I can fix it and contribute that fix upstream.  Before I dive in, I wanted to see if @lalitb , @esigo, or @ThomsonTan had any specific wishes on the way it should be done, or pointers aside from what's in https://github.com/open-telemetry/opentelemetry-cpp/blob/main/CONTRIBUTING.md

**Comment by lalitb** [comment]
@mprzybylski thanks for pitching in. I have some work done on this locally, and should be able to raise a PR out of it sometime first week of Jan.

**Comment by mprzybylski** [comment]
Thanks, @lalitb!

Please ping me when you raise that PR.  I'd very much like to read it, and build upon it, if necessary.
