### ISSUE TITLE
Unable to export to OTLP HTTP collector ERROR: unmarshal failed: unknown field \"scope_spans\" in v1.ResourceSpans"

### ISSUE THREAD

**Issue by shrutich91** [open-telemetry/opentelemetry-cpp#1681]
**Describe your environment**
Unable

**Steps to reproduce**
instrumenting foo program and exporting to OTLP HTTP endpoint

**What is the expected behavior?**
It should export to OTLP collector

**What is the actual behavior?**
 [Error] File: exporters/otlp/src/otlp_http_exporter.cc:107[OTLP HTTP Client] ERROR: Export 1 trace span(s) error: 1 ,Body:{"code":3,"message":"unmarshal failed: unknown field \"scope_spans\" in v1.ResourceSpans"}400Header:      Content-Length : 90

**Comment by lalitb** [comment]
What is the opentelemetry-collector version you are using - Please ensure it's v0.58.0 or higher ?

**Comment by shrutich91** [comment]
Thanks, that seemed to be causing the issue. OTEL Collector v0.58.0 resolved it
