### ISSUE TITLE
[Logs API] LoggerProvider changes

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1687]
Changes required in LoggerProvider::GetLogger()` method as per the logs API specs:
 - `Logger name` is not the part of logs data model, and can be removed.
 - `event_domain` (optional, required if you want to emit events) - These should be added to instrumentation scope attributes through SDK ( with key as `event_domain`)
 - `include_trace_context` (optional, true by default)
 - `attributes` - These should be added to instrumentation scope attributes through SDK. 

The GetLogger() method would look something like - 

```cpp
  virtual nostd::shared_ptr<Logger> LoggerProvider::GetLogger(nostd::string_view library_name,
                                              nostd::string_view library_version = "",
                                              nostd::string_view schema_url      = "",
                                              nostd::string_view event_domain,
                                              bool include_trace_context = true,
                                               const common::KeyValueIterable &attributes) = 0;
```

**Comment by owent** [comment]
Please don't stale this issue, I will continue finish left works when I have time.
Sorry, I only work on this in spare time and can not finish all changes in a short period of time.

**Comment by lalitb** [comment]
Thanks for informing @owent. Have un-stalled all these issues. In general, feel free to remove the `stale` tag for any such issues  - this is justified as you are the approver for this repo :)
