### ISSUE TITLE
MacOS Bazel Tests Fail When New Version of Bazel is Released

### ISSUE THREAD

**Issue by Brandon-Kimberly** [open-telemetry/opentelemetry-cpp#169]
**Is your feature request related to a problem?**
Yes, currently our MacOS Bazel CI test fails each time a new version of Bazel is released. This is fixed by simply updating the .bazelversion file to the most recent version of Bazel. However, this is very inconvenient and should not be necessary for every update to Bazel.

**Describe the solution you'd like**
The GitHub Actions MacOS runners have the most recent version of Bazel pre-installed, therefore there is no previous Bazel setup in the CI job. I would like for the CI job to install a specific version of Bazel allowing us to update out project's Bazel version at our discretion.

**Describe alternatives you've considered**
The primary alternative is to leave the CI job the way it is. This ensure that we are always using the latest Bazel version but also forces us to update the .bazelversion file each time Bazel is updated, even if it is a minor patch,

**Comment by maxgolov** [comment]
Is it possible to consume Bazel as a git submodule from https://github.com/bazelbuild/bazel mapped to `third_party/bazel`, and parse the latest version from git tag on a submodule? That way GitHub Action clones latest from Bazel master every time, and you'd retrieve the concrete latest version from there.

**Comment by maxgolov** [comment]
..or modify `.bazelversion` in a CI setup job based on latest tag on original Bazel repo, and automatically commit it back to remote as part of CI.
