### ISSUE TITLE
[Logs SDK] Modify InstrumentationScope class

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1690]
Instrumentation class needs to be modified to store key-value attributes. This is required for storing the event_name and attributes passed through LoggerProvider::GetLogger() method.

This is also consistent with the OTLP proto specs- 

https://github.com/open-telemetry/opentelemetry-proto/blob/1e69bf2e789665a56eed3a3e9cf4fd51ff784ab6/opentelemetry/proto/common/v1/common.proto#L71

**Comment by owent** [comment]
Please don't stale this issue, I will continue finish left works when I have time.
Sorry, I only work on this in spare time and can not finish all changes in a short period of time.
