### ISSUE TITLE
[Logs SDK] Rename and update existing LogRecord class, modify existing Recordable interface

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1691]
- To avoid conflict with the new LogRecord class, rename existing sdk::logs::LogRecord class to some better name (say sdk::logs::LogRecordData).
- Add setter for observed_timestamp in sdk:logs::Reordable and sdk::logs::LogRecordData.
- Similar to Span's Recordable, add a getter method for LogRecordData in Recordable class. This can be eventually implemented by all it's derived implementation (not in scope for now).
```cpp
  /**
   * Get the LogRecordData object for this Recordable.
   *
   * @return LogRecordData*
   */

  virtual explicit operator LogRecordData *() const { return nullptr; }

```

This would let us avoid having `ReadWriteLogRecord` class. This method can be potentially used inside `LogRecordProcessor` to filter the logs based on it's contents (not in scope for now).

**Comment by owent** [comment]
Can we just rename it to `ReadWriteLogRecord` and just set data of `Recordable` from it?

```cpp
// API:
namespace logs{
// prune class which only contains setters
class LogRecord;
}

//SDK
namespace sdk {
namespace logs{
// prune class which contains getters
class ReadableLogRecord : public LogRecord;

// A replacement of legacy LogRecord
class ReadWriteLogRecord : public LogRecord;

class Recordable {
public:
  void SetLogRecord(const ReadableLogRecord & record) {
    SetTimestamp(record.GetTimestamp());
    SetSeverity(record.GetSeverity());
    SetBody(record.GetBody());
   // And etc.
  }
};
}
}
```

How about this design? I think it's more simular to the relationship of trace span and recordable.

**Comment by lalitb** [comment]
Yes, that's look good too. 

nit - The Recordable interface will also have one method to get ReadWriteLogRecord which would return nullptr by default. 

```cpp
class Recordable {
   public:
    virtual explicit operator ReadWriteLogRecord *() const { return nullptr; }

}
```
