### ISSUE TITLE
[Logs SDK] LoggerProvider, LoggerContext changes.

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1692]
- LoggerProvider
  - LoggerProvider::GetLogger() : As per the new prototype. 
       -   Add `event_domain` to the list of attributes passed as argument, and eventually pass them to InstrumentationScope.
       -    Pass `include_trace_context` flag to Logger object during it's creation.
  - AddProcessor/RemoveProcessor - Pass LogRecordProcessor instead of LogProcessor. Should we change the name of methods too ?

- LoggerContext
   - AddProcessor/RemoveProcessor - Pass LogRecordProcessor instead of LogProcessor. Should we change the name of methods too ?

**Comment by owent** [comment]
Please don't stale this issue, I will continue finish left works when I have time.
Sorry, I only work on this in spare time and can not finish all changes in a short period of time.
