### ISSUE TITLE
[Logs SDK] - LogRecord , Logger changes

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1693]
- Logger 
   -  Constructor takes `include_trace_context` flag to use it further within spancontext fetch logic.
   - CreateLogRecord() - This will return new instance of sdk::LogRecord object.
   - EmitLogRecord() - Would invoke LogRecordProcessor::OnEmit method to pass logrecord to processor.
   - SpanContext fetch logic - 
        -  If valid `SpanContext` is passed through `EmitLogRecord()`, or valid `TraceId`/`SpanId` is passed using existing `Log()` method, use that irrespective of the value of `include_trace_context` flag.
        -  Else, if  `include_trace_context`  is set, use the `SpanContext` from currently active span.

- LogRecord
   -  The only way to create LogRecord object is through `Logger::CreateLogRecord()`. It's constructor will  take Logger object as argument. 
   - Implement the setters calling corresponding setters from Recordable. The Recordable object would be obtained through the Logger object passed in constructor above.

**Comment by owent** [comment]
Please don't stale this issue, I will continue finish left works when I have time.
Sorry, I only work on this in spare time and can not finish all changes in a short period of time.
