### ISSUE TITLE
Adding a Google Test Demo Document

### ISSUE THREAD

**Issue by erichsueh3** [open-telemetry/opentelemetry-cpp#170]
**Is your feature request related to a problem?**
The OpenTelemetry CPP repository currently uses the unit testing framework Google Test to thoroughly test the code in the repository. However, no documentation is provided to help new contributors understand Google Test and its integration within the repository; they must look up outside resources for reference, which by itself, is not extremely helpful within the context of using it in the repository.

**Describe the solution you'd like**
I propose this documentation on Google Test and its usage within the OpenTelemetry CPP repo be added because it would be an extremely helpful resource for new developers who are contributing bug fixes or features to the codebase. 

**Describe alternatives you've considered**
As a less consolidated solution, documentation and further elaboration could be provided in the [contributing](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/CONTRIBUTING.md) document. Please note that adding this test demo documentation to the contributing document may make it longer and harder to read.

**Comment by liadavid** [comment]
Maybe you already aware of it (and if you do, please ignore my comment). 

There is documentation about Google Test here: https://github.com/google/googletest
Specifically; https://github.com/google/googletest/blob/master/googletest/docs/primer.md

**Comment by pyohannes** [comment]
Hi @erichsueh3. Are the links given by Lia sufficient for you? We try to avoid duplicating existing documentation in the opentelemetry-cpp repository.

**Comment by erichsueh3** [comment]
Hi @liadavid, @pyohannes, the documentation I am proposing is less focused on the functionality of Google Test but more so on the integration of Google Test within the OpenTelemetry CPP repository; I believe this will be more specific in helping newer contributors understand its usage within the repository. Ideally, the documentation above would be referenced, but the Google Test demo itself would not have much overlap with it.
