### ISSUE TITLE
[Metrics API/SDK] Change Meter API/SDK to return nostd::unique_ptr for Sync Instruments

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1700]
The Sync Instruments created through Meter API are not used internally within SDK. So it would be good to return nostd::unique_ptr for them. Changes are required in API and SDK for
 - Counter ( UINT64 and Double)
 - Histogram ( UINT64 and Double)
 - UpDownCounter ( INT64 and Double)

The Async Instruments can continue to return `nostd::shared_ptr`.
As part of this or separate PR, we can also maintain the shared_ptr of Async Instrument (instead of current raw pointer) in Observable Registry https://github.com/open-telemetry/opentelemetry-cpp/blob/ac105bf419ba651adbe25552c67fb83b2a7dc80f/sdk/include/opentelemetry/sdk/metrics/state/observable_registry.h#L24

**Comment by esigo** [comment]
It's not possible to maintain shared_ptr for maintain the shared_ptr of Async Instrument https://github.com/open-telemetry/opentelemetry-cpp/blob/ac105bf419ba651adbe25552c67fb83b2a7dc80f/sdk/include/opentelemetry/sdk/metrics/state/observable_registry.h#L24

as we need to enable shared from this, which doesn't work with `nostd::shared_ptr`.

**Comment by lalitb** [comment]
> as we need to enable shared from this, which doesn't work with nostd::shared_ptr.

Thanks for trying. We can handle this as separate PR. As this is internal SDK change, should be good to handle post GA. Please raise a issue for this.
