### ISSUE TITLE
gRPCConfig.cmake found package configuration file  but it set gRPC_FOUND to FALSE so package "gRPC" is considered to be NOT   FOUND.

### ISSUE THREAD

**Issue by compoundradius** [open-telemetry/opentelemetry-cpp#1706]
Referencing Closed ticket #1384:

Following the recommendations at https://grpc.io/docs/languages/cpp/quickstart/
```
We strongly encourage you to install gRPC locally — using an appropriately set CMAKE_INSTALL_PREFIX — because there is no easy way to uninstall gRPC after you’ve installed it globally.
```
I have installed gRPC 1.50.0 to ```$HOME/.local```.
When compiling opentelemetry-cpp with ```cmake -DWITH_OTLP=ON ../```. I also had to patch your CMakeLists.txt to use the above recommended workaround:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 14db63d1..f7be3c54 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -270,6 +270,10 @@ if(WITH_OTLP)
   find_package(Protobuf)
   if(WITH_OTLP_GRPC OR (NOT DEFINED WITH_OTLP_GRPC AND NOT DEFINED
                                                        CACHE{WITH_OTLP_GRPC}))
+    find_package(Protobuf QUIET CONFIG)
+    if((NOT Protobuf_FOUND AND NOT PROTOBUF_FOUND))
+        find_package(Protobuf)
+    endif()
     find_package(gRPC)
   endif()
   if((NOT Protobuf_FOUND AND NOT PROTOBUF_FOUND) OR (NOT gRPC_FOUND))
```
This worked, but is there a better way?

**Comment by lalitb** [comment]
I think below command should work without changing cmake file:

``bash
$cmake -DWITH_OTLP=ON -DCMAKE_INSTALL_PREFIX=$HOME/.local ../
``

**Comment by compoundradius** [comment]
> I think below command should work without changing cmake file:
> 
> ```shell
> $cmake -DWITH_OTLP=ON -DCMAKE_INSTALL_PREFIX=$HOME/.local ../
> ```

This did work.

**Comment by lalitb** [comment]
@compoundradius It should be good to close this issue, or you have further questions?

**Comment by compoundradius** [comment]
No further questions other than will opentelemetry-cpp work well as a
subproject via Fetchcontent or as a git submodule or does it need to be
installed as it's own project? It seems like all the documentation points
to standalone installation/find_package.

**Comment by compoundradius** [comment]
Resolved.
