### ISSUE TITLE
Prometheus exporter gives build error

### ISSUE THREAD

**Issue by rgc183** [open-telemetry/opentelemetry-cpp#1728]
I am using bazel build in my project by following steps mentioned here: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md#incorporating-into-an-existing-bazel-project

Now, I try to use prometheus exporter in my project using:

`    deps = [
        "@io_opentelemetry_cpp//api",
        "@io_opentelemetry_cpp//exporters/prometheus:prometheus_exporter",
        "@io_opentelemetry_cpp//sdk:headers",
        "@io_opentelemetry_cpp//sdk/src/metrics"
    ],`

which causes an error:

`/root/.cache/bazel/_bazel_root/e6fb20bb08e42b93349ca637dd380aaf/external/com_github_jupp0r_prometheus_cpp/pull/BUILD.bazel:9:11: no such package '@civetweb//': The repository '@civetweb' could not be resolved and referenced by '@com_github_jupp0r_prometheus_cpp//pull:pull'
`
Now I did some digging and I found that prometheus is being included this way: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/bazel/repository.bzl#L111

And  `"@io_opentelemetry_cpp//exporters/prometheus:prometheus_exporter",` -> this is leading to https://github.com/open-telemetry/opentelemetry-cpp/blob/main/exporters/prometheus/BUILD#L104 where it only calls `pull` and `core` directories. However, civetweb is actually built in https://github.com/open-telemetry/opentelemetry-cpp/blob/main/WORKSPACE#L25 and call to this is missing in repository.bzl 

However, https://github.com/open-telemetry/opentelemetry-cpp/tree/main/examples/prometheus this builds fine since WORKSPACE calls dependency function.

**Comment by rgc183** [comment]
@lalitb

**Comment by rgc183** [comment]
I created local fix here: https://github.com/open-telemetry/opentelemetry-cpp/compare/main...rgc183:opentelemetry-cpp:bazel_fix

**Comment by owent** [comment]
It looks good, could you please raise a PR and rename.
Just a suggestion, is it better to rename `load_extra_deps` to `opentelemetry_extra_deps` ? Just like `grpc_extra_deps`
