### ISSUE TITLE
[Build] Bring your own dependency: nlohmann_json

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#1740]
Please provide a way, in the opentelemetry-cpp CMakeLists.txt, to provide an explicit dependency for nlohmann_json.

For example, in CMake (from the command line or from a super project),
`OTELCPP_NLOHMANN_JSON_PATH=/path/to/nlohmann_json`
would cause opentelemetry-cpp to build with the code provided.

**Comment by lalitb** [comment]
Can't we use CMAKE_PREFIX_PATH for this?

**Comment by marcalff** [comment]
> Can't we use CMAKE_PREFIX_PATH for this?

Good point, let me investigate this.

**Comment by owent** [comment]
If you use cmake 3.12 or upper, you can also use your own prebuilt  `nlohmann_json` with `nlohmann_json_ROOT=<install prefix>` .

See https://cmake.org/cmake/help/latest/command/find_package.html for more details

**Comment by marcalff** [comment]
Using
 OTELCPP_NLOHMANN_JSON_PATH=/path/to/nlohmann_json
can work for nlohmann_json, because it is a header only package: no libraries are installed.

Looking for a general solution to use either:

- ADD_SUBDIRECTORY()
- ExternalProject_Add()
- FetchContent_Declare() / FetchContent_MakeAvailable()

from a super project.

FOO_PATH=/path/to/source/code does not seem to work in the general case, so abandoning this request.

The problem here is to point to a repo, not a package.
