### ISSUE TITLE
OTLP exporter defaults to insecure connection

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-cpp#1769]
**Describe your environment** 
When trying to configure the SDK to send telemetry to a backend, the default OTLP exporter behaviour is to send using an unsecured connection.

This is not intuitive behaviour and goes against the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md?plain=1#L19). The environment variables are different, but the intent is the *_INSECURE environment variables default to false, meaning a secure connection is used.

Two nice to have:
- update the SDKs environment variable usage to match the spec
- if no environment variable is set, determine whether a secure connection is required using the endpoint protocol (eg http:// = insecure, https:// = secure)

**Steps to reproduce**
Setup SDK to send telemetry to an endpoint that required a secure connection (eg https://).

**What is the expected behavior?**
Telemetry successfully be exported to the configured endpoint.

**What is the actual behavior?**
Telemetry is not exported with an invalid protocol error. To get it to work, the SDK required the `OTEL_EXPORTER_OTLP_SSL_ENABLE` set to `true`.

**Comment by lalitb** [comment]
Also, need to change the env variable used from `OTEL_EXPORTER_OTLP_TRACES_SSL_ENABLE` to  `OTEL_EXPORTER_OTLP_INSECURE`

**Comment by marcalff** [comment]
@MikeGoldsmith 

Thanks for the report.

I think this is addressed by:

* #2060 for the GRPC endpoint protocol (http vs https)
* #1982 for using *_INSECURE environment variables

Closing the issue as resolved.

Please reopen and comment if something is still not working properly.
