### ISSUE TITLE
[API common] undefined reference to __builtin_ia32_pause when using Intel Compilers

### ISSUE THREAD

**Issue by gabswb** [open-telemetry/opentelemetry-cpp#1771]
**Describe your environment** 
C Compiler : icc version 19.0.3.199 (gcc version 9.3.1 compatibility)
C++ Compiler : icpc version 19.0.3.199 (gcc version 9.3.1 compatibility)

I am getting an undefined reference to `__builtin_ia32_pause` from common::SpinLockMutex.

It seems that the Intel C++ compiler can't link the GCC built-in function `__builtin_ia32_pause`.

**Comment by marcalff** [comment]
Possibly relevant:

https://github.com/curl/curl/issues/9081
