### ISSUE TITLE
OTLP HTTP Exporter headers not installed

### ISSUE THREAD

**Issue by jonathan-dev** [open-telemetry/opentelemetry-cpp#1784]
**Describe your environment** 
cmake 3.24.2
commit: d0571d8ac78f536098addac4288e5dce28f93da1
I am trying to build with the otlp http exporter inside a docker container (bitnami/minideb:latest).

**Steps to reproduce**
```
cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTING=OFF -DWITH_EXAMPLES=OFF -DBUILD_SHARED_LIBS=ON -DWITH_OTLP_HTTP=ON ..

make install -j
```

**What is the expected behavior?**
After building with the following options i am still i am missing the required header files that are used in the example:
```
#include "opentelemetry/exporters/otlp/otlp_http_exporter_factory.h"
#include "opentelemetry/exporters/otlp/otlp_http_exporter_options.h"
```

**What is the actual behavior?**
In fact the otlp file inside the exporters folder isn't created at all.

**Comment by jonathan-dev** [comment]
I get the following output when trying to run with `-DWITH_OTLP=ON`:
```
 cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTING=OFF -DWITH_EXAMPLES=OFF -DBUILD_SHARED_LIBS=ON -DWITH_OTLP=ON ..
-- Building for architecture ARCH=x64
CMake Warning at CMakeLists.txt:279 (find_package):
  By not providing "FindgRPC.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gRPC", but
  CMake did not find one.

  Could not find a package configuration file provided by "gRPC" with any of
  the following names:

    gRPCConfig.cmake
    grpc-config.cmake

  Add the installation prefix of "gRPC" to CMAKE_PREFIX_PATH or set
  "gRPC_DIR" to a directory containing one of the above files.  If "gRPC"
  provides a separate development package or SDK, be sure it has been
  installed.


CMake Warning at CMakeLists.txt:299 (find_package):
  By not providing "FindgRPC.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gRPC", but
  CMake did not find one.

  Could not find a package configuration file provided by "gRPC" with any of
  the following names:

    gRPCConfig.cmake
    grpc-config.cmake

  Add the installation prefix of "gRPC" to CMAKE_PREFIX_PATH or set
  "gRPC_DIR" to a directory containing one of the above files.  If "gRPC"
  provides a separate development package or SDK, be sure it has been
  installed.


-- PROTOBUF_PROTOC_EXECUTABLE=/usr/local/bin/protoc
-- opentelemetry-proto dependency satisfied by: git submodule
Using external nlohmann::json
Building with nostd types...
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/opentelemetry-cpp/build
root@5777322b97d8:/tmp/opentelemetry-cpp/build# make install
[  1%] Generating generated/third_party/opentelemetry-proto/opentelemetry/proto/common/v1/common.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/common/v1/common.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/resource/v1/resource.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/resource/v1/resource.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/trace/v1/trace.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/trace/v1/trace.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/logs/v1/logs.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/logs/v1/logs.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/metrics/v1/metrics.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/metrics/v1/metrics.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/trace/v1/trace_service.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/trace/v1/trace_service.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/logs/v1/logs_service.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/logs/v1/logs_service.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/metrics/v1/metrics_service.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/metrics/v1/metrics_service.pb.cc
Missing value for flag: --experimental_allow_proto3_optional
make[2]: *** [CMakeFiles/opentelemetry_proto.dir/build.make:74: generated/third_party/opentelemetry-proto/opentelemetry/proto/common/v1/common.pb.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:344: CMakeFiles/opentelemetry_proto.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
root@5777322b97d8:/tmp/opentelemetry-cpp/build#
```

**Comment by jonathan-dev** [comment]
> I get the following output when trying to run with `-DWITH_OTLP=ON`:
> 
> ```
>  cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTING=OFF -DWITH_EXAMPLES=OFF -DBUILD_SHARED_LIBS=ON -DWITH_OTLP=ON ..
> -- Building for architecture ARCH=x64
> CMake Warning at CMakeLists.txt:279 (find_package):
>   By not providing "FindgRPC.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "gRPC", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "gRPC" with any of
>   the following names:
> 
>     gRPCConfig.cmake
>     grpc-config.cmake
> 
>   Add the installation prefix of "gRPC" to CMAKE_PREFIX_PATH or set
>   "gRPC_DIR" to a directory containing one of the above files.  If "gRPC"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> 
> 
> CMake Warning at CMakeLists.txt:299 (find_package):
>   By not providing "FindgRPC.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "gRPC", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "gRPC" with any of
>   the following names:
> 
>     gRPCConfig.cmake
>     grpc-config.cmake
> 
>   Add the installation prefix of "gRPC" to CMAKE_PREFIX_PATH or set
>   "gRPC_DIR" to a directory containing one of the above files.  If "gRPC"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> 
> 
> -- PROTOBUF_PROTOC_EXECUTABLE=/usr/local/bin/protoc
> -- opentelemetry-proto dependency satisfied by: git submodule
> Using external nlohmann::json
> Building with nostd types...
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /tmp/opentelemetry-cpp/build
> root@5777322b97d8:/tmp/opentelemetry-cpp/build# make install
> [  1%] Generating generated/third_party/opentelemetry-proto/opentelemetry/proto/common/v1/common.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/common/v1/common.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/resource/v1/resource.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/resource/v1/resource.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/trace/v1/trace.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/trace/v1/trace.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/logs/v1/logs.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/logs/v1/logs.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/metrics/v1/metrics.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/metrics/v1/metrics.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/trace/v1/trace_service.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/trace/v1/trace_service.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/logs/v1/logs_service.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/logs/v1/logs_service.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/metrics/v1/metrics_service.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/metrics/v1/metrics_service.pb.cc
> Missing value for flag: --experimental_allow_proto3_optional
> make[2]: *** [CMakeFiles/opentelemetry_proto.dir/build.make:74: generated/third_party/opentelemetry-proto/opentelemetry/proto/common/v1/common.pb.h] Error 1
> make[1]: *** [CMakeFiles/Makefile2:344: CMakeFiles/opentelemetry_proto.dir/all] Error 2
> make: *** [Makefile:136: all] Error 2
> root@5777322b97d8:/tmp/opentelemetry-cpp/build#
> ```

Ok this problem is fixed by using the newest protobuf version. And I get my missing headers + some more problems.
But shouldn't I only be needing protobuf when using grpc?

New Problems:
```
[cmake] -- Configuring done
[cmake] CMake Error at /usr/local/lib/cmake/opentelemetry-cpp/opentelemetry-cpp-target.cmake:61 (set_target_properties):
[cmake]   The link interface of target "opentelemetry-cpp::proto" contains:
[cmake] 
[cmake]     protobuf::libprotobuf
[cmake] 
[cmake]   but the target was not found.  Possible reasons include:
[cmake] 
[cmake]     * There is a typo in the target name.
[cmake]     * A find_package call is missing for an IMPORTED target.
[cmake]     * An ALIAS target is missing.
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   /usr/local/lib/cmake/opentelemetry-cpp/opentelemetry-cpp-config.cmake:88 (include)
[cmake]   CMakeLists.txt:37 (find_package)
[cmake] 
[cmake] 
[cmake] CMake Error at /usr/local/lib/cmake/opentelemetry-cpp/opentelemetry-cpp-target.cmake:140 (set_target_properties):
[cmake]   The link interface of target "opentelemetry-cpp::otlp_http_client"
[cmake]   contains:
[cmake] 
[cmake]     nlohmann_json::nlohmann_json
[cmake] 
[cmake]   but the target was not found.  Possible reasons include:
[cmake] 
[cmake]     * There is a typo in the target name.
[cmake]     * A find_package call is missing for an IMPORTED target.
[cmake]     * An ALIAS target is missing.
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   /usr/local/lib/cmake/opentelemetry-cpp/opentelemetry-cpp-config.cmake:88 (include)
[cmake]   CMakeLists.txt:37 (find_package)
[cmake] 
[cmake] 
```

**Comment by owent** [comment]
gRPC also depends abseil and openssl/boringssl. nlohmann_json and CURL is depended by OTLP HTTP Exporter.
You can use `find_package(Protobuf)` and `find_package(nlohmann_json)` to import the missing targets above.

**Comment by jonathan-dev** [comment]
> gRPC also depends abseil and openssl/boringssl. nlohmann_json and CURL is depended by OTLP HTTP Exporter. After build and install protobuf and nlohmann_json, You can use `find_package(Protobuf)` and `find_package(nlohmann_json)` to import the missing targets above.

I did that and it solves this problem. But I don't get how I instruct cmake to build only with OTLP HTTP because I am not going to use gRPC and thus don't want to deal with its dependencies.
Now I am getting this error: 
```
error while loading shared libraries: libopentelemetry_otlp_recordable.so: cannot open shared object file: No such file or directory
```
although it is correctly installed with all other .so files and it is also linked in `target_link_libraries` using the `OPENTELEMETRY_CPP_LIBRARIES` variable.
The missing .so message only appears when having the following line (uncommenting fixes it):
```
auto exporter  = opentelemetry::exporter::otlp::OtlpHttpExporterFactory::Create(opts);
```

**Comment by sirzooro** [comment]
You can invoke cmake with `-DWITH_OTLP_GRPC=OFF` to disable OTLP GRPC protocol.

**Comment by jonathan-dev** [comment]
When running
```
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DWITH_EXAMPLES=OFF -DBUILD_SHARED_LIBS=ON -DWITH_OTLP=ON -DWITH_OTLP_HTTP=ON -DWITH_OTLP_GRPC=OFF ..
```
I get:
```
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building for architecture ARCH=x64
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) 
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindProtobuf.cmake:626 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:294 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/opentelemetry-cpp/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/opentelemetry-cpp/build/CMakeFiles/CMakeError.log".
```

that's on a fresh docker container. I don't get why I am required to have protobuf as it should only be required when having `-DWITH_OTLP_GRPC=ON` which I set to off.

**Comment by sirzooro** [comment]
Quote from [specification:](https://opentelemetry.io/docs/reference/specification/protocol/otlp/#otlphttp): "OTLP/HTTP uses Protobuf payloads encoded either in binary format or in JSON format.". So protobuf library is required for HTTP client too.

**Comment by jonathan-dev** [comment]
> > gRPC also depends abseil and openssl/boringssl. nlohmann_json and CURL is depended by OTLP HTTP Exporter. After build and install protobuf and nlohmann_json, You can use `find_package(Protobuf)` and `find_package(nlohmann_json)` to import the missing targets above.
> 
> I did that and it solves this problem. But I don't get how I instruct cmake to build only with OTLP HTTP because I am not going to use gRPC and thus don't want to deal with its dependencies. Now I am getting this error:
> 
> ```
> error while loading shared libraries: libopentelemetry_otlp_recordable.so: cannot open shared object file: No such file or directory
> ```
> 
> although it is correctly installed with all other .so files and it is also linked in `target_link_libraries` using the `OPENTELEMETRY_CPP_LIBRARIES` variable. The missing .so message only appears when having the following line (uncommenting fixes it):
> 
> ```
> auto exporter  = opentelemetry::exporter::otlp::OtlpHttpExporterFactory::Create(opts);
> ```

Ok I think I figured out what my problem was:
I always used `make install` instead of the suggested `cmake --install . --prefix /<install-root>/` and I forgot to call `ldconfig` after.

**Comment by owent** [comment]
> > > gRPC also depends abseil and openssl/boringssl. nlohmann_json and CURL is depended by OTLP HTTP Exporter. After build and install protobuf and nlohmann_json, You can use `find_package(Protobuf)` and `find_package(nlohmann_json)` to import the missing targets above.
> > 
> > 
> > I did that and it solves this problem. But I don't get how I instruct cmake to build only with OTLP HTTP because I am not going to use gRPC and thus don't want to deal with its dependencies. Now I am getting this error:
> > ```
> > error while loading shared libraries: libopentelemetry_otlp_recordable.so: cannot open shared object file: No such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > although it is correctly installed with all other .so files and it is also linked in `target_link_libraries` using the `OPENTELEMETRY_CPP_LIBRARIES` variable. The missing .so message only appears when having the following line (uncommenting fixes it):
> > ```
> > auto exporter  = opentelemetry::exporter::otlp::OtlpHttpExporterFactory::Create(opts);
> > ```
> 
> Ok I think I figured out what my problem was: I always used `make install` instead of the suggested `cmake --install . --prefix /<install-root>/` and I forgot to call `ldconfig` after.

You can configure cmake with `-DCMAKE_INSTALL_PREFIX=/<install-root>/`, and then `make install` is the same as `cmake --install . --prefix /<install-root>/` .
