### ISSUE TITLE
OTLP | otlp with Grpc - build metrics_grpc_example

### ISSUE THREAD

**Issue by yonatan555** [open-telemetry/opentelemetry-cpp#1788]
gcc -v 11.1.2
centos 7
cpp
I am trying to execute the metrics_grpc_example, up to 2 weeks, and this went bad.
I got alot of erros of linker:
`/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /usr/local/lib64/libabsl_graphcycles_internal.a(graphcycles.cc.o): in function `absl::synchronization_internal::GraphCycles::GetId(void*)':
graphcycles.cc:(.text+0xbe1): undefined reference to `absl::base_internal::LowLevelAlloc::AllocWithArena(unsigned long, absl::base_internal::LowLevelAlloc::Arena*)'
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /usr/local/lib64/libabsl_graphcycles_internal.a(graphcycles.cc.o): in function `absl::synchronization_internal::(anonymous namespace)::Vec<int>::Discard()':
graphcycles.cc:(.text+0x207f): undefined reference to `absl::base_internal::LowLevelAlloc::Free(void*)'
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /usr/local/lib64/libabsl_graphcycles_internal.a(graphcycles.cc.o): in function `absl::synchronization_internal::(anonymous namespace)::Vec<int>::Grow(unsigned int)':
graphcycles.cc:(.text+0x20d7): undefined reference to `absl::base_internal::LowLevelAlloc::AllocWithArena(unsigned long, absl::base_internal::LowLevelAlloc::Arena*)'
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /usr/local/lib64/libabsl_graphcycles_internal.a(graphcycles.cc.o): in function `absl::synchronization_internal::(anonymous namespace)::Vec<absl::synchronization_internal::(anonymous namespace)::Node*>::Discard()':
graphcycles.cc:(.text+0x2153): undefined reference to `absl::base_internal::LowLevelAlloc::Free(void*)'
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /usr/local/lib64/libabsl_graphcycles_internal.a(graphcycles.cc.o): in function `absl::synchronization_internal::(anonymous namespace)::Vec<absl::synchronization_internal::(anonymous namespace)::Node*>::Grow(unsigned int)':
graphcycles.cc:(.text+0x21ab): undefined reference to `absl::base_internal::LowLevelAlloc::AllocWithArena(unsigned long, absl::base_internal::LowLevelAlloc::Arena*)'
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /usr/local/lib64/libabsl_stacktrace.a(stacktrace.cc.o): in function `void** NextStackFrame<false, false>(void**, void const*, unsigned long, unsigned long)':
stacktrace.cc:(.text+0xb09): undefined reference to `absl::debugging_internal::AddressIsReadable(void const*)'
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /usr/local/lib64/libabsl_stacktrace.a(stacktrace.cc.o): in function `void** NextStackFrame<false, true>(void**, void const*, unsigned long, unsigned long)':
stacktrace.cc:(.text+0xb8e): undefined reference to `absl::debugging_internal::AddressIsReadable(void const*)'
`

I did these steps:
`
// basic commands
yum -y update
sudo yum install wget -y && yum install perl-IPC-Cmd -y
yum install python3 -y 
sudo yum makecache 
sudo yum -y install pkgconfig
sudo yum install libcurl -y 
sudo yum install libcurl-devel -y

// git
sudo yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm 
sudo yum install git -y 

// compiler c++ 17
sudo yum group install "Development Tools" -y 
sudo yum install centos-release-scl -y 
sudo yum install devtoolset-11 -y
scl enable devtoolset-11 bash

configured open-ssl 1.1.1
// openssl
wget https://linuxpip.org/install-openssl-linux/ - run the commands under this link
sudo yum install openssl-devel -y

// cmake
wget https://cmake.org/files/v3.24/cmake-3.24.0.tar.gz
scl enable devtoolset-11 bash
tar zxvf cmake-3.*
	cd cmake-3.*
	./bootstrap --prefix=/usr/local
	make -j$(nproc)
	make install

//gRPC
yum install -y build-essential autoconf libtool pkg-config
git clone -b v1.43.2 https://github.com/grpc/grpc
cd grpc
scl enable devtoolset-11 bash
git submodule update --init
mkdir -p cmake/build
pushd cmake/build
cmake -DBUILD_SHARED_LIBS=OFF -DgRPC_INSTALL=ON -DCMAKE_CXX_STANDARD=17 -DgRPC_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DgRPC_ABSL_PROVIDER=module -DgRPC_CARES_PROVIDER=module -DgRPC_PROTOBUF_PROVIDER=module -DgRPC_RE2_PROVIDER=module -DgRPC_SSL_PROVIDER=module -DgRPC_ZLIB_PROVIDER=module ../..
make
make install
popd

// install OTLP
mkdir source && cd source && git clone --recursive https://github.com/open-telemetry/opentelemetry-cpp
git submodule update --init
scl enable devtoolset-11 bash
cd opentelemetry-cpp
mkdir build && cd build
cmake -DBUILD_SHARED_LIBS=OFF -DWITH_STL=ON -DWITH_ABSEIL=OFF-DBUILD_TESTING=OFF -DWITH_EXAMPLES=OFF -DWITH_OTLP=ON -DWITH_PROMETHEUS=OFF -DWITH_OTLP_GRPC=ON -DCMAKE_PREFIX_PATH=/root/grpc/ ..
cmake --build . --target all
cmake --install .
`
please tell me if something is missing

**Comment by lalitb** [comment]
Reopening it. @yonatan555 do you still have this issue ?

**Comment by lalitb** [comment]
Keeping it closed, @yonatan555 please free to reopen if the issue is still valid.
