### ISSUE TITLE
CI is broken because of new GHA image

### ISSUE THREAD

**Issue by esigo** [open-telemetry/opentelemetry-cpp#1791]
The CI is broken because gcc upgraded from 9.4.0 to 11.3.0.
https://github.com/actions/runner-images/pull/6511

**Comment by ThomsonTan** [comment]
Does this break all our PR build?

**Comment by esigo** [comment]
yes

**Comment by ThomsonTan** [comment]
> Seems it's fixed in gtest-1.11.0 : [google/googletest#3024](https://github.com/google/googletest/pull/3024)

So our googletest is 2 years behind the current one? Should we update?

**Comment by ThomsonTan** [comment]
From the googletest release page [here](https://github.com/google/googletest/releases/tag/release-1.12.1), C++ 14 will be required for future releases. Do we need make plan for the same support as well?

**Comment by marcalff** [comment]
> From the googletest release page [here](https://github.com/google/googletest/releases/tag/release-1.12.1), C++ 14 will be required for future releases. Do we need make plan for the same support as well?
> 
> > This will be the last release to support C++11. Future releases will require at least C++14.

We already have other libraries (abseil, grpc) that also have announced a last release for C++11.

For now, I think we need to upgrade to googletest v1.12.1.

CI also broke for clang-format, because ubuntu-lastest now uses clang-format > 10

**Comment by marcalff** [comment]
> For now, I think we need to upgrade to googletest v1.12.1.

I tried that in PR #1797 and it is a failure.

The gcc 4.8 build is broken:

googletest 1.12.1 requires C++11

gcc 4.8 is pre C++11
