### ISSUE TITLE
CI benchmark doesn't build on Ubuntu 22.04

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-cpp#1801]
While it was reverted back to Ubuntu 20.04 to unblock CI benchmark in below CI, we need investigate why it doesn't work with Ubuntu 22.04 because we'll move there in the long term.

https://github.com/open-telemetry/opentelemetry-cpp/pull/1799

**Comment by marcalff** [comment]
Ubuntu 20.04 with an old gcc worked with gtest 1.10.0

Ubuntu 22.02 with a newer gcc broke with gtest 1.10.0

With recent changes : issue #1852, the version of gtest was bumped up:
  export GOOGLETEST_VERSION=1.12.1

Ubuntu 22.02 with a newer gcc works with gtest 1.12.1

So, #1852 as a side effect also fixed the benchmarks workflow.

Closing, as this is now resolved.
