### ISSUE TITLE
Installed target name of prometheus export changes in v1.8.0

### ISSUE THREAD

**Issue by owent** [open-telemetry/opentelemetry-cpp#1819]
**Describe your environment**

Build System: CMake

**What is the expected behavior?**

The installed target name of prometheus export changes from `opentelemetry-cpp::prometheus_exporter` to `opentelemetry-cpp::opentelemetry_exporter_prometheus` when using cmake.Should it keep the old name?

**What is the actual behavior?**

The old codes link `opentelemetry-cpp::prometheus_exporter` can not compile.

**Comment by lalitb** [comment]
This was deliberate, to keep it consistent with the naming for other targets. We can indicate it as breaking change in the release document ?

**Comment by owent** [comment]
> This was deliberate, to keep it consistent with the naming for other targets. We can indicate it as breaking change in the release document ?

The target name in v1.8.0 is `opentelemetry-cpp::opentelemetry_exporter_prometheus`, while other exporters are `opentelemetry-cpp::ostream_metrics_exporter`, `opentelemetry-cpp::otlp_http_metric_exporter`, 'opentelemetry-cpp::otlp_grpc_metrics_exporter'.

All targets have `opentelemetry-cpp::` prefix, is it redundant to add another `opentelemetry_` prefix for prometheus exporter?

**Comment by lalitb** [comment]
Ah. Got it. I was validating the generated cmake target names, and not the target names in the otel-cpp cmake config. Have fixed it in #1820. Please see if that works.
