### ISSUE TITLE
Prepare 1.8.1 release

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#1825]
As discussed in team meeting, prepare a 1.8.1 release.

Bugs targeted for 1.8.1:

- issue #1823 
- issue #1826 
- issue #1806 

@lalitb Any other bugs to add in this list ?

**Comment by lalitb** [comment]
Thanks @marcalff for the issue. This can be a patch release with only fix for #1823.

**Comment by sirzooro** [comment]
Could you also include fix for #1806?

**Comment by marcalff** [comment]
> Could you also include fix for #1806?

Issue #1806 was fixed by PR #1815, already merged, so yes, this fix will be included.

**Comment by esigo** [comment]
Is there anything else left? Shall I prepare the release tomorrow?

**Comment by flier** [comment]
> Is there anything else left? Shall I prepare the release tomorrow?

Hi @esigo,

Could you also include fix for #1834

**Comment by lalitb** [comment]
@flier -  CPack support is planned in #1662 , it would be included in next release. The plan is to add support for deb, rpm and nuget packages.

**Comment by esigo** [comment]
just release [v1.8.1](https://github.com/open-telemetry/opentelemetry-cpp/releases/tag/v1.8.1)
