### ISSUE TITLE
[Build] Build break when using WITH_OTLP_HTTP=ON, WITH_OTLP_GRPC=OFF

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#1826]
When compiling with the OTLP HTTP exporter but *not* the OTLP GRPC exporter,
the build fails:

```
In file included from .../opentelemetry-cpp/opentelemetry-cpp-1.8.0/exporters/otlp/src/otlp_grpc_utils.cc:4:
.../opentelemetry-cpp/opentelemetry-cpp-1.8.0/exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_utils.h:6:10: fatal error: grpcpp/grpcpp.h: No such file or directory
    6 | #include <grpcpp/grpcpp.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

Suggested fix for `exporter/otlp/CMakeLists.txt`:

- do not add `otlp_grpc_utils.cc` in the `opentelemetry_otlp_recordable` library
- add `otlp_grpc_utils.cc` in the `opentelemetry_exporter_otlp_grpc` library instead ? (to investigate)

**Comment by marcalff** [comment]
Tested the suggested fix internally in build farm, and it works.

Filing a PR for this

**Comment by marcalff** [comment]
@ThomsonTan 

If I understand correctly, file `src/otlp_grpc_utils.cc` should not be in library `opentelemetry_otlp_recordable`.

Now the question remains to decide in which library to add file `src/otlp_grpc_utils.cc`  instead:

- opentelemetry_exporter_otlp_grpc_client ?
- opentelemetry_exporter_otlp_grpc ? (trace specific, so probably not)
- opentelemetry_exporter_otlp_grpc_log ? (logs specific, so probably not)
- opentelemetry_exporter_otlp_grpc_metrics ? (metrics specific, so probably not)
- other new library for common GRPC code ?

Please advise on how to fix this.

**Comment by sirzooro** [comment]
What about compiling this file only when `WITH_OTLP_GRPC=ON`? It could stay in `opentelemetry_otlp_recordable` lib.

**Comment by ThomsonTan** [comment]
For bazel build, the new util code goes to a separate new lib, probably we could do the same for CMake? opentelemetry_exporter_otlp_grpc_client  looks another acceptable place.

https://github.com/open-telemetry/opentelemetry-cpp/blob/main/exporters/otlp/BUILD#L50
