### ISSUE TITLE
Support for ObservableInstrument::RemoveCallback from ObservableCallbackPtr

### ISSUE THREAD

**Issue by tauseef-ah** [open-telemetry/opentelemetry-cpp#1836]
Currently ObservableInstrument::RemoveCallback cannot be called from the Async Instrument Callback Function because of non recursive mutex in 
sdk\src\metrics\state\observable_registry.cc
```cpp
void ObservableRegistry::Observe(opentelemetry::common::SystemTimestamp collection_ts)
{
  std::lock_guard<std::mutex> lock_guard{callbacks_m_};
```
```cpp
void ObservableRegistry::RemoveCallback(opentelemetry::metrics::ObservableCallbackPtr callback,
                                        void *state,
                                        opentelemetry::metrics::ObservableInstrument *instrument)
{
  std::lock_guard<std::mutex> lock_guard{callbacks_m_};
```
Can this lock be changes to a recursive one?

**Comment by lalitb** [comment]
@tauseef-ah - Can you please clarify how are you trying to use RemoveCallback from within callback function ?
Both AddCallback an RemoveCallback should only be called through Async Instrument as below:

```cpp
auto async_instrument = meter.CreateInt64ObservableCounter(name, desc, unit);
async_instrument.AddCallback(callbackptr, nullptr);
...
..
async_instrument.RemoveCallback(callbackptr, nullptr);
```

**Comment by lalitb** [comment]
Reopening it, @tauseef-ah  can you reply to above query.

**Comment by lalitb** [comment]
Keeping it closed, @tauseef-ah please free to reopen if the issue is still valid.
