### ISSUE TITLE
[BUILD] Invalid checks for LIBCURL_VERSION_NUM

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#1837]
Found by code review.

In `HttpClient::MaybeSpawnBackgroundThread()`:

```
        // curl_multi_poll is added from libcurl 7.66.0, before 7.68.0, we can only wait util
        // timeout to do the rest jobs
#if LIBCURL_VERSION_NUM >= 0x074200
            /* wait for activity, timeout or "nothing" */
            mc = curl_multi_poll(self->multi_handle_, nullptr, 0,
                                 static_cast<int>(self->scheduled_delay_milliseconds_.count()),
                                 nullptr);
#else
            mc = curl_multi_wait(self->multi_handle_, nullptr, 0,
                                 static_cast<int>(self->scheduled_delay_milliseconds_.count()),
                                 nullptr);
#endif
```

According to the CURL [doc](https://curl.se/libcurl/c/curl_multi_poll.html), curl_multi_poll is added in 7.66.0.

So, the comment should not refer to 7.68, and the `LIBCURL_VERSION_NUM` check should not use 7.42.0

In `HttpClient::wakeupBackgroundThread()`:

```
void HttpClient::wakeupBackgroundThread()
{
// Before libcurl 7.68.0, we can only wait for timeout and do the rest jobs
// See https://curl.se/libcurl/c/curl_multi_wakeup.html
#if LIBCURL_VERSION_NUM >= 0x074400
  std::lock_guard<std::mutex> lock_guard{multi_handle_m_};
  if (nullptr != multi_handle_)
  {
    curl_multi_wakeup(multi_handle_);
  }
#endif
}
```

According to the CURL [doc](https://curl.se/libcurl/c/curl_multi_wakeup.html), curl_multi_wakeup is added in 7.68.0.

So, the `LIBCURL_VERSION_NUM` check should not use 7.44.0

**Comment by marcalff** [comment]
Actually, 0x42 is 66, so the code might be correct. Need to double check how curl encode versions numbers.

**Comment by owent** [comment]
> So, the LIBCURL_VERSION_NUM check should not use 7.44.0

0x44 is hex of 68

**Comment by marcalff** [comment]
Sorry about the false alarm.
Closing this bug then.
