### ISSUE TITLE
Optimize TraceZ Span Processing Speeds

### ISSUE THREAD

**Issue by jajanet** [open-telemetry/opentelemetry-cpp#184]
**Is your feature request related to a problem?**
For the initial iteration of [zPages](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/ext/src/zpages/README.md), more specifically [TraceZ](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/ext/src/zpages/README.md#tracez), spans are grabbed and temporarily stored using the [TraceZ span processor](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/ext/include/opentelemetry/ext/zpages/tracez_processor.h).

The OT C++ span processors [interface](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/include/opentelemetry/sdk/trace/processor.h) doesn't store any spans by default, and other current implementations [pass the responsibility](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/include/opentelemetry/sdk/trace/simple_processor.h) of ownership to an exporter at most. The TraceZ span processor functionality deviates from these by storing both running and completed spans, keeping references and ownership of them respectively.

The processor's containers are modified whenever a snapshot getter is called or a span starts/ends, which causes potential thread safety issues when the functions are called concurrently since these containers are shared across these functions. When different functions attempt to read/write to the same place in memory simultaneously, this causes a program to crash.

In order to make the **_span processor_** thread-safe, **_lock guards_** were added at these functions. At a large scale where many spans could be processed at once, this **_could potentially make TraceZ scale poorly speed-wise_**.

**Describe the solution you'd like**
We want to consider solutions that are also fast while being thread-safe. Some proposed solutions include:
- Use a proxy/shim instead of a processor. Similar to codeless attach profiling tools like [strace](https://en.wikipedia.org/wiki/Strace) @maxgolov 
- [Storing spans in a lock-free circular buff](https://github.com/open-telemetry/opentelemetry-cpp/pull/164#discussion_r455201812) @pyohannes 

**Describe alternatives you've considered**
Ideally, we also want to reduce contention (how long services query and use the same places in memory). We attempted to do this through copy-on-write and are considering other methods of doing so. 

**Additional context**
- TraceZ Span Processor [PR](https://github.com/open-telemetry/opentelemetry-cpp/pull/164)
- TraceZ Span Processor [Design Doc](https://docs.google.com/document/d/1kO4iZARYyr-EGBlY2VNM3ELU3iw6ZrC58Omup_YT-fU/edit#heading=h.5irk4csrpu0y)

**Comment by pyohannes** [comment]
I think you have two problems here that you should reason about in separation:
1. The thread-safety of `SpanData` itself. The recordable implementation `SpanData` doesn't give thread safety guarantees in between `OnStart` and `OnEnd` processor calls. When attributes are accessed in between those calls, another thread might write at the same time. To eliminate that possibility, I'd recommend to implement a custom `Recordable` that gives the needed thread safety guarantees.
2. Making the access to the vector storing running and ended spans thread safe (as aggregator and processor access those containers from different threads).

The lock-free circular buffer would address the second issue. I'm not sure about the details of the proxy/shim approach.

**Comment by jajanet** [comment]
@pyohannes Thanks for the thorough yet concise explanation! Based on your recommendation, we're opening a couple PRs soon to address this:
1.  PR for a custom recordable, which is essentially a copy of `span_data` but with locks in the getter/setter methods
2. PR to change the recordable used in the processor to this new custom recordable, as casting more than once (recordable -> span_data -> threadsafe_span_data) seems unnecessary if that's the span data we'll use in the aggregator.

I don't know the details behind the proxy/shim approach, but will update the issue accordingly when I get more information

**Comment by marcalff** [comment]
Closing, as zpages is removed, see #2292
