### ISSUE TITLE
Consider supporting `pkg-config`

### ISSUE THREAD

**Issue by dbolduc** [open-telemetry/opentelemetry-cpp#1850]
Supporting [`pkg-config`](https://people.freedesktop.org/~dbn/pkg-config-guide.html) means installing `*.pc` files for the different targets. This is a convenience for developers, which will enable things like [building with `make`](https://www.mrpt.org/tutorials/programming/first-steps/compiling_custom_applications_in_linux_with_a_makefile_and_pkg-config/) (or anything else that consumes `pkg-config` output).

**Comment by dbolduc** [comment]
Still want this...

**Comment by lalitb** [comment]
@dbolduc Removed the `stale` label now. This also has `help wanted` label if anyone would like to add the support.

**Comment by owent** [comment]
I can take this if no one follow this feature. My hands are tied recently, so I may start several days later.

**Comment by dbolduc** [comment]
I am going to work on this. Feel free to assign the issue to me.

I will probably just do the components I care about then leave the rest as an exercise :stuck_out_tongue:

**Comment by lalitb** [comment]
> I am going to work on this. Feel free to assign the issue to me.

Done. thanks for volunteering.
