### ISSUE TITLE
Collect in PeriodicExportingMetricReader ForceFlush before exporting

### ISSUE THREAD

**Issue by johanpel** [open-telemetry/opentelemetry-cpp#1858]
**Is your feature request related to a problem?**

Consider the scenario where some executable emitting metrics through the `PeriodicExportingMetricReader` is about to exit, but desires to collect and export the last value of an `ObservableGauge` one more time without waiting for the periodic collect and export.

**Describe the solution you'd like**

When using the `PeriodicExportingMetricReader`, it would be nice if `ForceFlush()` collects before exporting.

**Describe alternatives you've considered**
I have a metric that could be a `Counter`, but it gets updated very often and emits too many metric points. Therefore I really want to just collect and export it periodically using an `ObservableGauge`. I could work around it by using a `Counter` and periodically updating that myself, forcing one final update and flush upon exit. However, it seems the behavior I desire is common among other language SDKs as well, so I think it may be desired by others for `ForceFlush` to follow the behavior seen elsewhere.

**Additional context**

I hope I am not missing anything, but if I understand correctly, in the current implementation, an export is performed but no metrics are collected before exporting.
https://github.com/open-telemetry/opentelemetry-cpp/blob/main/sdk/src/metrics/export/periodic_exporting_metric_reader.cc#L85-L88

Other language SDKs appear to collect before exporting on ForceFlush:

Java: https://javadoc.io/static/io.opentelemetry/opentelemetry-sdk-metrics/1.21.0/io/opentelemetry/sdk/metrics/export/PeriodicMetricReader.html#forceFlush()
Python (see force_flush at the bottom, the superclass force_flush collects first): https://opentelemetry-python.readthedocs.io/en/latest/_modules/opentelemetry/sdk/metrics/_internal/export.html#PeriodicExportingMetricReader.force_flush

**Comment by lalitb** [comment]
> I hope I am not missing anything, but if I understand correctly, in the current implementation, an export is performed but no metrics are collected before exporting.

Yes, this is correct. Thanks for raising the issue. 

Related issues on specs:
https://github.com/open-telemetry/opentelemetry-specification/issues/2924
https://github.com/open-telemetry/opentelemetry-specification/issues/2983

**Comment by lalitb** [comment]
The `MetricReader::ForceFlush()` method needs more clarity from specification prospective. As of now,  python and java does collection while JS and C++ doesn't. 
Regarding the scenario described in this issue, it would make more sense for PeriodicExportingMetricReader::Shutdown() to do one last collection to capture all metrics before exiting ?

**Comment by johanpel** [comment]
> The `MetricReader::ForceFlush()` method needs more clarity from specification prospective

Agreed, thanks for linking the related issues.

> PeriodicExportingMetricReader::Shutdown() to do one last collection to capture all metrics before exiting

Yes, that would cover the scenario perfectly.

**Comment by sfc-gh-sili** [comment]
@lalitb Hi Lalit! Is there any reason PeriodicExportingMetricReader don't collect another round of data on Shutdown anymore? ref: https://github.com/open-telemetry/opentelemetry-cpp/blob/23206365dce31eeae1616f91fb73534d7b76f165/sdk/src/metrics/export/periodic_exporting_metric_reader.cc#L74-L74
