### ISSUE TITLE
SpanData loses type information

### ISSUE THREAD

**Issue by maxgolov** [open-telemetry/opentelemetry-cpp#186]
API surface allows to add attributes and events on `Span` that use the following typing system:

```cpp
                                      int32_t,
                                      int64_t,
                                      uint32_t,
                                      uint64_t,
                                      double,
                                      nostd::string_view,
                                      nostd::span<const bool>,
                                      nostd::span<const int32_t>,
                                      nostd::span<const int64_t>,
                                      nostd::span<const uint32_t>,
                                      nostd::span<const uint64_t>,
                                      nostd::span<const double>,
                                      nostd::span<const nostd::string_view>
```

`SpanExporter` and `SpanData` only exposes a subset of the following types via `SpanDataAttributeValue` :

```cpp
                                      bool,
                                      int64_t,
                                      uint64_t,
                                      double,
                                      std::string,
                                      std::vector<bool>,
                                      std::vector<int64_t>,
                                      std::vector<uint64_t>,
                                      std::vector<double>,
                                      std::vector<std::string>
```

Why this is bad:

- There's no way to design an exporter that would optimally pack and transmit 32-byte signed/unsigned integers. Type information on bit-width of original integer is lost.

- zPages inherently loses ability to 'see' what type was passed from app to SDK API call. This may be problematic - since API users may unintentionally pass 32-bit integer instead of 64-bit, but from exporters / span processors point of view there is no way to tell what type it was.

**Suggested solution**

Consider using the same type in SDK as on API surface:
```cpp
using SpanDataAttributeValue = common::AttributeValue;
```

But adding ownership / deep-copy semantics, such as if the processor / exporter needs to obtain a copy of original dictionary, then it may invoke a method such as `std::copy`-alike templated method that allows to transform from in-SDK view (read-only, const) to exporter-preferred container.

**Comment by pyohannes** [comment]
Great catch, I'll add the missing `int32_t` type. I'm not exactly sure about how to best realize the full suggested solution.

**Comment by maxgolov** [comment]
No problem, I am not blocked by this. Part of the reason why I'd like to keep track of this - I see that we'd eventually also get this one in: https://github.com/open-telemetry/opentelemetry-proto/issues/169 ... I'm also considering a few options how we can improve the process of creating owning 'copy` of the original dictionary.
