### ISSUE TITLE
Set recordable attributes before passing it to span processor

### ISSUE THREAD

**Issue by kmanghat** [open-telemetry/opentelemetry-cpp#187]
**Is your feature request related to a problem?**
Yes, the feature request is related to a problem. The tracez data aggregator is an object that collects span data from the span processor at regular intervals. The aggregation process starts in the constructor of the data aggregator and for collection of data it calls getters of SpanData.

Currently recordables are created in the constructor of the span and then passed onto the span processor before setting it's name and other attributes. There is a brief time where there exists a recordable in the span processor without a name or any of those attributes. During this time if the periodic aggregate function is called, it will not receive the correct information and possibly causing a race condition.

**Describe the solution you'd like**
The fix is simple - set these attributes before the recordable is passed to the span processor.

**Additional context**
Here is a [PR](https://github.com/open-telemetry/opentelemetry-cpp/pull/185/files#diff-ff684db3f68fbab2b9eb31f749753c1d) with these changes to demonstrate the fix and problem in question.

**Comment by pyohannes** [comment]
Please submit your fix as a separate PR, ideally with a test case. I see not problems with merging that.

**Comment by kmanghat** [comment]
Here is a [PR](https://github.com/open-telemetry/opentelemetry-cpp/pull/189) with just the change, is there a test file for span.cc at the moment? I can add tests but can it wait till my data aggregator PR is is approved?
