### ISSUE TITLE
Nlohmann library can cause conflict on CMake targets during build

### ISSUE THREAD

**Issue by cngzhnp** [open-telemetry/opentelemetry-cpp#1879]
**Describe your environment** 

Currently, in our project we are using `Nlohmann::JSON` library for another purpose which is added as a submodule. On other hand, we are also using `opentelemetry-cpp` library which brings with its own `Nlohmann::JSON` library which is a problematic. 

**Steps to reproduce**
During our build process, `Nlohmann::JSON` library that we used version is already parsed and `nlohmann_json` target is created by CMake. Afterwards, the next submodule is opentelemetry-cpp library and if it is built with Zipkin option (or could be another exporter which uses Nlohmann) which causes CMake build error like:

```
add_library cannot create target "nlohmann_json" because another target
  with the same name already exists.  The existing target is an interface
  library created in source directory
  "x/y/z/3rdParty/json".  See
  documentation for policy CMP0002 for more details.
```

**What is the expected behavior?**
My expectation is, even though 3rdParty dependency collision, it should be built up smoothly.

**What is the actual behavior?**
If project is used its own `Nlohmann::JSON` library, it is not possible to build.

**Additional context**
As a solution, in CMakeLists.txt after line 358, such a case must be included:

```cmake
...
  if(nlohmann_json_FOUND)
    message("Using external nlohmann::json")
  elseif(TARGET nlohmann_json) 
    message("nlohmann_json was already added as a CMake target!")
```
This will prevent during CMake process, if `Nlohmann::JSON` target is already found in the CMake target list, no need to do anything.

**Comment by owent** [comment]
You can `set(nlohmann_json_FOUND TRUE)` before adding otel-cpp, when both nlohmann_json and otel-cpp are imported by `add_subdirectory`.

**Comment by cngzhnp** [comment]
Sorry but it does not solve my problem at all, still same problem occured even though` set(nlohmann_json_FOUND TRUE)` was applied.

**Comment by cngzhnp** [comment]
So, it is written in the CMake documents obviously why this approach is not working at all. It states in `find_package` help page:

> "Regardless of the mode used, a PackageName_FOUND variable will be set to indicate whether the package was found." 

That means even though I set `nlohmann_json_FOUND` variable to `TRUE` before subdirectory is working, `find_package` will set it back to `FALSE` when package is not found. So, it does not work.

**Comment by owent** [comment]
> So, it is written in the CMake documents obviously why this approach is not working at all. It states in `find_package` help page:
> 
> > "Regardless of the mode used, a PackageName_FOUND variable will be set to indicate whether the package was found."
> 
> That means even though I set `nlohmann_json_FOUND` variable to `TRUE` before subdirectory is working, `find_package` will set it back to `FALSE` when package is not found. So, it does not work.

Sorry, this seems to be a trick for old version of cmake, we should consider import dependencies by this way indeed.
