### ISSUE TITLE
SpanData is not threadsafe

### ISSUE THREAD

**Issue by kmanghat** [open-telemetry/opentelemetry-cpp#188]
**Is your feature request related to a problem?**
Yes, the feature request is related to a problem. SpanData is a type of Recordable that mostly contains getters and setters. There are no locks added so it doesn't look like it is thread safe. Is there a reason for this or am I missing something?
The SpanData is a recordable used by the tracez span processor and data aggregator. The data aggregator requires data like the duration and name of SpanData and gets it with the help of accessors. Nothing prevents another thread from mutating this data while being accessed by the thread set up in the data aggregator.
At this time there are no issues because the information is set at only one location and the aggregator only accesses this information but it might be something to keep in mind.

**Describe the solution you'd like**
Addition of locks in these getters and setters to prevent race condition.

**Additional context**
[SpanData.h](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/include/opentelemetry/sdk/trace/span_data.h)

**Comment by pyohannes** [comment]
The SDK makes guarantees that a recordable is not available to any other thread:
* while it is processed by the `OnStart` processor method, and
* after it was handed over to the `OnEnd` method of the span processor.

If a processor (I think TraceZ is doing that) saves pointers to recordables and accesses values in between `OnStart` and `On End` invocations I'd advise you to implement your own `Recordable` that gives the needed thread safety guarantees. We'll most likely not add this to `SpanData`, as it's an overkill for most use cases.

**Comment by kmanghat** [comment]
Hi @pyohannes , thank you for the reply I have a follow up - Is the SpanData not accessed anywhere other than in OnStart and OnEnd. If it is how do you guarantee that only a single thread has access ? Giving it some thought I don't think the data aggregator access the SpanData during these two functions.

**Comment by pyohannes** [comment]
In the SDK `SpanData` is accessed via the `Recordable` interface, which in turn is accessed via the `Span` implementation. All setters in `Span` are protected by a [mutex](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/src/trace/span.cc#L75). The SDK doesn't ever invoke `SpanData` getters.

At some point the `Recordable` is passed to the `OnEnd` function of the processor, which also transfer ownership of the span to the processor. The processor then passes ownership on to the exporter.
