### ISSUE TITLE
Prometheus example crashes

### ISSUE THREAD

**Issue by bachittle** [open-telemetry/opentelemetry-cpp#1903]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.
- windows 10 x64
- ubuntu gcc x64

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.
- run prometheus in docker container
- compile opentelemetry via cmake with the WITH_PROMETHEUS flag turned on
- run the prometheus_example

**What is the expected behavior?**
What did you expect to see?
- Connection to my prometheus docker service, with metrics pushed in

**What is the actual behavior?**
What did you see instead?
- program crashes, outputting: `null context when constructing CivetServer. Possible problem binding to port.`

**Comment by marcalff** [comment]
@bachittle 

Thanks for the report.

Do you have a call stack by chance, this would help.

**Comment by esigo** [comment]
Hi @bachittle,
Thanks for reaching out to us.
Is your port 8080 already used by some other process when you run into this issue?

**Comment by bachittle** [comment]
well that is what is being used by prometheus. Unless the address you specify in the url is what is used by another process (civet web server)? In that case how do you specify where the prometheus url is?

**Comment by esigo** [comment]
sorry I mentioned the wrong port. The default port for the example app is `9464`. You could change the port with:
`bazel run //examples/prometheus/... -- all localhost:<port>`
or pass `all localhost:<port>` as arg to your executable. You then need to update the port in the [yaml](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/prometheus/prometheus.yml) file.
Please make sure the port is not used by any other app.

**Comment by bachittle** [comment]
the default port is 8080, at least that's what the addr string variable is set to in this main.cc file: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/prometheus/main.cc

even when I run it as `./prometheus_example counter localhost:8080` it does not work. If the prometheus server is on another port, like 9464 or 9090, it does not connect to it at all. When the prometheus server is on port 8080, like what I assumed would be where it would connect, it crashes with the error specified. 

so what port should the prometheus server be set as so this will work?

**Comment by lalitb** [comment]
> Also, I tried running prometheus on port 9464 and it did not connect and show metrics results.

@bachittle  - There are few changes in prometheus exporter recently in main branch (#1953), can you follow the example and see if you can fetch the metrics - https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/prometheus/main.cc

Meanwhile, will go through the docs and modify the steps documented there.

**Comment by bachittle** [comment]
thank you, have been working on other things but glad this got fixed!
