### ISSUE TITLE
How to remove active span and stop implicit child spans for a code path?

### ISSUE THREAD

**Issue by VivekSubr** [open-telemetry/opentelemetry-cpp#1911]
The java implementation seems to have a way to do this: https://github.com/open-telemetry/opentelemetry-java/issues/1717

I'm looking for some way to clear the ActiveSpan, without having it destroyed, such that any new start spans won't be the child of it.

**Comment by VivekSubr** [comment]
Setting invalid didn't seem to work,
  nostd::shared_ptr<trace::Span> resetSpan = nostd::shared_ptr<trace::Span>(new trace::DefaultSpan(trace::DefaultSpan::GetInvalid()));
    m_tracer->WithActiveSpan(resetSpan);

**Comment by lalitb** [comment]
Please clarify what are you trying to achieve - Make a Span active, and then make it inactive. Why do you want to make it active at first place in that case. You can create multiple spans child of root as below without making them active.

```cpp
auto span1 = tracer->StartSpan("span 1");
auto span2 = tracer->StartSpan("span 2");
...
..
span2->End();
..
span1->End();
```

**Comment by lalitb** [comment]
@VivekSubr  - The implicit context management (using Context API)  is not designed to handle these various mentioned stages of Spans - start, pause, resume , and stop. You can't remove the Span from context before it's logical completion, and replace any other span. Or cleanup the context in between. I would advice you not to use the implicit context management for your scenario, and instead directly pass the parent of span as an argument while it's creation.

**Comment by Falmarri** [comment]
Just wanted to comment this is really annoying not being able to do this. I have a client where it will lazily create a connection to the server. I want to create a separate, isolated span for the lifetime of the connection, and not have it be related to the trace of the individual request being made that happens to initiate the connection creation. This happens _several_ levels deep in my application that includes sqlite extensions. So there's basically 0 way to pass the lifetime manually
