### ISSUE TITLE
[BUILD] CMake calls find_package(CURL) in multiple places

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#1913]
Per the CMake makefiles:

```
./examples/http/CMakeLists.txt:find_package(CURL)
./exporters/otlp/CMakeLists.txt:  find_package(CURL REQUIRED)
./exporters/zipkin/CMakeLists.txt:find_package(CURL REQUIRED)
./ext/src/http/client/curl/CMakeLists.txt:find_package(CURL)
./ext/test/http/CMakeLists.txt:find_package(CURL)
./ext/test/w3c_tracecontext_test/CMakeLists.txt:find_package(CURL)
./CMakeLists.txt:    find_package(CURL)
```

CMake should not call find_package(CURL) so many times from nested directories.

Beside, the current logic is questionable:

```
find_package(CURL)
if(NOT CURL_FOUND)
  message(WARNING "Skipping example_w3c_tracecontext_test: CURL not found")
else()
```

If `CURL` is not found and `BUILD_W3CTRACECONTEXT_TEST` is set, the build should fail, not pass and do nothing.

Instead:

- Evaluate once **IF** CURL is needed, similar to `USE_NLOHMANN_JSON`
- Call find_package(CURL) once from the top level CMakeLists.txt
- Assume CURL_FOUND and related variables are already evaluated, in sub directories.

Implementing this cleanup will help to add the CURL dependency from different sources (git submodule, external project, alternate location).

**Comment by lalitb** [comment]
Thanks, agree CURL checks can be much simplified. Later, once #1145 and #1146 are implemented, with native HTTP client libraries used for Windows and Mac, CURL can be made mandatory only for POSIX.
