### ISSUE TITLE
Metrics Simple example isn't compiles

### ISSUE THREAD

**Issue by aradzu10** [open-telemetry/opentelemetry-cpp#1925]
**Describe your environment** 

https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/metrics_simple/metrics_ostream.cc#L77

This line isn't compiles - its says:
```bash
experimental/me/metrics_simple/metrics_ostream.cc:74:83: error: no match for 'operator=' (operand types are 'std::__cxx11::list<double>' and 'std::vector<double>')
   74 |                                           1000.0, 2500.0, 5000.0, 10000.0, 20000.0};
```

**Additional context**

Change it to `initilizaition list` or to `std::list<double>` as expected :)

**Comment by lalitb** [comment]
If you are using the otel-cpp version v1.8.1 or lower, please ensure to use the metrics example for the same version - https://github.com/open-telemetry/opentelemetry-cpp/blob/v1.8.1/examples/metrics_simple/metrics_ostream.cc. 
In latest commit, histogram boundaries are changed from std::list<double> to std::vector<double>
