### ISSUE TITLE
span.SetAttribute()  is allowing to duplicate key attributes when using OTLP exporter

### ISSUE THREAD

**Issue by MrSparc** [open-telemetry/opentelemetry-cpp#1944]
**Describe your environment** 
 * otel-cpp v1.8.1
 * Linux x86_64
 * Exporter OTLP gRPC

The  `span.SetAttribute()` , according to the API header `span.h`,  a value is replaced if same key already exists :
```cpp
  // Sets an attribute on the Span. If the Span previously contained a mapping
  // for
  // the key, the old value is replaced.
  virtual void SetAttribute(nostd::string_view key,
                            const common::AttributeValue &value) noexcept = 0;
```

This comes from analyzing  Data-Prepper logs, it was complaining that it couldn't parse a span because there were duplicate key attributes:

```
 ERROR org.opensearch.dataprepper.plugins.source.oteltrace.OTelTraceGrpcService - Failed to parse the request content [resource_spans {
  resource {
    attributes {
      key: "telemetry.sdk.version"
      value {
        string_value: "1.8.1"
      }
    }
    attributes {
      key: "telemetry.sdk.language"
      value {
        string_value: "cpp"
      }
    }
  ...
  }
  instrumentation_library_spans {
    ...
    spans {
      trace_id: "\241&h\032l\364pCL\343\355y\211\273\375\003"
      span_id: "\251V\351\253\300\242\335\337"
      name: "586d0492-0f60-4087-8d22-792e03e9b988"
      kind: SPAN_KIND_INTERNAL
      start_time_unix_nano: 1675075979889536317
      end_time_unix_nano: 1675076156092120780
      attributes {
        key: "source_uuid"
        value {
          string_value: "586d0492-0f60-4087-8d22-792e03e9b988"
        }
      }
      attributes {
        key: "source_uuid"
        value {
          string_value: "586d0492-0f60-4087-8d22-792e03e9b988"
        }
      }
...
] due to:
java.lang.IllegalStateException: Duplicate key span.attributes.source_uuid (attempted merging values 586d0492-0f60-4087-8d22-792e03e9b988 and 586d0492-0f60-4087-8d22-792e03e9b988)
```

Effectively the instrumented code was wrongly setting the same attribute to the running span in different functions, but it was not supposed to duplicate the key if span attributes is a map .
Then I changed the exporter from otlp gRPC to ostream, the attributes do not appear duplicated in the console.
So it looks like something related to the OTLP /gRPC implementation.

**Steps to reproduce**

Use `examples\otlp` that comes with the  source code changing  `lib_foo` instrumentation to use duplicated attributes
```
void foo_library()
{
  auto span = get_tracer()->StartSpan("library");
  auto scoped_span = trace::Scope(span);
  span->SetAttribute("same_key", "value_one");
  span->SetAttribute("same_key", "value_two");
  span->SetAttribute("same_key", "value_three");

  f2();
}
```
Then run the Docker otel collector and `examples/otlp/example_otlp_grpc_log` binary.
The collector will print trace data to stdout. 

**What is the expected behavior?**
The span's attribute `same_key` whould not be duplicated and  set with the last value `value_three`

**What is the actual behavior?**
Duplicated span attributes `same_key`:
```
InstrumentationScope foo_library 1.8.1
Span #0
    Trace ID       : 625e916dfcba6b98eb93ed54184f27c8
    Parent ID      : 
    ID             : a0bb9f6b0357fa51
    Name           : library
    Kind           : SPAN_KIND_INTERNAL
    Start time     : 2023-01-30 12:15:01.770034432 +0000 UTC
    End time       : 2023-01-30 12:15:02.026001443 +0000 UTC
    Status code    : STATUS_CODE_UNSET
    Status message : 
Attributes:
     -> same_key: STRING(value_one)
     -> same_key: STRING(value_two)
     -> same_key: STRING(value_three)
        {"kind": "exporter", "data_type": "traces", "name": "logging"}
```     
**Additional context**

**Comment by lalitb** [comment]
I am not sure if it would be easy to validate duplicate attribute before adding without compromising on performance, as the attributes are directly serialized into the proto data structures - If that is the case, the application need to avoid duplicate values. Will investigate further.

**Comment by lalitb** [comment]
@MrSparc this was discussed during community meeting today. The current behavior is with all the exporters, and this is due to the SDK design - span attributes are directly serialized in the exporter protocol structure.  The fix would require change in the SDK and it won't be possible to do that for now, even if that is not fully specs compliant. The application needs to ensure that key attributes are added properly. Closing this as "Won't fix". Please feel free to reopen it with your proposal if required.
