### ISSUE TITLE
Alpine Packages

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-cpp#1950]
While playing around with the OpenTelemetry demo applications I figured out that it would be nice to have the ability to load the OpenTelemetry C++ libraries pre-compiled from a package repository like grpc, re2, etc

So instead of 

```
RUN apk add git cmake make g++ grpc-dev re2-dev protobuf-dev c-ares-dev 
RUN git clone opentelemetry-cpp ... build ... make
```

Wouldn't it be nice to do the following instead?

```
RUN apk add git cmake make g++ grpc-dev re2-dev protobuf-dev c-ares-dev opentelemetry-cpp-dev
```

I played around with that a little bit and now I have the following:

https://github.com/svrnm/otel-abuild

I consider to create a merge request with https://gitlab.alpinelinux.org/alpine/aports/, but I wanted to check with you first what you think about that and maybe if there's some feedback on what I created.

Thanks

**Comment by marcalff** [comment]
Thanks @svrnm 

From a quick look:

* add license information on every file ?
* The jaeger exporter is [deprecated](https://github.com/open-telemetry/opentelemetry-cpp/issues/1892), and the build uses WITH_JAEGER=OFF, great. There should be no `opentelemetry-cpp-exporter-jaeger` package then.
* For the packages names, maybe use only the `opentelemetry-cpp-*` namespace, not `opentelemetry-*` (as seen in `RUN apk add ... opentelemetry-dev`)

For the license, I assume it will be:

```
# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
```

I have not tried the packages yet, will investigate further.

**Comment by svrnm** [comment]
> add license information on every file ?

The only file that's really relevant is the APKBUILD file, everything else is just there to speed up the build. If this get's added to the official alpine repositories they are no longer needed.

> The jaeger exporter is https://github.com/open-telemetry/opentelemetry-cpp/issues/1892, and the build uses WITH_JAEGER=OFF, great. There should be no opentelemetry-cpp-exporter-jaeger package then.

I forgot to take this off the list of packages that are generated. I just upgraded to 1.8.2 and saw the deprecation notes, will remove it.

> For the packages names, maybe use only the opentelemetry-cpp-* namespace, not opentelemetry-* (as seen in RUN apk add ... opentelemetry-dev)

Also a typo, thanks!

**Comment by lalitb** [comment]
This looks good. @svrnm - If you plan to maintain this going ahead, we can list it [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md#using-package-managers) along with unofficially available packages once this get's published.

As a sidenote, opentelemetry-cpp support building binary deb, rpm, NuGet packages using cpack as mentioned [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md#generatring-binary-packages), would be interesting to see what it takes to extend this for building alpine packages.

**Comment by svrnm** [comment]
> This looks good. @svrnm - If you plan to maintain this going ahead, we can list it [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md#using-package-managers) along with other unofficially available packages once this get's published.

I need to dig a little bit what the requirements are from the alpine / aport project, but yes, I am able to maintain it over there.

> As a sidenote, opentelemetry-cpp support building binary deb, rpm, NuGet packages using cpack as mentioned [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md#generatring-binary-packages), would be interesting to see what it takes to extend this for building alpine packages.

I was not aware of that, that's super cool! I've no experience with CPACK, so I can not speak about capabilities to create apk/alpine packages, but I can look into it.

**Comment by svrnm** [comment]
@lalitb @marcalff it's in "edge/testing" now:

https://pkgs.alpinelinux.org/packages?name=opentelemetry-*&branch=edge&repo=testing&arch=&maintainer=
