### ISSUE TITLE
Run metrics_ostream_example separately in bazel.asan/tsan?

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-cpp#1952]
In below CI script, we run metrics_ostream_example separately after bazel run. Is this necessary or can be removed?

https://github.com/open-telemetry/opentelemetry-cpp/blob/d56a5c702fc2154ef82400df4801cd511ffb63ea/ci/do_ci.sh#L296

**Comment by lalitb** [comment]
This was added as part of this issue - https://github.com/open-telemetry/opentelemetry-cpp/issues/1669, seems for some race conditions which were not reproducible through unit-tests. I think can be removed, now that we don't have the issue anymore.
