### ISSUE TITLE
absl conflict between grpc and nostd

### ISSUE THREAD

**Issue by VivekSubr** [open-telemetry/opentelemetry-cpp#1966]
**Describe your environment** 
Red Hat linux,
subramaniamv@eb7e020f3f96:/src/cna$ cat /etc/redhat-release
Fedora release 36 (Thirty Six)

**Steps to reproduce**
Build with OLTP_GRPC, C++14

export CXX=/"usr/bin/clang++ -std=c++14"
mkdir build && cd build
cmake .. -DCMAKE_PREFIX_PATH=$BUILD_DIR:$BUILD_DIR/include -DBUILD_SHARED_LIBS=ON -DWITH_JAEGER=ON -DWITH_OTLP=ON -DWITH_OTLP_GRPC=ON \
         -DBUILD_TESTING=OFF -DThrift_HOME=$BUILD_DIR/$THRIFT_SRC_DIR 
cmake --build . --target all
sudo cmake --install . --config Release --prefix ../.

**What is the expected behavior?**
Application build should work

**What is the actual behavior?**
Conflict between grpc absl and nostd absl,

```
In file included from genTracer.cc:32:
In file included from /usr/include/opentelemetry/exporters/otlp/otlp_grpc_exporter.h:11:
In file included from /usr/include/opentelemetry/proto/collector/trace/v1/trace_service.grpc.pb.h:25:
In file included from /usr/include/grpcpp/generic/async_generic_service.h:24:
In file included from /usr/include/grpcpp/impl/codegen/server_callback_handlers.h:25:
In file included from /usr/include/grpcpp/impl/codegen/server_callback.h:28:
In file included from /usr/include/grpcpp/impl/codegen/call_op_set.h:33:
In file included from /usr/include/grpcpp/impl/codegen/client_context.h:55:
In file included from /usr/include/grpcpp/impl/codegen/sync.h:32:
In file included from /usr/include/absl/synchronization/mutex.h:66:
/usr/include/absl/base/internal/identity.h:26:8: error: redefinition of 'identity'
struct identity {
       ^
/usr/include/opentelemetry/nostd/./internal/absl/types/../types/internal/../../base/internal/identity.h:26:8: note: previous definition is here
struct identity {
```

**Comment by lalitb** [comment]
@VivekSubr  Have you tried the suggestion here - https://github.com/open-telemetry/opentelemetry-cpp/tree/main/examples/otlp#additional-notes-regarding-abseil-library ?

**Comment by VivekSubr** [comment]
@lalitb - thank you very much! :)
