### ISSUE TITLE
ASYNC_EXPORT feature: compile time or runtime choice ?

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#1969]
The code currently has option `WITH_ASYNC_EXPORT_PREVIEW`.

This is a feature flag, in "preview", which presumably will become mainstream later when the code is considered stable: the configuration option `WITH_ASYNC_EXPORT_PREVIEW` will be removed.

The code, in the most part, implements both the sync and async features, in the same code base, like in http client.

The exporters however, are implemented with this pattern:

```
opentelemetry::sdk::common::ExportResult OtlpHttpExporter::Export(
    const nostd::span<std::unique_ptr<opentelemetry::sdk::trace::Recordable>> &spans) noexcept
{
  // common code

#ifdef ENABLE_ASYNC_EXPORT
  // implementation of async export
#else
  // implementation of sync export
#endif
}
```

As a result, once the code is compiled with ENABLE_ASYNC_EXPORT, the sync implementation available in the rest of the code base is no longer used by the http exporter.

Should really this be a compile time choice ?

Should this be a runtime choice instead, with a `bool async` member in the exporter options:

```
opentelemetry::sdk::common::ExportResult OtlpHttpExporter::Export(
    const nostd::span<std::unique_ptr<opentelemetry::sdk::trace::Recordable>> &spans) noexcept
{
  // common code

#ifdef ENABLE_ASYNC_EXPORT
  if (async)
  {
    // implementation of async export
  }
#endif

  // implementation of sync export
}
```

Please clarify the intent of this feature flag.

I would expect features to be added functionality (meaning there is now a choice between sync and async), not replacement of existing functionality (the sync export here is replaced by async).

If sync and async are really a compile time choice:

* some dead code exists in the async build, the sync code is no longer reachable
* the flag should not be named `PREVIEW`

**Comment by owent** [comment]
Set `max_concurrent_requests` to 0 just mean sync mode, I think we do not need another option.
OTLP gRPC exporter do not support async exporting now. So I think we may keep `WITH_ASYNC_EXPORT_PREVIEW` util we implement it.

**Comment by marcalff** [comment]
@owent 

> Set `max_concurrent_requests` to 0 just mean sync mode, I think we do not need another option. 

Thanks for the clarification.

So, to summarize:

* `WITH_ASYNC_EXPORT_PREVIEW` is a feature flag, still in progress as some parts are not implemented yet (gRPC)
* Once the feature flag is removed, the code will support both sync and async use cases
* The choice between sync and async will be done at runtime, with Set `max_concurrent_requests` to 0

Closing this issue as resolved.
