### ISSUE TITLE
`opentelemetry_exporter_otlp_http` not built with `-DWITH_OTLP_HTTP=On`

### ISSUE THREAD

**Issue by jodavaho** [open-telemetry/opentelemetry-cpp#1975]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.

Ubuntu 20.04
cmake version 3.15
vcpkg to manage dependencies

Sorry if this list is incomplete .. not sure what to share.

**Steps to reproduce**
```
git clone https://github.com/open-telemetry/opentelemetry-cpp --recursive
mkdir opentelemetry-cpp/build && cd opentelemetry-cpp/build
cmake .. -DCMAKE_TOOLCHAIN_FILE=~/workspace/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_TESTING=Off -DWITH_OTLP_HTTP=On
# OR 
cmake .. -DWITH_OTLP_HTTP=On -DBUILD_TESTING=Off
make -j16 # or just make
# long output
[ 94%] Linking CXX executable example_otlp_http
/usr/bin/ld: cannot find -lopentelemetry_exporter_otlp_http
collect2: error: ld returned 1 exit status
```

**What is the expected behavior?**
```
[ 100% ]
```

**What is the actual behavior?**

```
/usr/bin/ld: cannot find -lopentelemetry_exporter_otlp_http
collect2: error: ld returned 1 exit status
```

**Additional context**
I tried versions: v1.8.0 and main

**Comment by jodavaho** [comment]
Is `WITH_EXAMPLES=On` required?

**Comment by owent** [comment]
> Is `-DWITH_EXAMPLES=On` required?

No, but `-DWITH_OTLP=ON` is required is you want OTLP HTTP Exporter.

**Comment by jodavaho** [comment]
`-DWITH_OTLP` requires `gRPC`, which for various reasons is highly undesirable. However `-DWITH_EXAMPLES` builds the lib without requiring `gRPC`

**Comment by owent** [comment]
> > No, but -DWITH_OTLP=ON is required is you want OTLP HTTP Exporter.
> 
> `-DWITH_OTLP` looks for `gRPC`, which for various reasons is highly undesirable. However `-DWITH_EXAMPLES` builds the lib without requiring `gRPC`

You can use `-DWITH_OTL=ON -DWITH_OTLP_HTTP=ON -DWITH_OTLP_GRPC=OFF` to build OTLP HTTP exporters only.

**Comment by jodavaho** [comment]
Thank you!
