### ISSUE TITLE
Develop own  OpenTelemetry Collector

### ISSUE THREAD

**Issue by DCMinds** [open-telemetry/opentelemetry-cpp#1981]
Hi Team,

I have clone the opentelemetry and build it in my local machine. I am using Otlp http exporter to collect telemetry.
I want to write my own collector which will act as a server. It should be able to accept the request from my application that i will be sending using  Otlp http exporter and log it.

I am not sure about what response server shall provide on request to log the trace from my application.
Any suggestion/ reference to achieve same would be of great help

Thanks,
Dharmendra

**Comment by lalitb** [comment]
Why do you want to reinvent the wheel by writing your own collector server, when you can directly use the OTLP collector provided by OpenTelemetry - 
https://opentelemetry.io/docs/collector/. You can write the custom exporter for OTLP collector to further export your data. Probably I am not fully understanding your use case:)

**Comment by lalitb** [comment]
Regarding response code, as per the specs, the server should send `HTTP 200 OK` for full/partial success, and `HTTP 4xx` or `HTTP 5xx` otherwise.

otel-cpp treats 200 and 202 as success - https://github.com/open-telemetry/opentelemetry-cpp/blob/d56a5c702fc2154ef82400df4801cd511ffb63ea/exporters/otlp/src/otlp_http_client.cc#L112.

**Comment by DCMinds** [comment]
@lalitb Thanks for the quick response.

The reason why i want to develop my own server or collector is, we want to create a customized dashboard. where we can create various graphs and tables and do some static analysis based on our requirements

To achieve this i am trying something like this

**Python server/ collector**
from flask import Flask,  request
app = Flask(__name__)

@app.route('/v1/trace', methods = ['POST', 'GET'])
def trace():
    print(request)
    if request.method == 'POST':
        result = request.form
        print(result)
        print(result.get('Error'))
    print(request.args.get('foo_library'))
    return 'success'

if __name__ == '__main__':
   app.run()

**and C++ code/client using OTLP-htpp exporter**

opentelemetry::exporter::otlp::OtlpHttpExporterOptions opts;
void InitTracer()
{
  opts.url = "http://127.0.0.1:5000/v1/trace";
  // Create OTLP exporter instance
  auto exporter  = otlp::OtlpHttpExporterFactory::Create(opts);
  auto processor = trace_sdk::SimpleSpanProcessorFactory::Create(std::move(exporter));
  std::shared_ptr<opentelemetry::trace::TracerProvider> provider =
      trace_sdk::TracerProviderFactory::Create(std::move(processor));
  // Set the global trace provider
  trace::Provider::SetTracerProvider(provider);
}

void main() {
 InitTracer();

  auto provider = trace::Provider::GetTracerProvider();
  auto spn = provider->GetTracer("foo_library", OPENTELEMETRY_SDK_VERSION)->StartSpan("Hello");
  spn->SetAttribute("Error", "Failed to log");
}


 With the above code, i am able to send request from c++ to python server and resposce code is 200 from server
 but not able to see the content of the request that came from c++ client code
 
![image](https://user-images.githubusercontent.com/56649317/218372550-72d7275d-5d1f-472f-bb89-f9f20f9619f4.png)

**Comment by lalitb** [comment]
> result = request.form
> print(result)

Not a `flask` expert, but this seems to be assuming the contents to be form-data. You may want to try `request.get_data()` or `request.get_json()` to get the request contents.

**Comment by DCMinds** [comment]
@lalitb Thanks for the input.
I really appreciate it.
