### ISSUE TITLE
Prepare release, include fixes with abi breaking changes

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#1983]
Prepare future releases with breaking changes.

Due to expected changes in the spec, there will be breaking changes in the API/ABI.

Due to changes in the implementation, there are also known changes in the SDK interface, which can break applications when using shared libraries.

It is desirable to group many fixes that causes breaking changes at once, so listing here all the known issues that impact API/ABI.

It is also desirable to define the overall strategy to introduce breaking changes.

API/ABI:

* #2033 (API + SDK)
* #2032 (API + SDK)
* #1922 (API)
* #1416 (API)
* #828 (API) -> Providing alternate Span creation API to return nostd::unique_ptr.
* #2155
* #1753
* #2132
* #2279

SDK:

* https://github.com/open-telemetry/opentelemetry-cpp/issues/1845 (remove exporter options struct inheritance)
* https://github.com/open-telemetry/opentelemetry-cpp/issues/1402 (new members in exporter options struct)

**Comment by lalitb** [comment]
Adding few more issues in the list -

* https://github.com/open-telemetry/opentelemetry-cpp/issues/1922 (API)
* https://github.com/open-telemetry/opentelemetry-cpp/issues/1416 (API)
* https://github.com/open-telemetry/opentelemetry-cpp/issues/828 (API) -> Providing alternate Span creation API to return nostd::unique_ptr.

**Comment by marcalff** [comment]
On hold until the spec change is settled:

https://github.com/open-telemetry/opentelemetry-specification/pull/3186

If there is an ABI change, we nay need to expose both old and new ABI at the same time, by using something similar to

```
#define OPENTELEMETRY_BEGIN_OLD_NAMESPACE(VER) \
  namespace opentelemetry { inline namespace VER {

#define OPENTELEMETRY_END_OLD_NAMESPACE \
  }}

#define OPENTELEMETRY_OLD_NAMESPACE(VER) opentelemetry :: VER
```

and then expose old abi (for binary compatibility) and new abi, as follows:

```
OPENTELEMETRY_BEGIN_OLD_NAMESPACE(v1)
... declaration for class Span in v1 goes here, code unchanged ...
OPENTELEMETRY_END_OLD_NAMESPACE

#define OPENTELEMETRY_ABI_VERSION_NO 2

OPENTELEMETRY_BEGIN_NAMESPACE
... declaration for class Span in v2 goes here, with added methods ...
OPENTELEMETRY_END_NAMESPACE
```

**Comment by owent** [comment]
Adding logs API changes:

+ #1884 .

**Comment by lalitb** [comment]
> https://github.com/open-telemetry/opentelemetry-cpp/pull/1884 

the Logs API and SDK are still not stable, so we don't need to increment ABI version specifically for them.

**Comment by lalitb** [comment]
The original intent of having `OPENTELEMETRY_ABI_VERSION_NO` was to increment this version whenever there is ABI breaking, in-order to catch any ABI breaking issues  as unresolved symbols during link time, and thus avoid any weird memory corruption issues at runtime. It was thought not to maintain older API versions, probably to keep the API simple and easy to maintain. 

As per the otel-cpp [Versioning.md](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/Versioning.md#abi-stability) document, created in response to [Versioning and stability guidelines](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md) defined by Specs which was also reviewed at that time by specs contributor -

``
In case of ABI breaking changes, a new inline namespace version will be introduced, and the existing linked applications can continue using the older version unless they relink with newer version.
``

But this is good to continue discussing maintaining older versions, and there is no reason we can't change our existing guidelines for betterment.

**Comment by owent** [comment]
Adding trace SDK changes:

#2000

**Comment by lalitb** [comment]
Add #2155 to the list.

**Comment by marcalff** [comment]
Please comment on the linked PR #2222 for the technical discussion.
