### ISSUE TITLE
[GIT] Missing git tag for releases after v1.4.0

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#2002]
```git tag -l``` gives:

```
v0.1.0
v0.2.0
v0.3.0
v0.4.0
v0.5.0
v0.6.0
v0.7.0
v1.0.0
v1.0.0-rc1
v1.0.0-rc2
v1.0.0-rc3
v1.0.0-rc4
v1.0.1
v1.1.0
v1.1.1
v1.2.0
v1.3.0
v1.4.0
```

Releases published after 1.4.0 do not have a tag in git.

What I need is to make a local branch of each release, like so:

Works:

```
git checkout main
git checkout -b release-1.4.0 v1.4.0
```

Fails, tag v1.5.0 does not exists:

```
git checkout main
git checkout -b release-1.5.0 v1.5.0
```

**Comment by lalitb** [comment]
Not sure if I am missing something, but I see different output:
```
$ git tag -l
v0.1.0
v0.2.0
v0.3.0
v0.4.0
v0.5.0
v0.6.0
v0.7.0
v1.0.0
v1.0.0-rc1
v1.0.0-rc2
v1.0.0-rc3
v1.0.0-rc4
v1.0.1
v1.1.0
v1.1.1
v1.2.0
v1.3.0
v1.4.0
v1.4.1
v1.5.0
v1.6.0
v1.6.1
v1.7.0
v1.8.0
v1.8.1
v1.8.2
```

**Comment by marcalff** [comment]
I found out the difference.

I forked open-telemetry/opentelemetry-cpp into marcalff/opentelemetry-cpp after 1.4.0.

There are frequent merges to keep my branch up to date, so I see all commits, but tags created in open-telemetry/opentelemetry-cpp after the fork are not merged back to marcalff/opentelemetry-cpp.

Closing then, sorry for the false alarm.
