### ISSUE TITLE
OTLP exporter doesn't work with grpc in CMAKE_PREFIX_PATH

### ISSUE THREAD

**Issue by VivekSubr** [open-telemetry/opentelemetry-cpp#2009]
**Describe your environment**
Fedora 36

**Steps to reproduce**
* Build grpc and install as non-root, at a build location xyz, here it's 'grpc-install' folder.
* Build opentelemetry with otlp, with cmake build prefix of grpc-install location.
`cmake .. -DCMAKE_PREFIX_PATH=/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD:/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/include:/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/grpc-install -DBUILD_SHARED_LIBS=ON -DWITH_OTLP=ON -DWITH_OTLP_GRPC=ON -DBUILD_TESTING=OFF`

**What is the expected behavior?**
Build to go through and be usable... or else it should error out rather than produce an un-usable built.

**What is the actual behavior?**
Build goes through but is incomplete, it throws a warning, 
```
CMake Warning at CMakeLists.txt:281 (find_package):
  By not providing "FindgRPC.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gRPC", but
  CMake did not find one.
```

And does not build *.grpc.pb.h files, only .pb.h files,
`[  7%] Generating generated/third_party/opentelemetry-proto/opentelemetry/proto/common/v1/common.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/common/v1/common.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/resource/v1/resource.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/resource/v1/resource.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/trace/v1/trace.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/trace/v1/trace.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/logs/v1/logs.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/logs/v1/logs.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/metrics/v1/metrics.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/metrics/v1/metrics.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/trace/v1/trace_service.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/trace/v1/trace_service.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/logs/v1/logs_service.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/logs/v1/logs_service.pb.cc, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/metrics/v1/metrics_service.pb.h, generated/third_party/opentelemetry-proto/opentelemetry/proto/collector/metrics/v1/metrics_service.pb.cc`

And using this build results in application errors like,
```
In file included from genTracingInitFactory.cc:1:
/usr/include/opentelemetry/exporters/otlp/otlp_grpc_exporter.h:11:10: fatal error: 'opentelemetry/proto/collector/trace/v1/trace_service.grpc.pb.h' file not found
#include "opentelemetry/proto/collector/trace/v1/trace_service.grpc.pb.h"
```

**Additional context**
Above issue is not hit if built without cmake prefix for grpc, ie if grpc is in /usr.

**Comment by owent** [comment]
CMake list of elements are separated  by `;` , so you should use `-DCMAKE_PREFIX_PATH=/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD;/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/include:/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/grpc-install` instead.

See https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#lists for details.

**Comment by VivekSubr** [comment]
@owent - thanks, that helps but it still doesn't working for -rpath,

```
 79%] Linking CXX executable example_otlp_grpc
cd /src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/examples/otlp && /usr/bin/cmake -E cmake_link_script CMakeFiles/example_otlp_grpc.dir/link.txt --verbose=1
/usr/bin/g++ -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -Wl,-dT,/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/.package_note-opentelemetry-cpp-1.4.0-pkg_opentelemetry_4_1_0_1_only_otel_subramaniamv_localdata_subramaniamv.x86_64.ld -rdynamic CMakeFiles/example_otlp_grpc.dir/grpc_main.cc.o -o example_otlp_grpc  -Wl,-rpath,/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/examples/common/foo_library:/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/exporters/otlp:/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/sdk/src/trace:/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/sdk/src/resource:/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/sdk/src/metrics:/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/sdk/src/common ../common/foo_library/libcommon_foo_library.so ../../exporters/otlp/libopentelemetry_exporter_otlp_grpc.so ../../exporters/otlp/libopentelemetry_otlp_recordable.so ../../sdk/src/trace/libopentelemetry_trace.so ../../sdk/src/resource/libopentelemetry_resources.so ../../sdk/src/metrics/libopentelemetry_metrics.so ../../sdk/src/common/libopentelemetry_common.so ../../exporters/otlp/libopentelemetry_exporter_otlp_grpc_client.so ../../libopentelemetry_proto.a /usr/lib64/libprotobuf.so
/usr/bin/ld: ../../exporters/otlp/libopentelemetry_exporter_otlp_grpc.so: undefined reference to `absl::lts_20210324::Mutex::~Mutex()'
```

the absl libraries are in this case, at /src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/grpc-install/lib64, and cmake build is invoked as,

`cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_STANDARD=14 '-DCMAKE_PREFIX_PATH=/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/grpc/include;/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/grpc-install' -DCMAKE_LIBRARY_PATH_FLAG=/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/grpc-install/lib64 -DBUILD_SHARED_LIBS=ON -DWITH_OTLP=ON -DBUILD_TESTING=OFF`

I even tried setting LD_LIBRARY_PATH, that didn't help as well... basically the rpaths need to included custom paths

**Comment by owent** [comment]
> @owent - thanks, that helps but it still doesn't working for -rpath,
> 
> ```
>  79%] Linking CXX executable example_otlp_grpc
> cd /src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/examples/otlp && /usr/bin/cmake -E cmake_link_script CMakeFiles/example_otlp_grpc.dir/link.txt --verbose=1
> /usr/bin/g++ -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -Wl,-dT,/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/.package_note-opentelemetry-cpp-1.4.0-pkg_opentelemetry_4_1_0_1_only_otel_subramaniamv_localdata_subramaniamv.x86_64.ld -rdynamic CMakeFiles/example_otlp_grpc.dir/grpc_main.cc.o -o example_otlp_grpc  -Wl,-rpath,/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/examples/common/foo_library:/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/exporters/otlp:/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/sdk/src/trace:/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/sdk/src/resource:/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/sdk/src/metrics:/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/opentelemetry-cpp/build/sdk/src/common ../common/foo_library/libcommon_foo_library.so ../../exporters/otlp/libopentelemetry_exporter_otlp_grpc.so ../../exporters/otlp/libopentelemetry_otlp_recordable.so ../../sdk/src/trace/libopentelemetry_trace.so ../../sdk/src/resource/libopentelemetry_resources.so ../../sdk/src/metrics/libopentelemetry_metrics.so ../../sdk/src/common/libopentelemetry_common.so ../../exporters/otlp/libopentelemetry_exporter_otlp_grpc_client.so ../../libopentelemetry_proto.a /usr/lib64/libprotobuf.so
> /usr/bin/ld: ../../exporters/otlp/libopentelemetry_exporter_otlp_grpc.so: undefined reference to `absl::lts_20210324::Mutex::~Mutex()'
> ```
> 
> the absl libraries are in this case, at /src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/grpc-install/lib64, and cmake build is invoked as,
> 
> `cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_STANDARD=14 '-DCMAKE_PREFIX_PATH=/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/grpc/include;/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/grpc-install' -DCMAKE_LIBRARY_PATH_FLAG=/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/grpc-install/lib64 -DBUILD_SHARED_LIBS=ON -DWITH_OTLP=ON -DBUILD_TESTING=OFF`
> 
> I even tried setting LD_LIBRARY_PATH, that didn't help as well... basically the rpaths need to included custom paths

It's strange, RPATH should be added by default. Or could you try to run cmake with `-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON` to force add linking directories?

You can find more details on https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_RPATH_USE_LINK_PATH.html

**Comment by VivekSubr** [comment]
@owent unfortunately, that didn't help!

**Comment by owent** [comment]
What's your versions of gRPC and abseil-cpp? I build gRPC 1.52.0 and the abseil-cpp version in it is lts_20220623, not lts_20210324.
Do your have other abseil-cpp installed in your search paths?

**Comment by VivekSubr** [comment]
Actually, there was an old install of abseil in the VM itself... purged that and got it to work with command,

`cmake .. -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_STANDARD=14 '-DCMAKE_PREFIX_PATH=/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/grpc-install;/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/grpc-install/include' -DCMAKE_LIBRARY_PATH_FLAG=/src/cna/.build/dbg/rpm-package/opentelemetry/BUILD/grpc-install/lib64 -DBUILD_SHARED_LIBS=ON -DWITH_OTLP=ON -DWITH_OTLP_GRPC=ON -DBUILD_TESTING=OFF`

Thanks for your time!
