### ISSUE TITLE
Add CMake option to skip export and install

### ISSUE THREAD

**Issue by piratf** [open-telemetry/opentelemetry-cpp#2015]
Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry/). If so, please [open an issue on opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

**Is your feature request related to a problem?**
If so, provide a concise description of the problem.

My current project uses "FetchContent" to introduce the GRPC library and skip the Install step.
I found that this library will default "Install(Export)", which causes me to export GRPC targets too.
I want to skip "export" and "install" in this library to avoid a target name clash.

**Describe the solution you'd like**
What do you want to happen instead? What is the expected behavior?0

I would like to have the option to skip it, just like "gRPC_INSTALL_default" in the GRPC library.

**Describe alternatives you've considered**
Which alternative solutions or features have you considered?

Otherwise, I have to rename a lot of the target names of the existing project.

**Additional context**
Add any other context about the feature request here.

I'm not sure if this is a good idea, do you have any other recommendations?

**Comment by marcalff** [comment]
Thanks for the report, I think this is a valid request.

When a project uses opentelemetry-cpp to build and link with a static library, there is no need to install the opentelemetry-cpp headers and libraries with the final product, so having a way to prevent INSTALL of these artifacts is required.

**Comment by lalitb** [comment]
> When a project uses opentelemetry-cpp to build and link with a static library, there is no need to install the opentelemetry-cpp headers and libraries with the final product, so having a way to prevent INSTALL of these artifacts is required.

Agree, this is valid scenario.
