### ISSUE TITLE
Remove ubuntu-18.04 runner image dependency from CI pipeline.

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#2019]
ubunu-18.04 runner images won't be supported from April 1st 2023 as mentioned here - https://github.com/actions/runner-images/issues/6002.

ubuntu-18.04 is used in CI for testing the otel-cpp builds with GCC 4.8 compiler (the initial GCC compiler with C++11 support). As we won't have C++11 support dropped before April, it would be better to upgrade the CI pipeline. The quick fix would be to upgrade to Ubuntu 20.04, and work around the lack of GCC 4.8 by manually adding the package repositories from Xenial.

**Comment by marcalff** [comment]
This explains the failure in CI with GCC 4.8:

> To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 18.04. Builds that are scheduled to run during the brownout periods will fail.

**Comment by marcalff** [comment]
> The quick fix would be to upgrade to Ubuntu 20.04, and work around the lack of GCC 4.8 by manually adding the package repositories from Xenial.

Do we really need GCC 4.8, or just to compile with C++11 ?

How about compiling with a more recent GCC (available on Ubuntu 20.04), with -std=c++11 instead of the default ?

**Comment by ThomsonTan** [comment]
> > The quick fix would be to upgrade to Ubuntu 20.04, and work around the lack of GCC 4.8 by manually adding the package repositories from Xenial.
> 
> Do we really need GCC 4.8, or just to compile with C++11 ?
> 
> How about compiling with a more recent GCC (available on Ubuntu 20.04), with -std=c++11 instead of the default ?

I remember GCC 4.8 is still used by @owent .
https://github.com/open-telemetry/opentelemetry-cpp/issues/1830#issuecomment-1429025645

**Comment by lalitb** [comment]
> Do we really need GCC 4.8, or just to compile with C++11 ?

We do special handling for some of the scenarios GCC 4.8 fails with it's C++11 support ( regex being one of them). But yeah, if it's not easy to use GCC 4.8 over ubuntu ubuntu 20.04, we can switch to -std=c++11.
