### ISSUE TITLE
Add timeout to Exporter interface

### ISSUE THREAD

**Issue by snehilchopra** [open-telemetry/opentelemetry-cpp#203]
This issue concerns the addition of a `timeout` parameter to the exporter interface's [Export](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/include/opentelemetry/sdk/trace/exporter.h#L50) function.

This can help propagate a timeout from the processor to the configured exporter, and test for timeouts in the exporter's `Export` method as well.
 
Please let me know your thoughts on this.
@reyang @pyohannes

**Comment by pyohannes** [comment]
This is not part of the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#exportbatch). I think this should go into the spec first we add this.

The spec implies that the `Export` function should have an implicit timeout:
> Export() must not block indefinitely, there must be a reasonable upper limit after which the call must time out with an error result (Failure).

This could be set via the exporter constructor (which makes sense, because most likely one wants to have the same timeout for each call to `Export`).

However, I would prefer to leave this to vendor implementors to decide. For some a timeout might not make sense, they might just internally batch spans and asynchronously send those.

**Comment by snehilchopra** [comment]
Alright. I see your point.

However, if this is left to be vendor-specific, I believe the processor (batch or simple) doesn't need to take this into account in its testing suite, as any exporter could be configured to it?

I am talking specifically with regard to #195, in which I have an implementation of the batch processor.

**Comment by pyohannes** [comment]
> I believe the processor (batch or simple) doesn't need to take this into account in its testing suite, as any exporter could be configured to it?

Yes, that's my understanding. From processor side, you can rely that `Export()` doesn't block indefinitely and there's a reasonable upper limit after which it returns.

There can be exporters that are badly implemented and block for a long time. In that instance, the batch processor will have to drop more spans.

**Comment by snehilchopra** [comment]
> Yes, that's my understanding. From processor side, you can rely that Export() doesn't block indefinitely and there's a reasonable upper limit after which it returns.

So if I am understanding this correctly, the processor can basically treat the exporter as a blackbox that returns after a certain upper time limit (which is vendor-specific). All we have to do is check how much time it takes for the `exporter->Export()` method to return, subtract that from our timeout (say from the ForceFlush's timeout) and consequently see if we timed out or not.

Is that right? Please correct me if I am wrong.

**Comment by snehilchopra** [comment]
@pyohannes

**Comment by lalitb** [comment]
This is not in the specs, and so not supported. As @pyohannes mentioned vendor can pass this as an option to the exporter constructor, and implement this timeout implicitly.
