### ISSUE TITLE
[Logs SDK] Log Appender for spdlog

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#2046]
[spdlog](https://log4cpp.sourceforge.net/#git) is one of the commonly used logging framework for C++, and it would be good to have the logging appender for the framework using logging bridge API.

More details:

Bridge API specs - https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md
Bridge API implementation -  https://github.com/open-telemetry/opentelemetry-cpp/tree/main/api/include/opentelemetry/logs
Implementing sinks in spdlog - https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

The implementation should be part of the [opentelemetry-cpp-contrib](https://github.com/open-telemetry/opentelemetry-cpp-contrib) repo under the `instrumentation` directory.

**Comment by nirb-s1** [comment]
having a stdlog sink to OTLP (OTEL collector over HTTP or GRPC) can be awesome!

**Comment by marcalff** [comment]
Closing, this is now implemented in opentelemetry-cpp-contribs.
