### ISSUE TITLE
[CI] Add a include-what-you-use build

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#2052]
Add a [include-what-you-use](https://include-what-you-use.org/) build in CI.

**Comment by esigo** [comment]
depends on #2054.

**Comment by marcalff** [comment]
Example of bugs that include-what-you-use can fix upfront:

https://github.com/open-telemetry/opentelemetry-cpp/pull/2107

**Comment by yashaswi2000** [comment]
Hii, i would like to take this up

**Comment by esigo** [comment]
Hi @yashaswi2000, thanks for your interest. any PR would be appreciated :)
