### ISSUE TITLE
OTLP exporter assumes it must use SSL because GetOtlpDefaultIsSslEnable() is returning a wrong value

### ISSUE THREAD

**Issue by MrSparc** [open-telemetry/opentelemetry-cpp#2058]
**Describe your environment** 

- opentelemetry-cpp v1.8.3
- OTLP gRPC
- No SSL
- No OTLP env vars, just default settings 

**Steps to reproduce**
I'm facing an issue with SSL after upgrade from v1.8.2 to v1.8.3 with my gRPC telemetry.
The error is:
```
E0315 15:58:51.193959723  145649 ssl_transport_security.cc:1501] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number.
```

So debugging and comparing the behavior of both versions, I noticed that in v1.8.2 `OtlpGrpcExporterOptions` constructor is setting as default `use_ssl_credentials: false` but in the new **v1.8.3**  this default constructor is setting to `use_ssl_credentials: true`

This looks like a behaviour change introduced by this refactoring handling Boolean environment variables  https://github.com/open-telemetry/opentelemetry-cpp/pull/1982

Digging into the code to look the initialization of `use_ssl_credentials` in the constructor:
https://github.com/open-telemetry/opentelemetry-cpp/blob/15ab9ed9adb8150ff1f487a7e31303d6c12e863e/exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_exporter_options.h#L19-L25

This method  `GetOtlpDefaultIsSslEnable()` to initialize `use_ssl_credentials` is based on `GetOtlpDefaultTracesIsInsecure()`:

https://github.com/open-telemetry/opentelemetry-cpp/blob/15ab9ed9adb8150ff1f487a7e31303d6c12e863e/exporters/otlp/include/opentelemetry/exporters/otlp/otlp_environment.h#L60-L64

The issue is in the default return value of the following methods: 

- `GetOtlpDefaultTracesIsInsecure()` 
  https://github.com/open-telemetry/opentelemetry-cpp/blob/15ab9ed9adb8150ff1f487a7e31303d6c12e863e/exporters/otlp/src/otlp_environment.cc#L251
- `GetOtlpDefaultMetricsIsInsecure()` 
  https://github.com/open-telemetry/opentelemetry-cpp/blob/15ab9ed9adb8150ff1f487a7e31303d6c12e863e/exporters/otlp/src/otlp_environment.cc#L295
- `GetOtlpDefaultLogsIsInsecure()`
  https://github.com/open-telemetry/opentelemetry-cpp/blob/15ab9ed9adb8150ff1f487a7e31303d6c12e863e/exporters/otlp/src/otlp_environment.cc#L312

All these methods are returning by default  `false`  if no env vars are defined.
So a `false` return means, IS NOT insecure, then IS secure :exploding_head: 

I don't know the gRPC transpost must be by default secure or insecure, but if the default is secure then this behaviour was enforced in this version.

According to the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md): 
_Insecure: Whether to enable client transport security for the exporter's gRPC connection. This option only applies to OTLP/gRPC when an endpoint is provided without the http or https scheme_

So, if the gRPC endpoint scheme returns 'http' or 'https' as the following default, I think this value should overrided:
https://github.com/open-telemetry/opentelemetry-cpp/blob/15ab9ed9adb8150ff1f487a7e31303d6c12e863e/exporters/otlp/src/otlp_environment.cc#L78-L82

**What is the expected behavior?**
Upgrade from v1.8.2 to v1.8.3 without issues.

**What is the actual behavior?**
Upgrade to v1.8.3 wrongly assumes that gRPC connection are using SSL and fails because no certificates are defined.

**Additional context**
As workaround I need to set the env var `OTEL_EXPORTER_OTLP_INSECURE=true` in order to do not use SSL

**Comment by marcalff** [comment]
@MrSparc 

Thanks for the report, and for the detailed analysis.

> So debugging and comparing the behavior of both versions, I noticed that in v1.8.2 `OtlpGrpcExporterOptions` constructor is setting as default `use_ssl_credentials: false` but in the new **v1.8.3** this default constructor is setting to `use_ssl_credentials: true`
> 
> This looks like a behaviour change introduced by this refactoring handling Boolean environment variables #1982
> 

It is, and I am the one to blame here.

> According to the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md): _Insecure: Whether to enable client transport security for the exporter's gRPC connection. This option only applies to OTLP/gRPC when an endpoint is provided without the http or https scheme_
> 
> So, if the gRPC endpoint scheme returns 'http' or 'https' as the following default, I think this value should overrided:
> 

So, the important part is:

* **This option only applies to OTLP/gRPC when an endpoint is provided without the http or https scheme**

The evaluation of `OTEL_EXPORTER_OTLP_TRACES_INSECURE` to `false` by default is per the spec.

What was missed is that this variable should not be used if the endpoint provides an `http` or `https` scheme, because the scheme takes precedence.

This is a valid bug report.

**Comment by marcalff** [comment]
Related to this spec change:

* https://github.com/open-telemetry/opentelemetry-specification/pull/2476

**Comment by MrSparc** [comment]
Thanks @marcalff for your fast feedback and the PR proposal to improveit. 
The otel-cpp team are the best 👌 
Thanks for the amazing work all you are doing for the dev community!

**Comment by marcalff** [comment]
@MrSparc 

Thanks.

A fix is available, ready for review and test if you want to try it out:

* https://github.com/open-telemetry/opentelemetry-cpp/pull/2060

Feel free to comment on the PR.

**Comment by compoundradius** [comment]
Came here to report the same issue, but without the great analysis. Thanks!

**Comment by compoundradius** [comment]
Here to report that your fix works properly!
