### ISSUE TITLE
Zipkin example is not compiled successfully due to missing header file error

### ISSUE THREAD

**Issue by cngzhnp** [open-telemetry/opentelemetry-cpp#2068]
**Describe your environment** 
When "WITH_ZIPKIN" option is ON while compile Zipkin example, compiler complains about that "opentelemetry/exporters/zipkin/zipkin_exporter_factory.h" file not found.

**Steps to reproduce**
set(WITH_EXAMPLES ON)
set(WITH_ZIPKIN ON)

**What is the expected behavior?**
Zipkin example should be compiled successfully when its example is enabled.

**What is the actual behavior?**
Compiler error due to not found header file.

**Additional context**
Zipkin folder inside of "exporters" folder there is a CMakefile of this component. In this CMakefile, target_include_directories was not defined. In my opinion, this is a problem that needs to be fixed.

**Comment by marcalff** [comment]
This is surprising, because in the [CI] builds, the zipkin exporter example builds properly.

Below is a log taken from the clang 14 (maintainer mode) build.

```
Scanning dependencies of target example_zipkin
make[2]: Leaving directory '/home/runner/build'
make[2]: Entering directory '/home/runner/build'
[ 96%] Building CXX object examples/zipkin/CMakeFiles/example_zipkin.dir/main.cc.o
[ 96%] Linking CXX executable example_zipkin
make[2]: Leaving directory '/home/runner/build'
[ 96%] Built target example_zipkin
```

Please clarify how the build is done (with the cmake commands used), and paste the compiler error message seen.

**Comment by marcalff** [comment]
Thanks for the details. Approved the PR.
