### ISSUE TITLE
cmake can not find thrift

### ISSUE THREAD

**Issue by springile** [open-telemetry/opentelemetry-cpp#2073]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.

I'm in centos7

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

1. Build thrift and install it to /third_party/thrift/, which will have include, lib in /third_party/thrift, there is pkgconfig in lib.
2. Build opentelemetry with cmake -DBUILD_TESTING=OFF -DWITH_JAEGER=ON -DWITH_OTLP=ON -DWITH_OTLP_HTTP=ON -DWITH_OTLP_GRPC=ON -DWITH_ABSEIL=ON ..
3.  this error will come:
CMake Error at /usr/local/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Thrift (missing: Thrift_LIBRARIES Thrift_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindThrift.cmake:20 (find_package_handle_standard_args)
  exporters/jaeger/CMakeLists.txt:3 (find_package)

export PKG_CONFIG_PATH="/third_party/thrift/lib/pkgconfig:$PKG_CONFIG_PATH"

does not fix the error.

4. it works if I install thrift to /usr/local.

Please check.

Thanks.

**Comment by marcalff** [comment]
When a package is installed in a non standard location, CMake needs to be told where to look.

I think the variable to use is [CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html), not PKG_CONFIG_PATH.

Now, regarding `Jaeger`, be advised:

* `Jaeger` is documented as [DEPRECATED](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/DEPRECATED.md#jaeger-exporter).
* the `Thrift` dependency is deprecated as well
* `Jaeger` and `Thrift` are planned for [removal in July 2023](https://github.com/open-telemetry/opentelemetry-cpp/pull/2031)

**Comment by marcalff** [comment]
@springile

Please check if using `CMAKE_PREFIX_PATH` fixes the build, and let us know so this issue can be closed.

Thanks.

**Comment by springile** [comment]
Hi Marc

CMAKE_PREFIX_PATH fixes the issue.

One thing I want to tell you is that OpenTracing was working well without
CMAKE_PREFIX_PATH.

This issue has been there since we replaced opentracing with opentelemetry.

Thanks a lot.

David

**Comment by marcalff** [comment]
Thanks for the details.

Closing as resolved.
