### ISSUE TITLE
Some of CI build targets are not compiled in parallel

### ISSUE THREAD

**Issue by cngzhnp** [open-telemetry/opentelemetry-cpp#2074]
**Describe your environment** For example, when run `./ci/do_ci.sh cmake.maintainer.test` on my local machine, it takes too much time to build from scratch.

**Steps to reproduce**
run `./ci/do_ci.sh cmake.maintainer.test`

**What is the expected behavior?**
Target should be built with parallel option of make command if possible.

**What is the actual behavior?**
Some of targets in CI pipeline does not have any parallel options which takes too much time to build from scratch.

**Additional context**

**Comment by esigo** [comment]
We need to check if `make -k` works with `-j`.

**Comment by cngzhnp** [comment]
In my local environment, without parallel option it takes almost **9 minutes** to build `cmake.maintainer.test` target. 

With help of parallel build mechanism, it takes only around **2 minutes** to build. So, in my opinion it works. 

Do you think that should we also run tests in parallel?
