### ISSUE TITLE
Some of CI build targets are not compiled in parallel (Windows)

### ISSUE THREAD

**Issue by cngzhnp** [open-telemetry/opentelemetry-cpp#2077]
**Describe your environment** For example, when run ./ci/do_ci.ps1 cmake.maintainer.test on my local machine, it takes too much time to build from scratch.

**Steps to reproduce**
run ./ci/do_ci.ps1 cmake.maintainer.test

**What is the expected behavior?**
Target should be built with parallel option of make command if possible

**What is the actual behavior?**
Some of targets in CI pipeline does not have any parallel options which takes too much time to build from scratch.

**Additional context**

**Comment by owent** [comment]
In my opnion,we can use `cmake --build . -j$(nproc)` or `cmake --build . -j` instead of use `make -j`. It suppoort MSBUILD and ninja-build on windows.

**Comment by cngzhnp** [comment]
IMHO, it does not work because $(nproc) is a UNIX variable which probably is not supported by Windows environment. I believe there is another way to calculate total number of physical cores in Windows and we can put this variable here as well.

For example : `$nproc = (Get-ComputerInfo).CsNumberOfLogicalProcessors` this query result will be assigned to the variable. Afterwards, we can use `cmake --build . -j$(nproc)` like that I assume.

**Comment by lalitb** [comment]
We can also use [Ninja ](https://ninja-build.org/manual.html) to trigger parallel builds in Windows :

```
mkdir build
cd    build
cmake -G Ninja ..
cmake --build .    # this will run in parallel now
```

**Comment by malkia** [comment]
On Windows, you can rely on `NUMBER_OF_PROCESSORS` - easy to plug-in anywhere

On my machine (12 cores, 28 hyper-threaded)

```
c:\>set NUM
NUMBER_OF_PROCESSORS=28
```
