### ISSUE TITLE
Add an overload to ObservableInstrument::AddCallback to take a std::function

### ISSUE THREAD

**Issue by ashley-b** [open-telemetry/opentelemetry-cpp#2082]
**Is your feature request related to a problem?**
Current issues I find with the Observable callback are:
- It uses C style call back method
- Current interface is not type safe as it forces you to pass state via a void*
- Life times of the callback are not clear or forced to be done by the caller via RemoveCallback

**Describe the solution you'd like**
Adding method overloadeds to enable function objects as a callback
A token can be returned from AddCallback to be used to remove the callback later if required
```
class ObservableInstrument {
...
virtual CallbackToken AddCallback(std::function callback) noexcept = 0;
virtual void RemoveCallback(CallbackToken token) noexcept = 0;
....
```
This would allow for passing of lambda's
e.g
```
...
meter->AddCallback(
  [&some_varible](ObserverResult result) {
    nostd::get<nostd::shared_ptr<opentelemetry::metrics::ObserverResultT<int64_t>>>(result)-Observe(some_varible);
  }
);
...
```

**Describe alternatives you've considered**
I don't think there are any other alternatives to improve this.

**Additional context**
This could also be an opportunity to improve the calling convention of the callback
from
```
void (*)(ObserverResult, void *);
```
to
```
using ObserverResultNew = nostd::variant<int64_t, double>;
ObserverResultNew (*)();
```

Enabling callback to be concise
e.g
```
meter->AddCallback(
  [&some_varible]() -> ObserverResultNew {
    return some_varible;
  }
);
```

**Comment by lalitb** [comment]
Thanks for the suggestions. 

> It uses C style call back method

The reason behind using the C style callback is to maintain the ABI compatibility at API surface which is the primary requirement as documented here - https://github.com/open-telemetry/opentelemetry-cpp/blob/main/docs/abi-policy.md.   `std::function` is no guaranteed to be ABI complaint across different versions of given complier. We could have used [nostd::function_ref](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/nostd/function_ref.h), but I think storing function reference internally is more dangerous than function pointer. Also some of the compliers (specifically gcc4.8) was not happy with function references as class members.

> Current interface is not type safe as it forces you to pass state via a void*

The `void *` argument is not used internally by the SDK, but passed as it is without type-conversion during invoking callback. And it allows same callback to be registered for multiple instruments, as callbacks can then generate different metrics based on it's value. Callback should be aware of it's type and do appropriate conversion accordingly. Again, there is no better ABI compliant way to achieve the behavior. 

> Life times of the callback are not clear or forced to be done by the caller via RemoveCallback

I agree, though it is  clearly documented that the observable instrument should be maintained by the application, we can document the same for callback too. The assumption here was that the callback function would be part of  compiled binary code, and so have the address of code/text segment which remains always valid. But ofcourse this is not always true.

Feel free to discuss this further, and in general open for any better ABI compliant way to achieve the current behavior. Also any contribution to make it better are welcome.

**Comment by lalitb** [comment]
@ashley-b  Do you have further comments on this, or else this is good to be closed?

**Comment by lalitb** [comment]
closing based on above discussion. Please reopen if there are further questions.
