### ISSUE TITLE
Make OPENTELEMETRY_LIKELY_IF more general

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-cpp#2098]
This issue tracks the comments below to make macro `OPENTELEMETRY_LIKELY_IF` more general, and not tightly bound with if with condition.

https://github.com/open-telemetry/opentelemetry-cpp/pull/2094#discussion_r1165779909

**Comment by marcalff** [comment]
Closing, fixed by #2580
