### ISSUE TITLE
std::chrono::duration<Rep, Period>::max() compile error

### ISSUE THREAD

**Issue by ivgotcrazy** [open-telemetry/opentelemetry-cpp#2127]
**Describe your environment**

IDE: VS2022 with C++17

**Steps to reproduce**
Header file as below:
```c++
#pragma once

#include <list>
#include <memory>
#include <mutex>
#include <set>

#include "thread/common-thread.h"
#include "proxy-unknown.h"
#include "if-trace-mgr.h"

#include "opentelemetry/exporters/otlp/otlp_http_exporter_options.h"
#include "opentelemetry/trace/tracer.h"

namespace jukey::com
{

class TraceMgr : public ITraceMgr, public base::ProxyUnknown
{
public:
  TraceMgr(base::IComFactory* factory);
  ~TraceMgr();

  COMPONENT_FUNCTION_DECL
  COMPONENT_IUNKNOWN_IMPL

  // ITraceMgr
  virtual void Init() override;
  virtual SpanId StartSpan(const std::string& span_name) override;
  virtual void StopSpan(SpanId span_id) override;

private:
  struct TracerEntry
  {
    std::string trace_name;
    opentelemetry::nostd::shared_ptr<opentelemetry::trace::Tracer> tracer;
  };

private:
  opentelemetry::exporter::otlp::OtlpHttpExporterOptions m_opts;
  uint32_t m_next_span_id = 1;
  std::map<SpanId, TracerEntry> m_tracers;
  std::mutex m_mutex;
};

} // namespace
```

**What is the expected behavior?**
compile success

**What is the actual behavior?**
See attachment for compilation errors

It seems that the compiler thinks of std::chrono::duration<Rep, Period>::max() as the global max macro.

**Additional context**
![image](https://user-images.githubusercontent.com/3154075/235597955-4970df04-e7dd-49b7-93a3-320ab3c92372.png)

**Comment by ivgotcrazy** [comment]
![image](https://user-images.githubusercontent.com/3154075/235728540-0c793483-875c-4031-9f1e-696c77de086c.png)

**Comment by ivgotcrazy** [comment]
Thanks, it does indirectly include the windows.h header file. Problem solved.

**Comment by lalitb** [comment]
closed as discussed above.
