### ISSUE TITLE
How to change the port 4318 to other port for http exporter of open telemetry collector

### ISSUE THREAD

**Issue by springile** [open-telemetry/opentelemetry-cpp#2129]
Hi 

By default the port for http exporter is 4318.

Can we use other port for http exporter?

Is it configurable?

4318 may be used by other services.

Thanks

Yufei.

apiVersion: v1
kind: Namespace
metadata:
 name: opentelemetry

---
apiVersion: v1
kind: ConfigMap
metadata:
 name: otel-collector-conf
 namespace: opentelemetry
 labels:
   app: opentelemetry
   component: otel-collector-conf
data:
 otel-collector-config: |
   receivers:
     otlp:
       protocols:
         grpc:
         http:
   exporters:
     otlp/aspecto:
       endpoint: otelcol.aspecto.io:4317
       headers:
         Authorization: ${ASPECTO_API_KEY}
     jaeger:
       endpoint: jaeger-all-in-one:14250
       tls:
         insecure: true 
     logging:
   processors:
     batch:
     resource:
       attributes:
         - key: test.key
           value: "test-value"
           action: insert
   extensions:
     health_check:
     zpages:
       endpoint: :55679
   service:
     telemetry:
       logs:
         level: "debug"
     extensions: [zpages, health_check]
     pipelines:
       traces:
         receivers: [otlp]
         processors: [batch]
         exporters: [logging, jaeger, otlp/aspecto]

---
apiVersion: v1
kind: Service
metadata:
 name: otel-collector
 namespace: opentelemetry
 labels:
   app: opentelemetry
   component: otel-collector
spec:
 ports:
   - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver.
     port: 4317
     protocol: TCP
     targetPort: 4317
   - name: otlp-http # Default endpoint for OpenTelemetry HTTP receiver.
     port: 4318
     protocol: TCP
     targetPort: 4318
   - name: zpages
     port: 55679
     protocol: TCP
     targetPort: 55679
   - name: health-check
     port: 13133
     protocol: TCP
     targetPort: 13133
   - name: jaeger
     port: 16686
     protocol: TCP
     targetPort: 16686     
 selector:
   component: otel-collector
 type: LoadBalancer  

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: otel-collector
 namespace: opentelemetry
 labels:
   app: opentelemetry
   component: otel-collector
spec:
 selector:
   matchLabels:
     app: opentelemetry
     component: otel-collector
 minReadySeconds: 5
 replicas: 1
 template:
   metadata:
     namespace: opentelemetry
     labels:
       app: opentelemetry
       component: otel-collector
   spec:
     containers:
       - command:
           - '/otelcol'
           - '--config=/conf/otel-collector-config.yaml'
         env:
           - name: ASPECTO_API_KEY
             valueFrom:
               secretKeyRef:
                 name: aspecto
                 key: api-key
                 optional: false           
         image: otel/opentelemetry-collector:latest
         name: otel-collector
         resources:
           limits:
             cpu: '1'
             memory: 2Gi
           requests:
             cpu: 200m
             memory: 400Mi
         ports:
           - containerPort: 4317   #otlp grpc
           - containerPort: 4318   # otlp http
           - containerPort: 55679  # zpages
           - containerPort: 13133  # health check
         volumeMounts:
           - name: otel-collector-config-vol
             mountPath: /conf
     volumes:
       - configMap:
           name: otel-collector-conf
           items:
             - key: otel-collector-config
               path: otel-collector-config.yaml
         name: otel-collector-config-vol

**Comment by springile** [comment]
I changed 4318 to 5318 in above yaml file, it does not work, it still uses 4318.

bool Tracing::Initialize()
{
    static const wchar_t * fn(L"Tracing::initialize");

    SWItrcPrintln(NRC_TAG, fn, L"Initializing tracing");

    try {
        resource::ResourceAttributes attributes = {{"service", "test_service"}, {"version", (uint32_t)1}};
        auto resource                           = resource::Resource::Create(attributes);

        opentelemetry::exporter::otlp::OtlpHttpExporterOptions opts;
        opts.url = "http://localhost:4318/v1/traces";
        auto exporter  = otlp::OtlpHttpExporterFactory::Create(opts);
        auto processor = trace_sdk::SimpleSpanProcessorFactory::Create(std::move(exporter));
        std::shared_ptr<opentelemetry::trace::TracerProvider> provider =
            trace_sdk::TracerProviderFactory::Create(std::move(processor), resource);
        trace::Provider::SetTracerProvider(provider);        

    } catch (std::exception &e) {
        SWItrcLogError(SWITRC_WARNING_NSA, SWI_ERROR, fn, L"Failed to initialize open telemetry: %S", e.what());
        return false;
    }

    tracing_enabled = true;
    return true;

**Comment by marcalff** [comment]
Per earlier comments, the OTLP HTTP exporter port:
* can be changed programmatically
* can be changed in configuration using environment variables

No changes needed in opentelemetry-cpp, closing this issue.
