### ISSUE TITLE
How to delete some metrics from Meter?

### ISSUE THREAD

**Issue by songxing1993** [open-telemetry/opentelemetry-cpp#2131]
Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry/). If so, please [open an issue on opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

**Is your feature request related to a problem?**
If so, provide a concise description of the problem.

**Describe the solution you'd like**
What do you want to happen instead? What is the expected behavior?

**Describe alternatives you've considered**
Which alternative solutions or features have you considered?

**Additional context**
Add any other context about the feature request here.

**Comment by lalitb** [comment]
Please clarify if you want to delete the generated Measurements, or aggregated Metrics?  This is not specified in the specs, and so not supported.

**Comment by songxing1993** [comment]
> I want to delete some aggregated Metrics,but don't find associated interface. Have no idea

**Comment by lalitb** [comment]
@songxing1993  as mentioned, this is something not supported in opentelemetry specs, and so also not implemented in opentelemetry-cpp repo. Hope this answers your question.

**Comment by lalitb** [comment]
closing based on above discussion. Please reopen if there are further questions.
