### ISSUE TITLE
Update Recordable implementations to use SpanContext

### ISSUE THREAD

**Issue by nadiaciobanu** [open-telemetry/opentelemetry-cpp#214]
**Problem**
In the `Recordable` interface, links can be added by passing a `SpanContext` (containing `trace_id`, `span_id` and `trace_state`) into `AddLinks()`. Currently, `SpanContext` is not implemented, so the `SpanContext`-related fields in the links cannot be populated.

**Solution**
Update `AddLinks()` in implementations of the `Recordable` interface, including the [`OTLP Recordable`](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/exporters/otlp/src/recordable.cc) and [`SpanData`]( https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/include/opentelemetry/sdk/trace/span_data.h) to set `trace_id`, `span_id` and `trace_state` using the `SpanContext` parameter.

**Comment by lalitb** [comment]
#380 fixes it.
