### ISSUE TITLE
C++ SetAttribute() not Working properly

### ISSUE THREAD

**Issue by ZiiiSun** [open-telemetry/opentelemetry-cpp#2140]
issue happened while trying to SetAttrbute()
our project mainly uses **wstring**. Since SetAttribute() does not take wstring, we have a helper function which return a new copy of the given wstring as folloing:
`
std::string WideToUtf8(_In_ const std::wstring& inString)
`

**What is the expected behavior?**
I'm able to set attributes with value string as following code:
`Span->SetAttribute("key", "value");  // working fine`
but if im using our convertor to get a new string copy it wont work, code shown as following:
`std::wstring value = L"value"; `
`Span->SetAttribute("key", WideToUtf8(value));  // the value would either be garbled or empty` 

**I am curious why do the two above cases are acting so differently and I think it might be a bug. It would be great if anyone have suggestions on what I should do here :)**

**Comment by owent** [comment]
`SetAttribute` use string_view instead of string as argement, which means you should keep the inputed object be available and not be destroyed before this span is exported.

**Comment by ZiiiSun** [comment]
I get its taking a references, but since it is working when im pass a string like follow:
`SetAttribute("key", "value");`
but not working with;
`SetAttribute("key", HelperFunc()); // which helperfunc returns a newly copied string`

arent the above cases are the same? why does it only worked with the first case

**Comment by owent** [comment]
> I get its taking a references, but since it is working when im pass a string like follow: `SetAttribute("key", "value");` but not working with; `SetAttribute("key", HelperFunc()); // which helperfunc returns a newly copied string`
> 
> arent the above cases are the same? why does it only worked with the first case
The `"value"` in `SetAttribute("key", "value");` exists in the constant area (Maybe `.TEXT` section) of the executable program and remains valid throughout the entire lifetime of the program execution.While the return value of `HelperFunc()` will be destroyed after `SetAttribute("key", HelperFunc());`.

**Comment by lalitb** [comment]
Also to add, it depends on the exporter implementation. In most scenarios. the exporter will serialize the attribute value as part of `SetAttribute` implementation, and won't store the `value` internally for later usage. So `SetAttribute("key", HelperFunc())` will work fine with expected result. The ETW exporter is an exception, as it expects the reference to remain valid till Span is ended/exported.

**Comment by lalitb** [comment]
@ZiiiSun Do you have further questions - As mentioned earlier ETW exporter doesn't create copy of the attribute passed as reference so the attribute should exist for the lifetime of Span's export.

**Comment by lalitb** [comment]
Closing now. Please reopen if required.
