### ISSUE TITLE
Unary grpc call in otlp-grpc-exporter may lead poor cpu performance

### ISSUE THREAD

**Issue by joyeahzhang** [open-telemetry/opentelemetry-cpp#2144]
**Is your feature request related to a problem?**

I try to use batch_span_processor and otlp-grpc-exporter in the project to export the span. I found that otlp-grpc-exporter uses unary grpc call to "serialize data --> initialize request --> send --> destroy request" for each batch of export process. In my cognition, unary grpc call is inefficient, it will cause extra CPU overhead (frequent establishment and destruction of links) in the system. Unfortunately, my current system is in a situation where CPU resources are tight, so I want to find a way to reduce the CPU overhead during the span export process.

**Describe the solution you'd like**
I want to be able to use stream rpc to avoid frequent create and destroy requests.
Or there are other simpler ways to solve the problem of CPU resource shortage...

**Comment by owent** [comment]
I'm not sure the details about gRPC.But gRpc use channels to maintain connections, which is dependent from rpc call.
In my benchmark, when we create and export 50K spans and traces per second with batch processor and OTLP gRPC exporter, it cost about 16% CPU of a single core.The performance is enough to us.I'm not sure if it's acceptable in your situation?

**Comment by joyeahzhang** [comment]
> I'm not sure the details about gRPC.But gRpc use channels to maintain connections, which is dependent from rpc call. In my benchmark, when we create and export 50K spans and traces per second with batch processor and OTLP gRPC exporter, it cost about 16% CPU of a single core.The performance is enough to us.I'm not sure if it's acceptable in your situation?



@owent 
I also use the combination of batch_span_processor + otlp_grpc_exporter, but my test results in the program are very different from yours. When I create 4k span/s, then sample and export at different sample rates, I find that:
When sampling 25% and exporting (1k span/s): program CPU from 68% -> 72%
When sampling 50% and exporting (2k span/s): program CPU from 68% -> 74%
When sampling 100% and exporting (4k span/s): program CPU from 68% -> 77%
And when I create and export span at a rate of 10k/s, the situation is even worse, the overall CPU load of the program will jump from about 68% to 95%+

I hope to be able to keep the additional CPU load within 5% at a rate of 10k/s. If the performance of the exporter is as you said, I believe it can meet my needs, but now it is not the case, and I am now wondering what is not done right

**Comment by lalitb** [comment]
Just to add
 - The OTLP specs only specifies sending telemetry data as unary request - sequentially or concurrently (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlpgrpc). This most probably means that it not possible to configure OTLP collector to receive gRPC stream. Possible reason could that gRPC stream is more suited for sending large data, which is not the use case for traces. There may be a scenario where (say) the application only emit couple of batch span events in an hours interval.
 - I don't know about the gRPC internals, but if we can add support for HTTP/2 keepalive pings with Unary requests, it can have better performance if not equal to gRPC stream. As recommended here - https://grpc.io/docs/guides/performance/

**Comment by lalitb** [comment]
> And when I create and export span at a rate of 10k/s, the situation is even worse, the overall CPU load of the program will jump from about 68% to 95%+

It would be helpful to have the CPU profiling stats to see what part of pipeline is consuming the CPU. Also, what is system configuration where these tests are done ?
