### ISSUE TITLE
[Metrics API] The Record method of class Histogram now must have a context param, but in the Add method of class Counter it is optional

### ISSUE THREAD

**Issue by xieyuguang** [open-telemetry/opentelemetry-cpp#2155]
The Record method of class Histogram now must have a context param, but in the Add method of class Counter it is optional. This brings confusion to users.

**Comment by lalitb** [comment]
Yes agree, Histogram should have overload method without Context, to be consistent with other instruments. This can be accommodate as part a ABI breaking release whenever planned.
