### ISSUE TITLE
[BUILD] WITH_OTLP deprecated but removing it breaks the build

### ISSUE THREAD

**Issue by h-vetinari** [open-telemetry/opentelemetry-cpp#2160]
Even though the option `WITH_OTLP` is [deprecated](https://github.com/open-telemetry/opentelemetry-cpp/blob/v1.9.1/CMakeLists.txt#L162-L169), it's still used in [several](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-cpp+%2FWITH_OTLP%5Cb%2F&type=code) places throughout otel (including CI and docker).

Furthermore, following the deprecation warning and replacing it by `WITH_OTLP_GRPC` and/or `WITH_OTLP_HTTP` will not work, since `WITH_OTLP` is used [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/v1.9.1/exporters/CMakeLists.txt#L4-L6) to determine whether `exporters/otlp` is included (which is where `opentelemetry_exporter_otlp_{grpc,http}` are built).

**Comment by marcalff** [comment]
Fixed by PR #2161
