### ISSUE TITLE
[API] Remove Meters

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#2184]
Related to:
* https://github.com/open-telemetry/opentelemetry-specification/issues/2232
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4919 (see methods to remove an instrument and a meter)

Context

Using opentelemetry-cpp 1.9.1
Using metrics, with asynchronous instruments.
Using callbacks located in a shared library.

Use case:
- Create a Meter
- Create an asynchounous instrument
- add a callback to the instrument

Measurements are taken invoking the callback, and are exported.

Then:
- remove the callback from the instrument
- release the last instrument reference
- release the last meter reference

From this point, no new measurements are called.

The OTLP HTTP exporter however, still exports data about the metrics no longer measured, as seen in the opentelemetry-collector logs in the endpoint.

In my understanding, this is due to the aggregations used:
- sum aggregation of async counters continues, reporting a constant value
- probably likewise for gauges and the last value (not tested)
- etc

Please provide:
- in the API/SDK, an operation to remove a synchronous / asynchronous instrument from a Meter,
- in the API/SDK, an operation to remove a Meter from a MeterProvider.

so that exporters no longer report anything about defunct Meter and Metrics.

This is blocking: in practice, using Metrics with shared libraries is not possible currently with opentelemetry-cpp.

**Comment by lalitb** [comment]
Also related - **https://github.com/open-telemetry/opentelemetry-cpp/discussions/2168**. This is related to the aggregation, which probably doesn't get cleaned-up.
@marcalff - Thanks for raising the issue. If you don't have plan to work on it, should I assign it to myself. I think I will have some bandwidth during next week to fix it.

**Comment by marcalff** [comment]
Thanks @lalitb .

I am working on `Factory::Create()` methods for metrics, to get me started on this part of the code base.

Assigning to you then. I can help with testing and review.

**Comment by marcalff** [comment]
Adding the blocking tag, as using opentelemetry-cpp for metrics is not possible without this fix, when instrumenting meters in shared libraries (that can disappear upon unload)
