### ISSUE TITLE
Datadog and opentelemetry-cpp

### ISSUE THREAD

**Issue by dgoffredo** [open-telemetry/opentelemetry-cpp#2196]
Datadog is interested in integrating with opentelemetry-cpp. Previously we integrated with OpenTracing via [dd-opentracing-cpp][1]. We now have a dedicated core tracing library called [dd-trace-cpp][2] that does not implement any API.

Currently, Datadog customers can instrument their C++ code using opentelemetry-cpp and then configure the library to send traces to the Datadog Agent, which [speaks OTLP][3].

However, this precludes several Datadog-specific tracing features. An example of one such feature is the ways in which [trace sampling][4] can be configured.

Other programming language integrations, such as [Datadog's Go tracer][5], implement the "tracer" and "tracer provider" interfaces in a separate library that customers can then depend on to provide a Datadog-specific tracer for their otherwise OpenTelemetry-generic code.

Integrating with opentelemetry-cpp is important not only for customers using OpenTelemetry programmatically, but also for users of HTTP proxies whose tracing will be provided by OpenTelemetry, such as the [NGINX Ingress Controller for Kubernetes][6]. In fact, tracing support within HTTP proxies is my primary concern.

Which approach do you recommend for adapting the capabilities of [dd-trace-cpp][2] into OpenTelemetry?

I've done a cursory exploration of several options, which I'm happy to discuss here in more detail.

[1]: https://github.com/DataDog/dd-opentracing-cpp
[2]: https://github.com/DataDog/dd-trace-cpp
[3]: https://docs.datadoghq.com/opentelemetry/
[4]: https://docs.datadoghq.com/tracing/guide/ingestion_sampling_use_cases/
[5]: https://github.com/DataDog/dd-trace-go/blob/main/ddtrace/opentelemetry/example_test.go
[6]: https://github.com/kubernetes/ingress-nginx

**Comment by lalitb** [comment]
> I've done a cursory exploration of several options, which I'm happy to discuss here in more detail.

Would be interested to hear the options you have explored, either as comment here, or in general if you would like to join the community meeting to discuss further :)
As of now, you are right, there is no direct way to plugin a external Tracer object in otel-cpp SDK.

**Comment by dgoffredo** [comment]
@lalitb The two best candidates so far are:

1. Implement [TracerProvider][2] and the related interfaces in a third-party library.
    - Users of OpenTelemetry, such as [otel_ngx_module][1], include both
      opentelemetry-cpp and the third-party library in their build.
    - `main()`, or the relevant telemetry initialization function,
      optionally uses Datadog's `TracerProvider` from the third-party
      library.
    - All other user code is expressed in terms of opentelemetry-cpp's public
      API.
2. Implement `TracerProvider` and the related interfaces _within_ opentelemetry-cpp.
    - This means that [dd-trace-cpp][3] would be added to opentelemetry-cpp's
      [dependencies][4].
    - This is similar to what is done for [Event Tracing for Windows][5].
    - This approach is what is done for [Envoy][6].
    - Users need depend on opentelemtry-cpp only, and select the desired
      `TracerProvider` at runtime per (1).

All of the other options that I looked into have a similar user experience
but are technically inferior, e.g. defining a third-party [SpanProcessor][7]
that creates Datadog-specific spans in the background. Not ideal, and leaves
out control of propagation.

Another, completely different, approach would be to extend the OpenTelemetry
API so that currently-Datadog-specific features could be expressed within the
API -- the default implementations in the SDK would then also be extended to
be capable of everything done in [dd-trace-cpp][3]. I think that this would be
an unwise coupling between Datadog specifics and the larger telemetry
ecosystem.

What do you think of these approaches? How should we get Datadog aboard the
opentelemetry-cpp train?

If either (1) or (2) is viable, then I have a preference for (2). However, (1)
is what is done in [Go][8].

[1]: https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/nginx
[2]: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/trace/tracer_provider.h
[3]: https://github.com/DataDog/dd-trace-cpp
[4]: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/docs/dependencies.md
[5]: https://github.com/open-telemetry/opentelemetry-cpp/tree/main/exporters/etw
[6]: https://github.com/envoyproxy/envoy/tree/main/source/extensions/tracers/datadog
[7]: https://github.com/open-telemetry/opentelemetry-cpp/blob/fc8853e4186dae92574b6f9f3d07cb2808d83d9a/sdk/include/opentelemetry/sdk/trace/processor.h#L21
[8]: https://github.com/DataDog/dd-trace-go/blob/main/ddtrace/opentelemetry/example_test.go

**Comment by lalitb** [comment]
@dgoffredo thanks for providing the alternatives. These was also shortly discussed in community meeting. I would prefer option (1) here. The opentelemetry-cpp repo is supposed to have - API, SDK, and exporters as specified in otel specs. There are some exceptions - ETW and ElasticSearch exporters, but we plan to move them to otel-cpp-contrib repo as tracked in #1423, and #1424.

**Comment by dgoffredo** [comment]
Yes, this is good to close. I'll mention it in a future issue in opentelemetry-cpp-contrib, but we've cleared up the topic here, I think: Datadog can create its own implementation of the opentelemetry-cpp API using the opentelemetry-cpp SDK, and host the implementation in a separate repository.
