### ISSUE TITLE
OpenTelemetry's cmake file claims to publish OPENTELEMETRY_CPP_FOUND/etc. but really publishes OPENTELEMETRY-CPP_FOUND - with a dash.

### ISSUE THREAD

**Issue by niande-xbox** [open-telemetry/opentelemetry-cpp#2212]
**Describe your environment** 
Users of this library will look at the CMAKE file cmake/opentelemetry-cpp-config.cmake.in (as did [opentelemetry-cpp-contrib](https://github.com/open-telemetry/opentelemetry-cpp-contrib!) and try to use that target, but if you print CMAKE variables, you'll see that the _FOUND variable actually has the dash, which makes sense if you look at the find_package_handle_standard_args call at the bottom of [this file](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/cmake/opentelemetry-cpp-config.cmake.in).

**Steps to reproduce**
Print the CMAKE variables after running `find_package(opentelemetry-cpp CONFIG QUIET)`, and you'll see: `-- opentelemetry-cpp_FOUND=1` not `-- opentelemetry_cpp_FOUND=1`.

**What is the expected behavior?**
The documented CMAKE variables (which have an underscore rather than a dash) should match the actual CMAKE variables (with are with dashes).

**What is the actual behavior?**
They do not match.

**Additional context**
This leads to other dependent repos failing to include opentelemetry-cpp correctly.

**Comment by lalitb** [comment]
Thanks for reporting. We can probably document it here with a snippet - https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md#incorporating-into-an-existing-cmake-project. And fix the naming here - https://github.com/open-telemetry/opentelemetry-cpp/blob/049ab63103b2ede02c6f58c85927e7d4e1834807/cmake/opentelemetry-cpp-config.cmake.in#L21

**Comment by owent** [comment]
The  `<package name>_FOUND` is generated by cmake automatically, it's not always `OPENTELEMETRY-CPP_FOUND` , but may be   `opentelemetry-cpp_FOUND` when we use `find_package(opentelemetry-cpp)` . I think we can add a alias of `<package name>_FOUND` which named `OPENTELEMETRY_CPP_FOUND` .
