### ISSUE TITLE
opentelemetry-cpp vcpkg metrics

### ISSUE THREAD

**Issue by kirby-mimic** [open-telemetry/opentelemetry-cpp#2237]
I am not sure where to report this, as I believe the opentelemetry-cpp project does not produce the vcpkg package

This shows a list of opentelemetry-cpp features:

[https://vcpkg.link/ports/opentelemetry-cpp/versions](https://vcpkg.link/ports/opentelemetry-cpp/versions)
I was only using the otlp-grpc feature which works fine for normal traces, but added all features to ensure that the issue still existed.

from vcpkg.json
```
    {
      "name": "opentelemetry-cpp",
      "version>=": "1.9.1",
      "features": [ "elasticsearch", "etw", "jaeger", "otlp", "otlp-grpc", "otlp-http", "prometheus", "zipkin", "zpages" ]
    },
```
Looking at your metrics example as a guide:
[https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/otlp/grpc_metric_main.c](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/otlp/grpc_metric_main.cc)

The #include "opentelemetry/sdk/metrics/export/periodic_exporting_metric_reader_factory.h" header does not exist.

```
User@WinDev2305Eval MINGW64 ~/source/repos/MiniSpyClient/build/vcpkg_installed/x64-windows-static-md/include/opentelemetry/sdk/metrics/export (master)
$ ls -la
total 12
drwxr-xr-x 1 User 197121    0 Jul 14 12:37 ./
drwxr-xr-x 1 User 197121    0 Jul 14 12:37 ../
-rw-r--r-- 1 User 197121 1534 May 26 01:13 metric_producer.h
-rw-r--r-- 1 User 197121 2168 May 26 01:13 periodic_exporting_metric_reader.h
```

**Describe your environment** 
Windows Visual Studio x64 cmake project with vckpg.

**Steps to reproduce**
See example : https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/otlp/grpc_metric_main.cc

**What is the expected behavior?**
What did you expect to see?
Properly packaged headers.

**What is the actual behavior?**
What did you see instead?
Missing headers.
**Additional context**

**Comment by lalitb** [comment]
> I am not sure where to report this, as I believe the opentelemetry-cpp project does not produce the vcpkg package

Yes, that's correct. otel-repo doesn't officially release the vcpkg releases. For the existing vcpkg, you can use the example for otel-cpp v1.9.1 as below: 
https://github.com/open-telemetry/opentelemetry-cpp/blob/v1.9.1/examples/otlp/grpc_metric_main.cc

Or else, raise a issue in vcpkg to upgrade to newer otel-cpp version, perhaps tag the person who released the last package. Tagging @ThomsonTan as he has done vcpkg releases earlier.

**Comment by kirby-mimic** [comment]
The older example is sufficient for my needs. Thank you.
