### ISSUE TITLE
ABSL library conflicts: Reference to 'is_trivially_move_assignable' is ambiguous 

### ISSUE THREAD

**Issue by CoderPoet** [open-telemetry/opentelemetry-cpp#2238]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.

- GCC: 11.4.0
- Debian: 10

**Steps to reproduce**
Use vcpkg to install OpenTelemetry dependencies
```
{
  "name": "bug-reporter",
  "version": "0.1.0",
  "builtin-baseline": "21bbb14c4113b89cd06402e852e075341722304f",
  "dependencies": [
    {
      "name": "opentelemetry-cpp",
      "features": [
        "otlp",
        "otlp-grpc",
        "zpages",
        "prometheus"
      ]
    }
  ]
}
```

**What is the expected behavior?**
ABSL libraries no longer conflict with each other

**What is the actual behavior?**
```
Reference to 'is_trivially_move_assignable' is ambiguous 

candidate found by name lookup is 'absl::lts_20230125::is_trivially_move_assignable' 

candidate found by name lookup is 'absl::otel_v1::is_trivially_move_assignable'
```

**Additional context**

**Comment by CoderPoet** [comment]
https://github.com/microsoft/vcpkg/blob/master/ports/opentelemetry-cpp/portfile.cmake#L61

`WITH_ABSEIL=ON` does not take effect

**Comment by marcalff** [comment]
I assume the message `Reference to 'is_trivially_move_assignable' is ambiguous` is reported during the build, at compile time.

Please paste the **FULL** error message given by the compiler, including in which file/line the error occurs, and with the full include stack, so this can be investigated.

**Comment by marcalff** [comment]
Closing.

Feel free to reopen if/when more details are available, to reproduce the issue.
