### ISSUE TITLE
Log SSL Connection Information

### ISSUE THREAD

**Issue by samin36** [open-telemetry/opentelemetry-cpp#2250]
Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry/). If so, please [open an issue on opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

**Request**
I have successfully set up the HTTP metric/trace exporter to use SSL/TLS, but I am not seeing any connection specific information logged anywhere. With debug log level, I see the `[OTLP HTTP Client] Session state: connected` message, but that does not contain sufficient information.

**Describe the solution you'd like**
Upon establishing an HTTPS connection, the negotiated TLS version and the Cipher suite should be logged. Logging the entire handshake would also be nice to have for debugging purposes.

**Comment by lalitb** [comment]
libcurl verbose mode is switched off by default:
https://github.com/open-telemetry/opentelemetry-cpp/blob/8f97cab6860bae6afb9e2ba073ca35c7dd606b52/ext/src/http/client/curl/http_operation_curl.cc#L591

We can make it configurable. Though need to validate if this will also dump SSL handshake data.

**Comment by samin36** [comment]
> libcurl verbose mode is switched off by default:
> 
> https://github.com/open-telemetry/opentelemetry-cpp/blob/8f97cab6860bae6afb9e2ba073ca35c7dd606b52/ext/src/http/client/curl/http_operation_curl.cc#L591
> 
> We can make it configurable. Though need to validate if this will also dump SSL handshake data. Contributions are welcome in general to add this support.

Agree with making it configurable. We should be able to use the `CURLOPT_DEBUGFUNCTION` option to specify a callback that logs all the necessary information.

**Comment by samin36** [comment]
I can take a shot at implementing this. Sign me up!
