### ISSUE TITLE
Support to use different cmake package CONFIG of dependencies.

### ISSUE THREAD

**Issue by owent** [open-telemetry/opentelemetry-cpp#2251]
**Is your feature request related to a problem?**

Some issues (#705, #1359) was created before, and as talked in #2163, create a separate issue here.

**Describe the solution you'd like**
Patch imported target in cmake CONFIG packages to enable users to use prebuilt packages with different CONFIG settings.

**Comment by ThomsonTan** [comment]
Does this mean we patch target files from other packages?
> Patch imported target in cmake CONFIG packages to enable users to use prebuilt packages with different CONFIG settings.

**Comment by owent** [comment]
> Does this mean we patch target files from other packages?
> 
> > Patch imported target in cmake CONFIG packages to enable users to use prebuilt packages with different CONFIG settings.

For example, when user built packages with `-DCMAKE_BUILD_TYPE=RelWithDebInfo` , we can allow otel-cpp is built with `-DCMAKE_BUILD_TYPE=Debug` on Linux and macOS, and with `-DCMAKE_BUILD_TYPE=Release` on Windows.
