### ISSUE TITLE
Displays error when I execute tools\setup-buildtools.cmd

### ISSUE THREAD

**Issue by varasavelli** [open-telemetry/opentelemetry-cpp#2253]
I am installing the opentelemetry-cpp on windows 10 VM.

**Steps to reproduce**
I have just followed the steps from the document, got the error below.

PS C:\Venu\OTEL\OTLLibs\opentelemetry-cpp> tools\setup-buildtools.cmd

C:\Venu\OTEL\OTLLibs\opentelemetry-cpp>REM Copyright The OpenTelemetry Authors

C:\Venu\OTEL\OTLLibs\opentelemetry-cpp>REM SPDX-License-Identifier: Apache-2.0
Running with Administrative privilege...
Visual Studio installations detected:
C:\Program Files\Microsoft Visual Studio\2022\Professional
Building with vs2022 Professional...
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.6.5
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Using existing vcpkg installation...
Computing installation plan...
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.
Computing installation plan...
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.
Computing installation plan...
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.
Computing installation plan...
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.
Computing installation plan...
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.
Computing installation plan...
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.
Computing installation plan...
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.
Computing installation plan...
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.
Computing installation plan...
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.
Computing installation plan...
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.

**Comment by lalitb** [comment]
Doesn't look the issue with buildtool script. Can you check the vcpkg installation in you machine, if it is configured in classic mode ?

**Comment by vahw** [comment]
I do have vcpkg. I am going use these libraries in C++ projects on windows environment (Visual studio 2022). Could you please share the steps to install the libraries ?

**Comment by ThomsonTan** [comment]
@vahw have you tried to to use your local vcpkg which is probably out-of-date. You can simply try remove the path of you local vcpkg.exe from %PATH% then rerun the script tools\setup-buildtools.cmd.

**Comment by ThomsonTan** [comment]
Close it for now. Please reopen it if it happens again.
