### ISSUE TITLE
Spans are getting dropped due protobuf serializing error

### ISSUE THREAD

**Issue by mramakrishnaprasad** [open-telemetry/opentelemetry-cpp#2257]
Hi,

We are using this client library for exporting traces to opentelemetry collector using OTLP_GRPC protocol which will export the traces to Jaeger server.
Recently we have been seeing issues in exporting the traces/spans to OTEL collector with a lot of error logs indicating that the serialization of spans into a GRPC message failed.
One example error log is as below:
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:581] String field 'opentelemetry.proto.trace.v1.Span.Event.name' contains invalid UTF-8 data when serializing a protocol buffer.

We understand the issue is related to data being logged as an event to the span. The problem here is that the OTEL client library is integrated into too many applications so we are looking for some generic solution for this.

The AddEvent function is called with string arguments called by the application.

The expected behavior is that the client library should be able to serialize the data and export the spans to OTEL collector.

Kindly let us know what can be done here.

Thanks,
Rama

**Comment by esigo** [comment]
@mramakrishnaprasad This doesn't seem like an issue for OpenTelemetry library. We would need more context here.

**Comment by ThomsonTan** [comment]
@mramakrishnaprasad have you got more context on this issue?

**Comment by mramakrishnaprasad** [comment]
We have changed the communication protocol from OTLP_GRPC to OTLP_HTTP to get rid of this issue and its working.

Thanks.
