### ISSUE TITLE
Add Synchronous Gauge instrument to the metrics API/SDK

### ISSUE THREAD

**Issue by fgallegosalido** [open-telemetry/opentelemetry-cpp#2279]
Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry/). If so, please [open an issue on opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

**Is your feature request related to a problem?**
There's plenty of use cases described in the [specification issue](https://github.com/open-telemetry/opentelemetry-specification/issues/2318).

**Describe the solution you'd like**
I expect to have two new functions in the class `Meter` called `CreateInt64Gauge()` and `CreateDoubleGauge()` along with the template class `Gauge`. They should behave like the ObservableGauge instrument, but being synchronous instead of asynchronous.

**Describe alternatives you've considered**
This is described as an experimental feature in the OpenTelemetry specification: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#gauge

**Additional context**
Add any other context about the feature request here.

**Comment by lalitb** [comment]
Thanks for creating the issue. Adding for reference the Specs PR - 
https://github.com/open-telemetry/opentelemetry-specification/pull/3540 bringing this support.

**Comment by marcalff** [comment]
So:

* this is a recent addition in the spec,
* the meter API is impacted, as it needs a new virtual method,
* this makes it an ABI breaking change for C++.

We really need a plan to handle ABI changes gracefully, see #2222

**Comment by marcalff** [comment]
Depends on:

* https://github.com/open-telemetry/opentelemetry-cpp/pull/2224

which will add CI for a WITH_ABI_VERSION_2 build.
