### ISSUE TITLE
Issue when mapping OpenTelemetry MinMaxSumCount aggregator to Prometheus Gauge metric

### ISSUE THREAD

**Issue by CunjunWang** [open-telemetry/opentelemetry-cpp#228]
**Is your feature request related to a problem?**

Yes. According to the specification [here](https://github.com/jmacd/opentelemetry-specification/blob/jmacd/draft_metric_sdk_spec/specification/metrics/sdk.md#aggregator-implementations), we need to support `MinMaxSumCount` in OpenTelemetry. However, when I was translating OpenTelemetry metric data to Prometheus data type and mapping OpenTelemetry Aggregator to Prometheus, I referred to the specification [here](https://github.com/open-telemetry/oteps/blob/0839413fb5ac7aa7e22cc6f6d3bbd0d5556e822a/text/metrics/0118-statsd-and-prometheus-exporters.md#opentelemetry-aggregator-to-prometheus-exposition). The spec states we need to map `MinMaxLastSumCount` to Prometheus Gauge, and use the Last Value as the gauge metric. The problem is we don’t have a `MinMaxLastSumCount` aggregator. What we have is `MinMaxSumCount` aggregator but there is nothing can be mapped to gauge in this aggregator.

**Describe the solution you'd like**
1. Ignore this aggregator when mapping from OpenTelemetry to Prometheus for now, if possible.

2. Choose another value in the aggregator (min, max, sum, or count) to expose as the Prometheus gauge metric.

**Describe alternatives you've considered**
1. Support the `MinMaxLastSumCount` Aggregator. This is not a preferred solution because the team that implemented the aggregators will end their internship next week. It’s not a good choice to ask them add new implementations at this point.

**Comment by jmacd** [comment]
I would be happy for you to deviate from the specification, use the LastValue aggregator (to give the correct Prometheus Gauge) and let us sort this out later. The MMLSC proposal is stuck behind some OTLP negotiations, and it's possible we'll reject it and declare that LastValue is the correct default for ValueRecorder anyway.

For the sake of getting something to work, reporting (Sum/Count) is not terrible. You can see this was debated already: https://github.com/open-telemetry/opentelemetry-specification/issues/636

To be explicit, that's https://github.com/open-telemetry/oteps/pull/117 and https://github.com/open-telemetry/oteps/pull/118

**Comment by jmacd** [comment]
(sorry we didn't get to discuss this in the SIG meeting today!)

**Comment by CunjunWang** [comment]
> I would be happy for you to deviate from the specification, use the LastValue aggregator (to give the correct Prometheus Gauge) and let us sort this out later. The MMLSC proposal is stuck behind some OTLP negotiations, and it's possible we'll reject it and declare that LastValue is the correct default for ValueRecorder anyway.
> 
> For the sake of getting something to work, reporting (Sum/Count) is not terrible. You can see this was debated already: [open-telemetry/opentelemetry-specification#636](https://github.com/open-telemetry/opentelemetry-specification/issues/636)
> 
> To be explicit, that's [open-telemetry/oteps#117](https://github.com/open-telemetry/oteps/pull/117) and [open-telemetry/oteps#118](https://github.com/open-telemetry/oteps/pull/118)

Thanks for your reply! I will use sum as a gauge at the current stage. If there is any update, I will modify my implementation then.

**Comment by erichsueh3** [comment]
Hi @jmacd, just wanted to clarify on whether you mean Sum/Count as "Sum or Count", or as the average, "Sum divided by Count". I notice in the debate in [#636](https://github.com/open-telemetry/opentelemetry-specification/issues/636) you mentioned Sum/Count as an average, but we just wanted to make sure here as well.
