### ISSUE TITLE
[security] audit repository tooling

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-cpp#2282]
The security SIG is looking to ensure that security tooling is setup consistently across the organization. As a result, we're asking maintainers to ensure the following tools are enabled in each repository:

- [X] CodeQL enabled via [GitHub Actions](https://github.com/open-telemetry/opentelemetry-collector/blob/main/.github/workflows/codeql-analysis.yml) - enabled in opentelemetry-cpp here [GitHub Actions](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/.github/workflows/codeql-analysis.yml)
- [X] Static code analysis tool - missing, see #2297
- [X] Repository security settings
    - [X] Security Policy ✅ - enabled
    - [X] Security advisories ✅ - enabled
    - [X] Private vulnerability reporting ✅ - enabled
    - [X] Dependabot alerts ✅ - enabled
    - [X] Code scanning alerts ✅ - enabled

Parent issue: https://github.com/open-telemetry/sig-security/issues/12

**Comment by sakshi-1505** [comment]
@codeboten  I am an Outreachy candidate, can you please assign me this issue?

**Comment by codeboten** [comment]
Thanks @sakshi-1505, i don't have the ability to assign issues in this repo. @marcalff are you still working on this issue? would @sakshi-1505 be able to help? Thanks!

**Comment by sakshi-1505** [comment]
Not stale

**Comment by marcalff** [comment]
The last remaining part was to implement cppcheck in CI, which is now done.

Closing as completed.
