### ISSUE TITLE
Prometheus exporter does not add _total suffixes to counters

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-cpp#2287]
**What is the expected behavior?**

From https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#sums: 

> If the metric name for monotonic Sum metric points does not end in a suffix of _total a suffix of _total MUST be added by default, otherwise the name MUST remain unchanged. Exporters SHOULD provide a configuration option to disable the addition of _total suffixes.

**What is the actual behavior?**

Based on the unit test here: 

https://github.com/open-telemetry/opentelemetry-cpp/blob/f52ec6caded074437658643566bed0d83152a78a/exporters/prometheus/test/exporter_utils_test.cc#L107-L119

The counter metric does not have a `_total` suffix appended.

**Comment by marcalff** [comment]
Thanks for the report.

@esigo Sounds in the same area as #2213, please take a look.

**Comment by dashpole** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-cpp/pull/2213
