### ISSUE TITLE
[REMOVAL] Remove ZPAGES

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#2292]
Follow up on:

* https://github.com/open-telemetry/opentelemetry-cpp/pull/2291

Removal date tentative, pending discussion on deprecation pr.

Upon removal, close the following issues:

* #2271
* #184
* #166

Upon removal, file an issue on the specifications to remove C++ from the zpage spec (and possibly remove the zpage spec entirely)

**Comment by esigo** [comment]
to be removed after 1.13 release

**Comment by marcalff** [comment]
Actually, deprecation was done in release 1.12.0, so removal in 1.13.0 is ok.

Removal to occur after 1.13.0 is:
* #2383
