### ISSUE TITLE
[SDK] Allow metric instrument names to contain / characters

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#2303]
Once the following spec change is merged:
* https://github.com/open-telemetry/opentelemetry-specification/issues/3422

adjust the SDK to accept metric names with the new rules.

**Comment by lalitb** [comment]
nit - shouldn't be a bug ?

**Comment by ThomsonTan** [comment]
> nit - should it have a bug label?

Probably better to apply the spec-compliance label?
