### ISSUE TITLE
Prometheus exporter adds underscore suffix for metrics without unit

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-cpp#2317]
**Steps to reproduce**

If a metric does not have a unit set, the prometheus exporter will add an extra `_` suffix to the metric.  I have only second-hand knowledge of the issue, and don't have reproduction steps.

**What is the expected behavior?**

If the unit is empty, the name should not have an underscore or unit suffix added.

**What is the actual behavior?**

The metric `grpc.client.attempt.started` without a unit turns into:

```
# TYPE grpc_client_attempt_started_ counter
grpc_client_attempt_started_{grpc_method="grpc.testing.TestService/UnaryCall",grpc_target="dns:///10.52.1.55:14285"} 10 1694819876572
```

I believe this is because of this line: https://github.com/open-telemetry/opentelemetry-cpp/blob/0563a71ce3ea2c580f535996aeb8ce9246f2d703/exporters/prometheus/src/exporter_utils.cc#L45

We append an underscore regardless of if the unit is empty or not.

**Comment by yashykt** [comment]
This was seen on gRPC C++'s OTel plugin, but the pattern of usage is nothing out of the ordinary from what I understand. Reference - https://github.com/grpc/grpc/blob/62521a889fe134859aed7bdf4ea0730534f15d09/src/cpp/ext/otel/otel_plugin.cc#L170

A Meter with the name "grpc" was created, and a counter instrument with the name "grpc.client.attempt.started" was created out of it.

The counter was incremented like so - https://github.com/grpc/grpc/blob/62521a889fe134859aed7bdf4ea0730534f15d09/src/cpp/ext/otel/otel_client_filter.cc#L122
