### ISSUE TITLE
Changes to CONTRIBUTING.md to pass Cl/Format Check on PRs

### ISSUE THREAD

**Issue by snehilchopra** [open-telemetry/opentelemetry-cpp#233]
**Context**
There is currently a CircleCI check that checks for the proper format of all files in a PR using the tools clang-format, cmake-format, and buildifier.

**Problem**
In #195, I had been continuously failing this check.
![image](https://user-images.githubusercontent.com/31712484/88964489-50a57180-d25e-11ea-8860-4b51193f7ce6.png)

After looking at [CONTRIBUTING.md](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/CONTRIBUTING.md#how-to-send-pull-requests), it came to my notice that all contributors MUST run `tools/format.sh` BEFORE committing their changes. That script uses the 3 tools mentioned above to auto-format the files, and this might lead to a failure of the CI/Format check if the contributor has a different version of any of those tools installed locally than what it actually used in the check.

**Solution**
As is seen from the picture above, the check uses `clang-format version 8.0.0-3~ubuntu18.04.2 (tags/RELEASE_800/final)` and `cmake-format version 0.6.5.`.

Before installing these versions, make sure to uninstall any previous versions. You can use the following commands to do so
```
pip/pip3 uninstall clang-format
pip/pip3 uninstall cmake-format

sudo apt-get remove clang-format
sudo apt-get purge clang-format
```

For installing cmake_format 0.6.5., run
```
pip/pip3 install cmake-format==0.6.5.
```
For installing the appropriate version of clang-format, 
```
# Linux 
sudo apt-get install clang-format-8

# MacOS
brew install clang-format

# Using pip/pip3
pip/pip3 install clang-format==8.0.1
```

*NOTE:* On Linux, after installation, make sure to add both tools to your $PATH using the `export` command. See [this](https://linuxize.com/post/how-to-add-directory-to-path-in-linux/) on how to do so.

**Comment by snehilchopra** [comment]
@pyohannes @reyang @maxgolov It seems that a couple of people are facing this error. I was wondering whether I could get your insight on this and make the necessary changes to CONTRIBUTING.md file.

**Comment by jajanet** [comment]
It may be useful to add instructions for removing the old version of clang-format:
```
sudo apt-get remove clang-format
sudo apt-get purge clang-format
```
---------------

Also, maybe the command for running clang-format, which should be ran within the directory to be formatted

clang-format:
```
find . -regex '.*\.\(cpp\|hpp\|cu\|c\|h\)' -exec clang-format -style=file -i {} \;
```


clang-format-8 (installed using the Linux instruction above):
```
find . -regex '.*\.\(cpp\|hpp\|cu\|c\|h\)' -exec clang-format-8 -style=file -i {} \;
```

**Comment by snehilchopra** [comment]
Thanks for adding the uninstall instructions. 
For running the clang-format-8 tool, I think `tools/format.sh` from the root directory should suffice.

**Comment by jajanet** [comment]
Gotcha, that makes sense! I mentioned and ran the clang-format-8 command because `tools/format.sh` didn't work for me when installing clang-format-8 using `sudo apt-get install clang-format-8`. Either way, thanks for the help!

**Comment by snehilchopra** [comment]
Did `tools/format.sh` not recognize `clang-format-8`? 
If so, please look at issue again, towards the end. I have added the fix for that too.

**Comment by pyohannes** [comment]
Sorry, I'm late to have a look at this.

You can run the format task in a provided docker container. This should guarantee to consistent versions of tools used:
```
./ci/run_docker.sh ./ci/do_ci.sh format
```

**Comment by snehilchopra** [comment]
I did try running that, but I don't think it actually 'formats' your code. I believe it just tells you which files are not correctly formatted.

**Comment by pyohannes** [comment]
>  I believe it just tells you which files are not correctly formatted.

It actually should format the files.

**Comment by snehilchopra** [comment]
I see. It actually didn't end up formatting for me before.
I'll try it again and get back to you.

Thanks for the input!

**Comment by lalitb** [comment]
Closing - as `./ci/do_ci.sh format` does actual formatting.
