### ISSUE TITLE
How to get attribute from span

### ISSUE THREAD

**Issue by HolyMiss** [open-telemetry/opentelemetry-cpp#2345]
![image](https://github.com/open-telemetry/opentelemetry-cpp/assets/39044037/69410fb4-de3b-4f91-9c96-5b4e649affe1)
 The current Span class only provides the SetAttribute method. What should I do if I want to get the attributes in span in the Propagater I implemented?

**Comment by lalitb** [comment]
otel-cpp doesn't provide [Readable Span](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#additional-span-interfaces) interface. To optimize performance, the SDK implementation avoids keeping an intermediate copy of the attributes passed via `Span::SetAttribute()`, opting instead to serialize them directly to the exporter format. This approach complicates the provision of a Readable Span. Previous discussions on this topic can be found in issues #2108 and #1475.

**Comment by lalitb** [comment]
@HolyMiss - Do you have further questions, or the issue can be closed based on above reasoning ?

**Comment by HolyMiss** [comment]
> @HolyMiss - Do you have further questions, or the issue can be closed based on above reasoning ?

no thanks!
