### ISSUE TITLE
[OTLP Exporter] Add gzip compression support for OTLP/HTTP and OTLP/gRPC exporter.

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#2351]
As documented in Specs - https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#opentelemetry-protocol-exporter

```
Compression: Compression key for supported compression types. Supported compression: gzip.

Default: No value [2]
Env vars: OTEL_EXPORTER_OTLP_COMPRESSION OTEL_EXPORTER_OTLP_TRACES_COMPRESSION OTEL_EXPORTER_OTLP_METRICS_COMPRESSION OTEL_EXPORTER_OTLP_LOGS_COMPRESSION
```

High level changes for OTLP HTTP Exporter:
 - Add compression option (gzip/none) in [OtlpHttpExporterOptions](https://github.com/open-telemetry/opentelemetry-cpp/blob/11d5d9e0d8fd8ba876c8994714cc2647479b6574/exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_exporter_options.h#L24C8-L24C31), [OtlpHttpLogRecordExporterOptions](https://github.com/open-telemetry/opentelemetry-cpp/blob/11d5d9e0d8fd8ba876c8994714cc2647479b6574/exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_log_record_exporter_options.h#L24), [OtlpHttpMetricExporterOptions](https://github.com/open-telemetry/opentelemetry-cpp/blob/11d5d9e0d8fd8ba876c8994714cc2647479b6574/exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_metric_exporter_options.h#L24C8-L24C37). Default is `none`.
 - Modify [ext::http::client::curl](https://github.com/open-telemetry/opentelemetry-cpp/tree/v1.11.0/ext/include/opentelemetry/ext/http/client/curl) to 
     - If compression option is enabled,
         -  Make a HEAD request to server to validate if  `gzip` encoding is accepted. ( ? )
                - If accepted, compress the data using `zlib`, and set `Content-Encoding: gzip` header.
                - If not accepted, send uncompressed data and log a warning
     - If compression option is not enabled,
         -  send uncompressed data to server as done now. 

High level changes for OTLP gRPC Exporter:

- Add compression option (gzip/none) in [OtlpGrpcExporterOptions](https://github.com/open-telemetry/opentelemetry-cpp/blob/11d5d9e0d8fd8ba876c8994714cc2647479b6574/exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_exporter_options.h#L19C8-L19C31). Default is `none`.
- Modify [OtlpGrpcClient::MakeChannel](https://github.com/open-telemetry/opentelemetry-cpp/blob/11d5d9e0d8fd8ba876c8994714cc2647479b6574/exporters/otlp/src/otlp_grpc_client.cc#L51) to set the compression algorithm for the channel if enabled. Refer gRPC compression example here - https://github.com/grpc/grpc/blob/master/examples/cpp/compression/README.md#writing-a-client-and-a-server.

**Comment by perhapsmaple** [comment]
Hi @lalitb, I'm interested in working on this issue.  It seems quite easy to add gzip compression to a ``grpc::Channel``. However, I'm a little confused about the Http part. As far as I can understand, we have to send a curl request with the ``CURL_ACCEPT_ENCODING`` set to "gzip", and check the server's response for a ``Content-Encoding`` header.  Do we have to do this once in ``OtlpHttpClient`` before Posting data or do we have to modify ``ext::http::client`` to send a HEAD request and wait for a response from the server before every POST request. I'm new to curl so I may have gotten some things incorrectly. Any help regarding this is appreciated.
Thanks
