### ISSUE TITLE
Remove `WITH_REMOVE_METER_PREVIEW`, use `WITH_ABI_VERSION_2` instead

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#2363]
The feature `WITH_REMOVE_METER_PREVIEW` was implemented before ABI version 2 was defined.

It makes no sense to keep `WITH_REMOVE_METER_PREVIEW` now,
rework CMakeLists.txt to expose this feature in `WITH_ABI_VERSION_2`.

**Comment by lalitb** [comment]
Agree

**Comment by IamVishalSharma** [comment]
@marcalff  Could you please tell how i can build for:   ENABLE_REMOVE_METER_PREVIEW. i was trying below
 sudo cmake .. -DBUILD_SHARED_LIBS=ON -DWITH_OTLP_GRPC=ON -DWITH_OTLP_HTTP=ON -DWITH_PROMETHEUS=OFF -DBUILD_TESTING=OFF -DWITH_EXAMPLES_HTTP=ON -DWITH_ABSEIL=ON **-DENABLE_REMOVE_METER_PREVIEW=ON**

**Comment by marcalff** [comment]
The option name is `WITH_REMOVE_METER_PREVIEW`, see:

https://github.com/open-telemetry/opentelemetry-cpp/blob/main/CMakeLists.txt#L233-L239

To use it from CMake, use `-DWITH_REMOVE_METER_PREVIEW=ON`
