### ISSUE TITLE
Make `WITH_OTLP_HTTP_SSL_PREVIEW` mainstream

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#2365]
To discuss.

HTTP SSL support has been stable for a while.

The preview flag can be removed, and the code be mainstream (without ifdef).

This will decrease the overall complexity, and simplify CI builds.

Likewise for `WITH_OTLP_HTTP_SSL_TLS_PREVIEW`.

**Comment by lalitb** [comment]
Agree

**Comment by kkuehl** [comment]
Successfully using in production for weeks.

**Comment by marcalff** [comment]
> Successfully using in production for weeks.

@kkuehl Thanks for the feedback, this is good to know.

When nothing is reported, we are in the dark and left to wonder if a feature is working just fine or if it is not even used.

Making this mainstream then.
