### ISSUE TITLE
grpc v1.56.2 support

### ISSUE THREAD

**Issue by jhl07** [open-telemetry/opentelemetry-cpp#2374]
**Is your feature request related to a problem?**
My project needs grpc v1.56.2 cpp library linking with opentelemetry-cpp.

**Describe the solution you'd like**
I confirmed that the connection works well in opentelemetry-cpp v1.11.0 with MT,MTd build in vs2022 build environment, using grpc v1.39.0.

**Describe alternatives you've considered**
Compatible with grpc v1.56.2.

**Additional context**
And if possible, it would be nice to have the option to disable the SSL feature in the WITH_OTLP_GRPC option.

Thanks.

**Comment by owent** [comment]
You can use your own prebuilt libraries by set `CMAKE_PACKAGE_PATH` when building otel-cpp with cmake.

**Comment by marcalff** [comment]
With `CMake`, opentelemetry-cpp supports a bring-your-own dependency model.

Installing a grpc package to use in the build should work, please let us know if there are specific issues.

As for disabling SSL at build time, there are no such options.

**Comment by jhl07** [comment]
Referring to issue https://github.com/open-telemetry/opentelemetry-cpp/pull/2163,
I set all profobuf, gRPC, absl cmake find package paths to gRPC v1.56.2 version,
then lib build succeeded and ran well.
Thanks!

**Comment by marcalff** [comment]
@jhl07 Thanks for the update.

Closing this issue then.
