### ISSUE TITLE
 Change default port for OTLP exporter #968 

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-cpp#239]
By default the collector OTLP receiver is configured on port `55680`, the current default port in the OTLP exporter is still using the old OpenCensus receiver port. (`55678`) This should be changed.

**Comment by nadiaciobanu** [comment]
I can fix this!

**Comment by nadiaciobanu** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-cpp/pull/295

**Comment by codeboten** [comment]
Thanks for fixing @nadiaciobanu!
