### ISSUE TITLE
CURL issue

### ISSUE THREAD

**Issue by mclarsen** [open-telemetry/opentelemetry-cpp#2411]
I hit a runtime issue using the http exporter. 

Version: opentelemetry-cpp-1.12.0
Curl version: curl 7.68.0
OS: ubuntu 20.04 LTS

Error: `[Error] File: external/io_opentelemetry_cpp/ext/src/http/client/curl/http_operation_curl.cc:533 CURL, set option <20312> failed: <An unknown option was passed in to libcurl>` 

I tracked that option to `CURLOPT_PREREQFUNCTION`.

Relevant code:
https://github.com/open-telemetry/opentelemetry-cpp/blob/cb603ad97f33e52340e627e1cb43ba73bb1d7ef0/ext/src/http/client/curl/http_operation_curl.cc#L1057

The two curl options protected by this`#ifdef` were introduced in curl v 7.80 (https://curl.se/libcurl/c/CURLOPT_PREREQFUNCTION.html and https://curl.se/libcurl/c/CURLOPT_PREREQDATA.html). 

I think all that needs to be done is to bump the version in the ifdef.

**Comment by marcalff** [comment]
Please note that:
```
#if LIBCURL_VERSION_NUM >= 0x075000 
```

uses an hexadecimal notation, so 0x075000 actually means 0x07.0x50.0x00, which is 7.80.0 (in decimal).

The version check looks correct and matches the CURL documentation.

**Comment by marcalff** [comment]
Please check that the build uses the curl headers and the curl library from the same version.

It looks like:
- the build somehow used curl headers >= 7.80.0
- the build linked with Curl version: curl 7.68.0

If this is the case, option CURLOPT_PREREQFUNCTION is indeed missing in Curl library 7.68.0,
causing the error seen.

**Comment by mclarsen** [comment]
Ah, thanks for the explanation. Your suspicion was correct. I printed the version number number in the code and its a library mismatch.
