### ISSUE TITLE
Otel threads spawn before "main" impact signal handling

### ISSUE THREAD

**Issue by nleclercq** [open-telemetry/opentelemetry-cpp#2445]
Its seems that otel-ccp spawn some threads even before the `main` function is executed. 
That's at least  true when the instrumented application is linked against when the `otlp_grpc_exporter`.
Placing a breakpoint at the entry of `main`, we clearly see that 3 gRPC threads are already there. I guess they are spawn by hook executed when the shared library is loaded. 

The problem is that this behavior as an impact on the signal handling mechanism implemented by our (shared) library. It, in fact, prevents our handler from behind called.

**Comment by lalitb** [comment]
@nleclercq  - Can you share the stack trace, to understand the origin of threads. Also if you have the self-contained reproduction. otlp_grpc_exporter doesn't spawn any threads as of now (till #2407 is not merged). Batch span processor creates a worked thread during initialization, but it won't be before main unless you are creating a static/global instance of the processor.  But all theory for now, will wait for more details from your side :)

**Comment by nleclercq** [comment]
Damned! I actually have a singleton statically initialized as a global variable which makes a call to `opentelemetry::exporter::otlp::OtlpGrpcExporterFactory::Create`. I should have identified it as a potential source of the problem. Thanks for pointing this out. I'm going to switch to an explicit instantiation and see if it solves the problem. Stay tuned.

**Comment by nleclercq** [comment]
Ok. Switching to an explicit instantiation solves the problem. Thanks. I think we can close this issue.

**Comment by nleclercq** [comment]
Ok. Switching to an explicit instantiation solves the problem. Thanks. I think we can close this issue.

**Comment by owent** [comment]
> @nleclercq - Can you share the stack trace, to understand the origin of threads. Also if you have the self-contained reproduction. otlp_grpc_exporter doesn't spawn any threads as of now (until #2407 is merged). Batch span processor creates a worked thread during initialization, but it won't be before main unless you are creating a static/global instance of the processor. But all theory for now, will wait for more details from your side :)

#2407 do not spawn any thread, it will reuse the background threads of gRPC, and they are also created during or after initialization.
