### ISSUE TITLE
Wshadow error in `function_ref.h` 

### ISSUE THREAD

**Issue by sfc-gh-sili** [open-telemetry/opentelemetry-cpp#2495]
**Describe your environment**

CentoOS

**Steps to reproduce**

Compile with clang

**What is the actual behavior?**

```
bazel-out/aarch64-fastbuild-clang-tidy/bin/external/io_opentelemetry_cpp/api/_virtual_includes/api/opentelemetry/nostd/function_ref.h:38:26: error: declaration shadows a field of 'function_ref<type-parameter-0-0 (type-parameter-0-1...)>' [-Werror,-Wshadow]
    invoker_  = [](void *callable_, Args... args) -> R {
                         ^
bazel-out/aarch64-fastbuild-clang-tidy/bin/external/io_opentelemetry_cpp/api/_virtual_includes/api/opentelemetry/nostd/function_ref.h:28:9: note: previous declaration is here
  void *callable_                = nullptr;
        ^
bazel-out/aarch64-fastbuild-clang-tidy/bin/external/io_opentelemetry_cpp/api/_virtual_includes/api/opentelemetry/nostd/function_ref.h:52:26: error: declaration shadows a field of 'function_ref<type-parameter-0-0 (type-parameter-0-1...)>' [-Werror,-Wshadow]
    invoker_  = [](void *callable_, Args... args) -> R {
                         ^
bazel-out/aarch64-fastbuild-clang-tidy/bin/external/io_opentelemetry_cpp/api/_virtual_includes/api/opentelemetry/nostd/function_ref.h:28:9: note: previous declaration is here
  void *callable_                = nullptr;
```

Clang is complaining about shadowing declaration in `function_ref.h`

**Comment by marcalff** [comment]
Thanks for the report.

This looks valid, based on code review.

Please clarify which version of clang is used, and which compiling options are used if possible.

It will help to figure out why our CI did not catch this, as there are special builds with clang to detect all warnings, and somehow this was not caught.

**Comment by sfc-gh-sili** [comment]
I believe the flag `-Wshadow` combined with `-Werror` is what triggers this error message. I didn't find anything related to shadowing in our options though.

**Comment by owent** [comment]
Thanks, I also meet similar warnings with some old compilers in other repos before.
And I just raise a PR to fix this.
