### ISSUE TITLE
OpentTelemetry-Cpp vcpkg package includes gRPC and Protobuf when configured with the otlp-http option.

### ISSUE THREAD

**Issue by LarryOsterman** [open-telemetry/opentelemetry-cpp#2536]
**Describe your environment** 

Installing opentelemetry-cpp using the vcpkg package management system, specifying the "otlp-http" feature.

**Steps to reproduce**

Configure OpenTelemetry specifying the otlp-http feature:
```json
    {
      "name": "opentelemetry-cpp",
      "features": ["otlp-http"],
      "platform": "!(windows & !static)",
      "version>=": "1.3.0"
    },
```

**What is the expected behavior?**
OpenTelemetry otlp exporter in installed with no additional dependencies beyond curl.

**What is the actual behavior?**
OpenTelemetry is installed with:
```
 vcpkg depend-info  opentelemetry-cpp[otlp-http]
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Fetching registry information from https://github.com/microsoft/vcpkg (HEAD)...
vcpkg-cmake:
vcpkg-cmake-config:
abseil: vcpkg-cmake, vcpkg-cmake-config
protobuf: vcpkg-cmake, vcpkg-cmake-config
vcpkg-cmake-get-vars: vcpkg-cmake
c-ares: vcpkg-cmake, vcpkg-cmake-config
openssl: vcpkg-cmake, vcpkg-cmake-config, vcpkg-cmake-get-vars
re2: abseil, vcpkg-cmake, vcpkg-cmake-config
upb[codegen]: abseil, protobuf, vcpkg-cmake, vcpkg-cmake-config
zlib: vcpkg-cmake
curl[non-http, ssl, schannel, sspi]: vcpkg-cmake, vcpkg-cmake-config, zlib
grpc[codegen]: abseil, c-ares, openssl, protobuf, re2, upb, vcpkg-cmake, vcpkg-cmake-config, zlib
nlohmann-json: vcpkg-cmake, vcpkg-cmake-config
opentelemetry-cpp[otlp, otlp-http, otlp-grpc]: abseil, curl, grpc, nlohmann-json, vcpkg-cmake, vcpkg-cmake-config
```

There should be no reason for protobuf or grpc when configuring the http feature.

**Comment by ThomsonTan** [comment]
@LarryOsterman thanks for reporting this.

Which version of vcpkg are you using? The gRPC dependence has been removed from otlp-http feature in some recent vcpkg ports improvement.

https://github.com/microsoft/vcpkg/blob/a56d892ac792797d779eae79d3423e0131422628/ports/opentelemetry-cpp/vcpkg.json#L47

**Comment by LarryOsterman** [comment]
@#$ - Our baseline commit is 43cf47eccfbe27006cf9534a5db809798f8c37fe, which is from November of 2023.

Sorry for that.
