### ISSUE TITLE
Observable Metrics have no attributes

### ISSUE THREAD

**Issue by dufferzafar** [open-telemetry/opentelemetry-cpp#2555]
**Describe your environment** 

Doing this on Linux, with only metrics examples, with latest Git branch (v1.14)

**Steps to reproduce**
Compile `metrics_simple` example with this patch:

```patch
--- a/examples/common/metrics_foo_library/foo_library.cc
+++ b/examples/common/metrics_foo_library/foo_library.cc
@@ -42,7 +42,7 @@ class MeasurementFetcher
       value_ += random_incr;
       nostd::get<nostd::shared_ptr<opentelemetry::metrics::ObserverResultT<double>>>(
           observer_result)
-          ->Observe(value_ /*, labelkv */);
+          ->Observe(value_, {{"key", "value"}});
     }
   }
   static double value_;
```

**What is the expected behavior?**
Key Value attributes should be printed to screen.

**What is the actual behavior?**

No attributes!

```
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Mon Feb 26 19:14:55 2024
  end time      : Mon Feb 26 19:14:56 2024
  instrument name       : ostream_metric_example_observable_counter
  description   :
  unit          :
  type          : SumPointData
  value         : 4.1
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.14.1
}
```

**Additional context**

This is ONLY happening with Observable Counter & Gauge. Not with normal sync counters / histograms.

**Comment by dufferzafar** [comment]
I just went through the issue log, and it seems this is dupe of #2548, so I guess this can be closed?

**Comment by lalitb** [comment]
yeah, it's duplicate and can be closed.. I am going to look into the original issue today.

**Comment by dufferzafar** [comment]
@lalitb I just went through the commit https://github.com/open-telemetry/opentelemetry-cpp/commit/cf5cdaae860934469ae99826939f4f583674a836 to try to see what's breaking, but I'm too new to this 😅 

My understanding is that we changed all MetricAttributes to be Filtered now, made a change to the `sync_metric_storage`, but no corresponding to `async_metric_storage` I guess?

**Comment by lalitb** [comment]
@dufferzafar Can you reply here https://github.com/open-telemetry/opentelemetry-cpp/issues/2548#issuecomment-1965453377 - as seems I am missing something in repro :)
