### ISSUE TITLE
no support for OTEL_SERVICE_NAME

### ISSUE THREAD

**Issue by willie** [open-telemetry/opentelemetry-cpp#2559]
`OTEL_SERVICE_NAME` in the [SDK configuration documentation](https://opentelemetry.io/docs/languages/sdk-configuration/general/) sets the value of the [`service.name`](https://opentelemetry.io/docs/specs/semconv/resource/#service) resource attribute.

It appears that the C++ library does not implement `OTEL_SERVICE_NAME`, so `service.name` never gets defined.

**Comment by lalitb** [comment]
The support for environment variable is optional as per the [specs](https://github.com/open-telemetry/opentelemetry-specification/blob/ff66b248d5f746651008fb87ce7d672d12991a96/spec-compliance-matrix.md#environment-variables). You can specify service name directly as the resource attribute in config, or through the environment OTEL_RESOURCE_ATTRIBUTES.

**Comment by willie** [comment]
I guess that is a bug in the SDK docs then, as it doesn't mention any of the environmental variables as optional.

**Comment by lmolkova** [comment]
I understand that spec [indeed says](https://github.com/open-telemetry/opentelemetry-specification/blob/4f71c1642e541220e293bacf8c0d58f1fbcd3111/specification/configuration/sdk-environment-variables.md?plain=1#L15) that env var support is optional

> Implementations MAY choose to allow configuration via the environment variables in this specification, but are not required to.
If they do, they SHOULD use the names listed in this document.

At the same time OTEL_SERVICE_NAME env var is support by almost every lang impl and simplifies using otel. Please do consider keeping the issue open to get user feedback and evaluate if it's needed.

This is something we stumbled on when using otel in our Azure SDKs for C++ and it's unfortunate that c++ otel configuration is inconsistent with other langauges.
