### ISSUE TITLE
Schema URL inconsistently exported

### ISSUE THREAD

**Issue by samin36** [open-telemetry/opentelemetry-cpp#2569]
**Describe your environment** 
Opentelemetry-cpp v1.12.0 on Ubuntu 18

**Steps to reproduce**
Specify `schema_url` to the `GetMeter`, `GetTracer`, and `Resource::Create` functions and set up Tracer/Meter providers to export using the OTLP HTTP exporters.

**What is the expected behavior?**
The exported metrics and traces should contain the `schema_url`.

**What is the actual behavior?**
Only the exported traces contain the `schema_url`. The exported metric data does not contain the `schema_url`.

**Additional context**
I verified this by using the `logging` exporter in the Opentelemetry-Collector, which prints the metric/tracing data. I also set up a dummy HTTP server to log all incoming data at `/v1/metrics` and `/v1/traces` endpoint and only saw the `schema_url` for the tracing data.

**Comment by lalitb** [comment]
Thanks for the issue. The schema_url is not getting populated for metrics here: [OtlpMetricUtils::PopulateResourceMetrics()](https://github.com/open-telemetry/opentelemetry-cpp/blob/07f6cb54ece56691dbd2a94b0cbeec722ff6a631/exporters/otlp/src/otlp_metric_utils.cc#L215C6-L215C46).

Need to add 
```cpp
resource_metrics->set_schema_url(scope_metrics.scope_->GetSchemaUrl());
```

in above-mentioned method.
