### ISSUE TITLE
Symbol name "opentelemetry.proto.common.v1.AnyValue" conflicts with the existing symbol "opentelemetry.proto.common.v1.AnyValue".

### ISSUE THREAD

**Issue by archliu321** [open-telemetry/opentelemetry-cpp#2585]
I built opentelemetry-cpp to shared lib, but when i run my code, coredump occured with such message. Can anyone help me, thanks a lot.

[libprotobuf ERROR google/protobuf/descriptor_database.cc:669] Symbol name "opentelemetry.proto.common.v1.AnyValue" conflicts with the existing symbol "opentelemetry.proto.common.v1.AnyValue".

**Comment by archliu321** [comment]
more detail at
![image](https://github.com/open-telemetry/opentelemetry-cpp/assets/142767274/0896bb0f-a935-42b7-9d6b-d948194c8df4)

**Comment by esigo** [comment]
@archliu321 please provide minimal reproduction steps.
you are probably linking proto twice.

**Comment by archliu321** [comment]
@esigo Thank you very much for your suggestion. After careful investigation, I did find that I had inadvertently included the same proto definition twice in the project.
Now, It works well.
