### ISSUE TITLE
Add CMake Support for the JSON C++ Dependency

### ISSUE THREAD

**Issue by jajanet** [open-telemetry/opentelemetry-cpp#281]
**Is your feature request related to a problem?**
At the time of writing, there's a [JSON dependency](https://github.com/kmanghat/opentelemetry-cpp/tree/master/third_party/json) with only a Bazel build created. Since we're committed to both CMake and Bazel, there also needs to be CMake support.

**Describe the solution you'd like**
CMake can be added using `vcpkg install nlohmann-json`  as long as Bazel build is added.

**Describe alternatives you've considered**
After a CMake build is created for a quick fix to have full support for the JSON dependency, any current and future issues with building for Github dependencies in both CMake and Bazel can ideally be amended using Github submodules. This would mean `nlohmann-json` would be added under a submodules folder along with other repositories (Google Test, Google Benchmark, Protobuf). OTel Java currently does this as seen [here](https://github.com/open-telemetry/opentelemetry-java/blob/master/.gitmodules). This will be reasoned with in a future Github issue.

**Additional context**
https://github.com/open-telemetry/opentelemetry-cpp/pull/190#pullrequestreview-450953525

@maxgolov

**Comment by maxgolov** [comment]
I'll take a look at this.
