### ISSUE TITLE
gcc 7.3.1 bazel build error

### ISSUE THREAD

**Issue by charlely** [open-telemetry/opentelemetry-cpp#294]
input cmd: bazel build //examples/batch:example_simple

output: 
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/data/home/xxxx/.cache/bazel/_bazel_charleli/ae2757cba182123623167c390e6a2661/command.profile.gz'
INFO: Analyzed target //examples/batch:example_simple (21 packages loaded, 243 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /data/home/charleli/.cache/bazel/_bazel_charleli/ae2757cba182123623167c390e6a2661/sandbox
ERROR: /data/home/charleli/proj/cpp/opentelemetry-cpp/sdk/src/trace/BUILD:17:1: C++ compilation of rule '//sdk/src/trace:trace' failed (Exit 1) gcc failed: error executing command /usr/lib64/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 20 argument(s) skipped)

**Comment by lalitb** [comment]
Stale bug? Please reopen if still valid.
