### ISSUE TITLE
Specify OPENTELEMETRY_ABI_VERSION_NO with Bazel

### ISSUE THREAD

**Issue by BYVoid** [open-telemetry/opentelemetry-cpp#3019]
**Is your feature request related to a problem?**
`OPENTELEMETRY_ABI_VERSION_NO` is by default `1` in Bazel, and there is no where to configure it, unlike CMake (`WITH_ABI_VERSION_2`).

**Describe the solution you'd like**
Consider adding a Bazel flag to allow changing `OPENTELEMETRY_ABI_VERSION_NO` as in https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/BUILD.

**Describe alternatives you've considered**
I tried to patch the Bazel build files.

**Comment by BYVoid** [comment]
Thanks for merging.

Would you consider setting the default `abi_version_no` to `2` in Bazel? As Bazel is hermetic (all deps are built from source), there is no ABI compatibility issue at all. It makes sense to allow users to use the latest APIs guarded by `#if OPENTELEMETRY_ABI_VERSION_NO >=2` by default.

If this makes sense, I am happy to create another pull request.

**Comment by marcalff** [comment]
Moving to `OPENTELEMETRY_ABI_VERSION_NO = 2` will cause breaking changes.

For example, see how parameters for `opentelemetry::trace::TracerProvider::GetTracer()` changed.

Users should be asking explicitly for abi 2 instead if they want to use it, we can not ship it by default for now.

Beside, ABI v2 can change without notice with more breaking changes, it is not stable yet.
