### ISSUE TITLE
Add DocFX sanity check to CI

### ISSUE THREAD

**Issue by nadiaciobanu** [open-telemetry/opentelemetry-cpp#304]
**Problem**
We use Markdown for our documentation. Sometimes, Markdown files may contain broken links (for example due to the link being incorrect or moved).

**Solution**
Add [DocFX](https://dotnet.github.io/docfx/) sanity check to the CI, similar to open-telemetry/opentelemetry-specification#742.

**Comment by xukaren** [comment]
Hi! Is this still available? Could I pick this up for a first issue?

**Comment by xukaren** [comment]
Fixed in #336

**Comment by lalitb** [comment]
#578 fixes it.
