### ISSUE TITLE
Support Summary metrics

### ISSUE THREAD

**Issue by santigimeno** [open-telemetry/opentelemetry-cpp#3058]
Hello everyone.

In our project we integrate `opentelemetry-cpp` to export our telemetry data using the `OTLP` exporters the library provides. Some of the metrics we export fit better as `Summary` but the library doesn't support it. I understand the reason being `Summaries` are declared `Legacy` in the spec.

I've added the support myself in the `opentelemetry-cpp` version we use in our project but would like to upstream the changes. So I was wondering whether you'd be open for a PR that allows users to export `Summary` metrics (it doesn't cover things like instrument creation, etc).

Thanks

**Comment by lalitb** [comment]
`Summary` is not part of the specs, probably because most of it's use-cases can be covered through Histograms. And it's there in OTLP proto for integration with non-otel components. I'm not sure if implementing support for non-spec features is advisable.

**Comment by santigimeno** [comment]
Fair enough. I read the OTLP spec and thought it was a valid use case for apps that already exist out there which want to integrate with other OpenTelemetry components and that generate and need the percentiles that Summaries define for which either is not possible to migrate to Histograms, or Histograms don't cover exactly their use case.

Anyway, as soon as our changes are published I'll post a link to it in the issue in case someone needs smthg similar.

Thanks
