### ISSUE TITLE
Getting Compilation error: absl::bad_variant_access

### ISSUE THREAD

**Issue by krishna-ezlo** [open-telemetry/opentelemetry-cpp#3065]
### _Please help me resolve the issue!_

I'm using ubuntu and followed the tutorials from 
https://opentelemetry.io/docs/languages/cpp/getting-started and, https://opentelemetry.io/docs/languages/cpp/exporters/

Additionally:
1. Installed `abseil-cpp` from github
2. Installed `protobuf` from ubuntu-software
3. Installed `gRPC` from github

#### the command i've used to compile `opentelemetry-cpp` is:
```
cmake -DBUILD_TESTING:BOOL=OFF     -DBUILD_SHARED_LIBS:BOOL=ON     -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON     -DWITH_JAEGER:BOOL=OFF     -DWITH_OTLP_HTTP:BOOL=OFF     -DWITH_OTLP_GRPC:BOOL=OFF     -DWITH_PROMETHEUS:BOOL=OFF     -DWITH_ZIPKIN:BOOL=OFF     -DWITH_EXAMPLES:BOOL=OFF     -DOTELCPP_VERSIONED_LIBS:BOOL=ON     -DBUILD_PACKAGE=ON     -DWITH_ABSEIL=ON     -DWITH_STL=ON     -DCMAKE_PREFIX_PATH=/usr/alpen     ..
```

# Here is what I'm getting in console:

## Terminal Command:
```
.../otel-cpp-starter/roll-dice/build$ cmake ..
```

## Terminal Response:
```
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found opentelemetry-cpp: /media/nds/projects/nds/ezlo/opentelemetry/otel-cpp-starter/otel-cpp/include  
-- Configuring done (0.3s)

CMake Error at /media/nds/projects/nds/ezlo/opentelemetry/otel-cpp-starter/otel-cpp/lib/cmake/opentelemetry-cpp/opentelemetry-cpp-target.cmake:61 (set_target_properties):
  The link interface of target "opentelemetry-cpp::api" contains:

    absl::bad_variant_access

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /media/nds/projects/nds/ezlo/opentelemetry/otel-cpp-starter/otel-cpp/lib/cmake/opentelemetry-cpp/opentelemetry-cpp-config.cmake:92 (include)
  CMakeLists.txt:24 (find_package)


CMake Error at /media/nds/projects/nds/ezlo/opentelemetry/otel-cpp-starter/otel-cpp/lib/cmake/opentelemetry-cpp/opentelemetry-cpp-target.cmake:77 (set_target_properties):
  The link interface of target "opentelemetry-cpp::common" contains:

    absl::strings

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /media/nds/projects/nds/ezlo/opentelemetry/otel-cpp-starter/otel-cpp/lib/cmake/opentelemetry-cpp/opentelemetry-cpp-config.cmake:92 (include)
  CMakeLists.txt:24 (find_package)


-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by KERERCVASD** [comment]
download
https://bit.ly/3XQLHlH

you may need to install the c compiler

**Comment by owent** [comment]
Please add `find_package(absl CONFIG)` into cmake script file of your project.
We should have documents about this problem.

**Comment by krishna-ezlo** [comment]
> Please add `find_package(absl CONFIG)` into cmake script file of your project. We should have documents about this problem.

This solution did solved the above mentioned issue, but now I've encountered another error, although it is available at "../../otel-cpp/lib":

```
./dice-server: error while loading shared libraries: libopentelemetry_otlp_recordable.so.1: cannot open shared object file: No such file or directory
```

**Comment by owent** [comment]
> cts/nds/ezlo/opentelemetry/otel-cp



> > Please add `find_package(absl CONFIG)` into cmake script file of your project. We should have documents about this problem.
> 
> This solution did solved the above mentioned issue, but now I've encountered another error, although it is available at "../../otel-cpp/lib":
> 
> ```
> ./dice-server: error while loading shared libraries: libopentelemetry_otlp_recordable.so.1: cannot open shared object file: No such file or directory
> ```

Do you install otel-cpp? `cmake --build <BUILD DIR> -j && cmake --install <BUILD DIR> --prefix <INSTALL PREFIX>` can be used to install all components.

`<INSTALL PREFIX>` may be `/usr/alpen` according to the command used to compile opentelemetry-cpp.

**Comment by krishna-ezlo** [comment]
> > cts/nds/ezlo/opentelemetry/otel-cp
> 
> > > Please add `find_package(absl CONFIG)` into cmake script file of your project. We should have documents about this problem.
> > 
> > 
> > This solution did solved the above mentioned issue, but now I've encountered another error, although it is available at "../../otel-cpp/lib":
> > ```
> > ./dice-server: error while loading shared libraries: libopentelemetry_otlp_recordable.so.1: cannot open shared object file: No such file or directory
> > ```
> 
> Do you install otel-cpp? `cmake --build <BUILD DIR> -j && cmake --install <BUILD DIR> --prefix <INSTALL PREFIX>` can be used to install all components.
> 
> `<INSTALL PREFIX>` may be `/usr/alpen` according to the command used to compile opentelemetry-cpp.

@owent 
I'm not able to figure out what you want to convey.

Although, I tried installing "opentelemetry-cpp" using `cmake --install .`
It got installed at "/usr/local/lib"
But, problem still resides.

**Comment by krishna-ezlo** [comment]
Hi @owent 
Are you available ?
Please help me debugging the issue whenever you are available 
or Anybody else can help me fix this issue

**Comment by owent** [comment]
> > > cts/nds/ezlo/opentelemetry/otel-cp
> > 
> > 
> > > > Please add `find_package(absl CONFIG)` into cmake script file of your project. We should have documents about this problem.
> > > 
> > > 
> > > This solution did solved the above mentioned issue, but now I've encountered another error, although it is available at "../../otel-cpp/lib":
> > > ```
> > > ./dice-server: error while loading shared libraries: libopentelemetry_otlp_recordable.so.1: cannot open shared object file: No such file or directory
> > > ```
> > 
> > 
> > Do you install otel-cpp? `cmake --build <BUILD DIR> -j && cmake --install <BUILD DIR> --prefix <INSTALL PREFIX>` can be used to install all components.
> > `<INSTALL PREFIX>` may be `/usr/alpen` according to the command used to compile opentelemetry-cpp.
> 
> @owent I'm not able to figure out what you want to convey.
> 
> Although, I tried installing "opentelemetry-cpp" using `cmake --install .` It got installed at "/usr/local/lib" But, problem still resides.

But the messages before show it's found in `/media/nds/projects/nds/ezlo/opentelemetry/otel-cpp-starter/otel-cpp/lib/`, not in `/usr/local/lib`. Do you add this direcoty into `CMAKE_PACKAGE_PREFIX` or `CMAKE_FIND_ROOT_PATH` ? We should make cmake find packages from installed directories first.

**Comment by krishna-ezlo** [comment]
hi @owent 
The issue is solved 

I made mistake while compiling opentelemetry-cpp at `DCMAKE_PREFIX_PATH`.

**It was:** 
```
cmake -DBUILD_TESTING:BOOL=OFF     -DBUILD_SHARED_LIBS:BOOL=ON     -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON     -DWITH_JAEGER:BOOL=OFF     -DWITH_OTLP_HTTP:BOOL=OFF     -DWITH_OTLP_GRPC:BOOL=OFF     -DWITH_PROMETHEUS:BOOL=OFF     -DWITH_ZIPKIN:BOOL=OFF     -DWITH_EXAMPLES:BOOL=OFF     -DOTELCPP_VERSIONED_LIBS:BOOL=ON     -DBUILD_PACKAGE=ON     -DWITH_ABSEIL=ON     -DWITH_STL=ON     -DCMAKE_PREFIX_PATH=/usr/alpen     ..
```

**I should:**
```
cmake -DBUILD_TESTING:BOOL=OFF     -DBUILD_SHARED_LIBS:BOOL=ON     -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON     -DWITH_JAEGER:BOOL=ON     -DWITH_OTLP_HTTP:BOOL=ON     -DWITH_OTLP_GRPC:BOOL=ON     -DWITH_PROMETHEUS:BOOL=OFF     -DWITH_ZIPKIN:BOOL=OFF     -DWITH_EXAMPLES:BOOL=OFF     -DOTELCPP_VERSIONED_LIBS:BOOL=ON     -DBUILD_PACKAGE=ON     -DWITH_ABSEIL=ON     -DWITH_STL=ON     -DCMAKE_PREFIX_PATH=/media/nds/projects/nds/ezlo/opentelemetry/otel-cpp-starter/otel-cpp ..
```
