### ISSUE TITLE
GRPC + TLS Exporter failing to connect

### ISSUE THREAD

**Issue by kadhamecha-conga** [open-telemetry/opentelemetry-cpp#3070]
hi

i'm facing issue while exporting traces from nginx with open telemetry enable , and send it over grpc and TLS enable in NLB

GRPC Exporter is failing to establish a connection with the configured endpoint, resulting in the inability to export trace data.

[Error] File: /tmp/build/opentelemetry-cpp/exporters/otlp/src/otlp_grpc_exporter.cc:66 [OTLP TRACE GRPC Exporter] Export() failed with status_code: "UNAVAILABLE" error_message: "failed to connect to all addresses; last error: UNKNOWN: ipv4:x.x.x.x:443: connection attempt timed out before receiving SETTINGS frame"

otlp-collector-host: test.example.com
otlp-collector-port: 443

thanks,

**Comment by marcalff** [comment]
> otlp-collector-host: test.example.com
> otlp-collector-port: 443

This will fail, as expected.
Change the configuration to use a real endpoint.

**Comment by kadhamecha-conga** [comment]
@marcalff  I'm using the actual data, but I've redacted sensitive information to protect privacy.
