### ISSUE TITLE
GRPC + TLS Exporter not working 

### ISSUE THREAD

**Issue by kadhamecha-conga** [open-telemetry/opentelemetry-cpp#3074]
hi
            
            i'm facing issue while exporting traces from nginx with open telemetry enable , and send it over grpc and TLS enable in NLB
            
            GRPC Exporter is failing to establish a connection with the configured endpoint, resulting in the inability to export trace data.
            
            [Error] File: /tmp/build/opentelemetry-cpp/exporters/otlp/src/otlp_grpc_exporter.cc:66 [OTLP TRACE GRPC Exporter] Export() failed with status_code: "UNAVAILABLE" error_message: "failed to connect to all addresses; last error: UNKNOWN: ipv4:x.x.x.x:443: connection attempt timed out before receiving SETTINGS frame"
            
            otlp-collector-host: test.example.com (Redacted)
            otlp-collector-port: 443

            helm.sh/chart : ingress-nginx-4.11.3
            app.kubernetes.io/version : 1.11.2
            
            thanks,

**Comment by bansalrajat** [comment]
+1

**Comment by marcalff** [comment]
For the exporter to work, the endpoint must be up and running, and there must be network connectivity to reach this endpoint.

Failure to connect to a given IP address just looks like this is not the case.

Closing this issue.
