### ISSUE TITLE
Jaeger Propagator should not be deprecated

### ISSUE THREAD

**Issue by brucedlg** [open-telemetry/opentelemetry-cpp#3077]
**Is your feature request related to a problem?**
The Jaeger propagator is not supported without enabling deprecated code.

**Describe the solution you'd like**
The Jaeger propagator is deprecated in PR https://github.com/open-telemetry/opentelemetry-cpp/pull/1923 as part of effort removing / deprecating Jaeger exporter.
But the Jaeger propagator should not be deprecated according to specification: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#propagators-distribution
The specification lists Jaeger as one of the official propagators.
So we should unmark Jaeger propagator as deprecated.

**Describe alternatives you've considered**

**Additional context**
The Jaeger propagator is supported in Java, Go and other SDK without being deprecated.

**Comment by marcalff** [comment]
I agree, this deprecation is not justified, and can be revisited.

When #1923 was implemented (disclosure: I am the author), there was confusion between the Jaeger propagator and the Jaeger exporter.

Assuming the propagator can exist independently of the exporter, deprecating (later removing) the exporter should not have consequences for the propagator.
