### ISSUE TITLE
ElasticSearch http client URL is wrongly formated

### ISSUE THREAD

**Issue by MaxLeb** [open-telemetry/opentelemetry-cpp#3079]
Describe your environment

Using a manually built version of OpenTelemetry 1.16.1 on macOS with :

    -DWITH_EXAMPLES=OFF
    -DWITH_OTLP_HTTP=ON
    -DBUILD_TESTING=OFF
    -DWITH_OTLP_GRPC=OFF
    -DWITH_LOGS_PREVIEW=ON
    -DOPENTELEMETRY_INSTALL=ON
    -DBUILD_SHARED_LIBS=OFF
    -DWITH_ASYNC_EXPORT_PREVIEW=ON
    -DCMAKE_CXX_STANDARD=17
    -DWITH_ELASTICSEARCH=ON
Steps to reproduce

The usage is pretty simple:

First an init of the exporter with a single log record processor:

opentelemetry::exporter::logs::ElasticsearchExporterOptions opts(
    <host>,
    9200,
    "logs",
    30,
    true);

auto elkExporter = std::make_unique<opentelemetry::exporter::logs::ElasticsearchLogRecordExporter>(opts);

auto elkProcessor = opentelemetry::sdk::logs::SimpleLogRecordProcessorFactory::Create(std::move(elkExporter));
            
std::shared_ptr<opentelemetry::logs::LoggerProvider> provider = opentelemetry::sdk::logs::LoggerProviderFactory::Create(
    std::move(elkProcessor), resource);

opentelemetry::logs::Provider::SetLoggerProvider(provider);

m_Logger = provider->GetLogger("MyLogger", SOURCE_NAME);
Then, when logs needs to be sent a call to m_Logger.EmitLogRecord(xxx)

What is the expected behavior?
Host targeted by the exporter should have the `<host>:<port>` format/

**What is the actual behavior?**
The exporter was reporting this error `opentelemetry: [ES Log Exporter] Connection to elasticsearch failed`.
When adding the `reason` to the string it was outputing this: Could not resolve host: `elastic.mydomain.com9200` (missing `:`)

**Comment by MaxLeb** [comment]
Proposed patch: 
[0001-EXPORTER-Fix-ElasticsearchLogRecordExporter-http-cli.patch](https://github.com/user-attachments/files/17255429/0001-EXPORTER-Fix-ElasticsearchLogRecordExporter-http-cli.patch)

**Comment by marcalff** [comment]
Thanks @MaxLeb  for the report and the fix.

Please file a PR so it can be processed (CI, review, merge).

I see you have other fixes as well, PR also welcome for these.
