### ISSUE TITLE
[SEMANTIC CONVENTIONS] Upgrade to semantic conventions 1.28.0

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-cpp#3088]
Upgrade to semconv 1.28.0

This may also require to migrate from build-tools to weaver.

References:

* https://github.com/open-telemetry/semantic-conventions/pull/1458
* https://github.com/open-telemetry/build-tools/issues/322
* https://github.com/open-telemetry/opentelemetry-rust/pull/2098

**Comment by lmolkova** [comment]
> This may also require to migrate from build-tools to weaver.

This update should not require migration to weaver unless you want to start generating event definitions, but the next version might - I'm going to create a separate issue for weaver migration.
