### ISSUE TITLE
Migrate semantic conventions code generation to weaver

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-cpp#3089]
Semantic Convention tooling group is deprecating build-tools in favor of new code-generation tool - [weaver](https://github.com/open-telemetry/weaver), see https://github.com/open-telemetry/build-tools/issues/322 for the details.

Build-tools are compatible with the latest version of semantic-convention (1.28.0), but might become incompatible with the future versions of semantic-conventions. New features (such as event definition) are added to the weaver only and won't be supported by the build-tools.

Migration steps are documented [here](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/non-normative/code-generation.md#migrating-from-build-tools) along with some non-normative guidelines on the code organization and artifact stability.

Looking for volunteers and happy to help or provide any additional details.

**Comment by marcalff** [comment]
In progress, byt blocked by:

* https://github.com/open-telemetry/weaver/issues/411
