### ISSUE TITLE
ElasticSearch Exporter does not follow ECS guidelines and logging reference

### ISSUE THREAD

**Issue by ShadowMaxLeb** [open-telemetry/opentelemetry-cpp#3091]
**Describe your environment** 

Version 1.17.0 of this project.

**Steps to reproduce**
Use the `ElasticsearchLogRecordExporter`

**What is the expected behavior?**
The json sent should follow the [ECS guidelines](https://www.elastic.co/guide/en/ecs/current/ecs-guidelines.html) as much as possible as well as the [ECS logging reference](https://www.elastic.co/guide/en/ecs-logging/overview/current/intro.html#_default_fields)

**What is the actual behavior?**
Some basic field needed by ELK are not there like `@timestamp` (`timestamp` today in the code)

```
General guidelines
The document MUST have the @timestamp field.
Use the [data types](https://www.elastic.co/guide/en/elasticsearch/reference/8.15/mapping-types.html) defined for an ECS field.
Use the ecs.version field to define which version of ECS is used.
Map as many fields as possible to ECS.
```

All attributes/resources are set under the `attributes`/`resources` key while I think they should be set at the root of the json or at least give a possibility to set attributes/resources at the root of the object so we can fill some fields like [user.id](https://www.elastic.co/guide/en/ecs/8.11/ecs-user.html#field-user-id)

**Comment by Neema-Joju** [comment]
Hi,
I am an outreachy applicant. May I attempt this?

**Comment by ShadowMaxLeb** [comment]
I have started some work that I should share soon.
There might be some point to discuss.
