### ISSUE TITLE
[SHIM] Dangerous use of string_view

### ISSUE THREAD

**Issue by chusitoo** [open-telemetry/opentelemetry-cpp#3180]
The opentracing shim does a few conversions in either direction between the implementation of `opentracing::string_view` to `nostd::string_view`, by constructing the target with just the `.data()` part.

The approach might be OK as is, in general, but is highly speculative on the source buffer being null terminated. The alternative is explicitly constructing the target string view with the size of the buffer.

For instance, the proper mapping in [shim_utils.h L32](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/opentracing-shim/include/opentelemetry/opentracingshim/shim_utils.h#L32) would look like this:

```diff
-    AttributeValue operator()(opentracing::string_view v) { return nostd::string_view{v.data()}; }
+    AttributeValue operator()(opentracing::string_view v)
+    {
+      return nostd::string_view{v.data(), v.size()};
+    }
```

This would make it for the correct use of string view at the expense of a bit more verbosity.

**Comment by marcalff** [comment]
> This would make it for the correct use of string view at the expense of a bit more verbosity.

This also improves performances, saving a call to strlen().
