### ISSUE TITLE
Add functionality to create links on spans

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/opentelemetry-cpp#319]
According to the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#add-links), we must provide a way to record links on spans.

**Comment by lalitb** [comment]
#342 and #366 fixes it.

**Comment by jlisee** [comment]
@lalitb https://github.com/open-telemetry/opentelemetry-cpp/pull/342 was **closed** not merged so there is no public `AddLink` function in the `tracer::Span` API is that intentional or was it an oversight?

**Comment by owent** [comment]
> @lalitb #342 was **closed** not merged so there is no public `AddLink` function in the `tracer::Span` API is that intentional or was it an oversight?

According to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#specifying-links, links can be added when creating a `Span`. This is already supported and the codes are here https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/trace/tracer.h#L40

**Comment by jlisee** [comment]
> This is already supported and the codes are here https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/trace/tracer.h#L40

Thanks for the hint, is this API usage right below? Where `{}` is filling in empty attribute maps that are required? I found I hint in the test: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/test/trace/noop_test.cc#L54-L56 but it would be great to have this in the getting started section in the docs explicitly:

```cpp
// Get context from span to link
const trace_api::SpanContext ctx = otherSpan.GetContext()

// Create link to that span (is there a typedef/alias I can use here?)
std::vector<std::pair<trace_api::SpanContext, std::map<std::string, std::string>>> links = {
    {ctx, {}}
};
      
// Create span with that link (annoying to pass an empty attribute map here)
auto s1 = tracer->StartSpan("span_with_link", {}, links);
```

I did like the previous API which required fewer types and place holders:

```cpp
// Get context from span to link
const trace_api::SpanContext ctx = otherSpan.GetContext()

// Create span
auto s1 = tracer->StartSpan("span_with_link");

// Add Link
s1->AddLink(ctx, {})
```
