### ISSUE TITLE
Not all compiler support all C++20's components when using `-std=c++20`

### ISSUE THREAD

**Issue by owent** [open-telemetry/opentelemetry-cpp#3200]
**Describe your environment**

OS: Linux
Compiler: GCC 11

**Steps to reproduce**
Compiling otel-cpp with `-std=c++20`

**What is the expected behavior?**
Building success.

**What is the actual behavior?**

```bash
/home/runner/work/cmake-toolset/cmake-toolset/test/third_party/packages/opentelemetry-cpp-v1.18.0/exporters/elasticsearch/src/es_log_recordable.cc:181:36: error: ‘format’ is not a member of ‘std’
  181 |   const std::string dateStr = std::format("{:%FT%T%Ez}", timePoint);
      |                                    ^~~~~~
gmake[2]: *** [exporters/elasticsearch/CMakeFiles/opentelemetry_exporter_elasticsearch_logs.dir/build.make:93: exporters/elasticsearch/CMakeFiles/opentelemetry_exporter_elasticsearch_logs.dir/src/es_log_recordable.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1593: exporters/elasticsearch/CMakeFiles/opentelemetry_exporter_elasticsearch_logs.dir/all] Error 2
```

**Additional context**
<https://github.com/owent/cmake-toolset/actions/runs/12311600885/job/34362063562>

There may be other errors

```bash
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
[cmake] Please set them or make sure they are set and tested correctly in the CMake files:
[cmake] GMOCK_LIB
[cmake]     linked by target "url_parser_test" in directory D:/workspace/git/github/opentelemetry/opentelemetry-cpp/ext/test/http
[cmake]     linked by target "curl_http_test" in directory D:/workspace/git/github/opentelemetry/opentelemetry-cpp/ext/test/http
[cmake] 
[cmake] CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by lalitb** [comment]
I'm wondering if features from C++17 and later should be conditionally allowed in the code using preprocessor directives (as in this case), as addressing errors related to them could be challenging.

**Comment by owent** [comment]
> I'm wondering if features from C++17 and later should be conditionally allowed in the code using preprocessor directives (as in this case), as addressing errors related to them could be challenging.

In my understanding, the anwser is NO. The library feature-test macros are only be defined after the headers are included. But we can not include it when it's not exists.
