### ISSUE TITLE
Rename SpanContext to SpanReference

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-cpp#362]
Update needed to track these changes: open-telemetry/opentelemetry-specification#1075

**Comment by TuckTuckFloof** [comment]
Is this issue still open?

**Comment by ThomsonTan** [comment]
@TuckTuckFloof yes, are you interested to help this?

**Comment by TuckTuckFloof** [comment]
Yea, I've been looking to do some open source stuff, complete first timer, now what do I have to do?

**Comment by ThomsonTan** [comment]
Take a look at the spec link https://github.com/open-telemetry/opentelemetry-specification/pull/1075, make sure all the occurrences are correctly renamed in this repo, and follow our contribution guideline [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/CONTRIBUTING.md).

**Comment by TuckTuckFloof** [comment]
I'm in, so look for more instances like the one in the spec link and make a pr then?

**Comment by ThomsonTan** [comment]
That's right. Just a reminder, please also take a look at the contribution guideline above before uploading PR. Thanks and happy contributing.

**Comment by TuckTuckFloof** [comment]
Thank you, and will do. I've already forked it and found 1 instance lol.

**Comment by TuckTuckFloof** [comment]
Oh, I found span_context, would you like me to change those to span_reference for consistency?

**Comment by ThomsonTan** [comment]
That's a good find. I think it is great to keep it consistent with the struct name. @open-telemetry/cpp-approvers please share thoughts.

**Comment by TuckTuckFloof** [comment]
Alright, I got it done, I'm gonna hang around before the PR though, just in case you guys want me to change span_context to span_reference, as stated before

**Comment by TuckTuckFloof** [comment]
@ThomsonTan Do you think I should just make a PR as is or should I wait for other responses?

**Comment by ThomsonTan** [comment]
I think it is fine to create the PR.

**Comment by TuckTuckFloof** [comment]
you got it

**Comment by TuckTuckFloof** [comment]
Ok, so I couldn't get the tools/format.sh file to work, couldnt find buildifier and the link to get it just doesn't exist apparently

**Comment by lalitb** [comment]
Make sure you install formatting tool by running this [script](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/ci/install_format_tools.sh).

**Comment by TuckTuckFloof** [comment]
Oh, thank you, I hope this'll get it to work

**Comment by TuckTuckFloof** [comment]
Alright, commited

**Comment by TuckTuckFloof** [comment]
Alright, I'm back, it's telling me that considering that they are different commit histories, I can't make a PR

**Comment by ThomsonTan** [comment]
Could you please share the detailed error message of creating the PR? Could you please try rebase your change to the latest and create PR again?

**Comment by TuckTuckFloof** [comment]
I'll try the rebase because it literally doesn't say anything else other than that they're different commit histories. Which is weird because it shows me the changes I made.

**Comment by lalitb** [comment]
Please hold on this change, as there is ongoing discussion to revert back this renaming:

https://github.com/open-telemetry/opentelemetry-specification/issues/1126

**Comment by lalitb** [comment]
@ThomsonTan  closing this issue  -as the changes in specs are reverted back  -  https://github.com/open-telemetry/opentelemetry-specification/pull/1127.
