### ISSUE TITLE
Adding span collection limits

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#365]
As per the recent [spec ](https://github.com/open-telemetry/opentelemetry-specification/pull/942) change : 

Max attributes per span : 1000
Max links per span : 1000
Max events per span : 1000

The upper bound needs to be validated.

**Comment by pyohannes** [comment]
Those limits are not mandatory by the spec (they're a MAY), so I will remove the bug label.

**Comment by lalitb** [comment]
@anshulkumar19  - I have assigned it to myself, while you are working on it ( to ensure there is no parallel work on it ).

**Comment by anshulkumar19** [comment]
Thanks @lalitb

**Comment by anshulkumar19** [comment]
@lalitb Currently this is WIP (span limit struct is added but constraint is used only in span_data ), intended to get it reviewed from the perspective of complexity introduced in current structure as this is an optional feature suggested by the spec.

**Comment by lalitb** [comment]
Thanks @anshulkumar19 - Will review it in regards to the complexity introduced.

**Comment by lalitb** [comment]
closing as this is optional requirement, and there is no plan to implement these limits.
