### ISSUE TITLE
Clarify ABI requirements

### ISSUE THREAD

**Issue by g-easy** [open-telemetry/opentelemetry-cpp#37]
Building on top of https://github.com/open-telemetry/opentelemetry-cpp/pull/24, I added an example of two libraries that are built with OpenTelemetry API and different STLs (libc++ versus libstdc++): https://github.com/g-easy/opentelemetry-cpp/commit/5dc5f2e2bcc0704191629f68fdbb1ecb9201a0cf

Using them both appears to result in a link error due to the OpenTelemetry API using `std::shared_ptr`.

Please help me understand whether I'm doing something wrong, or whether we need to change the requirements around STL use.

**Comment by rnburn** [comment]
> clang++-8 -I../api/include/ -std=c++11 -stdlib=libstdc++ lib1.o lib2.o main.o -o main

This looks like you're trying to statically link the libraries into the same executable where lib1 was built against libc++ and the others were built against libstdc++. I don't think that's going to work.

What can work is using DSOs that have the standard c++ library statically linked in and the symbols properly managed with an export map.

**Comment by g-easy** [comment]
What does this mean for libraries that want to use OpenTelemetry for instrumentation? They can never ship `*.a` files, and they need to be careful with their export map?

**Comment by rnburn** [comment]
You can ship .a files, but you need them to be built against the same standard c++ library that you link against. 

And that's the case regardless of whether you linked in the OpenTelemetry API or not.

If you combine C++ object files to form a .a, then if any of the object files use standard c++ library functions, your .a library will have external references to standard c++ library functions. And to resolve them, you'll need for the final linking to be done against the same version of the standard c++ library.

**Comment by rnburn** [comment]
I don't think mixing .a's linked against different version of the standard c++ library is a scenario we need to worry about supporting because that would be problematic regardless of whether you use OpenTelemetry.

If you remove the OpenTelemetry references from your example, but change your f1 and f2 functions to invoke standard library functions, you'll run into similar linking errors.

**Comment by rnburn** [comment]
> What does this mean for libraries that want to use OpenTelemetry for instrumentation? They can never ship *.a files, and they need to be careful with their export map?

The core value proposition of a stable ABI is, you can load an OpenTelemetry implementation as a plugin. Whoever linked and distributed the plugin needs to worry about export maps, but the end user doesn't. They just invoke need to call opentelemetry::plugin::LoadFactory with the path to the plugin and then they can create tracers and meters and go about instrumenting their code.

It doesn't matter which version of the standard c++ library the user linked against and the plugin linked against because with a stable abi in the virtual methods it will work regardless.

**Comment by g-easy** [comment]
Q1. For an instrumented library to use the otel API, its entry point should be `GetTracerProvider()`, yes?

Q2. What my example shows is that `GetTracerProvider()` has ABI issues because it uses `std::shared_ptr`.

Here's an example of only using `GetTracer()` and not `GetTracerProvider()` and that works fine when mixing STLs because there are no STL dependencies: https://github.com/open-telemetry/opentelemetry-cpp/commit/6ae3442473b88eac71f531ee50181c07ef6294f4

**Comment by rnburn** [comment]
> Q2. What my example shows is that GetTracerProvider() has ABI issues because it uses std::shared_ptr.

It doesn't use std::shared_ptr in the virtual methods. You can still interact with a type that's using STL containers internally through the vtable functions. Look at the example I put together [here](https://gist.github.com/rnburn/501935437e8c2d4f547b95a96cd6661a). It shows two DSOs interacting with a Cont abstract class even though they have different definitions of ContImpl (simulating what different STL versions would look like).

**Comment by g-easy** [comment]
I've looked at the example and borrowed from it (thanks!) in the stuff I've been trying out. I haven't been able to get it to work on top of #24. Could you please take a look at https://github.com/g-easy/opentelemetry-cpp/commit/770de3514dca15bd9243a49dbf8a07e2bd646c53 and help me understand what I'm doing wrong? I'm using two shared libs (like in your example) and not mixing STLs.

**Comment by rnburn** [comment]
It's because of this [issue](https://github.com/open-telemetry/opentelemetry-cpp/pull/24/files#r374990377)

You can't put a class like noop tracer that inherits from std::enable_shared_from_this into a unique_ptr. It has to go into a shared_ptr otherwise the enable_shared_from_this's reference count will be zero.

**Comment by rnburn** [comment]
std::enable_shared_from_this is built on top of std::weak_ptr. The std::bad_weak_ptr error is mentioned in the [notes](https://en.cppreference.com/w/cpp/memory/enable_shared_from_this)

**Comment by g-easy** [comment]
[Fixing](https://github.com/open-telemetry/opentelemetry-cpp/commit/d0c9ca3f297f85dbe7aee6ddb1a31d1821afa4d7) the issue makes main not crash. Nice. The next thing I've run into is that each library has a separate TracerProvider: [example](https://github.com/open-telemetry/opentelemetry-cpp/commit/e648d43fe4d0c3555f3ac3fe2ae31de2e05aee99)

**Comment by rnburn** [comment]
You need the singleton functions to be exposed in the export map.

Take a look at my case 3 comments in this https://github.com/open-telemetry/opentelemetry-cpp/issues/4#issuecomment-583947450

**Comment by g-easy** [comment]
Looks like that [fixes](https://github.com/open-telemetry/opentelemetry-cpp/commit/49bba11db33892fc0f11476b959e1a1cdd2c6b2e) the separate providers problem. Thanks for putting up with all the questions. :)

**Comment by g-easy** [comment]
I also managed to get it to work when mixing and matching STLs: https://github.com/g-easy/opentelemetry-cpp/commit/17a310b94c6fe52fd47f8376b8a375b3c4f7c529

**Comment by g-easy** [comment]
My take-away is that instrumenting a library with OpenTelemetry is non-trivial and we should document (ideally in the form of a cookbook that people can copy-paste from) how to do it correctly.

* The header-only singleton results in every translation unit having an implementation of `GetTracerProvider()` as a weak symbol.
* The `.so` will also have it as a weak symbol.
* Unless the `.so` is statically linked (to include the STL), then it's a non-weak symbol, which causes problems.
* Using an export map turns it into a weak symbol again and everything works out using the usual weak symbol rules.

**Comment by rnburn** [comment]
>*  Unless the .so is statically linked (to include the STL), then it's a non-weak symbol, which causes problems.
> * Using an export map turns it into a weak symbol again and everything works out using the usual weak symbol rules.

An export map is important whenever you statically link dependencies like the standard C++ library, but it shouldn't be necessary if all the dependencies are linked dynamically.

The GetTracerProvider singleton should work fine when there's no export map and dependencies are dynamically linked, no?

**Comment by g-easy** [comment]
> The GetTracerProvider singleton should work fine with a .so when there's no export map and dependencies are dynamically linked, no?

Yep, it should work fine in that case because `GetTracerProvider` remains a weak symbol.

**Comment by lalitb** [comment]
This is there now: https://github.com/open-telemetry/opentelemetry-cpp/blob/master/docs/abi-policy.md

Please reopen if you think something is still missing.
