### ISSUE TITLE
Implementing a Recordable interface for Logs 

### ISSUE THREAD

**Issue by xukaren** [open-telemetry/opentelemetry-cpp#412]
**Problem**
An important use case of logging is to allow log records to be sent to multiple export destinations, as seen in these logging libraries:
* [Log4cxx](http://svn.apache.org/repos/asf/incubator/log4cxx/tags/v0_9_7/xdocs/www/manual/Introduction.html#AppendersAndLayouts)
* [Plog](https://github.com/SergiusTheBest/plog#multiple-appenders)
* [Log4J](https://logging.apache.org/log4j/2.x/manual/appenders.html)

In the current Logging SDK, a LogRecord is created as a `unique_pointer` by the SDK, then moved to a processor, then passed by `const reference` to an exporter. This implementation does not allow more than one processor per Logger.

**Solution**
One solution could be to implement a `Recordable` interface, similar to what is currently used for [traces](https://github.com/open-telemetry/opentelemetry-cpp/blob/984e6ca3c311b00397559d8486972a8b23efd067/sdk/include/opentelemetry/sdk/trace/recordable.h). The recordable idea outlined [here](https://github.com/open-telemetry/opentelemetry-cpp/issues/2).

**Alternatives Considered**
Another possible (simpler but less performant) solution is to pass a `LogRecord` as a `shared_ptr` to be shared between the multiple processors/exporters. However, this approach could offer inconsistent performance related to memory-management which is a goal. 

**Additional Context**
Further discussion about the Recordable interface can be found in https://github.com/open-telemetry/opentelemetry-cpp/pull/44 and https://github.com/open-telemetry/opentelemetry-cpp/pull/49. 

cc @alolita @MarkSeufert

**Comment by meastp** [comment]
@xukaren I don't know if you think it's relevant, as you already have a multiple examples, but Boost.Log is also designed around multiple sinks / export destinations as seen [in the Boost.Log design overview documentation](https://www.boost.org/doc/libs/1_74_0/libs/log/doc/html/log/design.html).

**Comment by xukaren** [comment]
Resolved by #438
