### ISSUE TITLE
Supporting single vs. multiple exporters per processor for Logs

### ISSUE THREAD

**Issue by xukaren** [open-telemetry/opentelemetry-cpp#417]
I think the approach most are leaning towards for logs, following the traces implementation, is attaching only 1 exporter to a processor. However, another consideration is to support multiple exporters per processor. 

Advantages of attaching multiple exporters to a processor: 
* Could reduce number of times batching is done 

Disadvantages:
* Could also increase the time it takes to complete the export to all destinations, since each batch export would only take as little of time as the slowest exporter takes to finish its export. 

Unknown: 
* What would be the return status from the processor from `ForceFlush()` or `Shutdown()` not _all_ the exporters succeed/fail at the same time? 
* Would user interact directly with processor or exporter to shutdown or forceflush a certainexporter? 

Opening up this issue for discussion

cc @alolita @MarkSeufert

**Comment by lalitb** [comment]
There is a separate issue to support multiple span processors ( #664). No plan is to support multiple exporters per processor.
