### ISSUE TITLE
Define default timeout for all processor and exporter interfaces 

### ISSUE THREAD

**Issue by xukaren** [open-telemetry/opentelemetry-cpp#418]
An idiomatic timeout that is finite should be defined consistently for traces, metrics, and logs, for the ForceFlush() and Shutdown() methods of the Processor, and the Export() and Shutdown() methods of the Exporters. This timeout should ensure these methods never block indefinitely, as per the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#shutdown-1).

**Comment by lalitb** [comment]
#419 fixes it. @ThomsonTan to confirm ?

**Comment by ThomsonTan** [comment]
> #419 fixes it. @ThomsonTan to confirm ?

Yes, set timeout to `std::chrono::microseconds::max()` resolves this issue.
