### ISSUE TITLE
Remove duplicate enum declarations

### ISSUE THREAD

**Issue by xukaren** [open-telemetry/opentelemetry-cpp#420]
Identical enums that are defined in multiple files can be removed and reused instead. An example is the `ExportResult` enum used in the `exporter.h` file in the [trace SDK](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/include/opentelemetry/sdk/trace/exporter.h#L15) and the [logs SDK](https://github.com/open-telemetry/opentelemetry-cpp/pull/403/files#diff-d506356831038e0a23cefad4aa469b1f73ef30b67d9eb8d8910ad42d6d9bf482R33) folders.  Both implement the enum values `kSuccess` and `kFailure`. This enum could be shared instead of redefined in both places.

**Comment by anshulkumar19** [comment]
@xukaren I would like to work on this issue, can you please assign it to me. This seems a tech debt issue and can arise again if further code changes are not merged carefully keeping this in mind. 
Do we have any process or guideline to avoid these kind of issues once fixed, maybe we can integrate a static analysis tool to detect code smells in PR itself.

**Comment by xukaren** [comment]
Yup, thanks so much. @open-telemetry/cpp-approvers should be able to assign you to this :)

**Comment by reyang** [comment]
@anshulkumar19 assigned to you, thanks!
