### ISSUE TITLE
Removing and refactoring `SpanDataAttributeValue`

### ISSUE THREAD

**Issue by xukaren** [open-telemetry/opentelemetry-cpp#442]
Currently in the SDK, `SpanDataAttributeValue`, defined in [trace/attribute_utils.h](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/include/opentelemetry/sdk/trace/attribute_utils.h) has the same implementation as `OwnedAttributeValue` in [common/attribute_utils.h](https://github.com/open-telemetry/opentelemetry-cpp/pull/438/commits/b28a759d0d095d61712ecc9111daa835373fc091#diff-9e843c3a348e462e97fdd4ba3c99136694e8f9acc04c382b40b4e5d7d9758be0). 

The redefinition is redundant for traces, so it can be removed, and all usages of `SpanDataAttributeValue` can be refactored to use `OwnedAttributeValue`.

**Comment by lalitb** [comment]
#482 fixes this.
