### ISSUE TITLE
dynamically generate curl header file with macro if curl installed

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#446]
Based  on comment here:
https://github.com/open-telemetry/opentelemetry-cpp/pull/445#discussion_r542216350
Instead of defining macro for all the `cpp` source files which use curl based http client, it's suggested to instead automatically generate/update the header file for WITH_CURL macro, and ensure we include this header file wherever needed.

**Comment by jsuereth** [comment]
Note: There's also an aspect of the BAZEL build where it'd be ideal if we had a header file that included the necessary -D.  See #444 for an example in bazel where libraries using CURL need to add the defines.

**Comment by lalitb** [comment]
>@lalitb The issue originally reported seem out of date now.

> Could this be closed ?

Yes I think this can be closed now.
