### ISSUE TITLE
empty_attributes.h doesn't include #pragma once

### ISSUE THREAD

**Issue by MarkSeufert** [open-telemetry/opentelemetry-cpp#464]
**Describe your environment** 
I was building an example that included both the exporter's `in_memory_span_exporter.h` and trace's `simple_processor.h`. When I built the project using Bazel, I got the following error: 
```
bazel-out/darwin-fastbuild/bin/sdk/_virtual_includes/headers/opentelemetry/sdk/common/empty_attributes.h:19:6: error: redefinition of 'GetEmptyAttributes'
    &GetEmptyAttributes() noexcept
     ^
bazel-out/darwin-fastbuild/bin/sdk/_virtual_includes/headers/opentelemetry/sdk/common/empty_attributes.h:19:6: note: previous definition is here
    &GetEmptyAttributes() noexcept
```

**What is the expected behavior?**
What I expected was that any header file that gets included more than once would be guarded with `#pragma once`. I found that the `empty_attributes.h` file doesn't contain this guard, and adding it in resulted in my program compiling properly. 

To solve this issue, add `#pragma once` to [this file](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/include/opentelemetry/sdk/common/empty_attributes.h).

**Comment by alolita** [comment]
Should be required for all header files. @MarkSeufert can you submit a PR for this fix?

**Comment by lalitb** [comment]
#479 fixes it.
