### ISSUE TITLE
warning STL4029: std::atomic_*() overloads for shared_ptr are deprecated in C++20

### ISSUE THREAD

**Issue by maxgolov** [open-telemetry/opentelemetry-cpp#475]
Use of functionality that is now frowned upon by C++20 compiler:

https://github.com/open-telemetry/opentelemetry-cpp/blob/b80dccbfffb65b97746aa45f491dcd0c1583ecec/sdk/include/opentelemetry/sdk/common/atomic_shared_ptr.h#L49

Code works. But the construct is deprecated and should be reworked.

`C:\work\opentelemetry-cpp.build_tools\sdk\include\opentelemetry\sdk\common\atomic_shared_ptr.h(49): warning C4996: 'std::atomic_load': warning STL4029: std::atomic_*() overloads for shared_ptr are deprecated in C++20. The shared_ptr specialization of std::atomic provides superior functionality. You can define _SILENCE_CXX20_OLD_SHARED_PTR_ATOMIC_SUPPORT_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.`

**Comment by alolita** [comment]
We should not be using deprecated features. Need to address these warnings in an automated way. E.g. excluding 3rd-party libraries.
