### ISSUE TITLE
Refactor Elasticsearch Log Exporter to use Synchronous HTTP methods

### ISSUE THREAD

**Issue by MarkSeufert** [open-telemetry/opentelemetry-cpp#484]
**Is your feature request related to a problem?**
The Elasticsearch exporter currently uses [asynchronous http requests](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/exporters/elasticsearch/src/es_log_exporter.cc#L181) to communicate with the Elasticsearch instance, where the error and response of the request is received through [callback methods](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/exporters/elasticsearch/src/es_log_exporter.cc#L44). Since the Export() method needs wait for the result of the http request, it has to block until the response is received.

**Describe the solution you'd like**
Using synchronous http requests will simplify the design of the exporter, since there will no longer be a need for the callback methods. Instead, the http request call would look something like:
`auto response = session->SendRequestSync();`

**Additional context**
The synchronous functionality is being added in PR #448, which needs to be merged before this issue can be worked on.

cc - @alolita @xukaren

**Comment by lalitb** [comment]
This can be closed for now. Async http requests are the right approach, as this allows to Cancel/Abort the request as needed.
