### ISSUE TITLE
Extract batch span processor configuration in its own class

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-cpp#497]
**Is your feature request related to a problem?**
It will be good to consistently use a "Options" class for all components in the opentelemetry ecosystem. As an example 
see https://github.com/open-telemetry/opentelemetry-cpp/blob/master/exporters/otlp/include/opentelemetry/exporters/otlp/otlp_exporter.h#L14

**Describe the solution you'd like**
Add a SpanBatchProcessorOptions struct with config members from constructor https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/include/opentelemetry/sdk/trace/batch_span_processor.h#L36

**Describe alternatives you've considered**
Keep a mix of configuration pattern vs arguments to the constructor. This is inconsistent.

**Comment by maxgolov** [comment]
@bogdandrutu - are you suggesting 'generic' configuration, - should this configuration be at the `TracerProvider` level and apply to `Tracer` -> `Exporter` ? Since options might be different for different kinds of exporters: some require networking `host:port`; while others may require file / pipe name / path; some require ingestion / authorization keys in addition to `host:port`, or encoding type / content type, could we reuse either:

- dictionary of key-value variants - property bag similar to `nostd::map<nostd::string_view, common::AttributeValue>` [ref](https://github.com/open-telemetry/opentelemetry-cpp/blob/f9db910ff1be246cbc6e29b4e10683be9daa562c/api/include/opentelemetry/common/attribute_value.h#L13)

or 

- string-based or JSON-string based or XML string-based configuration

?

**Comment by lalitb** [comment]
@bogdandrutu  - We need more details on how you expect it to be done. As mentioned by @maxgolov  - options would differ across components. Currently, this is what we are doing for Zipkin :

https://github.com/open-telemetry/opentelemetry-cpp/blob/84b0458ad857bf656dc72046982c9b31a8b7ad18/exporters/zipkin/include/opentelemetry/exporters/zipkin/zipkin_exporter.h#L22

```
struct ZipkinExporterOptions
{
  // The endpoint to export to. By default the OpenTelemetry Collector's default endpoint.
  std::string endpoint     = ZIPKIN_ENDPOINT_DEFAULT;
  TransportFormat format   = TransportFormat::JSON;
  std::string service_name = "default-service";
  std::string ipv4;
  std::string ipv6;
};

class ZipkinExporter
{
    ZipkinExporter(const ZipkinExporterOptions &options);
};
```

**Comment by bogdandrutu** [comment]
My point is that I would like to see a `BatchSpanProcessorOptions` struct and the current BatchSpanProcessor constructor to be changed to `explicit BatchSpanProcessor(std::unique_ptr<SpanExporter> &&exporter, const BatchSpanProcessorOptions options = BatchSpanProcessorOptions.Default());` or include the exporter in the options as well.

**Comment by maxgolov** [comment]
Can we have different exporters have different structs, but optionally implementing a parser, like - `FromJson(json_config)` or `FromString(str_config)` .. in essence, we then consolidate all configuration objects using one common interface. Then if some metaprovider would like to consolidate different exporters - it may pass configuration to those as strings. Then each individual exporter (or configurator for the exporter) knows how to parse, and populate the struct. Maintaining each struct for each exporter unique. One example of generic configuration surface is how it is handled in QT5:
https://doc.qt.io/qt-5/qsettings.html

i.e.
```cpp
class IExporterSettings /* abstract interface */
{
  bool FromJSON(std::string json_config);
  bool FromString(std::string string_config);
}
```

Then every exporter knows how to transform from generic settings by providing its own implementation that populates the good old C struct from that.

**Comment by bogdandrutu** [comment]
I see that as a next step, initially what I want is to have all components have their own Options (later that can implement an interface like you described) and use that object instead of manually passing the config params
