### ISSUE TITLE
CMake find_package failed to import opentelemetry-cpp

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-cpp#513]
We added packaged installation in PR https://github.com/open-telemetry/opentelemetry-cpp/pull/432, which could install opentelemetry-cpp correctly to the designated target. But I got below message while import the installed package from a standalone project.

Seems we missed to pass include dir as `PATH_VAR` for `configure_package_config_file`.

> lib/cmake/opentelemetry-cpp-config.cmake:64 (message):
  File or directory referenced by variable OPENTELEMETRY_CPP_INCLUDE_DIRS
  does not exist !

**Comment by andriy-fd** [comment]
Is there any chance that this happened again? 
We see the same error on gihub after recent changes for runners: https://github.com/actions/runner-images/commit/a0af039ba1565df601a4c5630c264ab777daf66a

error:
```
Make Error at build/vcpkg_installed/x64-windows-static-md/share/opentelemetry-cpp/opentelemetry-cpp-config.cmake:75 (message):
  File or directory
  C:/a/astra-endpoint-otel/astra-endpoint-otel/build/vcpkg_installed/include
  referenced by variable OPENTELEMETRY_CPP_INCLUDE_DIRS does not exist !
Call Stack (most recent call first):
  build/vcpkg_installed/x64-windows-static-md/share/opentelemetry-cpp/opentelemetry-cpp-config.cmake:85 (set_and_check)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  src/telemetry/tracing/base/CMakeLists.txt:5 (find_package) 
```
