### ISSUE TITLE
Add gRPC Instrumentation

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#530]
Add support for  gRPC C++ client and server api calls instrumentation either using
 - gRPC C++ inceptors ( if available - seems to be experimental support for now : https://grpc.github.io/grpc/cpp/classgrpc_1_1experimental_1_1_interceptor.html )
 -  gRPC channel filters - similar to how it is done for OpenCensus ( https://github.com/grpc/grpc/tree/master/src/cpp/ext/filters/census ).

**Comment by ovidiubuligan** [comment]
I see a B3Propagator was commited  today , Is this the recomended format for trace propagation?  Or should the W3C format be used ?

**Comment by lalitb** [comment]
For instrumentations, 

> I see a B3Propagator was commited today , Is this the recomended format for trace propagation? Or should the W3C format be used ?

From instrumentation library prospective, it can be assumed that the right type of propagator would be already set ( refer : https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#global-propagators ). While it is not yet implemented for C++ ( https://github.com/open-telemetry/opentelemetry-cpp/issues/540). 
So there would be api to `set` and `get` default propagator, which would be usable from instrumentation library.

**Comment by bryanuribe** [comment]
Is this still open/available? Would I be able to pick this up?
cc: @alolita

**Comment by maxgolov** [comment]
> I see a B3Propagator was commited today , Is this the recomended format for trace propagation? Or should the W3C format be used ?

Depends on your cloud service provider. w3c should be the default endorsed and recommended:
https://www.w3.org/blog/2019/12/trace-context-enters-proposed-recommendation/

B3 is `optional` and supposed to live in `external` package.

**Comment by maxgolov** [comment]
@bryanuribe - in terms of gRPC w3c context propagation, I think @Hablapatabla is already working in this direction:
https://github.com/open-telemetry/opentelemetry-cpp/pull/729
You can join our channel on Slack to discuss more. Slack channel has more context.

**Comment by maxgolov** [comment]
@alolita - let's discuss this item during C++ SIG call. I guess what we need to achieve:
- generic example that shows how to use ANY propagator: standard + extended set.
- possibly a helper template / utility class that allows our customers to plug in any propagator of their choice.
- validation effort associated with verifying E2E that all propagators are functional.

 I can help with W3C Trace Context validation, early customer feedback, etc. I have customers lined up for that already.

**Comment by maxgolov** [comment]
@bryanuribe - would you be able to join the next C++ SIG meeting? It would be immensely helpful if you can help us with B3 context propagator validation, and maybe covering Amazon-specific context propagator in contrib repo. Slack channel where we can discuss it:
https://cloud-native.slack.com/archives/C01SM7Y71DJ

**Comment by bryanuribe** [comment]
@maxgolov Yes, I will be at the next SIG meeting. Awesome, I will reach out to you over slack

**Comment by alolita** [comment]
@maxgolov will join in for the next SIG meeting - let's discuss.

**Comment by lalitb** [comment]
#729 closes this
