### ISSUE TITLE
Rename HTTPTextFormat to TextMapPropagator

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#536]
As per the specs:
https://github.com/open-telemetry/opentelemetry-specification/blob/b17f8c993af285cfb0b9cfeb872c15911c720ad2/specification/context/api-propagators.md#textmap-propagator

The relevant specs PR : https://github.com/open-telemetry/opentelemetry-specification/pull/793

**Comment by lalitb** [comment]
@TomRoSystems - Can you please assign it to yourself. Not sure why I can't find your alias for Assignees.

**Comment by ThomsonTan** [comment]
Probably need to join the OpenTelemetry community to be part of assignee? See below link for examples. I am assigning this issue to myself just for keeping it for @TomRoSystems. Feel free to take it once you join the community.

https://github.com/open-telemetry/community/issues

**Comment by TomRoSystems** [comment]
> Probably need to join the OpenTelemetry community to be part of assignee? See below link for examples. I am assigning this issue to myself just for keeping it for @TomRoSystems. Feel free to take it once you join the community.
> 
> https://github.com/open-telemetry/community/issues

Thanks. I've already become a member. Please re-assign to me.
