### ISSUE TITLE
Fix condition always false in http_trace_context and create common utils file for propagators

### ISSUE THREAD

**Issue by TomRoSystems** [open-telemetry/opentelemetry-cpp#539]
**Description**
Bug was discovered during review https://github.com/open-telemetry/opentelemetry-cpp/pull/523 :
https://github.com/open-telemetry/opentelemetry-cpp/pull/523#discussion_r563690488

also move common stuff for `http_trace_context.h` and `b3_propagator.h` into one file.

**Comment by TomRoSystems** [comment]
Please assing me to this issue.

**Comment by seemk** [comment]
I believe this can be closed now as this code was refactored out with #608
