### ISSUE TITLE
Instrumentation: Implement Apache HTTP Server module for opentelemetry

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#554]
Enable requests served by Apache HTTP server for distributed tracing via Opentelemetry api/sdk, and contribute it to `opentelemetry-cpp-contrib` repo.

Apache HTTP server provides support for extending the existing core HTTP server functionality through dynamically loadable modules. . Eg, `mod-ssl` is one of the common modules provided by apache to handle HTTPS requests. This approach can be leveraged to hook into the different phases of HTTP request processing to generate span out of that.

Reference : https://httpd.apache.org/docs/2.4/developer/modguide.html

cc @TomRoSystems

**Comment by TomRoSystems** [comment]
Thanks. Please assign me.

**Comment by lalitb** [comment]
This is added in contrib-repo: https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/7.

**Comment by cforce** [comment]
still arm support is missing - https://github.com/open-telemetry/opentelemetry-cpp-contrib/issues/332
