### ISSUE TITLE
Instrumentation: Implement Nginx module for opentelemetry

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#555]
Enable requests served by Nginx server for distributed tracing via Opentelemetry api/sdk, and contribute it to opentelemetry-cpp-contrib repo.

Reference:
1. Creating dynamic modules for nginx: https://www.nginx.com/blog/compiling-dynamic-modules-nginx-plus/#obtain-module
2. Opentracing nginx module: https://github.com/opentracing-contrib/nginx-opentracing

**Comment by seemk** [comment]
I guess we can close this now: https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/nginx
