### ISSUE TITLE
Prometheus server and Exporter interaction 

### ISSUE THREAD

**Issue by Krishna-Koley17** [open-telemetry/opentelemetry-cpp#557]
What kind of change we have to do to hit Prometheus server from Exporter ???
Like code change , config change , address & port setting etc
Any sample code or GitHub reference will be very helpful.

Awaiting for quick response........

Thanks in advanced.

**Comment by lalitb** [comment]
Please create github issue only for Bug or Feature requests. And use Discussion forum or gitter channel for any questions pertaining to usability of api/sdk or given feature. We would be closing this issue. Requesting you to start a new thread under `Discussion` forum, or `gitter` channel.
