### ISSUE TITLE
Add installation instructions for CMake

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-cpp#564]
The install doc is empty which needs to be filled in with details.

https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md

**Comment by maxgolov** [comment]
I can add separate instructions for how to build using `CMake` via GUI - Visual Studio 2019 IDE.

**Comment by lalitb** [comment]
#612 fixes this. @maxgolov - we can create separate ticket for build instruction using VS 2019.
