### ISSUE TITLE
Implement InstrumentationLibrary Instance in SDK

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#567]
As per specs for [Tracer Creation](https://github.com/open-telemetry/opentelemetry-specification/blob/1a0395e482d4fec6faab0ee4b7bc1dc5fdd3e493/specification/trace/sdk.md#tracer-creation) :

`New Tracer instances are always created through a TracerProvider (see API). The name and version arguments supplied to the TracerProvider must be used to create an InstrumentationLibrary instance which is stored on the created Tracer.`

Currently for cpp, we do pass instrumentation library name and version in tracer sdk, but it is never used internally to create `InstrumentationLibrary ` instance, and further passing it to otel (and other) exporters: https://github.com/open-telemetry/opentelemetry-cpp/blob/25a7178a8d703407f4bbf322c16eb044b58c9a2a/sdk/include/opentelemetry/sdk/trace/tracer_provider.h#L35-L37 

As per the otel protocol:
https://github.com/open-telemetry/opentelemetry-proto/blob/e73df7c9f3c474c992990e82aa09ee46c39d6aab/opentelemetry/proto/common/v1/common.proto#L72-L78:

```proto
// InstrumentationLibrary is a message representing the instrumentation library information
// such as the fully qualified name and version. 
message InstrumentationLibrary {
  // An empty instrumentation library name means the name is unknown. 
  string name = 1;
  string version = 2;
}
```

 

`

**Comment by ThomsonTan** [comment]
Do we need create a definition of `InstrumentationLibrary` for SDK or reuse the definition from OTLP? Reuse it will introduce dependency on protobuf.

**Comment by lalitb** [comment]
> Do we need create a definition of `InstrumentationLibrary` for SDK or reuse the definition from OTLP? Reuse it will introduce dependency on protobuf.

Yes, we need to create SDK implementation, and then propagate to otlp exporter.
