### ISSUE TITLE
Add Getting Started / Quick Start guide

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#571]
Probably as separate markdown doc which can be referenced from main page. 
As an example, how it is done by in Java:
https://github.com/open-telemetry/opentelemetry-java/blob/main/QUICKSTART.md

**Comment by PrathameshAshra** [comment]
Can i take care of this ?
 I am planning to create a new .MD file and which will be a better version of
  https://github.com/open-telemetry/opentelemetry-cpp#quick-start
 the inspiration would be taken from 
 https://github.com/open-telemetry/opentelemetry-java/blob/main/QUICKSTART.md

**Comment by lalitb** [comment]
Sure @PrathameshAshra . Thanks for extending the help. Assigning to you. Would be good if you can come up some initial doc sometime next week, and we can then incrementally enhance it subsequently.
cc @pyohannes as he has plan to integrate it with API doc.

**Comment by PrathameshAshra** [comment]
thanks @lalitb, would keep @pyohannes in loop. meanwhile would try to come up with initial doc or something like template ish.

**Comment by PrathameshAshra** [comment]
@pyohannes , any suggestions before I start  ? 
I am  looking forward for something like https://github.com/open-telemetry/opentelemetry-java/blob/main/QUICKSTART.md but for CPP

**Comment by pyohannes** [comment]
The Java QuickStart guide is a good template to follow. We currently only need sections for _Set up_, _Tracing_, and _Tracing SDK Configuration_. We should also cover multi-threaded scenarios (like in this [example](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/multithreaded/main.cc)).

I added a very minimal _Getting started_ as a [main page of the API documentation](https://github.com/open-telemetry/opentelemetry-cpp/pull/582/files), but we also need something more comprehensive.

If you're in doubt it's best you get up a WIP PR with a rough draft or outline, and we can go from there.

**Comment by lalitb** [comment]
Closing this, as we have a Getting started guide in place. Will create separate issues for SDK docs/api and target for GA milestone.
