### ISSUE TITLE
Is centos a viable deployment option? 

### ISSUE THREAD

**Issue by sandakith** [open-telemetry/opentelemetry-cpp#577]
Trying out opentelementry for the first time and wanted to check first if centos 7 is a option for deployment. Also, tried to search around previos issues and it seems folks run into issues with it. Appreciate if anyone can comment on their experience on compiling/running opentelemetry-cpp in centos varients

**Comment by ThomsonTan** [comment]
@sandakith I am not aware of any known installation issue specific to centos (at least for CMake package installation). Free free to try it and report the issue here if any.

**Comment by lalitb** [comment]
Github doesn't provide any  `rpm` based virtual environment to deploy and test, so all our CI pipelines are based on `ubuntu`. Our setup sciripts are specific to `deb` environment ( `ci/setup_cmake.sh`, `./ci/setup_ci_environment.sh` ), so you may have to setup the environment yourself, followed by running bazel/cmake to build/test. Would look forward to experience.

**Comment by lalitb** [comment]
Closing this ticket. Let us know if you need further help.
