### ISSUE TITLE
The sampled flag using Context HTTP Propagator

### ISSUE THREAD

**Issue by isma3ilovich** [open-telemetry/opentelemetry-cpp#615]
Hello,

I am using HttpTraceContext to inject my  context 
`   opentelemetry::trace::Scope scope(rootSpan);
   propagatorFormat.Inject(Setter, headers,opentelemetry::context::RuntimeContext::GetCurrent());`

The sampled flag  is always 00 ( not sampled)

I'm using AlwaysOnSampler 

`  auto provider = nostd::shared_ptr<opentelemetry::trace::TracerProvider>(
      new sdktrace::TracerProvider(processor, opentelemetry::sdk::resource::Resource::Create({}),
                                   std::make_shared<opentelemetry::sdk::trace::AlwaysOnSampler>()));`

How i can change sampled flag ?

Thanks .

**Comment by lalitb** [comment]
@isma3ilovich  - Just to confirm if you are using the latest code, as there were some changes done on propagating sampled flag:
https://github.com/open-telemetry/opentelemetry-cpp/pull/603/files

**Comment by isma3ilovich** [comment]
@lalitb  Thanks for your quick reply.
No,I am using  v0.2.0

**Comment by lalitb** [comment]
We plan to have new v0.3.0 release today, or early next week. Meanwhile, if you would like to try with latest commit.

**Comment by isma3ilovich** [comment]
@lalitb  The issue is resolved with latest commit.
Thanks.
