### ISSUE TITLE
Enable tls authentication for otlp grpc exporter

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#629]
As of now, otlp-grpc exporter doesn't support tls authentication :

https://github.com/open-telemetry/opentelemetry-cpp/blob/9aae3e64bdc71520fd3b737bc054ad8c604aead5/exporters/otlp/src/otlp_exporter.cc#L36-L41

This needs to be supported. The certificate should be made available to exporter programmatically and (optionally) through environment variable:

OTEL_EXPORTER_OTLP_CERTIFICATE 
OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE 
OTEL_EXPORTER_OTLP_METRICS_CERTIFICATE

Reference -
 [specs](
https://github.com/open-telemetry/opentelemetry-specification/blob/f62744a679814937214fd17394ab3fa8a9099424/specification/protocol/exporter.md)

**Comment by maxgolov** [comment]
Environment variables have effect on entire process. Does it mean that a single process can only utilize one and only set of certificates, for streaming to only one end-point at a time, and "dual-home" as a a concept cannot be supported? There may be other scenarios, where the code should dynamically rotate the cert, like it is done with KeyVault `GetCertificates` API at runtime. I realize it's more of a spec question rather than implementation question, but having this "hardcoded" via environment variable does not seem to meet the needs of a robust and secure production system.

**Comment by maxgolov** [comment]
Can we have a provision in our API to abstract away the environment variables, such as `GetCertificate` API in SDK. That way we can augment the actual implementation with more secure implementation that may not necessarily obtain the cert based on environment variable. Nearly all OS and Languages provide some form of crypto API for certificate management, including REST APIs for automated certificate rotations in the cloud.

**Comment by pyohannes** [comment]
> Environment variables have effect on entire process. Does it mean that a single process can only utilize one and only set of certificates, for streaming to only one end-point at a time, and "dual-home" as a a concept cannot be supported?

According to the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-configuration.md#programmatic), the SDK needs to make every configuration available programmatically:
> The SDK MUST provide a programmatic interface for all configuration.

This should give full flexibility in configuration.

Configuration via environment variables is [optional](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md):
> SDKs MAY choose to allow configuration via the environment variables in this specification, but are not required to. 

So we might not make the OTLP exporter configurable by environment variables, but we for sure need to add a programmatic way to support specifying TLS certificates.

**Comment by lalitb** [comment]
Thanks @pyohannes , @maxgolov  - Have updated the issue details accordingly.

**Comment by padmaja-nadkarni** [comment]
I made a change in my fork of this repository to support SslCredentials by specifying the path to cacert pem file via grpc::SslCredentialsOptions. Following is a snippet of that code. If this feels appropriate, I am happy to contribute:

```
if (options.use_ssl_credentials) {
      grpc::SslCredentialsOptions ssl_opts;
      ssl_opts.pem_root_certs= get_file_contents((options.ssl_credentials_cacert_path).c_str());;
      auto channel_creds = grpc::SslCredentials(ssl_opts);
      channel = grpc::CreateChannel(options.endpoint, channel_creds);
  }
```

**Comment by lalitb** [comment]
Thanks @padmaja-nadkarni  - would be great to get this contribution.  Please go ahead and raise the PR.
