### ISSUE TITLE
non-inline functions in api/include/opentelemetry/trace/propagation/detail/*.h

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#642]
This will cause linking error if these functions are used across multiple instrumentation units, and later linked together in application.

**Comment by ThomsonTan** [comment]
Wondering why it doesn't cause link error now?

**Comment by lalitb** [comment]
https://github.com/open-telemetry/opentelemetry-cpp/blob/c03cc612b619bd87b32e270566f12162b98ef9a5/api/include/opentelemetry/trace/propagation/detail/context.h#L12

https://github.com/open-telemetry/opentelemetry-cpp/blob/c03cc612b619bd87b32e270566f12162b98ef9a5/api/include/opentelemetry/trace/propagation/detail/hex.h#L35

https://github.com/open-telemetry/opentelemetry-cpp/blob/c03cc612b619bd87b32e270566f12162b98ef9a5/api/include/opentelemetry/trace/propagation/detail/hex.h#L44

https://github.com/open-telemetry/opentelemetry-cpp/blob/c03cc612b619bd87b32e270566f12162b98ef9a5/api/include/opentelemetry/trace/propagation/detail/string.h#L17

**Comment by lalitb** [comment]
> Wondering why it doesn't cause link error now?

If we have two different libraries instrumented ( say mysql and sqlite ) using our api, and later try linking both these libraries in an application, we should see the linking error. As these free functions would be defined in both these instrumented libraries. I don't think we tested that.

**Comment by seemk** [comment]
That slipped in :thinking: Think it's ok to make `api` a non-interface library having its compiled sources? Not sure it makes sense to inline everything

**Comment by lalitb** [comment]
> Think it's ok to make `api` a non-interface library having its compiled sources?

How can this be done, as the `api` is supposed to be a header-only library?

**Comment by seemk** [comment]
Ah I just saw (https://github.com/open-telemetry/opentelemetry-cpp/blob/main/docs/requirements.md)

But why does such a requirement exist?

**Comment by lalitb** [comment]
> But why does such a requirement exist?

I think it's the ease of use for devs of instrumented libraries, as they just need to include opentelemetry API headers for instrumentation, and no need to worry about building api as a static/shared library before use. Also, this ensures that api and instrumented libraries are built using the same compiler which eliminates the ABI incompatibility that may arise because of the different compiler or different version of the same compiler. Although we do mitigate this ABI incompatibility by ensuring not to use certain stl classes across interface boundaries.

@pyohannes @maxgolov can add more if required as they have more history of it :)

**Comment by eyakimov-bbg** [comment]
I think we covered this a bit in : https://github.com/open-telemetry/opentelemetry-cpp/blob/main/docs/library-distribution.md
not sure how out of date this is at this point. In any case, unfortunately I've just been bit by the lack of these inlines too :(

**Comment by eyakimov-bbg** [comment]
> Wondering why it doesn't cause link error now?

This would only create a link error if two different **built** targets include this. Given that api doesn't produce a built target by itself (since its header only), if only one child library uses this these headers then you will not have a problem. You will need two built targets to trigger this error. For example, lets say you build opentelemetry-sdk that pulls in this code from opentelemetry-api, and then lets say we add a new test that depends on opentelemetry-sdk AND it uses this code from opentelemetry-api, only then would you trigger this condition
