### ISSUE TITLE
Allow to programmatically populate settings for OTELResourceDetector

### ISSUE THREAD

**Issue by maxgolov** [open-telemetry/opentelemetry-cpp#656]
Presently resource detector uses environment variable here:

https://github.com/open-telemetry/opentelemetry-cpp/blob/484700a0da2547852653271d2bdc10b50830bb86/sdk/src/resource/resource_detector.cc#L15

This approach won't work for Windows Universal Store (e.g. Xbox) applications:
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps.md

Because these applications cannot use environment variables. There may be some alternative approach available to populate the variable programmatically? e.g. using something like `OTELResourceDetector::SetResourceAttributes(...)` , that way the `Detect` method can still return the `Resource` object successfully after. But this time - it is built from programmatically-passed value, not obtaining it from env var.

Then UWP store app may use some remote config provisioning technique to obtain the settings, e.g. from remote JSON file first. Then pass these resource values to `OTELResourceDetector` via `SetResourceAttributes`. Then the rest of code should still be able to call into `OTELResourceDetector().Detect()` as before. Auto-detecting the settings passed to it via API, not from env var.

This small improvement should make the SDK compile'able for Universal Store / Xbox apps. This is not affecting system services, or web-services. But may become relevant if SDK is used in client apps at some point in future. We can add the necessary `#ifdef WINDOWS_UWP` to avoid `getenv` if targeting Xbox Games or Windows Universal Store apps.

@lalitb

**Comment by lalitb** [comment]
@maxgolov  there are three approaches to specify the resource attributes according to  specs 
- [Resource::Create](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#create): Resource attributes can be specified as an argument to this function. This is something that can be leveraged by UWP.
- [Custom resource detectors](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#create): Custom resource detectors can be created for platforms ( eg, UWP here) outside SDK. This can be created in a way not depend on the env variable. 
- [OTEL_RESOURCE_ATTRIBUTES](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#create) - Probably need input from others, but to me, it should be fine to have something like  `#ifdef ENV_VARIABLE_NOT_SUPPORTED` to avoid getenv calls across SDK, and so skip resource setting through this env variable,

**Comment by lalitb** [comment]
@max, should we be using the `GetEnvironmentVariable` function to read the env variables for Windows instead of `getenv`/`getenv_s` for Windows, as this is supported by UWP apps too, similar to how it is done by libcurl (https://github.com/curl/curl/blob/master/lib/getenv.c). Apart from that, we can have a more generic macro check like (say) `ENV_VARIABLE_NOT_SUPPORTED` for the scenario where a custom resource detector needs to be used instead of env variables.

**Comment by lalitb** [comment]
This can be closed, as env-var are used only if NO_GETENV macro is not defined.
