### ISSUE TITLE
`sdk::Trace::SpanDataLink` doesn't give access to key link information

### ISSUE THREAD

**Issue by eyjohn** [open-telemetry/opentelemetry-cpp#657]
**Is your feature request related to a problem?**
I was trying to read the links for testing purposes, only to realise that the key part of the link (the span context referenced) isn't accessible. A TODO kinda summarises the gap here:
https://github.com/open-telemetry/opentelemetry-cpp/blob/afa2e79819a2fddb44487db8ffdf95aa62f47fc7/sdk/include/opentelemetry/sdk/trace/span_data.h#L64

**Describe the solution you'd like**
There are a few ways of fixing this.
1. As per the TODO, forward all accessors of the held `SpanContext` to the `SpanDataLink`
2. Inherit `SpanDataLink` from `SpanContext` (similar interfaces to the above)
3. Provide an accessor (ideally const &) to the held `SpanContext`

Personally, I suggest 3, given that the specification mentioned that the SpanContext (presumably in its entirety, including trace_state/flags and any future features...) to be part of the Link: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#specifying-links  . This would be the same for 2, but for 1 it suggests that this class needs to be forever paired with SpanContext and co-evolve. 

**Describe alternatives you've considered**
None available, 3 options of how to address this have been highlighted above.

**Comment by lalitb** [comment]
Thanks for reporting the issue, Agree on option 3 as the preferred option. We already return a const reference to the attributes map, so can add another method to return a const reference to `SpanContext`. 

Time to start looking into all TODOs (#604 )
