### ISSUE TITLE
List of components and their dependent component licenses

### ISSUE THREAD

**Issue by maxgolov** [open-telemetry/opentelemetry-cpp#683]
**List of components and their Copyright notices / Licenses**

All code contributed in this repo is licensed under **Apache License v2.0** with a few notable exceptions:

- [MPark Variant](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/nostd/mpark/variant.h) - Boost license. This code can be removed entirely and replaced by Google Abseil implementation, that is **Apache License v2.0** ( #572 ) . That ultimately allows all of OpenTelemetry C++ API be licensed under the same **Apache License v2.0**.

- [HTTP client](https://github.com/open-telemetry/opentelemetry-cpp/tree/main/ext/include/opentelemetry/ext/http/client/curl) presently depends on [libcurl](https://curl.se/libcurl/) , which is implemented under its own [MIT/X-alike license](https://curl.se/docs/copyright.html) . This is required for Zipkin and Elastic exporters.

- [nlohmann/json](https://github.com/nlohmann/json) - _Required_ for Zipkin and Elastic exporter. _Required_ for zPages. And _Optional_ for specific subtype of ETW exporter. The library is licensed under [MIT License](https://github.com/nlohmann/json/blob/develop/LICENSE.MIT). Products builds that are shipping with OTLP gRPC exporter or ETW exporter, and NOT including zPages - do not require this module, but it may come in handy for other aspects, e.g. remote provisioning of exporter using JSON configuration.

- [TraceLogging Dynamic for Windows](https://github.com/microsoft/tracelogging-dynamic-windows) library - strongly recommended for ETW exporter, as default transport channel - is also [MIT License](https://github.com/microsoft/tracelogging-dynamic-windows/blob/main/LICENSE). Products shipping on Linux do not require this component.

- Certain other parts of OTLP exporter may require **Boost** ? cc: @ThomsonTan to confirm on where it will be required.

**Proposal**

The goal is to **create a markdown document that captures above detail with all the licenses**; alongside with build options that enable these components mentioned above. Not every build combo requires all the licenses. Having the OSS components document enables any product commercially shipping with OpenTelemetry C++ SDK to easily list all the required licenses in their distro, prepackaged build of SDK. Reference example of [OSS components document](https://github.com/microsoft/cpp_client_telemetry/blob/master/docs/List-of-OSS-Components.md) that we need to add to the repo.

**Comment by lalitb** [comment]
Moving to GA milestone as this is documentation change.

**Comment by lalitb** [comment]
#844 resolves this.
