### ISSUE TITLE
Simplify sdk library structure

### ISSUE THREAD

**Issue by eyjohn** [open-telemetry/opentelemetry-cpp#684]
The sdk is currently structured a little inconsistently compared to some of the other packages/areas in that it has a shared headers target but a separate built target for each section.

It may be simpler to either:
1. Mimic the structure of exporters where multiple libraries are defined at root level with select headers that apply to just them e.g. [exporters_ostream](https://github.com/open-telemetry/opentelemetry-cpp/tree/main/exporters/ostream) 
2. Create a megalibrary of just "sdk", this would be simpler but create a much bigger build target/dependency both internally and with external projects. If this is deemed a favourable direction then it probably makes sense to do this in exporters too.

I'm also hoping this allows us to eliminate "src" in all the target names e.g. "//sdk/src/trace", I don't really see any value in having a different naming structure for the header only sections of the sdk versus the compiled sections.

Whichever way this is done, it'll be quite a sweeping change and should probably be timed with the least amount of active PRs open in the sdk to reduce breakages.

**Comment by lalitb** [comment]
As per my understanding, this was planned as per the source code distribution package we plan to release  - one package each for API and SDK, and separate packages for the exporters. If we later decide to move to have API and SDK packages for each of the signals ( trace, logs, metrics), the first option would make sense.

**Comment by maxgolov** [comment]
I agree with both statements, that we could have made it "more flat" .. And at the same time - we need to keep the `api` package separate. For example: ETW exporter (header-only) presently uses near-zero code from `sdk`. So any churn in `sdk` is not affecting ETW exporter. About the same comment would apply to other exporters or SDKs implemented simply based off `api` contract. 

I'm also wondering if we could have something like a single header, e.g. `#include <opentelemetry/opentelemetry.h>` that would have been an umbrella header that refers to the necessary functionality and features via including something like `<opentelemetry/config.h>` and including all other accessory headers (api, nostd, etc.) within?

**Comment by eyjohn** [comment]
Ok, since the goal is to keep sdk as a single unit, any concerns with flattening this to a single build target? At the moment we have a target for the headers only, as well as a target for each subfolder for the compiled artefacts. I'm suggesting having only a single target for ALL sdk (one CMakeLists.txt/BUILD with only one library target). 

_(I think it is possible to have a composable workflow in CMake, i.e. build lots of small libraries and then bundle them into a single library, but IIRC this only works for static libraries and would be non-trivial, also not sure about doing this for bazel, so would rather avoid this)_

If we go down this path, users only need to specify a dependency on sdk as a whole rather than the specific sections of the sdk that they use i.e. only this is required: https://github.com/open-telemetry/opentelemetry-cpp/blob/a3755f492cb1de671f348b33bd4965b4eac995d3/opentelemetry-cpp-config.cmake.in#L24 (and lines 26-30 will cease to exist)

For tests, we can still either keep them separate targets as they are today, or combine them into a single test target. In my organisation, we tend to group them into a single target based on the "type" of test, unit vs integration vs performance/benchmark but I'm interested in what others think about this?

**Comment by lalitb** [comment]
I like the idea of consolidating sdk as a single build target, and it's consistent with the way we build `api` (though it's all header). And specifically targets like `common`, `version`, `resource` doesn't make sense to exist separately. The only concern is whether will this will enforce users to include complete sdk target even though they are interested in a specific signal (say traces)  

The above proposal is definitely aligned to have a single sdk package which we have been talking about. and would like to hear more thoughts to agree on it. Thanks for proposing it.

**Comment by lalitb** [comment]
@eyjohn  - Regarding the proposal for a single sdk build-target, it was discussed briefly in today's community meeting. One of the suggestions was to have a build option for creating a single sdk build target for CMake, and let the default build create the multiple targets ( as it is done now ). Later on, based on the usage, we can switch to have a single sdk target for both CMake and bazel.  We can continue discussing this here, or in the next community meeting as you want.

**Comment by maxgolov** [comment]
What do you think about optional build target that would consolidate the standard set of everything into one single library?

Or maybe building more than one flavor of it, i.e. for Windows that could be a
- .dll `[/MD|/MDd]`
- static .lib with dynamic runtime `[/MD|MDd]`
- static lib with static runtime `[/MT|MTd]`

That way ultimately the package would contain only ONE set of headers and ONE .lib (+ optionally .dll for the 1st flavor mentioned above). The integration then requires inclusion of only one library `libOpenTelemetry-v1[.a|.so]` or `OpenTelemetry-v1.lib|.dll`, not needing to link separate components.

The way how I see it - we could have had a build combo that controls what exporters you want to include in one library. And if I need non-standard custom vendor exporters, I can still build one binary with just my build combo. In `CMake` this is relatively easy to achieve, esp. in latest version of CMake 3.19/3.20 and above, which provides configuration presets.

It is akin to building `ffmpeg.exe` with that or the other set of features included. Having more than one .lib or .a file in a build system is unusual, to say the least. Much bigger projects usually end up needing just one linkable build artifact. It would be good if we provide a single target like this.

**Comment by eyjohn** [comment]
On the overall topic of one-lib vs many libs, I think there are merits to both composable builds that give users control of exactly what they want to build and link versus a much easier to handle. Arguably this applies at API vs SDK vs exporters level too but the Spec has kinda enforced some requirements there.

With that said, my overall gut feel is that simplicity of use in most contexts would be the most important priority, with better composition (i.e. I only need trace so don't give me metrics) and more configurable build options (i.e. I don't need exporter foo so don't build it) coming second.

Based on this I would suggest just having build targets for libOpenTelemetry_api (header only, no linkage), libOpenTelemetry_sdk, libOpenTelemetry_ext and libOpenTelemetry_exporters, (the exact content of exporters would be dependent on the configured build flags). I would suggest resolving this linkage convention prior to GA as we can't easily change this afterwards.

We do have the option of producing both composable and combined artefacts, e.g. have both libOpenTelemetry_sdk.so AND libOpenTelemetry_sdk_trace.so (and metrics/common/etc...) where users can choose which they want to link against, but I fear this would add more complexity and take us further from the "simplicity of use" motivation.

I'm happy to go and implement this "both" options variant to start but I do think that switching to the combined builds only in the future is likely to make using OpenTelemetry simpler, albeit with slightly more build time/size overhead. 

---

@maxgolov I loosely agree with supporting a range of build targets for different use-cases, I'm still not convinced about bundling vendor exporters as per discussion in https://github.com/open-telemetry/opentelemetry-cpp/issues/713, but I agree with having the libraries built for the three variants above. I'm not sure if we already have this but enabled_shared/enabled_static build options can be added to configure what you build/export. In Linux, it would be common to bundle headers + static libs in a -dev package and the .so in the runtime package.

--- 

Somewhat related to composable + combined builds. I would suggest a new naming convention for the composable libraries in SDK of libOpenTelemetry_sdk_trace rather than libOpenTelmetry_trace which is what I think we use today, same for exporters tbh. This would avoid possible naming clashes such as if we wanted to do something like ext/trace in the future to say bundle some trace utilities/extras.
