### ISSUE TITLE
opentelemetry cpp unable to connect to collector

### ISSUE THREAD

**Issue by contractormarketplace** [open-telemetry/opentelemetry-cpp#696]
I am running the example program provided :-

opentelemetry-cpp/examples/simple/example_simple

The program is not sending spans to the collector. 

**Environment

OS: Ubuntu 20.04.2 LTS
Collector Version aws-otel-collector-0.8.0
Dataprepper Version 0.8.0-beta

**Comment by contractormarketplace** [comment]
collector and data prepper configurations are attached

[otel-collector-config.yml.txt](https://github.com/open-telemetry/opentelemetry-cpp/files/6376192/otel-collector-config.yml.txt)
[trace_analytics_no_ssl.yml.txt](https://github.com/open-telemetry/opentelemetry-cpp/files/6376193/trace_analytics_no_ssl.yml.txt)

**Comment by maxgolov** [comment]
This example is not actually sending to `OTLP` exporter, but to `OStreamSpanExporter`

https://github.com/open-telemetry/opentelemetry-cpp/blob/a3755f492cb1de671f348b33bd4965b4eac995d3/examples/simple/main.cc#L14

Have you modified it to use OTLP exporter instead, if so - could you please attach your modified example.

**Comment by contractormarketplace** [comment]
Thanks @maxgolov for your guidance. 

I updated the code to have OtlpExporter as follows :

  auto exporter = std::unique_ptr<sdktrace::SpanExporter>(
      //new opentelemetry::exporter::trace::OStreamSpanExporter);
      new opentelemetry::exporter::trace::OtlpExporter);

But the code does NOT compile, the include file included from otlp_exporter.h, includes the following

opentelemetry/proto/collector/trace/v1/trace_service.grpc.pb.h

But the above file is NOT in the source anywhere and hence the compile issue. Can you clarify? I have attached the modified source for your reference.
[main.cc.txt](https://github.com/open-telemetry/opentelemetry-cpp/files/6398825/main.cc.txt)

**Comment by ThomsonTan** [comment]
> Thanks @maxgolov for your guidance.
> 
> I updated the code to have OtlpExporter as follows :
> 
> auto exporter = std::unique_ptrsdktrace::SpanExporter(
> //new opentelemetry::exporter::trace::OStreamSpanExporter);
> new opentelemetry::exporter::trace::OtlpExporter);
> 
> But the code does NOT compile, the include file included from otlp_exporter.h, includes the following
> 
> opentelemetry/proto/collector/trace/v1/trace_service.grpc.pb.h
> 
> But the above file is NOT in the source anywhere and hence the compile issue. Can you clarify? I have attached the modified source for your reference.
> [main.cc.txt](https://github.com/open-telemetry/opentelemetry-cpp/files/6398825/main.cc.txt)

Did you build opentelemetry-cpp with OTLP? With CMake, you'll need passing `-DWITH_OTLP=ON` to its configuration command line.

**Comment by maxgolov** [comment]
@ThomsonTan - I wonder if we can make it default? And only if we are running on a system where we can't compile it (e.g. checking compiler version in CMake script), we toggle it off.. Or we can toggle it off if CMake can't find gRPC. Then OTLP will always be on by default.

**Comment by ThomsonTan** [comment]
Concur the idea to enable OTLP by default as it will be the major exporter for OpenTelemetry. I don't suggest to turn off building it if missing dependence is detected which could cause confusion (for the case OTLP is wanted, doing build without it is wasting time comparing with fail early), but prompt which dependence is missing and show flag to turn OTLP off will be very helpful.

**Comment by lalitb** [comment]
@contractormarketplace - Closing this issue. Please use the example from here: https://github.com/open-telemetry/opentelemetry-cpp/tree/main/examples/otlp, and create a ticket if it doesn't work.
