### ISSUE TITLE
context: support getting and setting span without a key

### ISSUE THREAD

**Issue by seemk** [open-telemetry/opentelemetry-cpp#711]
It is not possible get and set the span on a context without using the span key, e.g. current usage of getting a span:

```c++
ctx.GetValue(trace::kSpanKey);
```
According to the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#context-interaction):
```
The API MUST provide the following functionality to interact with a Context instance:
- Extract the Span from a Context instance
- Insert the Span to a Context instance

The functionality listed above is necessary because API users SHOULD NOT have access to the Context Key used by the Tracing API implementation.
```

The key based access is used everywhere internally and externally, for example nginx instrumentation has a helper function for the same purpose: https://github.com/open-telemetry/opentelemetry-cpp-contrib/blob/main/instrumentation/nginx/src/propagate.cpp#L102

We do have a helper function called `GetCurrentSpan` in propagators' detail namespace:
https://github.com/open-telemetry/opentelemetry-cpp/blob/d1f0b136e3cf88e3d13b2b979520fafe32705319/api/include/opentelemetry/trace/propagation/detail/context.h#L12-L20

Similar function in the JS API:
https://github.com/open-telemetry/opentelemetry-js-api/blob/b5784d30e51f5f7ffbdba0e6b83c07dd23b50c8d/src/context/context.ts#L44-L46

I propose renaming `GetCurrentSpan` in `trace::propagation::detail` to `GetSpan` (also making it return a span not span context) and move it to a proper header and namespace. In a similar way `SetSpan` should be added.

**Comment by lalitb** [comment]
I Agree. The current location and namespace look good, I don't think we are using it outside propagators.
