### ISSUE TITLE
Compliance Matrix Validation for rel1.0.0 - Baggage , Resource

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#718]
This ticket is to validate the below attributes of the Spec Compliance Matrix for Rel 1.0.0. While validation, if there is any ticket created for non-compliance, mention that next to the non-compliant point below in the description.

Link: 
Baggage: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/spec-compliance-matrix.md#baggage
Resource: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/spec-compliance-matrix.md#resource

Baggage:
* [ ] Basic Support
* [ ] Use official header name baggage

Resource:
* [ ] Create from Attributes
* [ ] Create empty
* [ ] Merge (v2)
* [ ] Retrieve attributes
* [ ] Default value for service.name

**Comment by maxgolov** [comment]
One issue we need to fix for `Resource` API : #733

**Comment by lalitb** [comment]
**[Baggaget](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/spec-compliance-matrix.md#baggage)**

> *Basic Support* : 

https://github.com/open-telemetry/opentelemetry-cpp/blob/v0.7.0/api/include/opentelemetry/baggage/baggage.h

> *Use official header name baggage*

https://github.com/open-telemetry/opentelemetry-cpp/blob/ac0e6174e74f845e7d375a156b5abea33956c056/api/include/opentelemetry/baggage/propagation/baggage_propagator.h#L13

**Comment by lalitb** [comment]
**[Resource](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/spec-compliance-matrix.md#resource)**

> *Create from Attributes*

https://github.com/open-telemetry/opentelemetry-cpp/blob/ac0e6174e74f845e7d375a156b5abea33956c056/sdk/src/resource/resource.cc#L30


> *Create empty*

https://github.com/open-telemetry/opentelemetry-cpp/blob/ac0e6174e74f845e7d375a156b5abea33956c056/sdk/src/resource/resource.cc#L48

> *Merge (v2)*

https://github.com/open-telemetry/opentelemetry-cpp/blob/ac0e6174e74f845e7d375a156b5abea33956c056/sdk/src/resource/resource.cc#L23

> Retrieve attributes

https://github.com/open-telemetry/opentelemetry-cpp/blob/ac0e6174e74f845e7d375a156b5abea33956c056/sdk/src/resource/resource.cc#L62

> Default value for service.name

https://github.com/open-telemetry/opentelemetry-cpp/blob/ac0e6174e74f845e7d375a156b5abea33956c056/sdk/src/resource/resource.cc#L37

**Comment by lalitb** [comment]
Validated all the specs compliance points.
