### ISSUE TITLE
Add sampling API

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-cpp#72]
Add sampling API which follows https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-sampling.md.

**Comment by pyohannes** [comment]
Some notes:
* This is the related [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#sampling).
* When working on designing the interface, consider the project's [ABI policy](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/docs/abi-policy.md).
* This work depends on the [`SpanContext`](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#spancontext), which is not available yet. Coming up with a `SpanContext` implementation is probably a prerequisite.
* Ideally, first open a PR with the proposed sampler API, then work on the implementation of individual samplers once this is approved.
* Consider implementations in other projects:
  - [Java](https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/src/main/java/io/opentelemetry/sdk/trace/Sampler.java)
  - [Go](https://github.com/open-telemetry/opentelemetry-go/blob/master/api/trace/sampler.go)
  - [Python](https://github.com/open-telemetry/opentelemetry-python/blob/master/opentelemetry-api/src/opentelemetry/trace/sampling.py)

**Comment by reyang** [comment]
More notes:
* Algorithm to ensure consistent probability sampling across services [draft spec](https://github.com/open-telemetry/opentelemetry-specification/pull/331).

**Comment by reyang** [comment]
Related PRs: #118 #122 #125 #126 #128 #136 #142 #119 #136 #175 #199 #238
