### ISSUE TITLE
Avoid pointer to reference to temporaries in `SetResource` API

### ISSUE THREAD

**Issue by maxgolov** [open-telemetry/opentelemetry-cpp#733]
**Repro Steps**

- Compile with standard library (STL) classes.
- Run all tests: 335 tests passed; 10 tests failed (all related to `SetResource` API).

![image](https://user-images.githubusercontent.com/34072974/117610929-6c0baa00-b117-11eb-9124-4e76de07aa04.png)

@lalitb - this is problematic spot. It won't work too well with temporaries because it's assigning a pointer to reference.

If `Resource` is compiled with `std::variant`. And a temporary is passed to API, e.g.

`SetResource("key", "value")`

It'd break.. Sorry, I found it just now. Haven't noticed during code review originally.. :( Now I tagged the spot in review below:

https://github.com/open-telemetry/opentelemetry-cpp/pull/706#r629059711_

**Exact Problematic Test Spot**

![image](https://user-images.githubusercontent.com/34072974/117611007-8fcef000-b117-11eb-8ef3-8d5099b3ec2b.png)

Same issue across all 10 tests.

**How to Fix**

We need to avoid a pointer to temporary here. Since `Resource` values are not changing often, perhaps a copy is more appropriate than a pointer?

**Comment by lalitb** [comment]
This is not related to `resource` sdk implementation, but the result of implicit conversion of `const char *` (or any pointer type ) to bool as specified in C++17 working draft:
https://timsong-cpp.github.io/cppwp/n4659/conv#bool

``
7.14 Boolean conversions

A prvalue of arithmetic, unscoped enumeration, pointer, or pointer to member type can be converted to a prvalue of type bool. A zero value, null pointer value, or null member pointer value is converted to false; any other value is converted to true. For direct-initialization, a prvalue of type std​::​nullptr_­t can be converted to a prvalue of type bool; the resulting value is false.
``

There is a proposal to consider this conversion as narrowing, and so not allowed in C++20 :
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1957r2.html

It seems that default nostd::variant handles this conversion properly.

The solution as of now is to explicitly convert any string literal into `std::string` before storing it in `OwnedAttributeValue`.

**Comment by maxgolov** [comment]
Same issue exists with both recent gcc (Ubuntu 20.04-LTS) and latest Visual Studio 2019 `std::variant`. It is also there in `absl::variant` implementation. We can't wait for C++20 update until this feature is released widely, as it would take years for the customers to get to that recent compiler / STL update that would have the fix. I'm proposing a fix that works in #771
