### ISSUE TITLE
'tools/format.sh' FUBARs the entire project

### ISSUE THREAD

**Issue by Hablapatabla** [open-telemetry/opentelemetry-cpp#736]
**Describe your environment** 

CMake v3.20.1
Bash v3.2.57(1)
clang-format v11.1.0
cmake-format v0.6.13
buildifier 
Macbook Pro - OS Catalina v10.15.7

**Steps to reproduce**
~/source/opentelemetry-cpp
```
$: tools/format.sh
```

**What is the expected behavior?**
Code I added to the project to be formatted for commits.

**What is the actual behavior?**
Tool removes every character 'r' that is the last character in its line in every file of the entire project. Renders hundreds of source code files invalid, and the entire project is ruined. The only solution is to re-clone, re-edit, and re-build, as the tool modifies the source code itself, and changes are saved.

<img width="470" alt="post-format-git-status" src="https://user-images.githubusercontent.com/54953949/117710478-2a731180-b1a0-11eb-8c9f-1b0a530a06dc.png">
<img width="481" alt="post-format-diff-1" src="https://user-images.githubusercontent.com/54953949/117710491-2cd56b80-b1a0-11eb-87a8-1e3be4c97cb2.png">
<img width="483" alt="post-format-diff-2" src="https://user-images.githubusercontent.com/54953949/117710503-2fd05c00-b1a0-11eb-9f9a-e33e395d365d.png">

**Comment by maxgolov** [comment]
If you have visual tools that show the number of lines of lines actually changed, like TortoiseGit on Windows, you can quickly revert the files that have zero changes, keeping only those that actually have lines Added or Deleted.

**Comment by lalitb** [comment]
closing as it's not a configuration issue.
@Hablapatabla  - please open a thread on the discussion you still have any issue.
