### ISSUE TITLE
Checked in GTest is older than the required by the source code

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-cpp#746]
**Describe your environment**:
* gcc version: 8.3.1
* OS: RHEL 8.3
* CMake version: 3.18

**Steps to reproduce**
```sh
# Build gtest checked in the repository
./tools/build-gtest.sh
# Use it to build the opentelemetry-cpp source code
mkdir build
cd build
cmake .. -DGTEST_ROOT=/tmp/build/gtest/lib
make VERBOSE=1
```

**What is the expected behavior?**
Build the `timestamp_test` executable without errors.

**What is the actual behavior?**
```sh
[  0%] Linking CXX executable timestamp_test
cd /home/iblancas/projects/opentelemetry-cpp/build/api/test/core && /home/iblancas/projects/environ/lib/python3.6/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/timestamp_test.dir/link.txt --verbose=1
/usr/bin/c++ -rdynamic CMakeFiles/timestamp_test.dir/timestamp_test.cc.o -o timestamp_test  /tmp/build/gtest/lib/libgtest.a /tmp/build/gtest/lib/libgtest_main.a -lpthread 
CMakeFiles/timestamp_test.dir/timestamp_test.cc.o: In function `testing::internal2::TypeWithoutFormatter<opentelemetry::v0::common::SystemTimestamp, (testing::internal2::TypeKind)2>::PrintValue(opentelemetry::v0::common::SystemTimestamp const&, std::ostream*)':
timestamp_test.cc:(.text._ZN7testing9internal220TypeWithoutFormatterIN13opentelemetry2v06common15SystemTimestampELNS0_8TypeKindE2EE10PrintValueERKS5_PSo[_ZN7testing9internal220TypeWithoutFormatterIN13opentelemetry2v06common15SystemTimestampELNS0_8TypeKindE2EE10PrintValueERKS5_PSo]+0x21): undefined reference to `testing::internal2::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::ostream*)'
CMakeFiles/timestamp_test.dir/timestamp_test.cc.o: In function `testing::internal2::TypeWithoutFormatter<opentelemetry::v0::common::SteadyTimestamp, (testing::internal2::TypeKind)2>::PrintValue(opentelemetry::v0::common::SteadyTimestamp const&, std::ostream*)':
timestamp_test.cc:(.text._ZN7testing9internal220TypeWithoutFormatterIN13opentelemetry2v06common15SteadyTimestampELNS0_8TypeKindE2EE10PrintValueERKS5_PSo[_ZN7testing9internal220TypeWithoutFormatterIN13opentelemetry2v06common15SteadyTimestampELNS0_8TypeKindE2EE10PrintValueERKS5_PSo]+0x21): undefined reference to `testing::internal2::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::ostream*)'
CMakeFiles/timestamp_test.dir/timestamp_test.cc.o: In function `testing::internal2::TypeWithoutFormatter<std::chrono::duration<long, std::ratio<1l, 1000000000l> >, (testing::internal2::TypeKind)2>::PrintValue(std::chrono::duration<long, std::ratio<1l, 1000000000l> > const&, std::ostream*)':
timestamp_test.cc:(.text._ZN7testing9internal220TypeWithoutFormatterINSt6chrono8durationIlSt5ratioILl1ELl1000000000EEEELNS0_8TypeKindE2EE10PrintValueERKS6_PSo[_ZN7testing9internal220TypeWithoutFormatterINSt6chrono8durationIlSt5ratioILl1ELl1000000000EEEELNS0_8TypeKindE2EE10PrintValueERKS6_PSo]+0x21): undefined reference to `testing::internal2::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::ostream*)'
```

# Additional context
It seems everything works properly when building using GTest 1.8.0.

**Comment by iblancasa** [comment]
Some suggestions:
* Update the instructions from the `INSTALL.md` file to explain how to build the dependencies (using the checked in scripts)
* Improve how `GTest` is searched (using more the features from `find_package` instead of looking directly for the libraries) and enforce a minimal version

**Comment by lalitb** [comment]
The gtest version 1.10.x seems to be fine, and same as we use in our[ ci environment](https://github.com/open-telemetry/opentelemetry-cpp/blob/834bba68d9211d9e0225cde0b9d7b6680555b450/ci/setup_cmake.sh#L9).

By quick look at this script (./tools/build-gtest.sh), it seems that the actual install location for gtest ( headers and libraries ) is `/tmp/build` and not `/tmp/build/gtest`. 

So probably otel-cpp cmake build command should be:

`cmake .. -DGTEST_ROOT=/tmp/build/`

Though I do agree  INSTALL.md doc needs improvement, and we welcome contributions to improve it :)

**Comment by iblancasa** [comment]
Thanks for your answer @lalitb!

You are right, if I point `GTEST_ROOT` to `/tmp/build/` it works. I used the other path because I found the libraries there (after running the script) and I though those were the correct ones.

```console
➜ iblancasa > /tmp/build  fd libgtest_main
gtest/lib/libgtest_main.a
lib64/libgtest_main.a
```

Something I'm curious about is why if I use `/tmp/build/gtest` the build fails:
```console
➜ iblancasa  /tmp/build  md5sum lib64/libgtest_main.a
0e272bec40a5367e05184c77f4ebdb2e  lib64/libgtest_main.a
➜ iblancasa  /tmp/build  md5sum lib64/libgtest.a 
42c79c14d09d48249d3b67534dae6c88  lib64/libgtest.a
➜ iblancasa  /tmp/build  md5sum gtest/lib/libgtest_main.a 
0e272bec40a5367e05184c77f4ebdb2e  gtest/lib/libgtest_main.a
 ➜ iblancasa  /tmp/build  md5sum gtest/lib/libgtest.a 
42c79c14d09d48249d3b67534dae6c88  gtest/lib/libgtest.a
```

But well, it is not really important.

I'll create a PR to address the comments related to building the third-party 😄

**Comment by lalitb** [comment]
glad it worked.

> Something I'm curious about is why if I use /tmp/build/gtest the build fails 

/tmp/build/gtest is build location, not install location. So the gtest headers are missing there. If otel-cpp cmake build take these headers from default location (/usr/include, /usr/local/include) and libraries from /tmp/build/gtest, this can result in mismatch and so the error. Again my guess :)

> I'll create a PR to address the comments related to building the third-party 😄

Thank you.

**Comment by ThomsonTan** [comment]
We are using customized logic to find GTest only for in tree build from our submodule `third_party/googletest`, othersize `find_package()` is used, but seems `tools/build-gtest.sh` doesn't follow this convention and build submodule into a temp folder. Probably we should add an option `-WITH-GTEST-SUBMODULE`.

**Comment by iblancasa** [comment]
@ThomsonTan sorry but I think my comment was not really descriptive. What I wanted to say was: instead of doing this:
```cmake
  if(EXISTS ${CMAKE_BINARY_DIR}/lib/libgtest.a)
    # Prefer GTest from build tree. GTest is not always working with
    # CMAKE_PREFIX_PATH
    set(GTEST_INCLUDE_DIRS
        ${CMAKE_CURRENT_SOURCE_DIR}/third_party/googletest/googletest/include
        ${CMAKE_CURRENT_SOURCE_DIR}/third_party/googletest/googlemock/include)
    set(GTEST_BOTH_LIBRARIES
        ${CMAKE_BINARY_DIR}/lib/libgtest.a
        ${CMAKE_BINARY_DIR}/lib/libgtest_main.a
        ${CMAKE_BINARY_DIR}/lib/libgmock.a)
```
Try to set the correct CMake variables allowing the `find_package(GTest REQUIRED)` find the GTest libraries. Or, at least, explain how to get the libraries under the `${CMAKE_BINARY_DIR}/lib/` folder

**Comment by iblancasa** [comment]
Also, for finding `benchmark`, I had to add manually the path where it is build to `CMAKE_PREFIX_PATH`. For building `benchmark` I used `./tools/build-benchmark.sh`.

**Comment by maxgolov** [comment]
@iblancasa @ThomsonTan @lalitb 

These scripts all have been largely tested with these flows on Ubuntu.

https://github.com/open-telemetry/opentelemetry-cpp/tree/main/docker
- ubuntu14.04
- ubuntu16.04
- ubuntu18.04
- ubuntu20.04

There could have been unintentional regressions due to new tests being added.
I think it would be good to add similar set of containerized builds for RedHat / CentOS.

Docker launch script is easy to adjust from Windows to shell:
https://github.com/open-telemetry/opentelemetry-cpp/blob/main/tools/build-docker.cmd
I can help to create the same script for Linux / Mac.

There is a practical reason why you may not want to build with `find_package` and find_package(GTest REQUIRED)` : if you are building on old `Ubuntu-14.04`, then the package that may come already preinstalled with distro is **TOO OLD** . So you end up needing to build in a build tree with your own version of more recent version of GTest.

I do not have objections if you can sort out how to build the more recent version of GTest for old distros? The min we were trying to support is anything that by default comes with at least `gcc-4.8.x`, that dates back to `Ubuntu-14.04` and I guess `rhel-7.x` from 2014.

Last time I tried `Ubuntu-14.04` in Docker build was late last year. It all worked well. With protobuf. Without gRPC though, from what I remember.

**Comment by maxgolov** [comment]
@iblancasa - can you help us to maintain this build setup for latest, as well as older RHEL 7.x?

**Comment by maxgolov** [comment]
> Again my guess :)

This guess is correct, and the case when it happens is when we run on a distro that is too old.

**Comment by iblancasa** [comment]
> These scripts all have been largely tested with these flows on Ubuntu.

Yes, I know but, when I try to set my development environment, I would expect a different behavior. I mean: if I have one script to build `GTest`, I don't expect to search the built libraries under `/tmp/build/`. Specially, after reading the `CMakeLists.txt` from the top level, I would expect to find the `GTest` libraries under `${CMAKE_BINARY_DIR}/lib/` because the CMake code looks for the `${CMAKE_BINARY_DIR}/lib/libgtest.a` library at some point. Similar situation with `benchmark`. I think it would be a good idea to, at least, document it to make the process easier for future developers. What do you think?

> There is a practical reason why you may not want to build with find_package and find_package(GTest REQUIRED) . If you are building on old Ubuntu-14.04, then the GTest, CMake, Benchmark, protobuf packages that may come with distro are TOO OLD . So you end up needing to build in a build tree with your own version of more recent version of GTest.

It totally makes sense. Can I add a comment to the `CMakeListst.txt` file to explain this situation? To avoid confusion in the future.

> @iblancasa - can you help us to maintain this build setup for latest, as well as older RHEL 7.x?
Yes. I can take a look. I'll create a new issue to address this.

**Comment by maxgolov** [comment]
> Yes. I can take a look. I'll create a new issue to address this.

@iblancasa - yes, please. This would help the project immensely!
