### ISSUE TITLE
Recording exception to Span

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#760]
As per the specs (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#record-exception) :

``
To facilitate recording an exception languages SHOULD provide a RecordException method if the language uses exceptions. This is a specialized variant of AddEvent, so for anything not specified here, the same requirements as for AddEvent apply.
``

As C++ supports exceptions, the feature should be supported.

**Comment by lalitb** [comment]
``Recordable::RecordException(Exception &exception)``

It won't be easy to support as passing exceptions can break ABI compatibility. It's instead recommended for instrumentation libraries to serialize Exceptions and pass using `Recordable::AddEvent`.
Will wait for other thoughts, before closing this issue.

**Comment by lalitb** [comment]
Closing as mentioned above.

**Comment by ThomsonTan** [comment]
> `Recordable::RecordException(Exception &exception)`
> 
> It won't be easy to support as passing exceptions as argument can break ABI compatibility. It's instead recommended for instrumentation libraries to serialize Exceptions and pass using `Recordable::AddEvent`.
> Will wait for other thoughts, before closing this issue.

Could we document this suggestion?
