### ISSUE TITLE
Jaeger Exporter : Mapping OTel Resource into Jaeger Process

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#767]
Current Jaeger Thrift exporter [implementation](https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/exporters/jaeger/src/recordable.cc#L107) maps service_name from resource attributes into Jaeger process. The rest of the resource attributes also need to be mapped to the Jaeger Process as mentioned in specs:
https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/specification/trace/sdk_exporters/jaeger.md#resource

This is how it is handled by otel-go implementation: https://github.com/open-telemetry/opentelemetry-go/blob/d3b1280863f421bba9656543296b71c133f1ba13/exporters/trace/jaeger/jaeger.go#L346

**Comment by anshulkumar19** [comment]
@lalitb Can you assign this to me?

**Comment by lalitb** [comment]
@anshulkumar19  - Do you want me to pick this up, as we need to fix this for GA.

**Comment by anshulkumar19** [comment]
> @anshulkumar19 - Do you want me to pick this up, as we need to fix this for GA.

Sorry @lalitb for coming late on this, please pick this up as needed for GA and I am little bit occupied with other things.

**Comment by ThomsonTan** [comment]
@anshulkumar19 no problem. I'll take it.
