### ISSUE TITLE
Jaeger: Handle InstrumentationLibrary

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#768]
As per the specs, InstrumentationLibrary should be reported as Jaeger span tags:
https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/specification/trace/sdk_exporters/jaeger.md#instrumentationlibrary

**Comment by anshulkumar19** [comment]
I would like to pick this up, can I get it assigned?

**Comment by lalitb** [comment]
Sure.  @ThomsonTan can help you if needed as he knows this component better.
