### ISSUE TITLE
Missing Code of Conduct

### ISSUE THREAD

**Issue by BobinMathew** [open-telemetry/opentelemetry-cpp#772]
This repo is missing a Code of Conduct.
Cant I give a PR ?

**Comment by lalitb** [comment]
Yes please go ahead. Thank you :)

**Comment by BobinMathew** [comment]
Hi @lalitb I think a link to the "OpenTelemetry Community Code of Conduct" would be more convenient for this repo. What do you think?

**Comment by lalitb** [comment]
Yes, link to this should be enough : https://github.com/open-telemetry/community/blob/main/code-of-conduct.md

**Comment by eyjohn** [comment]
Thank you for this (issue + PR)!
