### ISSUE TITLE
Implement OpenTracing shim

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-cpp#78]
Refer to https://github.com/open-telemetry/opentelemetry-python/tree/v1.10.0/shim/opentelemetry-opentracing-shim.

**Comment by chalin** [comment]
Consider changing "bridge" to "shim" in the title (since the terminology has changed since this issue was created).

**Comment by lalitb** [comment]
> Consider changing "bridge" to "shim" in the title (since the terminology has changed since this issue was created).

Thanks, done.
