### ISSUE TITLE
Unable to build example code.

### ISSUE THREAD

**Issue by contractormarketplace** [open-telemetry/opentelemetry-cpp#781]
I am trying to run the example program provided :-

opentelemetry-cpp/examples/simple

The instructions on how to get a build are not clear. 

I have modified the main to allow the program to send traces to the collector which is running in my local environemnt.

I run cmake using the following command :-

/opentelemetry-cpp/examples/simple$ cmake -DCMAKE_PREFIX_PATH=$MY_INSTALL_DIR -DWITH_OTLP=ON

$MY_INSTALL_DIR is the location of my gRPC installation.
opentelemetry-cpp/examples/simple$ echo $MY_INSTALL_DIR 
/home/osboxes/.local

Make command is unable to find the required .h files.

opentelemetry-cpp/examples/simple$ make
[ 25%] Building CXX object CMakeFiles/foo_library.dir/foo_library/foo_library.o
/home/osboxes/elysium/opentelemetry-cpp/opentelemetry-cpp/examples/simple/foo_library/foo_library.cc:1:10: fatal error: opentelemetry/trace/provider.h: No such file or directory
    1 | #include "opentelemetry/trace/provider.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/foo_library.dir/build.make:63: CMakeFiles/foo_library.dir/foo_library/foo_library.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/foo_library.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

My main.cc is attached. I have made the following modifications to call the Opentelemetry collector with the traces.

 auto exporter = std::unique_ptr<sdktrace::SpanExporter>(
      //new opentelemetry::exporter::trace::OStreamSpanExporter);
      new opentelemetry::exporter::trace::OtlpExporter);

Any guidance is appreciated.

**Environment

OS: Ubuntu 20.04.2 LTS
Collector Version aws-otel-collector-0.8.0
Dataprepper Version 0.8.0-beta
[main.cc.txt](https://github.com/open-telemetry/opentelemetry-cpp/files/6521428/main.cc.txt)

**Comment by lalitb** [comment]
The correct way of building the example would be using this command from repo build-root:
```console
~/build/$ cmake <repo-root>
~/build/$ cmake --build . --target example_simple
```

**Comment by contractormarketplace** [comment]
I did not fully understand, is this build process documented somewhere?

From what you have mentioned, I go to the directory opentelemetry-cpp/examples/simple

cmake /home/osboxes/elysium/opentelemetry-cpp/opentelemetry-cpp

cmake --build . --target example_simple

I still get compile issues, it's not able to find the #include "opentelemetry/trace/provider.h"

**Comment by lalitb** [comment]
You need to run this from repo root if that is the build directory.

**Comment by contractormarketplace** [comment]
@lalitb That helps, but I now get the following error.

[ 90%] Building CXX object examples/simple/CMakeFiles/example_simple.dir/main.cc.o
In file included from /home/osboxes/elysium/opentelemetry-cpp/opentelemetry-cpp/examples/simple/main.cc:8:
/home/osboxes/elysium/opentelemetry-cpp/opentelemetry-cpp/exporters/otlp/include/opentelemetry/exporters/otlp/otlp_exporter.h:5:10: fatal error: opentelemetry/proto/collector/trace/v1/trace_service.grpc.pb.h: No such file or directory
    5 | #include "opentelemetry/proto/collector/trace/v1/trace_service.grpc.pb.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [examples/simple/CMakeFiles/example_simple.dir/build.make:63: examples/simple/CMakeFiles/example_simple.dir/main.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:4326: examples/simple/CMakeFiles/example_simple.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:4333: examples/simple/CMakeFiles/example_simple.dir/rule] Error 2
make: *** [Makefile:1657: example_simple] Error 2

**Comment by lalitb** [comment]
The simple example doesn't use otlp exporter. So WITH_OTLP=ON option shouldn't be provided.

**Comment by contractormarketplace** [comment]
@lalitb I have modified the main to  allow the program to send traces to the collector which is running in my local environment.

My main.cc was attached. I have made the following modifications to call the Opentelemetry collector with the traces. 

Alternately, do you have examples where the traces are sent to the collector so that I can run that?

auto exporter = std::unique_ptrsdktrace::SpanExporter(
//new opentelemetry::exporter::trace::OStreamSpanExporter);
new opentelemetry::exporter::trace::OtlpExporter);

Based on earlier suggestions from your team, I compiled WITH_OTLP=ON

**Comment by ThomsonTan** [comment]
@contractormarketplace there is there OTLP example so you don't need modify the simple example to export data to OTLP collector. Below link has more details.

https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/otlp/README.md#L1

**Comment by contractormarketplace** [comment]
@ThomsonTan , @lalitb , Thank you for your guidance.
I am stuck trying to build the OTLP example

opentelemetry-cpp/build$ cmake --build . --target example_otlp

The above is the command I tried, are you able to provide further guidance on how to build this example.

**Comment by ThomsonTan** [comment]
@contractormarketplace what is the error output of running `cmake --build . --target example_otlp`? I just run it and produced example_otlp successfully. I guess there is still some dependence missing.

**Comment by contractormarketplace** [comment]
osboxes@osboxes:~/elysium/opentelemetry-cpp/opentelemetry-cpp/build$ cmake --build . --target example_otlp
make: *** No rule to make target 'example_otlp'.  Stop.

**Comment by ThomsonTan** [comment]
Could you please clean the `build` folder and regenerate build files by CMake, but with `-DWITH_OTLP=ON` option? Then the the above cmake command again.

**Comment by contractormarketplace** [comment]
Here is what I did, the clean does not fix the problem.

osboxes@osboxes:~/elysium/opentelemetry-cpp/opentelemetry-cpp/build$ rm CMakeCache.txt
make clean
cmake -DCMAKE_PREFIX_PATH=$MY_INSTALL_DIR -DWITH_OTLP=ON ..
cmake --build . --target example_otlp
make: *** No rule to make target 'example_otlp'.  Stop.

**Comment by ThomsonTan** [comment]
Could you please check `WITH_OTLP` is set to `ON` in the genreated `CMakeCache.txt`?

```
//Whether to include the OpenTelemetry Protocol in the SDK
WITH_OTLP:BOOL=ON
```

**Comment by contractormarketplace** [comment]
//Whether to include the OpenTelemetry Protocol in the SDK
WITH_OTLP:BOOL=ON

I see this entry in CMakeCache.txt

**Comment by contractormarketplace** [comment]
I did a fresh git clone to download the source to get a fresh copy of the code. I run into the same issue.

**Comment by ThomsonTan** [comment]
Could you please share `CMakeFiles/CMakeOutput.log` under the build directory?

**Comment by contractormarketplace** [comment]
[CMakeOutput.log](https://github.com/open-telemetry/opentelemetry-cpp/files/6529542/CMakeOutput.log)

**Comment by ThomsonTan** [comment]
I just built example_otlp successfully in a fresh Ubuntu docker container. 

A few more questions:
1. Did you clone the repo with `git clone --recursive`?
2. Could you please rerun CMake with `cmake .. -DWITH_OTLP=ON --debug-output`, and share the console output in a new file?

**Comment by contractormarketplace** [comment]
[shyamOutput.txt](https://github.com/open-telemetry/opentelemetry-cpp/files/6529983/shyamOutput.txt)

I now did a clone --recursive and got the same results. The attached file shows some errors, not sure what those are.

To summarize here are the commands, I used.

git clone --recursive https://github.com/open-telemetry/opentelemetry-cpp.git

cmake -DCMAKE_PREFIX_PATH=$MY_INSTALL_DIR -DWITH_OTLP=ON --debug-output .. > shyamOutput.txt 2>&1

cmake --build . --target example_otlp

**Comment by ThomsonTan** [comment]
It seems the build scripts were not generated completely by CMake which causes the build error. Please make sure gtest is installed corrected in your environment. You could take a look at below script, but it installs gtest to `/tmp/build`, you may want to change the installation target to `/usr/local` or need to specify `GTEST_DIR` to point to `/tmp/build`.

A quick workaround it adding `-DBUILD_TESTING=OFF` to the CMake configure command line, which disables building all our test code hence remove dependence on GTest.

https://github.com/open-telemetry/opentelemetry-cpp/blob/main/tools/build-gtest.sh

**Comment by contractormarketplace** [comment]
@ThomsonTan , thank you for your guidance got through the first issue, now cmake --build . --target example_otlp throws the following errors :-

/usr/bin/ld: /home/osboxes/.local/lib/libgrpc.a(route_components.upb.c.o):(.data.rel.ro+0x290): undefined reference to `envoy_config_core_v3_ProxyProtocolConfig_msginit'
/usr/bin/ld: /home/osboxes/.local/lib/libgrpc.a(proxy_protocol.upbdefs.c.o):(.data.rel+0x0): undefined reference to `envoy_config_core_v3_ProxyProtocolConfig_msginit'
collect2: error: ld returned 1 exit status
make[3]: *** [examples/otlp/CMakeFiles/example_otlp.dir/build.make:131: examples/otlp/example_otlp] Error 1
make[2]: *** [CMakeFiles/Makefile2:865: examples/otlp/CMakeFiles/example_otlp.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:872: examples/otlp/CMakeFiles/example_otlp.dir/rule] Error 2
make: *** [Makefile:281: example_otlp] Error 2

**Comment by ThomsonTan** [comment]
How did you install gRPC? Perhaps try the gRPC installation guide below?

https://github.com/open-telemetry/opentelemetry-cpp/blob/main/ci/setup_grpc.sh

**Comment by contractormarketplace** [comment]
@ThomsonTan 
I had to reinstall gRPC using the script you provided. I also had to reinstall protobuf using the scripts in the same ci directory. And I was able to get a build! Thank you.

Issues running the example, We have collector running on our local server 10.10.110.93:55680, I passed this in as a parameter to the executable as follows :-

osboxes@osboxes:~/elysium/opentelemetry-cpp/opentelemetry-cpp/build/examples/otlp$ ./example_otlp 10.10.110.93:55680

But I get the following error message
[OTLP Exporter] Export() failed: failed to connect to all addresses
[OTLP Exporter] Export() failed: failed to connect to all addresses
[OTLP Exporter] Export() failed: failed to connect to all addresses
[OTLP Exporter] Export() failed: failed to connect to all addresses

Any ideas as to what needs to be done to send the traces to the collector instance running on our server?

**Comment by ThomsonTan** [comment]
55680 is legacy OTLP network work and it deprecated. Please make sure your collector is listening on that port as the error message implies OTLP cannot to the endpoint provided by the collector. Or you can try instructions in below doc which runs the collector in docker container.

https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/otlp/README.md

**Comment by contractormarketplace** [comment]
@ThomsonTan , The example_otlp is able to send traces to the collector - there was some firewall issue on the server which was preventing the sending of the traces. 

One other issue is that the service name parameter being sent to the collector is "unknown_service". Ideally, we would like the service name to be more descriptive. Is this the known behavior? Is there a way to set the service name by maybe using some environment variables?

**Comment by ThomsonTan** [comment]
Good to know it is an firewall issue. To specify service name, you'll need create a `Resource` like [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/sdk/test/resource/resource_test.cc#L62) with `service.name`, and pass it to the constructor of [`TracerProvider`](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/sdk/src/trace/tracer_provider.cc#L16).

**Comment by lalitb** [comment]
> Is there a way to set the service name by maybe using some environment variables?

In addition to what @ThomsonTan suggested, you can also set env variable `OTEL_RESOURCE_ATTRIBUTES` in format `key1=value1,key2=value2`. Also, I think we are good to close this issue. Going ahead, please use the `Discussion` forum for any such help or queries.

**Comment by contractormarketplace** [comment]
@ThomsonTan @lalitb thank you for all your assistance,  you may close this ticket.
