### ISSUE TITLE
why nostd::unique_ptr<Scope>  not Scope

### ISSUE THREAD

**Issue by halayli** [open-telemetry/opentelemetry-cpp#787]
Any reason why WithActiveSpan returns `nostd::unique_ptr<Scope>` instead of simply returning Scope?

**Comment by lalitb** [comment]
`Scope` object manages the ongoing span `context`, and context unwinding happens when this object goes out of scope. It's important to have only one copy of this object, so it's wrapped under nostd::unique_ptr. 

Also, if it's meant to be a question and not an issue we can move it to Discussions

**Comment by halayli** [comment]
I totally get the purpose of a span's `Scope` and its integration with the Context's internal `Stack`. But I don't understand why it needs to be allocated on the heap. It's a performance penalty that can be avoided, IMO. A scope class with deleted copy constructors should be enough. In fact for this particular case, they are implicitly deleted because it has a `std::unique_ptr` member variable.

It's definitely a question and not an issue. Sorry, I forgot about the discussion feature. Feel free to move it there.

**Comment by lalitb** [comment]
We can keep it open for now in case it's a potential issue :) For now, will let @pyohannes reply at his work time as he originally implemented this. Else, will look into it.

**Comment by halayli** [comment]
Sounds great, thanks!

**Comment by lalitb** [comment]
Ok, had a quick look at the code, looks like we should be returning the `Scope` object instead of `nostd::unique_ptr<Scope>`. Will raise a PR for same to be reviewed internally.

**Comment by lalitb** [comment]
@halayli @pyohannes  - Have raised a PR #788 with changes suggested in the issue. Can you please review them once?

**Comment by halayli** [comment]
Thanks for taking care of it! Yep, this should do it.
