### ISSUE TITLE
Implement HTTP(OTLP/HTTP+JSON Protocol) exporters

### ISSUE THREAD

**Issue by owent** [open-telemetry/opentelemetry-cpp#803]
Implement [OTLP/HTTP+JSON exporter](https://github.com/open-telemetry/opentelemetry-proto) trace exporter and metrics exporters.

Refer to:

1. https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md
2. https://github.com/open-telemetry/oteps/blob/main/text/0122-otlp-http-json.md
3. https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-web
4. https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver

I want to implement a HTTP exporter to fit [OTLP/HTTP specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp) and do not depend on gRPC. And I found I need implement a `Recordable` which is almost the same as `opentelemetry::exporter::otlp::OtlpRecordable` . I'm wondering if we can create a extension (e.g. sdk_proto) and move `opentelemetry::exporter::otlp::OtlpRecordable` and all conversion codes from sdk to opentelemetry-proto into the this this extension? So that we can reuse the codes in more exporters.

@ThomsonTan

**Comment by lalitb** [comment]
Thanks, @owent, this would be really helpful. 
Looking at the OTLP implementation for [otel-go](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/otlp) implementation, which is similar to what you are proposing though it's finally published as a single package/release containing both grpc and http.

**Comment by owent** [comment]
If I commit codes inner otlp exporter, maybe we should split `WITH_OTLP` into `WITH_OTLP_GRPC` and `WITH_OTLP_HTTP` ? Some environments may just want http exporter and do'nt want to depend grpc.

**Comment by ThomsonTan** [comment]
Yes, I think split `WITH_OTLP` into 2 variables makes sense here. Thanks for contributing this.

**Comment by owent** [comment]
Closed by #810
