### ISSUE TITLE
baggage.h is missing #include <cctype> for MSVC2015

### ISSUE THREAD

**Issue by lidavidm** [open-telemetry/opentelemetry-cpp#808]
**Describe your environment** 

Windows 10 x64
MSVC 19.00.24210 (VS2015)

**Steps to reproduce**

OpenTelemetry (latest main @ 12e56f9f4ad2e2a870482d89b999a9cf7c493e85) was built with `cmake -GNinja .. -DWITH_API_ONLY=ON -DCMAKE_INSTALL_PREFIX=../install -DBUILD_TESTING=OFF`. 

Then I tried to build a trivial application including an OpenTelemetry header:

```cpp
#include <opentelemetry/baggage/baggage.h>

int main(int, char**) {
    return 0;
}
```

**What is the expected behavior?**
The application should build successfully.

**What is the actual behavior?**

```
C:\Users\User\opentelemetry-cpp\install>cl.exe -Iinclude /EHsc /DHAVE_ABSEIL_VARIANT=1 test.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

test.cc
include\opentelemetry/baggage/baggage.h(225): error C2039: 'isalnum': is not a member of 'std'
c:\users\user\opentelemetry-cpp\install\include\opentelemetry\nostd\./absl/types/variant.h(809): note: see declaration of 'std'
include\opentelemetry/baggage/baggage.h(248): error C2039: 'isdigit': is not a member of 'std'
c:\users\user\opentelemetry-cpp\install\include\opentelemetry\nostd\./absl/types/variant.h(809): note: see declaration of 'std'
include\opentelemetry/baggage/baggage.h(252): error C2039: 'isdigit': is not a member of 'std'
c:\users\user\opentelemetry-cpp\install\include\opentelemetry\nostd\./absl/types/variant.h(809): note: see declaration of 'std'
include\opentelemetry/baggage/baggage.h(252): error C2039: 'toupper': is not a member of 'std'
c:\users\user\opentelemetry-cpp\install\include\opentelemetry\nostd\./absl/types/variant.h(809): note: see declaration of 'std'
include\opentelemetry/baggage/baggage.h(273): error C2039: 'isalnum': is not a member of 'std'
c:\users\user\opentelemetry-cpp\install\include\opentelemetry\nostd\./absl/types/variant.h(809): note: see declaration of 'std'
```

**Additional context**

Adding `#include <cctype>` to baggage.h fixes the issue.

**Comment by ThomsonTan** [comment]
@lidavidm thanks for reporting and investigation. Would you like to submit a PR with the fix?

**Comment by maxgolov** [comment]
If you don't mind, could you please apply the fix, and try pulling locally from this PR:
https://github.com/open-telemetry/opentelemetry-cpp/pull/771

This PR eliminates the `HAVE_ABSEIL_VARIANT` option. Making Abseil Variant now the default, because that is the only one that works for vs2015. I think we also need to add unit tests for baggage - to catch issues like this.

I'm planning to add CI loop for vs2015 once the above PR is merged.

**Comment by lidavidm** [comment]
Sorry about the delay - I'll submit a PR and test against the Abseil branch when I get a chance.
