### ISSUE TITLE
Add Prometheus exporter

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-cpp#81]
Add Prometheus exporter to prove metrics SDK. Consider adding console exporter for metrics.

**Comment by alolita** [comment]
Hi @reyang we are starting to work on building the Prometheus exporter for the metrics SDK. Can you please assign this issue to me @alolita. I will provide the handles of our interns working on this too.

**Comment by alolita** [comment]
Our interns are @cunjunwang, @erichsueh3 - they are in the process of becoming members.

**Comment by alolita** [comment]
Hi @reyang greetings! Can you please also add my intern engineers @CunjunWang, @EricHsueh3 to this issue? We're working on the exporter implementation and have already submitted the design for review. Please see https://github.com/open-telemetry/opentelemetry-cpp/pull/172 Many thanks Reiley!

**Comment by reyang** [comment]
> Hi @reyang greetings! Can you please also add my intern engineers @CunjunWang, @erichsueh3 to this issue? We're working on the exporter implementation and have already submitted the design for review. Please see #172 Many thanks Reiley!

Currently I cannot add them since their names won't show up (not a member). Happy to sponsor them to be members of OpenTelemetry.

**Comment by erichsueh3** [comment]
@reyang, can you assign me to this issue? I believe I've just been added as a member of OpenTelemetry.

**Comment by lalitb** [comment]
closing as initial implementation was completed as part of #280  #282 . 
The implementation may change as metrics specs is being revisited.
