### ISSUE TITLE
HTTPClient : Support for full URL argument instead of host & port

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#812]
As discussed [here](https://github.com/open-telemetry/opentelemetry-cpp/pull/810#discussion_r642303340):

- [HttpClient::CreateSession](https://github.com/open-telemetry/opentelemetry-cpp/blob/ac0e6174e74f845e7d375a156b5abea33956c056/ext/include/opentelemetry/ext/http/client/http_client.h#L229) method should support passing full URL as an argument instead of host and port (or perhaps support both). This would be then consistent with `HttpClientSync::Get(url)` and `HttpClientSync::Post(url)` methods.
- Validate if HTTPS URL is parsed successfully, and supported for curl implementation. Remove `TODO` from here once `https` works/fixed:

https://github.com/open-telemetry/opentelemetry-cpp/blob/ac0e6174e74f845e7d375a156b5abea33956c056/ext/include/opentelemetry/ext/http/client/curl/http_client_curl.h#L123

**Comment by ohamuy** [comment]
Hey! Could I pick up this issue?

**Comment by ohamuy** [comment]
@lalitb Would you rather have me allow for [HttpClient::CreateSession](https://github.com/open-telemetry/opentelemetry-cpp/blob/ac0e6174e74f845e7d375a156b5abea33956c056/ext/include/opentelemetry/ext/http/client/http_client.h#L229) to have the template have multiple parameters, one for host/port and one for a full url? Or would you rather have me change the current implementation to simply fix https and work for full url

**Comment by ohamuy** [comment]
I’d like to work on this issue. Can you please assign this to me? @alolita

**Comment by lalitb** [comment]
Thanks @ohamuy  - assigned to you now. We can use function overloading to support both unless you see benefit with templates?

**Comment by ohamuy** [comment]
Yea @lalitb I could definitely do function overloading. Also how do we know whether the user wants http or https appended if they only provide the host and port? Also for testing would I use Bazel or is there some other way to test my code?

**Comment by lalitb** [comment]
> Yea @lalitb I could definitely do function overloading. Also how do we know whether the user wants http or https appended if they only provide the host and port? Also for testing would I use Bazel or is there some other way to test my code?

default should be always `http` unless use explicitly specified `https`. This should be irrespective of whether port number is 80 or 443.

**Comment by ohamuy** [comment]
Hey @lalitb @reyang I wrote this block of code overloading the Session to allow for url input. This utilizes the urlparser in the common folder. What would you like me to return if it doesn't successfully parse? Nullptr? Also this code compiles successfully using Bazel
```
 std::shared_ptr<http_client::Session> CreateSession(nostd::string_view url) noexcept override
  {
	  auto parsedUrl = common::UrlParser(std::string(url));
	  if (!parsedUrl.success_) {
		  //return std::make_shared<Session>();
	  }
	  auto session    = std::make_shared<Session>(*this, parsedUrl.host_, parsedUrl.port_);
	  auto session_id = ++next_session_id_;
	  session->SetId(session_id);
	  sessions_.insert({session_id, session});
	  return session;
  }

**Comment by lalitb** [comment]
@ohamuy  - Your approach looks good. We can return the Session object with an empty/non-existent host, and default port(80). And let the actual connection failure get caught at ResponseHandler level:

```cpp
 std::shared_ptr<http_client::Session> CreateSession(nostd::string_view url) noexcept override
  {
	  auto parsedUrl = common::UrlParser(std::string(url));
	  if (!parsedUrl.success_) {
                  //TBD - Log error once error handler is supported
		  return std::make_shared<Session>(*this, "empty-host", 80);
	  }
	  auto session    = std::make_shared<Session>(*this, parsedUrl.host_, parsedUrl.port_);
	  auto session_id = ++next_session_id_;
	  session->SetId(session_id);
	  sessions_.insert({session_id, session});
	  return session;
  }
```

While using ,
```cpp
  auto session = httpClient.createSession("localhost", 8000);
  auto request = session->CreateRequest();
  request->AddHeader(..);
  SimpleResponseHandler res_handler;
  session->SendRequest(res_handler);
```
`res_handler` will catch the connection error.

**Comment by ohamuy** [comment]
@lalitb Ok great, I'll add these changes and get a PR ready (will have to get it reviewed first within Amazon!)

**Comment by ohamuy** [comment]
We can close this issue now, correct? @lalitb
