### ISSUE TITLE
Implement metrics API

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-cpp#82]

**Comment by alolita** [comment]
@reyang @maxgolov Please assign this Issue to @Brandon-Kimberly @ankit-bhargava @hudsonhumphries @alolita to this task. We're working on the metrics API and will submit a design proposal shortly.

**Comment by reyang** [comment]
> @reyang @maxgolov Please assign this Issue to @Brandon-Kimberly @ankit-bhargava @HudsonHumphries @alolita to this task. We're working on the metrics API and will submit a design proposal shortly.

We can only assign GitHub Issue to people who joined the OpenTelemetry community, please refer to the instructions [here](https://github.com/open-telemetry/community/blob/master/community-membership.md#requirements).

**Comment by alolita** [comment]
@reyang Thanks for the link. We've completed most of the items in the checklist you shared. We will complete rest of the items and circle back.

**Comment by reyang** [comment]
> @reyang Thanks for the link. We've completed most of the items in the checklist you shared. We will complete rest of the items and circle back.

Put @maxgolov and me as the sponsors 😄

**Comment by alolita** [comment]
@reyang This implementation has been completed and merged. Please close this issue.
