### ISSUE TITLE
Implement a batching span processor

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/opentelemetry-cpp#83]
In addition to the [simple span processor](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/src/trace/simple_processor.h), a batching span processor needs to be implemented.

The batching span processor must conform to [spec requirements](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#batching-processor).

For buffering spans, the circular buffer introduced in #52 should be used. For timer functionality, the dispatcher introduced in #63 should be used.

**Comment by snehilchopra** [comment]
It seems that the dispatcher hasn't been merged into the main repo yet.
Is there something pending with the implementation?

**Comment by reyang** [comment]
Closed by #195.
