### ISSUE TITLE
Add performance benchmark tests for Baggage API

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#837]
Performance benchmark tests are missing for Baggage API. This needs to be added.
Reference:
Sampler benchmark tests: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/sdk/test/trace/sampler_benchmark.cc

**Comment by maxgolov** [comment]
It's a great task, and it would really help to compare `before` vs `after` whenever we consider any refactor in this domain.

Let's make any refactoring decisions judging by perf numbers.
