### ISSUE TITLE
Add bazel build for grpc example

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#838]
grpc example ( https://github.com/open-telemetry/opentelemetry-cpp/tree/main/examples/grpc ) supports only cmake build as of now. bazel build needs to be added.

cc @jsuereth added bug as discussed here : https://github.com/open-telemetry/opentelemetry-cpp/pull/729#pullrequestreview-674615647

**Comment by owent** [comment]
I'm interesting in this. There some problems in #666 before.

+ The old gRPC do not support legacy compilers and bazel 4.
+ There are also more problems if using `C++20` (Which remove many deprecated APIs before) even we use the gRPC with the version is not that old.

I'm not familiar with `bazel` and I think there may be the same problems if we add `bazel` support for grpc example.
Looking for the solution of best pratice.

**Comment by lalitb** [comment]
For the gcc compiler, we can document the minimum supported gcc version for gRPC/otlp as defined by gRPC (4.9+ or 5.1+ whatever works) : 
gRPC needs gcc 4.9+(https://grpc.io/docs/), and abseil needs gcc 5.1+ (https://abseil.io/docs/cpp/platforms/platforms).

We can further split our Bazeil build CI into two parts - 4.8 compiler without building grpc/otlp exporter, 5.0+ compiler with grpc/otlp exporter. This will allow us to upgrade Bazel and gRPC versions both.

**Comment by lalitb** [comment]
I am putting it as help needed, probably someone with good knowledge `bazel` can help here.

**Comment by lalitb** [comment]
#910 fixes it.
