### ISSUE TITLE
Add exporter support for spans that aren't stored in a single contiguous segment

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/opentelemetry-cpp#84]
The [current exporter implementation](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/include/opentelemetry/sdk/trace/exporter.h#L50) assumes, that spans are passed as a contiguous array. This might not be the case for spans stored in circular buffers (#52).

The exporter interface should be adapted to support exporting spans that aren't stored as a contiguous array.

**Comment by lalitb** [comment]
@pyohannes  - Is this duplicate to #62 ?

**Comment by pyohannes** [comment]
@lalitb Yes, this is contained in #62.
