### ISSUE TITLE
Add forking support to the exporters and processors

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/opentelemetry-cpp#85]
Exporters and processors should be fork safe. In case of a fork, 
* no data should be duplicated, and 
* vendor implementers must have the possibility to re-initialize open connections (sockets) or files.

This could be implemented via [restart](https://github.com/lightstep/lightstep-tracer-cpp/blob/master/src/recorder/stream_recorder/stream_recorder.cpp#L149-L174) functions in span processors and exporters.

**Comment by snehilchopra** [comment]
Hey @pyohannes !

After checking out the restart functions linked above, I have an idea of how the processors could be made fork safe, but not entirely sure about the exporters.

The exporters would be vendor-specific, meaning that each exporter would be handled differently.

I am thinking of providing an interface, such as the [ForkAwareRecorder](https://github.com/lightstep/lightstep-tracer-cpp/blob/master/src/recorder/fork_aware_recorder.h) for both processors and exporters, wherein we can register fork handlers.

I have an idea on how to go about implementing the handlers for the built-in processors we have (simple and batch), but I guess I can leave the fork handlers' implementations to the author of the vendor-specific exporter?

**Comment by pyohannes** [comment]
> I have an idea on how to go about implementing the handlers for the built-in processors we have (simple and batch), but I guess I can leave the fork handlers' implementations to the author of the vendor-specific exporter?

Yes, definitely, your on spot with that. For exporters we just can provide an interface that vendors can (optionally) implement. Handling will be different for each exporter, as it might involve handling socket or file handles.

**Comment by snehilchopra** [comment]
Sounds good! Thank you so much!
