### ISSUE TITLE
Issues when compiling the jaeger example with cmake in alpine platform (cannot find -lopentelemetry_api)

### ISSUE THREAD

**Issue by r03942139** [open-telemetry/opentelemetry-cpp#898]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.

Platform - alpine:3.12.7
opentelemetry-cpp - 1.0.0-rc2
Build - cmake 3.17.2, Bazel 3.7.2
JAVA - openjdk11

**Steps to reproduce**
COPY ["./opentelemetry-cpp-1.0.0-rc2", "/opentelemetry-cpp-1.0.0-rc2"]
RUN cd opentelemetry-cpp-1.0.0-rc2 \
 && mkdir build && cd build \
 && cmake .. -DBUILD_TESTING=ON -DWITH_JAEGER=ON -DWITH_OTLP=OFF \
 && cmake --build . --target all \
 && cmake --install . --config Debug --prefix /usr/local/ \
 && ctest \
 && cd .. && bazel build //... \
 && bazel test //...

// Try to compile jaeger by cmake, since the bazel build is not supported yet.
RUN cd /opentelemetry-cpp-1.0.0-rc2/examples/jaeger/ \
 && cmake .. \
 && make

**What is the expected behavior?**
The Jaeger example in /opentelemetry-cpp-1.0.0-rc2/examples/jaeger/ can be compiled and installed.

**What is the actual behavior?**
Compilation errors as LOG below
[  4%] Building CXX object plugin/load/CMakeFiles/load_plugin_example.dir/main.o
[  9%] Linking CXX executable load_plugin_example
**/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lopentelemetry_api
collect2: error: ld returned 1 exit status
make[2]: *** [plugin/load/CMakeFiles/load_plugin_example.dir/build.make:104: plugin/load/load_plugin_example] Error 1
make[1]: *** [CMakeFiles/Makefile2:264: plugin/load/CMakeFiles/load_plugin_example.dir/all] Error 2**
make: *** [Makefile:104: all] Error 2

**Additional context**
Hoping that there is more details about how to compile the jaeger example. As it is shown in the simple example.
/opentelemetry-cpp-1.0.0-rc2/examples/simple/
Thanks.

====== The Full LOG =====
Step 79/84 : RUN cd /opentelemetry-cpp-1.0.0-rc2/examples/jaeger/  && cmake ..  && make
 ---> Running in 7f450ac73943
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must contain a literal, direct call to the project() command.  Add a line of code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CURL: /usr/lib/libcurl.so (found version "7.77.0")  
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.17)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Warning (dev) at simple/CMakeLists.txt:7 (add_executable):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "example_simple" links to some libraries for which the
  linker must search:

    opentelemetry_trace, opentelemetry_exporter_ostream_span
    opentelemetry_api

  and other libraries with known full path:

    /opentelemetry-cpp-1.0.0-rc2/examples/jaeger/simple/libfoo_library.a

  CMake is adding directories in the second list to the linker search path in
  case they are needed to find libraries from the first list (for backwards
  compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
  or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
  more information.
This warning is for project developers.  Use -Wno-dev to suppress it.

Generating done
Build files have been written to: /opentelemetry-cpp-1.0.0-rc2/examples/jaeger

Scanning dependencies of target load_plugin_example
[  4%] Building CXX object plugin/load/CMakeFiles/load_plugin_example.dir/main.o
[  9%] Linking CXX executable load_plugin_example
**/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lopentelemetry_api
collect2: error: ld returned 1 exit status**
make[2]: *** [plugin/load/CMakeFiles/load_plugin_example.dir/build.make:104: plugin/load/load_plugin_example] Error 1
make[1]: *** [CMakeFiles/Makefile2:264: plugin/load/CMakeFiles/load_plugin_example.dir/all] Error 2
make: *** [Makefile:104: all] Error 2

**Comment by lalitb** [comment]
You don't need to have separate RUN command in the above Dockerfile to build the Jaeger example. Because the build invoked by the first RUN step in the above docker example would have already created binary for the Jaeger example.

As of now, our example cmake configurations are implemented to be built directly from root level CMakeLists.txt. This needs to be fixed, but it's not specific to Jaeger.

**Comment by lalitb** [comment]
Ok. second RUN command is required because Jaeger's example can't be built through Bazel. Probably this support needs to be added.

**Comment by ThomsonTan** [comment]
It is not expected to run cmake under sub-directory like `/opentelemetry-cpp-1.0.0-rc2/examples/jaeger/`. 

Your first `RUN` command as below should built jaeger example, or do you mean it is missing in the build output?

> && cmake .. -DBUILD_TESTING=ON -DWITH_JAEGER=ON -DWITH_OTLP=OFF
&& cmake --build . --target all

**Comment by r03942139** [comment]
> It is not expected to run cmake under sub-directory like `/opentelemetry-cpp-1.0.0-rc2/examples/jaeger/`.
> 
> Your first `RUN` command as below should built jaeger example, or do you mean it is missing in the build output?
> 
> > && cmake .. -DBUILD_TESTING=ON -DWITH_JAEGER=ON -DWITH_OTLP=OFF
> > && cmake --build . --target all

Thank you for clarifications from lalitb and ThomsonTan, I appreciate it! :)
The build command ran successfully for **cmake .. -DBUILD_TESTING=ON -DWITH_JAEGER=ON -DWITH_OTLP=OFF**, so it shall be built.
A rookie question here is where could I find the binary for the Jaeger example?
Thanks.
