### ISSUE TITLE
Unable to see traces from Jaeger examples to Jaeger UI in minikube/alpine environment

### ISSUE THREAD

**Issue by r03942139** [open-telemetry/opentelemetry-cpp#901]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.

Platform - alpine:3.12.7
opentelemetry-cpp - 1.0.0-rc2
Build - cmake 3.17.2

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

https://github.com/open-telemetry/opentelemetry-cpp/tree/main/exporters/jaeger
Steps to deploy the opentelemetry-cpp with Jaeger

**STEP1: The Dockerfile part to install and enable the example binaries (alpine)**
COPY ["./opentelemetry-cpp-1.0.0-rc2", "/opentelemetry-cpp-1.0.0-rc2"]
RUN cd opentelemetry-cpp-1.0.0-rc2 \
 && mkdir build \
 && cd build \
 && cmake .. -DBUILD_TESTING=OFF -DWITH_JAEGER=ON -DWITH_OTLP=OFF \
 && cmake --build . --target all \
 && cmake --install . --config Debug --prefix /usr/local/
RUN chmod 777 -R /opentelemetry-cpp-1.0.0-rc2

**STEP2: The terminal part to deploy Jaeger All-in-one service (UI can be seen on http://127.0.0.1:51620) ** 
$ **kubectl apply -f jaeger-all-in-one.yaml**
deployment.apps/jaeger created
service/jaeger-query created
service/jaeger-collector created
service/jaeger-agent created
service/zipkin created
$ **kubectl get service jaeger-query**
NAME           TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
jaeger-query   LoadBalancer   10.109.110.227   <pending>     8081:30401/TCP   50s
C02YRA22LVCG:trafficserver-ingress-controller jchen14$ minikube service jaeger-query --url
🏃  Starting tunnel for service jaeger-query.
|-----------|--------------|-------------|------------------------|
| NAMESPACE |     NAME     | TARGET PORT |          URL           |
|-----------|--------------|-------------|------------------------|
| default   | jaeger-query |             | http://127.0.0.1:51620 |
|-----------|--------------|-------------|------------------------|
http://127.0.0.1:51620
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.

**STEP3: Tried to send traces when logging in to bash shell with example_jaeger, but cannot see traces on UI**
bash-5.0$ **ls opentelemetry-cpp-1.0.0-rc2/build/examples**
CMakeFiles           batch                http                 multi_processor      plugin
Makefile             cmake_install.cmake  **jaeger**               multithreaded        simple
bash-5.0$ **./opentelemetry-cpp-1.0.0-rc2/build/examples/jaeger/example_jaeger** 

**What is the expected behavior?**
What did you expect to see?
Expect to see traces in **simple/example_simple**, like: f1->f1->f2->library
It seems that I was missing something.

**What is the actual behavior?**
Cannot see traces sent from example_jaeger

**Additional context**
Cannot assure if the jaeger-agent is running.
If not running, is it possible that someone can guide how to **config the jaeger-agent** to connect with my **jaeger_example**?

$ kubectl get all --all-namespaces
|-----------|-------------------|-------------|-------------|-------------|-------------|-------------|
|NAMESPACE|   NAME|       TYPE|           CLUSTER-IP|       EXTERNAL-IP|   PORT(S)   |                           AGE|
|-----------|-------------------|-------------|-------------|-------------|-------------|-------------|
|default   | service/jaeger-agent  | ClusterIP | None    | \<none\> |  5775/UDP,6831/UDP,6832/UDP,5778/TCP | 13m|
|default | service/jaeger-collector | ClusterIP  | 10.101.123.96 | \<none\>   |14267/TCP,14268/TCP,9411/TCP |   13m |
|default   | service/jaeger-query | LoadBalancer | 10.109.110.227 | \<pending\> |  8081:30401/TCP   |  13m |
|default   | service/kubernetes   |  ClusterIP | 10.96.0.1   | \<none\> | 443/TCP    |  11h|
|default     |  service/zipkin   | ClusterIP | None | \<none\>  | 9411/TCP  | 13m|

**My main.cc for example_jaeger (only put the changed parts)**
int main(int argc, char *argv[])
{
  if (argc == 2)
  {
    opts.server_addr = argv[1];
  }
  opts.server_addr      = "localhost";
  opts.server_port      = 6831;
  // opts.transport_format = TransportFormat::kThriftUdpCompact; // Will report error: 'TransportFormat' has not been declared
  // Removing this line will leave the default noop TracerProvider in place.
  InitTracer();

  foo_library();
}

**References**
https://github.com/open-telemetry/opentelemetry-cpp/tree/main/exporters/jaeger
Instructions: Get Jaeger and run Jaeger agent.

https://github.com/jaegertracing/jaeger-kubernetes
To deploy my Jaeger by jaeger-all-in-one-template.yml.

Pardon my rookie-level questions. Thanks!

**Comment by lalitb** [comment]
@r03942139 - Did you try the example code through Jaeger All-In-One docker container or binary (https://www.jaegertracing.io/docs/1.24/getting-started/#all-in-one). If it works there, you may want to check your minikube configuration/settings which is not related to the Jaeger exporter implementation.

**Comment by r03942139** [comment]
> @r03942139 - Did you try the example code through the Jaeger All-In-One docker container or binary (https://www.jaegertracing.io/docs/1.24/getting-started/#all-in-one). If it works there, you may want to check your minikube configuration/settings which is not related to the Jaeger exporter implementation.

@lalitb - To clarify, if I run the Jaeger-all-in-one 1.24, and my service with the opentelemetry-cpp & jaeger is in a different container. 
Is it workable that I execute **./opentelemetry/build/examples/jaeger/example_jaeger**,  then the traces could be passed to the Jaeger All-In-One's agent? 
Thanks.

**Comment by ThomsonTan** [comment]
@r03942139 could you please share the jaeger-all-in-one.yaml you are using?

**Comment by r03942139** [comment]
> @r03942139 could you please share the jaeger-all-in-one.yaml you are using?

Hello @ThomsonTan,

The following is my  jaeger-all-in-one.yaml.
Since my opentelemetry-cpp with Jaeger is installed on another pod in the namespace: trafficserver-test, so I assign every jaeger components to the namespace: trafficserver-test.
Thanks.


///////////  jaeger-all-in-one.yaml /////////// 
apiVersion: v1
kind: List
items:
# - apiVersion: extensions/v1beta1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: jaeger
    namespace: trafficserver-test
    labels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app.kubernetes.io/name: jaeger
    template:
      metadata:
        labels:
          app: jaeger
          app.kubernetes.io/name: jaeger
          app.kubernetes.io/component: all-in-one
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "16686"
      spec:
          containers:
          -   env:
              - name: COLLECTOR_ZIPKIN_HTTP_PORT
                value: "9411"
              image: jaegertracing/all-in-one
              name: jaeger
              ports:
                - containerPort: 5775
                  protocol: UDP
                - containerPort: 6831
                  protocol: UDP
                - containerPort: 6832
                  protocol: UDP
                - containerPort: 5778
                  protocol: TCP
                - containerPort: 16686
                  protocol: TCP
                - containerPort: 9411
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: "/"
                  port: 14269
                initialDelaySeconds: 5
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-query
    namespace: trafficserver-test
    labels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: query
  spec:
    ports:
      - name: query-http
        port: 80
        protocol: TCP
        targetPort: 16686
    selector:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
    # type: LoadBalancer
    type: NodePort
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-collector
    namespace: trafficserver-test
    labels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: collector
  spec:
    ports:
    - name: jaeger-collector-tchannel
      port: 14267
      protocol: TCP
      targetPort: 14267
    - name: jaeger-collector-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: jaeger-collector-zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
    selector:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-agent
    namespace: trafficserver-test
    labels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: agent
  spec:
    ports:
    - name: agent-zipkin-thrift
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: agent-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
    - name: agent-configs
      port: 5778
      protocol: TCP
      targetPort: 5778
    clusterIP: None
    selector:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
- apiVersion: v1
  kind: Service
  metadata:
    name: zipkin
    namespace: trafficserver-test
    labels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: zipkin
  spec:
    ports:
    - name: jaeger-collector-zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
    clusterIP: None
    selector:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one

**Comment by r03942139** [comment]
@ThomsonTan 
[jaeger-all-in-one.txt](https://github.com/open-telemetry/opentelemetry-cpp/files/6811705/jaeger-all-in-one.txt)
Please review my yaml file (Sorry that I transform to txt to be accepted by git)

**Comment by r03942139** [comment]
> @r03942139 - Did you try the example code through Jaeger All-In-One docker container or binary (https://www.jaegertracing.io/docs/1.24/getting-started/#all-in-one). If it works there, you may want to check your minikube configuration/settings which is not related to the Jaeger exporter implementation.

@lalitb I tried to follow your steps on Docker, but it seems that I cannot see traces still. The following are my steps to reproduce:

(1)  Deploy a Jaeger all-in-one, confirm that the UI can be seen on http://localhost:16686/ 
$ **docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 14250:14250 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.24**

(2) Deploy my service on docker 
$ **docker build -f Dockerfile -t myapp_alpine .**
======= The content of my Dockerfile =====
COPY ["./opentelemetry-cpp-1.0.0-rc2", "/opentelemetry-cpp-1.0.0-rc2"]
RUN cd opentelemetry-cpp-1.0.0-rc2 \
 && mkdir build \
 && cd build \
 && cmake .. -DBUILD_TESTING=OFF -DWITH_JAEGER=ON -DWITH_OTLP=OFF \
 && cmake --build . --target all \
 && cmake --install . --config Debug --prefix /usr/local/
====================

(3) Run the Docker of my app, and execute example_jaeger when I am in the docker instance
$ **docker run -it ats_alpine**
bash-5.0$ **./opentelemetry-cpp-1.0.0-rc2/build/examples/jaeger/example_jaeger** 
bash-5.0$
======= My addition to the main.cc of example_jaeger =====
int main(int argc, char *argv[])
{
  if (argc == 2)
  {
    opts.server_addr = argv[1];
  }
  **opts.server_addr      = "localhost";
  opts.server_port      = 6831;**
  InitTracer();

  foo_library();
}
===================================
Didn't add **opts.transport_format = TransportFormat::kThriftUdpCompact;** because it will report error: 'TransportFormat' has not been declared

(4) Refresh the Jaeger UI, the traces were not displayed successfully.


I followed the procedures above to reproduce the issues. Please feel free to let me know if you need more information.
Thanks!

**Comment by ThomsonTan** [comment]
@r03942139 I just ran the docker command line in your stop (1), then run example_otlp in host. I do see "unknown_service" in the Jaeger UI after refresh.

Can you try run unmodified example_otlp in your host? The problem could be your container client cannot connect to the Jaeger container.

**Comment by r03942139** [comment]
> @r03942139 I just ran the docker command line in your stop (1), then run example_otlp in host. I do see "unknown_service" in the Jaeger UI after refresh.
> 
> Can you try run unmodified example_otlp in your host? The problem could be your container client cannot connect to the Jaeger container.

@ThomsonTan  Thanks for looking into it.
Does you mean I remove the following lines in my example_jaeger?

In main.cc:
opts.server_addr      = "localhost";
opts.server_port      = 6831;

**Comment by ThomsonTan** [comment]
Yes, the 2 lines change is not necessary as it is the default configuration.

**Comment by r03942139** [comment]
> > @r03942139 - Did you try the example code through Jaeger All-In-One docker container or binary (https://www.jaegertracing.io/docs/1.24/getting-started/#all-in-one). If it works there, you may want to check your minikube configuration/settings which is not related to the Jaeger exporter implementation.
> 
> @lalitb I tried to follow your steps on Docker, but it seems that I cannot see traces still. The following are my steps to reproduce:
> 
> (1) Deploy a Jaeger all-in-one, confirm that the UI can be seen on http://localhost:16686/
> $ **docker run -d --name jaeger -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 14250:14250 -p 9411:9411 jaegertracing/all-in-one:1.24**
> 
> (2) Deploy my service on docker
> $ **docker build -f Dockerfile -t myapp_alpine .**
> *********The content of my Dockerfile *********
> COPY ["./opentelemetry-cpp-1.0.0-rc2", "/opentelemetry-cpp-1.0.0-rc2"]
> RUN cd opentelemetry-cpp-1.0.0-rc2
> && mkdir build
> && cd build
> && cmake .. -DBUILD_TESTING=OFF -DWITH_JAEGER=ON -DWITH_OTLP=OFF
> && cmake --build . --target all
> && cmake --install . --config Debug --prefix /usr/local/
> 
> (3.1) Run the Docker of my app, and execute example_jaeger when I am in the docker instance
> $ **docker run -it myapp_alpine**
> bash-5.0$ **./opentelemetry-cpp-1.0.0-rc2/build/examples/jaeger/example_jaeger**
> bash-5.0$
> (3.2) Another trial to link jaeger, but also in vain
> $ **docker run --rm -it myapp_alpine --link jaeger -p8080-8083:8080-8083 -e JAEGER_AGENT_HOST="jaeger" all**
> 
> (4) Refresh the Jaeger UI, the traces were not displayed successfully. (Only traces of **jaeger-query** can be found)
> 

@ThomsonTan 
Pardon you again!

I reproduced this procedure (Deployment on **Docker**), but set my example_jaeger to default revision.
I could still see jaeger-query on my jaeger all-in-one.
It seems that the traces from the example_jaeger are not sent to the Jaeger UI.

Is there anything I missed between this two?  (for instance, some configurations need to be done on **my docker instance**: myapp_alpine)
Thanks.

**Comment by ThomsonTan** [comment]
@r03942139 I think the problem could be that the example_jaeger running inside container cannot send data to UDP port 6831 in host. 

Could you please try run the example as `example_jaeger host.docker.internal` in the interactive console in the client container?

**Comment by r03942139** [comment]
> @r03942139 I think the problem could be that the example_jaeger running inside container cannot send data to UDP port 6831 in host.
> 
> Could you please try running the example as `example_jaeger host.docker.internal` in the interactive console in the client container?

@ThomsonTan 
Thank you very much. 
By executing `example_jaeger host.docker.internal` , the traces can be sent to the Jaeger web UI with the name "unknown service". I think I will quickly run it on k8s/minikube, to see if it works in the k8s/minikube.
I think we can close this ticket soon.
Thanks again!

**Comment by r03942139** [comment]
Hello all,
Thanks for all your help. I finally deployed the jaeger example on k8s/minikube.
I used the Jaeger operator to deploy.

Though I need `example_jaeger host.docker.internal`  to run on Docker.
I could use `example_jaeger` solely to run. 

I will close this ticket.
Thanks again!

Reference:
https://github.com/jaegertracing/jaeger-operator

**Comment by r03942139** [comment]
> "unknown_service"

@ThomsonTan 
As a follow-up question, is it possible that we can name our service name when sending traces to Jaeger UI?
Since the default is "unknown_service".

I checked some APIs on the user guide but failed to find related content.
https://opentelemetry-cpp.readthedocs.io/en/latest/otel_docs/namespace_opentelemetry__trace.html
Thanks.
