### ISSUE TITLE
Any plan to support customize the otlp gRPC header for authentication？

### ISSUE THREAD

**Issue by aaron-ai** [open-telemetry/opentelemetry-cpp#909]
Actually, opentelemetry-java allows user to customize the metadata in the header, which is convenient to implement our own authentication in collector, any plan for cpp? Thank you.

**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
Provide the ability to customize the gRPC header.

**Describe alternatives you've considered**
No.

**Additional context**
Nothing.

**Comment by lalitb** [comment]
This is an important requirement to allow custom metadata headers for authentication. Though as of now, it's not planned for the 1.0.0 release, unless someone wants to contribute the support - due to limited available bandwidth with us.
