### ISSUE TITLE
Failed to create a shared object with jaeger_trace_exporter static library (alpine/minikube)

### ISSUE THREAD

**Issue by r03942139** [open-telemetry/opentelemetry-cpp#912]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.

Platform - alpine:3.12.7
opentelemetry-cpp - 1.0.0-rc2
Build - cmake 3.17.2
/usr/bin/c++:  (Alpine 9.3.0) 9.3.0
/usr/bin/cc: (Alpine 9.3.0) 9.3.0

**Steps to reproduce**
bash-5.0$ **c++  -I/opt/ats/include   -std=c++17 -ggdb3 -pipe -Wall -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -Wno-format-truncation -Wno-cast-function-type -Wno-stringop-overflow -Wno-invalid-offsetof -Wno-noexcept-type -mcx16 -fpic -c main.cc -o main.lo**

bash-5.0$ **cc -shared   -Wl,-E -o main.so  main.lo /usr/local/lib64/libjaeger_trace_exporter.a -fPIC -lexecinfo  -lssl -lcrypto**
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/local/lib64/libjaeger_trace_exporter.a(jaeger_exporter.cc.o): relocation R_X86_64_PC32 against symbol `_ZN13opentelemetry2v06common20KeyValueIterableViewISt5arrayISt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiELm0EEED1Ev' can not be used when **making a shared object**; recompile with -fPIC
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
bash-5.0$ 

If not included the **libjaeger_trace_exporter.a**, then the compilation could work, but when executing the shared object in other application, it will show the following message.
bash-5.0$ **cc -shared   -Wl,-E -o main.so  main.lo -fPIC -lexecinfo  -lssl -lcrypto**
.......
executing main.so as a plugin......
main.so: _ZN13opentelemetry2v08exporter6jaeger14JaegerExporterC1ERKNS2_21JaegerExporterOptionsE: symbol not found

**What is the expected behavior?**
What did you expect to see?
Tried to make a shared object of example_jaeger by compiler:c++ and cc.
Hope to compile and build a shared object after the opentelemetry-cpp is built, not just the binary built during the library built.

**What is the actual behavior?**
What did you see instead?
Cannot compile with the static library  /usr/local/lib64/libjaeger_trace_exporter.a. successfully.

**Additional context**

Hope to create create a shared object of the jaeger example.
And I can use the opentelemetry-cpp library anytime after the library is built.

bash-5.0$ **ls /usr/local/lib64**
cmake                                     libopentelemetry_exporter_ostream_span.a  libopentelemetry_zpages.a
libhttp_client_curl.a                     libopentelemetry_resources.a              pkgconfig
libjaeger_trace_exporter.a                libopentelemetry_trace.a
libopentelemetry_common.a                 libopentelemetry_version.a

Thanks.

**Comment by lalitb** [comment]
Just to confirm, did you follow the instructions to generate the position independent code using steps mentioned in the INSTALL document: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md#building-as-standalone-cmake-project ?

**Comment by r03942139** [comment]
> position independent code
Hi @lalitb 
The following is my commands to build up the libraries.

RUN cd opentelemetry-cpp-1.0.0-rc3 \
 && mkdir build \
 && cd build \
 && cmake .. -DBUILD_TESTING=OFF -DWITH_JAEGER=ON -DWITH_OTLP=OFF \
 && cmake --build . --target all \
 && cmake --install . --config Debug --prefix /usr/local/ \
 && chmod 777 -R /opentelemetry-cpp-1.0.0-rc3

**Comment by lalitb** [comment]
Yes, please add `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` and check.

**Comment by r03942139** [comment]
@lalitb 
After adding the **-DCMAKE_POSITION_INDEPENDENT_CODE=ON** tag, the following commands will have no error report.

bash-5.0$ **c++  -I/opt/ats/include  -IC  -std=c++17 -ggdb3 -pipe -Wall -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -Wno-format-truncation -Wno-cast-function-type -Wno-stringop-overflow -Wno-invalid-offsetof -Wno-noexcept-type -mcx16 -fpic -c main.cc -o main.lo -B /opentelemetry-cpp-1.0.0-rc3 -B /usr/local/include**
bash-5.0$ **cc -shared -Wl,-E -o hello_world.so main.lo -lexecinfo -lssl -lcrypto -B /opentelemetry-cpp-1.0.0-rc3 -B /usr/local/include**
bash-5.0$ ls /usr/local/include/
nlohmann       opentelemetry  thrift

However, when the main.so is executed in my other application, it still report the following error:
...... main.so: _ZN13opentelemetry2v03sdk8resource8Resource6CreateERKNS1_6common12AttributeMapE: symbol not found

Do you have any idea on how to link all the libraries during c++ and cc tools?
Thanks.

**Comment by r03942139** [comment]
I think I can close this ticket, since I can use the following command to include the jaeger & opentelemetry libs.
Thanks.

$ cc -shared   -Wl,-E -o hello_world.so  main.lo  -lexecinfo  -lssl -lcrypto  -ljaeger_trace_exporter -lopentelemetry_common -lopentelemetry_trace -lopentelemetry_resources -lopentelemetry_version -lopentelemetry_exporter_ostream_span -lopentelemetry_zpages -lthrift -lthriftnb -lthriftz 

Now the problem is on thrift thing, so it is not a opentelemetry-jaeger thing
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/local/lib/libthrift.a(TOutput.cpp.o): relocation R_X86_64_PC32 against symbol `stderr' can not be used when making a shared object; recompile with -fPIC

Thanks.

**Comment by r03942139** [comment]
Pardon for bothering @lalitb once again, I hit the opentelemetry-related issue, and I would like to re-open this issue.
Thanks.

bash-5.0$ **c++ -I/opt/ats/include -std=c++17 -ggdb3 -pipe -Wall -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -Wno-format-truncation -Wno-cast-function-type -Wno-stringop-overflow -Wno-invalid-offsetof -Wno-noexcept-type -mcx16 -fpic -c main.cc -o main.lo**

bash-5.0$ **cc -shared -Wl,-E -o hello_world.so main.lo -lexecinfo -lssl -lcrypto -ljaeger_trace_exporter -lopentelemetry_common -lopentelemetry_trace -lopentelemetry_resources -lopentelemetry_version -lopentelemetry_exporter_ostream_span -lopentelemetry_zpages -lthrift -lthriftnb -lthriftz**

I rebuilt the thrift (0.14.2) with -fPIC, and everything works fine. But the built shared object reported the following issue
Error relocating......  main.so: _ZN13**opentelemetry**2v03**sdk**6**common**6**Random**20**GenerateRandomBuffer**ENS0_5**nostd**4**span**IhLm18446744073709551615EEE: symbol not found

The bold line 
**nostd::shared_ptr<trace::TracerProvider>(new sdktrace::TracerProvider(std::move(processor)));**
is the line started reported issues

=========== My main.cc ==========
#include "opentelemetry/exporters/jaeger/recordable.h"
#include "opentelemetry/exporters/jaeger/jaeger_exporter.h"
#include "opentelemetry/sdk/trace/simple_processor.h"
#include "opentelemetry/sdk/trace/tracer_provider.h"
#include "opentelemetry/trace/provider.h"

namespace trace    = opentelemetry::trace;
namespace nostd    = opentelemetry::nostd;
namespace sdktrace = opentelemetry::sdk::trace;
namespace jaeger   = opentelemetry::exporter::jaeger;

namespace
{
opentelemetry::exporter::jaeger::JaegerExporterOptions opts;
void InitTracer()
{
  // Create Jaeger exporter instance
  auto exporter  = std::unique_ptr<sdktrace::SpanExporter>(new jaeger::JaegerExporter(opts));
  auto processor = std::unique_ptr<sdktrace::SpanProcessor>(
      new sdktrace::SimpleSpanProcessor(std::move(exporter)));
  **auto provider =
      nostd::shared_ptr<trace::TracerProvider>(new sdktrace::TracerProvider(std::move(processor)));**
  // Set the global trace provider
  trace::Provider::SetTracerProvider(provider);
}
.........
==================================================

The static libraries I have installed

bash-5.0$ **ls /usr/local/lib64**
cmake                                     libopentelemetry_exporter_ostream_span.a  libopentelemetry_zpages.a
libhttp_client_curl.a                     libopentelemetry_resources.a              pkgconfig
libjaeger_trace_exporter.a                libopentelemetry_trace.a
libopentelemetry_common.a                 libopentelemetry_version.a

bash-5.0$ **ls /usr/local/lib**
cmake          libthrift.a    libthriftnb.a  libthriftz.a   pkgconfig

**Comment by lalitb** [comment]
@r03942139 - Can you check the order in which libraries are specified in your last command. In general, if the `libA` needs a symbol from `libB`, `libA` should come before `libB` in the linker command line invocation.  With that rule, `-lopentelemetry_common` should be somewhere at the end of the list of libraries.

**Comment by r03942139** [comment]
@lalitb 
Thanks for the hint. The problem solved when I changed the opentelemetry_common to the last part of linking libraries.
cc -shared -Wl,-E -o hello_world.so main.lo -lexecinfo -lssl -lcrypto -ljaeger_trace_exporter -lopentelemetry_trace -lopentelemetry_resources -lopentelemetry_version -lopentelemetry_exporter_ostream_span -lopentelemetry_zpages **-lopentelemetry_common** -lhttp_client_curl -lthrift -lthriftnb -lthriftz
