### ISSUE TITLE
Allow to use local GSL

### ISSUE THREAD

**Issue by owent** [open-telemetry/opentelemetry-cpp#914]
**Is your feature request related to a problem?**
I found [ms-gsl][1] is a excellent tool to write modern C++ codes, and I want to use it in my project.At the same time I think it's better to let opentelemetry use the same [ms-gsl][1].

**Describe the solution you'd like**
`find_package(Microsoft.GSL QUIET)` before `set(GSL_DIR third_party/ms-gsl)` and `include_directories(${GSL_DIR}/include)`

**Describe alternatives you've considered**
I find another library - [gsl-lite][2] and it seems have better compatibility for old compilers. Maybe we can use it for old compilers?

**Additional context**
None

[1]: https://github.com/microsoft/GSL.git
[2]: https://github.com/gsl-lite/gsl-lite.git

**Comment by lalitb** [comment]
@owent - Can we close this issue, if #915 fixes it.

**Comment by owent** [comment]
Yes
