### ISSUE TITLE
Helper methods for accessing Span directly from Context in Span API

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-cpp#950]
The 1.0.0 specification states:

```
This section defines all operations within the Tracing API that interact with the Context.

The API MUST provide the following functionality to interact with a Context instance:

- Extract the Span from a Context instance
- Insert the Span to a Context instance
The functionality listed above is necessary because API users SHOULD NOT have access to the Context Key used by the Tracing API implementation.

If the language has support for implicitly propagated Context (see here), the API SHOULD also provide the following functionality:

- Get the currently active span from the implicit context. This is equivalent to getting the implicit context, then extracting the Span from the context.
- Set the currently active span to the implicit context. This is equivalent to getting the implicit context, then inserting the Span to the context.
```

I was looking for documentation or example (e.g. context propagation) where this is done.  In some languages, they provide helper methods directly on Span which will extract/insert into context (both explicitly or implicitly).  

Specifically, I think this may need to be public: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/trace/propagation/detail/context.h#L14

It looks like these methods may be on Tracer: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/trace/tracer.h#L146.  This is inconsistent with other APIs.

Ideally the propogation:detail + tracer methods would get reconciled into a standard header with Span <-> Context interaction.

**Comment by lalitb** [comment]
@jsuereth  -
To ensure that I understand the ask here:
 - Below functions are to be moved from `trace::propagation` to `trace` namespace ( and make them part of public API ), either keep them as `inline` function, or make them `static` function in `Span` class:
       - trace::propagation::GetSpan()
       - trace::propagation::SetSpan()
 - No changes are required for below static methods on implicitly propagated context:
       - trace::Tracer:: GetCurrentSpan()
       - trace::Tracer:: WithActiveSpan()

**Comment by lalitb** [comment]
@jsuereth  - would you please help clarifying the questions above. Thanks :)

**Comment by jsuereth** [comment]
Sorry for huge delay in response.   Just getting back to OSS things.

> Below functions are to be moved from trace::propagation to trace namespace ( and make them part of public API ), either keep them as inline function, or make them static function in Span class

Yeah, the ask is move this out of the propagation package and have them "near" the span class.   You can make them inline or static on `Span`, but they should be near span.  The PR (#967) you sent LGTM

> No changes are required for below static methods on implicitly propagated context:

I'm suggesting, for consistency with other SDKs/APIs, that these methods live *near* the other context + span related methods.   The Specification does NOT place these on Tracer, so it's a major inconsistency.

You can leave the static methods on tracer, but I'd suggest you also provide them near the GetSpan/SetSpan methods and just have Tracer call into it.   I'd also deprecate the `trace::Tracer::WithActiveSpan` version of the method.  I think it's leftover from earlier specification.
