### ISSUE TITLE
OTLP Environment variables do not match specification

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-cpp#971]
Currently, [OTLP environment variables (OTEL_EXPORTER_OTLP_GRPC_ENDPOINT)](https://github.com/open-telemetry/opentelemetry-cpp/blob/5067e49bce39e8dd4c3986042e558e965c73a253/exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_exporter.h#L24) does not [match the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/specification/protocol/exporter.md).

Copied relevant sections:

## Configuration Options

The following configuration options MUST be available to configure the OTLP exporter. Each configuration option MUST be overridable by a signal specific option.

| Configuration Option | Description                                                  | Default           | Env variable                                                 |
| -------------------- | ------------------------------------------------------------ | ----------------- | ------------------------------------------------------------ |
| Endpoint             | Target to which the exporter is going to send spans or metrics. The endpoint MUST be a valid URL with scheme (http or https) and host, and MAY contain a port and path. A scheme of https indicates a secure connection. When using `OTEL_EXPORTER_ENDPOINT` with OTLP/HTTP, exporters SHOULD follow the collector convention of appending the version and signal to the path (e.g. `v1/traces` or `v1/metrics`). The per-signal endpoint configuration options take precedence and can be used to override this behavior. See the [OTLP Specification][otlphttp-req] for more details. | `https://localhost:4317` | `OTEL_EXPORTER_OTLP_ENDPOINT` `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` `OTEL_EXPORTER_OTLP_METRICS_ENDPOINT` |
| Certificate File     | Path to certificate file for TLS credentials of gRPC client. Should only be used for a secure connection. | n/a               | `OTEL_EXPORTER_OTLP_CERTIFICATE` `OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE` `OTEL_EXPORTER_OTLP_METRICS_CERTIFICATE` |
| Headers              | Key-value pairs to be used as headers associated with gRPC or HTTP requests. See [Specifying headers](./exporter.md#specifying-headers-via-environment-variables) for more details.                   | n/a               | `OTEL_EXPORTER_OTLP_HEADERS` `OTEL_EXPORTER_OTLP_TRACES_HEADERS` `OTEL_EXPORTER_OTLP_METRICS_HEADERS` |
| Compression          | Compression key for supported compression types. Supported compression: `gzip`| No value              | `OTEL_EXPORTER_OTLP_COMPRESSION` `OTEL_EXPORTER_OTLP_TRACES_COMPRESSION` `OTEL_EXPORTER_OTLP_METRICS_COMPRESSION` |
| Timeout              | Max waiting time for the backend to process each spans or metrics batch. | 10s               | `OTEL_EXPORTER_OTLP_TIMEOUT` `OTEL_EXPORTER_OTLP_TRACES_TIMEOUT` `OTEL_EXPORTER_OTLP_METRICS_TIMEOUT` |

Supported values for `OTEL_EXPORTER_OTLP_*COMPRESSION` options:

- If the value is missing, then compression is disabled.
- `gzip` is the only specified compression method for now. Other options MAY be supported by language SDKs and should be documented for each particular language.

Example 1

The following configuration sends all signals to the same collector:

```bash
export OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
```

Example 2

Traces and metrics are sent to different collectors:

```bash
export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://collector:4317

export OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=https://collector.example.com/v1/metrics
```

### Specify Protocol

Currently, OTLP has more than one transport protocol it can support, e.g.
`grpc`,  `http/json`, `http/protobuf`.   As of 1.0 of the specification, there
*is no specified default, or configuration via environment variables*.  We
reserve the following environment variables for configuration of protocols in
the future:

- `OTEL_EXPORTER_OTLP_PROTOCOL`
- `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL`
- `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL`

SDKs have an unspecified default, if no configuration is provided.

### Specifying headers via environment variables

The `OTEL_EXPORTER_OTLP_HEADERS`, `OTEL_EXPORTER_OTLP_TRACES_HEADERS`, `OTEL_EXPORTER_OTLP_METRICS_HEADERS` environment variables will contain a list of key value pairs, and these are expected to be represented in a format matching to the [W3C Correlation-Context](https://github.com/w3c/baggage/blob/master/baggage/HTTP_HEADER_FORMAT.md), except that additional semi-colon delimited metadata is not supported, i.e.: key1=value1,key2=value2. All attribute values MUST be considered strings.

**Comment by lalitb** [comment]
Thanks for copying the relevant sections. This means there would be only one OTLP exporter configured at given time ( as specified by `OTEL_EXPORTER_OTLP_PROTOCOL` ), and so all of them share the same env variables names.

**Comment by lalitb** [comment]
And to add further -  otel-cpp doesn't support environment variables as defined in the specs, this is also indicated clearly in the compliance matrix : 
https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#environment-variables


Feature | Go | Java | JS | Python | Ruby | Erlang | PHP | Rust | C++ | .NET | Swift
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

OTEL_EXPORTER_OTLP_* | + | + |   | + | + | - | - | + | - | - | -
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --


We would like to take exception for supporting the env-variables as per the specs, as the support can be added latter without breaking the API. @jsuereth  - let us know your thought on this.

**Comment by lalitb** [comment]
@jsuereth  - Sorry for multiple comments :) This was discussed in today's meeting. And as the env-var used in code are not same as required by specs, we planned to document them explicitly ( done in #971 ). Also mentioned there that both would be  supported simultaneously in future.

**Comment by jsuereth** [comment]
Do you have users of these env variables now?

The specification denotes:

> The following configuration options MUST be available to configure the OTLP exporter.

If you didn't have *any* environment variable configuration, that would make sense.   However if you do provide environment variable configuration, then it should be consistent with otel.  This is a major issue for consistency across the SDKs in OTel.

At a minimum, I think you should:

- Support `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`.  This should ALWAYS override the existing `OTEL_EXPORTER_OTLP_GRPC_ENDPOINT` + `OTEL_EXPORTER_OTLP_GRPC_SSL_ENABLE` settings.
- Support `OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE` which would override `OTEL_EXPORTER_OTLP_GRPC_SSL_CERTIFICATE`

What's the reason for (continued) divergence right now?

**Comment by lalitb** [comment]
> Do you have users of these env variables now?

We don't know for sure, but we are trying best  avoid doing breaking changes while in release candidate.

> If you didn't have any environment variable configuration, that would make sense. However if you do provide environment variable configuration, then it should be consistent with otel. This is a major issue for consistency across the SDKs in OTel.

Good point. Will add support for OTEL_EXPORTER_OTLP_TRACES_ENDPOINT and OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE as suggested by you.

**Comment by lalitb** [comment]
@jsuereth  - Can you review this PR #974 for the changes.

Another alternate suggestion from @ThomsonTan -  instead of any code changes for now,  we can enable the NO_ENV macro ( which basically for now disable all environment variables ( used here : https://github.com/open-telemetry/opentelemetry-cpp/blob/c8b35ff0df9bd1e7c6a2e1d805bb664331bfdea6/sdk/include/opentelemetry/sdk/common/env_variables.h#L16-L18 ) 
, and then enable it once we are compliant with the specs
